---
permalink: online-help/concept-what-the-expected-range-of-performance-is.html 
sidebar: sidebar 
keywords:  
summary: 예상 값 범위는 특정 시간에 예상되는 상위 및 하위 성능 값의 예측 또는 예측입니다. 워크로드 지연 시간의 경우 상한값이 성능 임계값을 구성합니다. 실제 값이 성능 임계값을 넘어가면 Unified Manager에서 성능 이벤트 알림을 트리거합니다. 
---
= 예상되는 성능 범위는 얼마입니까
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
예상 값 범위는 특정 시간에 예상되는 상위 및 하위 성능 값의 예측 또는 예측입니다. 워크로드 지연 시간의 경우 상한값이 성능 임계값을 구성합니다. 실제 값이 성능 임계값을 넘어가면 Unified Manager에서 성능 이벤트 알림을 트리거합니다.

예를 들어, 정규 업무 시간 동안 오전 9시 사이에 있습니다 대부분의 직원은 오전 9시부터 오후 5시까지 이메일을 확인할 수 있습니다 오전 10시 30분 이메일 서버에 대한 수요가 증가하면 이 기간 동안 백엔드 스토리지의 워크로드 활동이 증가합니다. 직원들은 이메일 클라이언트에서 느린 응답 시간을 알아차릴 수 있습니다.

점심 시간 동안 오후 12시 사이에 오후 1시 그리고 오후 5시 이후 업무가 끝날 때 대부분의 직원들은 컴퓨터에서 떨어져 있을 가능성이 높습니다. 일반적으로 이메일 서버에 대한 수요가 감소하므로 백엔드 스토리지에 대한 요구도 감소합니다. 또는 오후 5시 이후에 시작되는 스토리지 백업 또는 바이러스 검사 등의 예약된 워크로드 작업이 있을 수 있습니다 백 엔드 스토리지에서의 활동을 늘려줍니다.

워크로드 활동의 증가 및 감소는 몇 일 동안 예상되는 작업 범위를 결정합니다. 이때 워크로드의 범위는 상한 및 하단으로 결정됩니다. 개체의 실제 워크로드 활동이 상한 또는 하위의 경계를 벗어나 일정 기간 동안 경계 외부에 있는 경우, 개체가 초과 사용 또는 과소사용됨을 나타낼 수 있습니다.



== 예상 범위 형성 방법

Unified Manager에서 분석을 시작하기 전에, 그리고 GUI에 예상 I/O 응답 시간 및 작업 범위가 표시되기 전에 최소 3일간의 워크로드 활동을 수집해야 합니다. 필요한 최소 데이터 수집은 워크로드 활동에서 발생하는 모든 변경 사항을 고려하지 않습니다. Unified Manager는 첫 3일간의 활동을 수집한 후 24시간마다 오전 12시에 예상 범위를 조정하여 워크로드 활동 변경사항을 반영하고 보다 정확한 성능 임계값을 설정합니다.

[NOTE]
====
DST(일광 절약 시간)는 시스템 시간을 변경하여 모니터링되는 작업 부하에 대한 예상 성능 통계 범위를 변경합니다. Unified Manager가 즉시 예상 범위를 수정하기 시작하는데, 완료까지 약 15일이 걸립니다. 이때 Unified Manager를 계속 사용할 수 있지만 Unified Manager에서 이벤트를 감지하는 데 예상 범위가 사용되므로 일부 이벤트는 정확하지 않을 수 있습니다. 시간 변경 전에 감지된 이벤트는 영향을 받지 않습니다. 클러스터 또는 Unified Manager 서버에서 시간을 수동으로 변경하면 이벤트 분석 결과에도 영향을 줍니다.

====