---
permalink: online-help/concept-cluster-configuration-and-performance-data-collection-activity.html 
sidebar: sidebar 
keywords:  
summary: 클러스터 구성 데이터의 수집 간격은 15분입니다. 예를 들어, 클러스터를 추가한 후에는 15분 이내에 Unified Manager UI에 클러스터 세부 정보를 표시할 수 있습니다. 이 간격은 클러스터에 대한 변경에도 적용됩니다. 
---
= 클러스터 구성 및 성능 데이터 수집 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 구성 data_의 수집 간격은 15분입니다. 예를 들어, 클러스터를 추가한 후에는 15분 이내에 Unified Manager UI에 클러스터 세부 정보를 표시할 수 있습니다. 이 간격은 클러스터에 대한 변경에도 적용됩니다.

예를 들어, 클러스터의 SVM에 새 볼륨 2개를 추가하는 경우 다음 폴링 간격 후 UI에서 새로운 객체를 볼 수 있으며 이는 최대 15분이 될 수 있습니다.

Unified Manager는 5분마다 모니터링되는 모든 클러스터에서 current_performance 통계를 수집합니다. 이 데이터를 분석하여 성능 이벤트 및 잠재적 문제를 식별합니다. 이 제품은 30일 동안의 5분 내역 성능 데이터와 390일 동안의 1시간 내역 성능 데이터를 보존합니다. 이를 통해 현재 달의 매우 세부적인 성능 세부 정보와 최대 1년의 일반적인 성능 추세를 볼 수 있습니다.

컬렉션 폴은 몇 분 간격으로 오프셋되므로 모든 클러스터의 데이터가 동시에 전송되지 않아 성능에 영향을 줄 수 있습니다.

다음 표에서는 Unified Manager가 수행하는 수집 활동에 대해 설명합니다.

|===
| 활동입니다 | 시간 간격입니다 | 설명 


 a| 
성능 통계 폴링
 a| 
5분마다
 a| 
각 클러스터에서 실시간 성능 데이터 수집



 a| 
통계 분석
 a| 
5분마다
 a| 
모든 통계 폴링 후에 Unified Manager는 수집된 데이터를 사용자 정의, 시스템 정의 및 동적 임계값과 비교합니다.

성능 임계값이 위반된 경우 Unified Manager는 이벤트를 생성하고 지정된 사용자에게 해당 e-메일을 보냅니다(구성된 경우).



 a| 
구성 폴링
 a| 
15분마다
 a| 
각 클러스터에서 세부 인벤토리 정보를 수집하여 모든 스토리지 오브젝트(노드, SVM, 볼륨 등)를 식별합니다.



 a| 
요약
 a| 
매시간
 a| 
에서는 최신 12개의 5분 성능 데이터 컬렉션을 시간별 평균으로 요약합니다.

매시간 평균 값은 일부 UI 페이지에서 사용되며 390일 동안 유지됩니다.



 a| 
예측 분석 및 데이터 정리
 a| 
매일 자정이 지나면
 a| 
클러스터 데이터를 분석하여 향후 24시간 동안 볼륨 지연 시간 및 IOPS에 대한 동적 임계값을 설정합니다.

30일이 지난 5분 동안의 성능 데이터를 데이터베이스에서 삭제합니다.



 a| 
데이터 잘라내기
 a| 
매일 오전 2시 이후
 a| 
390일이 지난 모든 이벤트 및 동적 임계값을 데이터베이스에서 삭제합니다.



 a| 
데이터 잘라내기
 a| 
매일 오전 3시 30분 이후
 a| 
390일이 지난 1시간 동안의 성능 데이터를 데이터베이스에서 삭제합니다.

|===