---
permalink: online-help/concept-what-event-management-system-events-are.html 
sidebar: sidebar 
keywords:  
summary: '이벤트 관리 시스템\(EMS\)은 ONTAP 커널의 여러 부분에서 이벤트 데이터를 수집하고 이벤트 전달 메커니즘을 제공합니다. 이러한 ONTAP 이벤트는 Unified Manager에서 EMS 이벤트로 보고할 수 있습니다. 중앙 집중식 모니터링 및 관리를 통해 이러한 EMS 이벤트를 기반으로 중요한 EMS 이벤트 및 경고 알림을 간편하게 구성할 수 있습니다.' 
---
= 이벤트 관리 시스템 이벤트란 무엇입니까
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
EMS(이벤트 관리 시스템)는 ONTAP 커널의 여러 부분에서 이벤트 데이터를 수집하고 이벤트 전달 메커니즘을 제공합니다. 이러한 ONTAP 이벤트는 Unified Manager에서 EMS 이벤트로 보고할 수 있습니다. 중앙 집중식 모니터링 및 관리를 통해 이러한 EMS 이벤트를 기반으로 중요한 EMS 이벤트 및 경고 알림을 간편하게 구성할 수 있습니다.

Unified Manager에 클러스터를 추가하면 Unified Manager 주소가 클러스터에 알림 대상으로 추가됩니다. EMS 이벤트는 클러스터에서 이벤트가 발생하는 즉시 보고됩니다.

Unified Manager에서 EMS 이벤트를 수신하는 방법에는 두 가지가 있습니다.

* 특정 수의 중요한 EMS 이벤트가 자동으로 보고됩니다.
* 개별 EMS 이벤트를 구독할 수 있습니다.


Unified Manager에서 생성되는 EMS 이벤트는 이벤트가 생성된 방법에 따라 다르게 보고됩니다.

|===
| 기능 | 자동 EMS 메시지 | 등록된 EMS 메시지 


 a| 
사용 가능한 EMS 이벤트입니다
 a| 
EMS 이벤트의 하위 집합입니다
 a| 
모든 EMS 이벤트



 a| 
EMS가 트리거될 때 메시지 이름입니다
 a| 
Unified Manager 이벤트 이름(EMS 이벤트 이름에서 변환됨)
 a| 
"Error EMS Received(오류 EMS 수신)" 형식의 비특이적. 상세 메시지는 실제 EMS 이벤트의 도트 표기 형식을 제공한다



 a| 
메시지가 수신되었습니다
 a| 
클러스터가 검색되는 즉시
 a| 
필요한 각 EMS 이벤트를 Unified Manager에 추가한 후 다음 15분 폴링 주기가 지나면



 a| 
이벤트 수명 주기
 a| 
다른 Unified Manager 이벤트와 동일: 새 상태, 확인됨 상태, 해결된 상태 및 폐기 상태
 a| 
이벤트가 생성된 후 15분 후에 클러스터를 새로 고친 후 EMS 이벤트가 더 이상 사용되지 않습니다



 a| 
Unified Manager 다운타임 동안 이벤트를 캡처합니다
 a| 
예. 시스템이 시작되면 각 클러스터와 통신하여 누락된 이벤트를 획득합니다
 a| 
아니요



 a| 
이벤트 세부 정보
 a| 
제안된 수정 조치를 ONTAP에서 직접 가져와 일관된 해결 방법을 제공합니다
 a| 
이벤트 세부 정보 페이지에서 수정 조치를 사용할 수 없습니다

|===
[NOTE]
====
새로운 자동 EMS 이벤트 중 일부는 이전 이벤트가 해결되었음을 나타내는 정보 이벤트입니다. 예를 들어, "'FlexGroup 구성 요소공간 상태 모두 정상''' 정보 이벤트는 "'FlexGroup 구성 요소에는 공간 문제가 있음'' 오류 이벤트가 해결되었음을 나타냅니다. 다른 이벤트 심각도 유형과 동일한 이벤트 수명 주기를 사용하여 정보 이벤트를 관리할 수 없지만 동일한 볼륨에서 또 다른 "속도 문제" 오류 이벤트가 발생하면 이벤트가 자동으로 폐기됩니다.

====