---
permalink: online-help/concept-event-state-definitions.html 
sidebar: sidebar 
keywords:  
summary: 이벤트의 상태는 적절한 수정 조치가 필요한지 여부를 식별하는 데 도움이 됩니다. 이벤트는 New, Acknowledged, Resolved 또는 Obsolete가 될 수 있습니다. 새 이벤트와 승인된 이벤트 모두 활성 이벤트로 간주됩니다. 
---
= 이벤트 상태 정의
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이벤트의 상태는 적절한 수정 조치가 필요한지 여부를 식별하는 데 도움이 됩니다. 이벤트는 New, Acknowledged, Resolved 또는 Obsolete가 될 수 있습니다. 새 이벤트와 승인된 이벤트 모두 활성 이벤트로 간주됩니다.

이벤트 상태는 다음과 같습니다.

* * 신규 *
+
새 이벤트의 상태입니다.

* * 확인됨 *
+
사용자가 이벤트를 승인했을 때의 상태입니다.

* * 해결됨 *
+
해결됨으로 표시된 이벤트의 상태입니다.

* * 사용되지 않음 *
+
자동으로 수정되거나 이벤트의 원인이 더 이상 유효하지 않은 경우의 이벤트 상태입니다.

+
[NOTE]
====
더 이상 사용되지 않는 이벤트를 확인하거나 확인할 수 없습니다.

====




== 이벤트의 여러 가지 상태 예

다음 예제에서는 수동 및 자동 이벤트 상태의 변화를 보여 줍니다.

이벤트 클러스터에 연결할 수 없음 이 트리거되면 이벤트 상태는 새로 만들기 입니다. 이벤트를 확인하면 이벤트 상태가 확인으로 변경됩니다. 적절한 수정 조치를 취했다면 해당 이벤트를 '해결됨'으로 표시해야 합니다. 그런 다음 이벤트 상태가 Resolved 로 변경됩니다.

정전 때문에 Cluster Not Reachable 이벤트가 발생한 경우 전원이 복구되면 클러스터가 관리자 개입 없이 작동을 시작합니다. 따라서 Cluster Not Reachable 이벤트가 더 이상 유효하지 않으며 이벤트 상태가 다음 모니터링 주기에서 Obsolete로 변경됩니다.

이벤트가 Obsolete 또는 Resolved 상태인 경우 Unified Manager에서 알림을 보냅니다. 알림의 전자 메일 제목 줄 및 전자 메일 콘텐츠는 이벤트 상태에 대한 정보를 제공합니다. SNMP 트랩에는 이벤트 상태에 대한 정보도 포함되어 있습니다.
