---
permalink: online-help/concept-what-happens-to-performance-threshold-policies-when-an-object-is-moved-opm.html 
sidebar: sidebar 
keywords:  
summary: 성능 임계값 정책은 스토리지 개체에 할당되므로 개체를 이동할 경우 이동을 완료한 후에도 할당된 모든 임계값 정책이 개체에 연결된 상태로 유지됩니다. 예를 들어, 볼륨 또는 LUN을 다른 애그리게이트로 이동하는 경우 임계값 정책은 새 애그리게이트에 있는 볼륨 또는 LUN에 대해 여전히 활성 상태입니다. 
---
= 오브젝트를 이동할 때 성능 임계값 정책이 어떻게 되는지 확인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능 임계값 정책은 스토리지 개체에 할당되므로 개체를 이동할 경우 이동을 완료한 후에도 할당된 모든 임계값 정책이 개체에 연결된 상태로 유지됩니다. 예를 들어, 볼륨 또는 LUN을 다른 애그리게이트로 이동하는 경우 임계값 정책은 새 애그리게이트에 있는 볼륨 또는 LUN에 대해 여전히 활성 상태입니다.

임계값 정책에 대한 보조 카운터 조건이 있는 경우(예: 결합 정책) - 예를 들어 aggregate 또는 노드에 추가 조건이 할당된 경우 - 보조 카운터 조건이 볼륨 또는 LUN이 이동된 새 Aggregate 또는 노드에 적용됩니다.

변경된 임계값 정책을 사용하는 객체에 대해 새 활성 이벤트가 존재하는 경우 해당 이벤트는 폐기된 것으로 표시되고 임계값 정책은 카운터를 새로 정의된 임계값 정책으로 모니터링하기 시작합니다.

볼륨 이동 작업을 수행하면 ONTAP에서 정보 변경 이벤트를 보냅니다. 성능 탐색기 페이지의 이벤트 타임라인과 성능/볼륨 세부 정보 페이지에 변경 이벤트 아이콘이 표시되어 이동 작업이 완료된 시간을 나타냅니다.

[NOTE]
====
개체를 다른 클러스터로 이동하는 경우 사용자 정의 임계값 정책이 개체에서 제거됩니다. 필요한 경우 이동 작업이 완료된 후 개체에 임계값 정책을 할당해야 합니다. 그러나 동적 및 시스템 정의 임계값 정책은 새 클러스터로 이동된 후 개체에 자동으로 적용됩니다.

====


== HA 테이크오버 및 반환 중 임계값 정책 기능

고가용성(HA) 구성에서 테이크오버 또는 반환 작업이 발생하는 경우 한 노드에서 다른 노드로 이동된 객체는 수동 이동 작업과 동일한 방식으로 임계값 정책을 유지합니다. Unified Manager에서는 15분마다 클러스터 구성의 변경 사항을 확인하기 때문에, 클러스터 구성을 다음에 폴링할 때까지 새 노드로 전환할 때 미치는 영향이 식별되지 않습니다.

[NOTE]
====
테이크오버와 반환 작업이 15분 구성 변경 수집 기간 내에 발생하는 경우 성능 통계가 한 노드에서 다른 노드로 이동하지 않는 것을 확인할 수 있습니다.

====


== 애그리게이트 재배치 중 임계값 정책 기능

를 사용하여 한 노드에서 다른 노드로 애그리게이트를 이동하는 경우 `aggregate relocation start` 명령, 단일 및 조합 임계값 정책이 모든 개체에 유지되고 임계값 정책의 노드 부분이 새 노드에 적용됩니다.



== MetroCluster 절체 시 Threshold 정책 기능

MetroCluster 구성에서 클러스터 간에 이동하는 오브젝트에는 사용자 정의 임계값 정책 설정이 유지되지 않습니다. 필요한 경우 파트너 클러스터로 이동한 볼륨 및 LUN에 임계값 정책을 적용할 수 있습니다. 오브젝트가 원래 클러스터로 다시 이동되면 사용자 정의 임계값 정책이 자동으로 다시 적용됩니다.

xref:concept-volume-behavior-during-switchover-and-switchback.adoc[스위치오버 및 스위치백 중 볼륨 동작]
