---
permalink: online-help/concept-guidelines-for-adding-alerts.html 
sidebar: sidebar 
keywords:  
summary: 클러스터, 노드, 애그리게이트 또는 볼륨, 특정 심각도 유형의 이벤트 등 리소스를 기반으로 하는 알림을 추가할 수 있습니다. 모범 사례로서, 객체가 속한 클러스터를 추가한 후 중요 객체에 대한 알림을 추가할 수 있습니다. 
---
= 알림 추가 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터, 노드, 애그리게이트 또는 볼륨, 특정 심각도 유형의 이벤트 등 리소스를 기반으로 하는 알림을 추가할 수 있습니다. 모범 사례로서, 객체가 속한 클러스터를 추가한 후 중요 객체에 대한 알림을 추가할 수 있습니다.

다음 지침 및 고려 사항을 사용하여 알림을 생성하여 시스템을 효과적으로 관리할 수 있습니다.

* 경고 설명입니다
+
알림을 효과적으로 추적할 수 있도록 알림에 대한 설명을 제공해야 합니다.

* 리소스
+
어떤 물리적 또는 논리적 리소스에 경고가 필요한지 결정해야 합니다. 필요에 따라 자원을 포함하거나 제외할 수 있습니다. 예를 들어, 경고를 구성하여 애그리게이트를 면밀히 모니터링하려면 리소스 목록에서 필요한 애그리게이트를 선택해야 합니다.

* 이벤트 심각도입니다
+
지정된 심각도 유형(Critical, Error, Warning)의 이벤트가 경고를 트리거할지, 트리거할 경우 어떤 심각도 유형을 트리거할지 결정해야 합니다.

* 이벤트 이름입니다
+
생성된 이벤트 유형에 따라 알림을 추가하는 경우 경고가 필요한 이벤트를 결정해야 합니다

* 작업
+
알림을 받는 사용자의 사용자 이름과 이메일 주소를 제공해야 합니다. SNMP 트랩을 알림 모드로 지정할 수도 있습니다. 알림을 생성할 때 실행되도록 알림을 통해 스크립트를 연결할 수 있습니다.

* 알림 빈도
+
지정된 시간 동안 수신자에게 알림을 반복적으로 보내도록 알림을 구성할 수 있습니다. 알림에 대해 이벤트 알림이 활성화되는 시간을 결정해야 합니다. 이벤트 알림이 이벤트가 확인될 때까지 반복되도록 하려면 알림을 반복할 빈도를 결정해야 합니다.

* 스크립트를 실행합니다
+
스크립트를 경고와 연결할 수 있습니다. 경고가 생성될 때 스크립트가 실행됩니다.


