---
permalink: online-help/concept-what-a-data-continuity-collection-cycle-is.html 
sidebar: sidebar 
keywords:  
summary: 데이터 연속성 수집 주기는 기본적으로 5분마다 실행되는 실시간 클러스터 성능 수집 주기를 벗어나 성능 데이터를 검색합니다. Unified Manager는 데이터 연속성 컬렉션을 통해 실시간 데이터를 수집할 수 없을 때 발생하는 통계 데이터의 격차를 해소합니다. 
---
= 데이터 연속성 수집 주기는 얼마입니까
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 연속성 수집 주기는 기본적으로 5분마다 실행되는 실시간 클러스터 성능 수집 주기를 벗어나 성능 데이터를 검색합니다. Unified Manager는 데이터 연속성 컬렉션을 통해 실시간 데이터를 수집할 수 없을 때 발생하는 통계 데이터의 격차를 해소합니다.

Data Continuity 컬렉션은 ONTAP 버전 8.3.1 이상 소프트웨어가 설치된 클러스터에서만 지원됩니다.

Unified Manager는 다음과 같은 이벤트가 발생할 경우 기간별 성능 데이터에 대한 데이터 연속성 수집 폴링을 수행합니다.

* 클러스터는 처음에 Unified Manager에 추가됩니다.
+
Unified Manager는 이전 15일 동안의 기간별 성능 데이터를 수집합니다. 따라서 클러스터를 추가한 후 몇 시간 이내에 클러스터에 대한 2주간의 기간별 성능 정보를 볼 수 있습니다.

+
또한 시스템 정의 임계값 이벤트가 있는 경우 이전 기간에 대해 보고됩니다.

+
[NOTE]
====
15일 동안의 기간별 볼륨 통계가 현재 수집되지 않습니다.

====
* 현재 성능 데이터 수집 주기가 정해진 시간에 완료되지 않습니다.
+
실시간 성능 폴링이 5분 수집 기간을 초과할 경우 데이터 연속성 수집 주기가 시작되어 누락된 정보를 수집합니다. Data Continuity 수집 기능이 없으면 다음 수집 기간을 건너뜁니다.

* Unified Manager는 일정 기간 동안 액세스할 수 없었던 적이 있으며 다음과 같은 상황에서 온라인 상태로 돌아갑니다.
+
** 다시 시작되었습니다.
** 소프트웨어 업그레이드 또는 백업 파일 생성 중에 종료되었습니다.
** 네트워크 중단이 복구됩니다.


* 클러스터가 일정 기간 동안 액세스할 수 없게 된 경우 다음과 같은 상황에서 온라인 상태로 돌아갑니다.
+
** 네트워크 중단이 복구됩니다.
** WAN 연결이 느리면 정상적인 성능 데이터 수집이 지연됩니다.




데이터 연속성 수집 주기는 최대 24시간의 기록 데이터를 수집할 수 있습니다. Unified Manager가 24시간 이상 중단된 경우, UI 페이지에 성능 데이터의 차이가 나타납니다.

데이터 연속성 수집 주기와 실시간 데이터 수집 주기를 동시에 실행할 수 없습니다. 실시간 성능 데이터 수집이 시작되기 전에 데이터 연속성 수집 주기를 완료해야 합니다. 1시간 이상의 기간별 데이터를 취합하기 위해 데이터 연속성 수집이 필요한 경우 Performance 대시보드 상단에 해당 클러스터에 대한 배너 메시지가 표시됩니다.
