---
permalink: online-help/concept-metrocluster-configuration-verification.html 
sidebar: sidebar 
keywords:  
summary: MetroCluster 구성이 올바르게 설정되어 있는지 확인하여 MetroCluster 구성에서 미러링된 워크로드의 성능 문제를 방지할 수 있습니다. 또한 구성을 변경하거나 소프트웨어 또는 하드웨어 구성요소를 업그레이드하여 워크로드 성능을 향상할 수 있습니다. 
---
= MetroCluster 구성 검증
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 구성이 올바르게 설정되어 있는지 확인하여 MetroCluster 구성에서 미러링된 워크로드의 성능 문제를 방지할 수 있습니다. 또한 구성을 변경하거나 소프트웨어 또는 하드웨어 구성요소를 업그레이드하여 워크로드 성능을 향상할 수 있습니다.

FC(Fibre Channel) 스위치, 케이블 및 ISL(Inter-Switch Link)을 비롯하여 _MetroCluster 설치 및 구성 가이드_에서는 MetroCluster 구성에서 클러스터를 설정하기 위한 지침을 제공합니다. 또한 로컬 및 원격 클러스터가 미러 볼륨 데이터와 통신할 수 있도록 MetroCluster 소프트웨어를 구성하는 데도 도움이 됩니다.

MetroCluster 구성을 _MetroCluster 설치 및 구성 가이드_의 요구 사항과 비교하여 MetroCluster 구성에서 구성 요소를 변경하거나 업그레이드할 경우 작업 부하 성능이 향상될 수 있는지 확인할 수 있습니다. 이 비교는 다음 질문에 대한 해답을 제공합니다.

* 컨트롤러가 워크로드에 적합합니까?
* 더 많은 처리량을 처리하기 위해 ISL 번들을 더 큰 대역폭으로 업그레이드해야 합니까?
* 대역폭을 늘리기 위해 스위치의 버퍼 대 버퍼 크레딧(BBC)을 조정할 수 있습니까?
* 워크로드에 SSD(Solid State Drive) 스토리지에 대한 쓰기 처리량이 높은 경우 처리량을 수용하기 위해 FC-to-SAS 브릿지를 업그레이드해야 합니까?


MetroCluster 구성 요소 교체 또는 업그레이드에 대한 자세한 내용은 _MetroCluster 서비스 설명서_를 참조하십시오.
