---
permalink: online-help/concept-what-report-importing-is.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager에서 보고서 가져오기 옵션을 사용하여 보고서를 가져오고 가져온 보고서를 이름 및 간단한 설명과 함께 저장할 수 있습니다. 보고서를 가져오면 Unified Manager에서 제공하는 표준 보고서 외에도 사용자 지정 보고서를 환경에 추가할 수 있습니다. 
---
= 보고서를 가져오는 것은 무엇입니까
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager의 * Import Report * 옵션을 사용하여 보고서를 가져오고 가져온 보고서를 이름과 간단한 설명과 함께 저장할 수 있습니다. 보고서를 가져오면 Unified Manager에서 제공하는 표준 보고서 외에도 사용자 지정 보고서를 환경에 추가할 수 있습니다.

를 가져올 수 있습니다 `.rptdesign` 이미 생성된 파일입니다. 가져온 보고서를 실행, 공유, 예약 및 삭제할 수 있습니다.

Unified Manager는 가져오기 보고서 로그 파일을 jboss.log, ocum-report.log 및 ocserver-debug.log 파일에 저장합니다.

[NOTE]
====
고객 지원 부서는 보고서 설계를 지원하지 않지만 보고서 가져오기 작업 중에 발생하는 문제에 대해 지원을 제공합니다.

====
보고서 가져오기 기능에는 다음 지원이 포함됩니다.

* 열 범위가 1로 설정된 여러 머리글이 있는 보고서 (`colspan=1`)
* 차트가 있는 보고서만 해당
* 목록과 그리드만 있는 보고서
* 보고서에 사용된 암호는 ""base64"" 형식으로 인코딩되어야 합니다. 다른 인코딩 형식(예: ""JCE"" 형식)을 사용하는 보고서는 가져오기 프로세스 중에 오류를 발생시킬 수 있습니다.
* 데이터 집계가 포함된 보고서에는 보고서의 테이블 데이터에 집계된 열 요소가 포함되어야 합니다.


텍스트, CSV 및 Excel 형식의 보고서는 다음 시나리오에서 지원됩니다.

* 표 요소는 에서만 사용할 수 있습니다 `.rptdesign` 파일
* 머리글 행이 하나만 있는 테이블


[NOTE]
====
열 범위가 1보다 큰 보고서는 가져올 수 없습니다. 텍스트, CSV 또는 Excel 형식의 보고서에 둘 이상의 머리글 행이 있는 경우 첫 번째 머리글 행만 고려되고 나머지는 무시됩니다.

====