---
permalink: online-help/concept-sources-of-performance-events.html 
sidebar: sidebar 
keywords:  
summary: 성능 이벤트는 클러스터의 워크로드 성능과 관련된 문제입니다. 응답 시간이 느려 스토리지 객체를 식별하는 데 도움이 되며, 이를 지연 시간이라고도 합니다. 동시에 발생한 다른 상태 이벤트와 함께 응답 시간을 지연시켰거나 이로 인해 발생한 문제를 파악할 수 있습니다. 
---
= 성능 이벤트의 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능 이벤트는 클러스터의 워크로드 성능과 관련된 문제입니다. 응답 시간이 느려 스토리지 객체를 식별하는 데 도움이 되며, 이를 지연 시간이라고도 합니다. 동시에 발생한 다른 상태 이벤트와 함께 응답 시간을 지연시켰거나 이로 인해 발생한 문제를 파악할 수 있습니다.

Unified Manager는 다음 소스에서 성능 이벤트를 수신합니다.

* * 사용자 정의 성능 임계값 정책 이벤트 *
+
설정한 사용자 지정 임계값을 기반으로 성능 문제가 발생합니다. 성능 카운터의 임계값이 위반되었을 때 이벤트가 생성되도록 애그리게이트 및 볼륨 등의 스토리지 개체에 대한 성능 임계값 정책을 구성합니다.

+
이러한 이벤트를 수신하려면 성능 임계값 정책을 정의하고 스토리지 개체에 할당해야 합니다.

* * 시스템 정의 성능 임계값 정책 이벤트 *
+
시스템 정의된 임계값을 기반으로 하는 성능 문제입니다. 이러한 임계값 정책은 일반적인 성능 문제를 해결하기 위해 Unified Manager 설치에 포함됩니다.

+
이러한 임계값 정책은 기본적으로 활성화되어 있으며 클러스터를 추가한 직후에 이벤트를 볼 수 있습니다.

* * 동적 성능 임계값 이벤트 *
+
성능 문제는 IT 인프라에서 발생하는 장애 또는 오류 또는 클러스터 리소스를 과도하게 활용하는 워크로드의 결과입니다. 이러한 이벤트의 원인은 일정 기간 동안 자체적으로 해결되거나 수리 또는 구성 변경으로 해결될 수 있는 간단한 문제일 수 있습니다. 동적 임계값 이벤트는 공유 클러스터 구성 요소를 많이 사용하는 다른 워크로드로 인해 ONTAP 시스템의 볼륨 워크로드가 느리다는 것을 나타냅니다.

+
이러한 임계값은 기본적으로 설정되어 있으며 새 클러스터에서 데이터를 수집한 후 3일이 지나면 이벤트가 표시될 수 있습니다.


