---
permalink: online-help/concept-unified-manager-performance-monitoring-features.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager는 ONTAP 소프트웨어를 실행하는 시스템에서 성능 통계를 수집하고 분석합니다. 동적 성능 임계값과 사용자 정의 성능 임계값을 사용하여 많은 클러스터 구성 요소에 대해 다양한 성능 카운터를 모니터링합니다. 
---
= Unified Manager 성능 모니터링 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager는 ONTAP 소프트웨어를 실행하는 시스템에서 성능 통계를 수집하고 분석합니다. 동적 성능 임계값과 사용자 정의 성능 임계값을 사용하여 많은 클러스터 구성 요소에 대해 다양한 성능 카운터를 모니터링합니다.

응답 시간(지연 시간)이 높으면 예를 들어, 스토리지 객체(예: 볼륨)가 정상보다 느리게 작동하고 있음을 나타냅니다. 또한 이 문제는 볼륨을 사용하는 클라이언트 응용 프로그램의 성능이 저하되었음을 나타냅니다. Unified Manager는 성능 문제가 있는 스토리지 구성요소를 식별하고 성능 문제를 해결하기 위해 수행할 수 있는 권장 조치 목록을 제공합니다.

Unified Manager에는 다음과 같은 기능이 포함되어 있습니다.

* ONTAP 소프트웨어를 실행하는 시스템에서 워크로드 성능 통계를 모니터링 및 분석합니다.
* 클러스터, 노드, 애그리게이트, 포트, SVM에 대한 성능 카운터 추적 볼륨, LUN, NVMe 네임스페이스 및 LIF:
* IOPS(작업), MBps(처리량), 지연 시간(응답 시간), 활용률을 비롯한 시간별 워크로드 작업을 그래프로 표시합니다. 성능 용량 및 캐시 비율입니다.
* 임계값을 위반할 때 이벤트를 트리거하고 이메일 경고를 보내는 사용자 정의 성능 임계값 정책을 생성할 수 있습니다.
* 시스템 정의 임계값과 동적 성능 임계값을 사용하여 워크로드 활동을 파악하고 성능 문제를 알립니다.
* 경합 중인 클러스터 구성 요소를 명확하게 식별합니다.
* 클러스터 구성 요소를 과도하게 사용하는 워크로드 및 늘어난 활동에 의해 성능이 영향을 받는 워크로드를 식별합니다.

