---
permalink: online-help/concept-cluster-components-and-why-they-can-be-in-contention.html 
sidebar: sidebar 
keywords:  
summary: '클러스터 구성 요소의 경합이 발생할 때 클러스터 성능 문제를 식별할 수 있습니다. 구성 요소를 사용하는 볼륨 워크로드의 성능이 저하되고 클라이언트 요청에 대한 응답 시간(지연 시간\)이 증가하며, 이 경우 Unified Manager에서 이벤트가 발생합니다.' 
---
= 클러스터 구성 요소 및 구성 요소의 경합이 발생할 수 있는 이유
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 구성 요소의 경합이 발생할 때 클러스터 성능 문제를 식별할 수 있습니다. 구성 요소를 사용하는 볼륨 워크로드의 성능이 저하되고 클라이언트 요청에 대한 응답 시간(지연 시간)이 증가하며, 이 경우 Unified Manager에서 이벤트가 발생합니다.

경합이 발생한 구성 요소는 최적 수준에서 수행할 수 없습니다. 성능이 저하되었으며, _ 피해자라고 하는 다른 클러스터 구성 요소와 워크로드의 성능이 지연 시간을 증가했을 수 있습니다. 구성 요소의 경합을 줄이려면 작업 부하를 줄이거나 작업 처리 능력을 높여 성능이 정상 수준으로 돌아가도록 해야 합니다. Unified Manager는 5분 간격으로 워크로드 성능을 수집 및 분석하므로, 클러스터 구성 요소가 지속적으로 초과 사용되는 경우에만 감지합니다. 5분 간격 동안 짧은 시간 동안만 지속되는 일시적인 과사용량 급증은 감지되지 않습니다.

예를 들어, 스토리지 aggregate에서 발생하는 경합이 발생할 수 있습니다. 그 이유는 하나 이상의 워크로드가 I/O 요청을 이행하기 위해 경합하기 때문입니다. Aggregate의 다른 워크로드에 영향을 줄 수 있으므로 성능이 저하될 수 있습니다. 집합에서의 활동 양을 줄이기 위해 하나 이상의 워크로드를 덜 바쁜 Aggregate로 이동하는 것과 같이 현재 aggregate에 대한 전체 워크로드 수요를 줄일 수 있는 다양한 단계를 수행할 수 있습니다. QoS 정책 그룹의 경우 처리량 제한을 조정하거나 워크로드를 다른 정책 그룹으로 이동하여 워크로드가 더 이상 제한되지 않도록 할 수 있습니다.

Unified Manager에서 다음 클러스터 구성 요소를 모니터링하여 경합 상태를 경고합니다.

* 네트워크 *
+
클러스터의 iSCSI 프로토콜 또는 FC(Fibre Channel) 프로토콜에 의한 입출력 요청 대기 시간을 나타냅니다. 대기 시간은 클러스터가 I/O 요청에 응답하기 전에 iSCSI Ready to Transfer(R2T) 또는 FCP Transfer Ready(XFER_RDY) 트랜잭션이 완료될 때까지 기다리는 데 걸리는 시간입니다. 네트워크 구성 요소의 경합이 발생할 경우, 블록 프로토콜 계층의 높은 대기 시간이 하나 이상의 워크로드 지연 시간에 영향을 미치게 됩니다.

* * 네트워크 처리 *
+
프로토콜 계층과 클러스터 간의 I/O 처리와 관련된 클러스터의 소프트웨어 구성요소를 나타냅니다. 이벤트가 감지된 이후 네트워크 처리를 처리하는 노드가 변경되었을 수 있습니다. 네트워크 처리 구성 요소의 경합이 발생한 경우, 네트워크 처리 노드의 높은 사용률이 하나 이상의 워크로드 지연 시간에 영향을 미치고 있음을 의미합니다.

* * QoS 정책 *
+
워크로드가 구성원인 스토리지 QoS(서비스 품질) 정책 그룹을 나타냅니다. 정책 그룹 구성 요소의 경합이 발생한 경우 정책 그룹의 모든 워크로드가 설정된 처리량 제한에 따라 조절되고, 이로 인해 하나 이상의 워크로드 지연 시간이 영향을 받습니다.

* 클러스터 인터커넥트 *
+
클러스터된 노드가 물리적으로 연결된 케이블과 어댑터를 나타냅니다. 클러스터 인터커넥트 구성 요소의 경합이 발생한 경우, 클러스터 인터커넥트에서 I/O 요청이 있을 때까지 대기 시간이 길어 하나 이상의 워크로드 지연 시간에 영향을 미치게 됩니다.

* * 데이터 처리 *
+
는 클러스터와 워크로드를 포함하는 스토리지 애그리게이트 간의 I/O 처리와 관련된 클러스터의 소프트웨어 구성요소를 나타냅니다. 이벤트가 감지된 이후 데이터 처리를 처리하는 노드가 변경될 수 있습니다. 데이터 처리 구성 요소의 경합이 발생한 경우, 데이터 처리 노드의 높은 활용률이 하나 이상의 워크로드 지연 시간에 영향을 미치고 있음을 의미합니다.

* * MetroCluster 리소스 *
+
MetroCluster 구성에서 클러스터 간 데이터를 미러링하는 데 사용되는 NVRAM 및 ISL(Interswitch Link)을 비롯한 MetroCluster 리소스를 나타냅니다. MetroCluster 구성 요소의 경합이 발생한 경우, 로컬 클러스터의 워크로드로부터 높은 쓰기 처리량을 의미하거나 링크 상태 문제가 로컬 클러스터에 있는 하나 이상의 워크로드 지연 시간에 영향을 줍니다. 클러스터가 MetroCluster 구성에 없으면 이 아이콘이 표시되지 않습니다.

* * 애그리게이트 또는 SSD 애그리게이트 운영 *
+
워크로드가 실행되는 스토리지 애그리게이트를 나타냅니다. 애그리게이트 구성 요소의 경합이 발생할 경우, 애그리게이트의 활용률이 높아지면 하나 이상의 워크로드 지연 시간에 영향을 미치게 됩니다. Aggregate는 모든 HDD 또는 HDD와 SSD(Flash Pool 애그리게이트)의 혼합으로 구성됩니다. 'SSD Aggregate'는 모든 SSD(All-Flash 애그리게이트) 또는 SSD와 클라우드 계층(FabricPool 애그리게이트)의 혼합으로 구성됩니다.

* * 클라우드 지연 시간 *
+
클러스터 및 사용자 데이터가 저장되는 클라우드 계층 간의 I/O 처리와 관련된 클러스터의 소프트웨어 구성요소를 나타냅니다. 클라우드 지연 시간 구성 요소의 경합이 발생할 경우, 클라우드 계층에서 호스팅되는 볼륨의 대량 읽기가 하나 이상의 워크로드 지연 시간에 영향을 미치고 있음을 의미합니다.

* SnapMirror * 를 동기화합니다
+
SnapMirror Synchronous 관계의 기본 볼륨에서 보조 볼륨으로 사용자 데이터를 복제하는 것과 관련된 클러스터의 소프트웨어 구성요소를 나타냅니다. 동기식 SnapMirror 구성 요소의 경합이 발생한 경우, SnapMirror Synchronous 작업의 활동이 하나 이상의 워크로드 지연 시간에 영향을 미치고 있음을 의미합니다.


