---
permalink: online-help/concept-using-a-threshold-policy-with-the-node-failover-planning-page.html 
sidebar: sidebar 
keywords:  
summary: 잠재적 장애 조치가 테이크오버 노드의 성능을 허용할 수 없는 수준으로 떨어뜨릴 경우 성능/노드 장애 조치 계획 페이지에서 알림을 받을 수 있도록 노드 임계값 정책을 생성할 수 있습니다. 
---
= 노드 장애 조치 계획 페이지에서 임계값 정책 사용
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
잠재적 장애 조치가 테이크오버 노드의 성능을 허용할 수 없는 수준으로 떨어뜨릴 경우 성능/노드 장애 조치 계획 페이지에서 알림을 받을 수 있도록 노드 임계값 정책을 생성할 수 있습니다.

"노드 HA 쌍 초과 사용"이라는 시스템 정의 성능 임계값 정책은 임계값이 6개의 연속 수집 기간(30분)에 걸쳐 위반될 경우 경고 이벤트를 생성합니다. HA 쌍에서 노드의 결합된 성능 용량이 200%를 초과하면 임계값이 위반된 것으로 간주됩니다.

시스템 정의 임계값 정책의 이벤트는 페일오버로 인해 테이크오버 노드의 지연 시간이 허용되지 않는 수준으로 증가한다는 사실을 알립니다. 특정 노드에 대해 이 정책에 의해 생성된 이벤트가 표시되면 해당 노드의 성능/노드 장애 조치 계획 페이지로 이동하여 페일오버로 인한 예상 지연 시간 값을 볼 수 있습니다.

이 시스템 정의 임계값 정책을 사용하는 것 외에도 ""Performance Capacity Used - Takover"" 카운터를 사용하여 임계값 정책을 생성한 다음 선택한 노드에 정책을 적용할 수 있습니다. 임계값을 200%보다 낮게 지정하면 시스템 정의 정책의 임계값이 위반되기 전에 이벤트를 받을 수 있습니다. 시스템 정의 정책 이벤트가 생성되기 전에 알림을 받으려면 임계값을 초과하는 최소 기간을 30분 미만으로 지정할 수도 있습니다.

예를 들어, HA 쌍에서 노드의 결합된 성능 용량이 175%를 10분 이상 초과하면 경고 이벤트를 생성하도록 임계값 정책을 정의할 수 있습니다. 이 정책을 Node1과 Node2에 적용할 수 있습니다. Node2는 HA 쌍을 형성합니다. Node1 또는 Node2에 대한 경고 이벤트 알림을 수신한 후 해당 노드에 대한 성능/노드 페일오버 계획 페이지를 보고 테이크오버 노드에 대한 예상 성능 영향을 평가할 수 있습니다. 페일오버가 발생하는 경우 테이크오버 노드에 과부하가 발생하지 않도록 수정 조치를 취할 수 있습니다. 노드에 사용된 결합된 성능 용량이 200% 미만이면 테이크오버 노드의 지연 시간이 허용되지 않는 레벨에 도달하지 않습니다. 이는 페일오버 중에 발생하는 경우에도 마찬가지입니다.
