---
permalink: online-help/concept-volume-performance-explorer-page.html 
sidebar: sidebar 
keywords:  
summary: 이 페이지에서는 클러스터의 볼륨에 대한 자세한 성능 정보를 제공합니다. 이 페이지의 제목은 FlexVol 볼륨을 보고 있는지 FlexGroup 볼륨을 보고 있는지에 따라 달라집니다. 
---
= 성능/볼륨 또는 성능/FlexGroup 탐색기 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 페이지에서는 클러스터의 볼륨에 대한 자세한 성능 정보를 제공합니다. 이 페이지의 제목은 FlexVol 볼륨을 보고 있는지 FlexGroup 볼륨을 보고 있는지에 따라 달라집니다.

볼륨 또는 FlexGroup 탐색기 페이지에서 특정 기간 동안 볼륨 성능을 추적하고 비교할 수 있으므로 볼륨 성능을 문제 해결하고 미세 조정할 수 있습니다.

[NOTE]
====
루트 볼륨은 이 페이지에 표시되지 않습니다.

====
보기 및 비교 기능 사용:

* FlexVol 볼륨의 경우 이 볼륨의 성능을 다음과 비교할 수 있습니다.
+
** 같은 Aggregate의 다른 볼륨
** 이 볼륨이 상주하는 Aggregate입니다
** 이 볼륨이 상주하는 SVM
** 이 볼륨에 있는 LUN입니다


* FlexGroup 볼륨의 경우 이 FlexGroup의 성능을 다음과 비교할 수 있습니다.
+
** FlexGroup가 상주하는 애그리게이트입니다
** FlexGroup가 상주하는 SVM
** FlexGroup의 구성 볼륨입니다




차트의 통계는 각 수집 기간 후에 업데이트됩니다. 기본적으로 5분마다 업데이트됩니다. 선택기의 통계 보기 에서는 이전 시간 동안의 평균 통계를 표시하는 옵션을 제공합니다. 이 기능을 사용하면 NetApp ""성능 보장"" 프로그램을 지원하는 지연 시간 차트를 확인할 수 있습니다.

성능/볼륨 탐색기 또는 성능/FlexGroup 탐색기 페이지에서 다음을 수행할 수 있습니다.

* 임계값 관련 문제 및 세부 정보를 봅니다
* 볼륨 성능 데이터를 추적하고 비교합니다
* 임계값 관련 문제를 조사하고 해결합니다
* 성능 문제를 조사하고 해결합니다
* System Manager를 실행하여 볼륨의 구성을 변경합니다
+
OnCommand 관리자 또는 스토리지 관리자 역할을 사용하여 Unified Manager에 로그인하고 ONTAP 9.5 이상을 사용하는 경우 * 볼륨 구성 * 버튼을 사용할 수 있습니다.



[NOTE]
====
데이터 보호(DP) 볼륨의 경우 사용자 생성 트래픽에 대한 카운터 값만 표시됩니다. 8.3 이전 버전의 ONTAP 소프트웨어와 함께 클러스터를 설치하면 카운터 값이 표시되지 않습니다.

====