---
permalink: online-help/concept-what-reports-do.html 
sidebar: sidebar 
keywords:  
summary: 보고서에는 잠재적인 문제를 검토 및 식별할 수 있는 스토리지 개체에 대한 자세한 정보가 표시됩니다. 
---
= 보고서의 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
보고서에는 잠재적인 문제를 검토 및 식별할 수 있는 스토리지 개체에 대한 자세한 정보가 표시됩니다.

보고서를 저장, 삭제, 공유, 예약 및 가져올 수 있습니다. 특정 보고서를 검색할 수도 있습니다. 보고서를 사용자 지정하여 특정 사용 사례를 처리하고 나중에 사용할 수 있도록 사용자 지정된 보고서를 저장할 수 있습니다. 필터링, 정렬, 그룹화, 서식 지정 등의 추가 작업을 수행할 수 있습니다.

기본적으로 각 보고서 그룹은 보고서 유형 및 설명으로 표시됩니다. 보고서를 실행하여 특정 보고서 그룹을 볼 수 있습니다.

보고서를 실행한 후 보고서를 추가로 사용자 지정하고 사용자 지정 보고서를 저장할 수 있습니다. 보고서 페이지에 저장된 사용자 지정 보고서를 특정 보고서 범주 아래에 그룹화하여 볼 수 있습니다.

보고서를 보내도록 예약하거나 PDF, XHTML, CSV, XLS 또는 텍스트와 같은 지원되는 형식 중 하나로 보고서를 공유할 수 있습니다.

보고서를 다양한 형식으로 내보내고 데스크톱에 저장할 수 있습니다. 생성된 보고서에서 개별 열 데이터를 내보낼 수 있습니다.

보고서 설계 파일을 불러올 수 있습니다 (`.rptdesign` 파일)을 사용하여 가져온 보고서를 보고서 페이지에 저장합니다. 사용자 정의 보고서와 가져온 보고서를 삭제할 수 있습니다.

다음 보고서를 가져올 수 있습니다.

* 열 범위가 1로 설정된 여러 머리글이 있는 보고서
* 차트가 있는 보고서만 해당
* 목록과 그리드만 있는 보고서


텍스트, CSV 및 Excel 형식의 보고서는 다음 시나리오에서 지원됩니다.

* 표 요소는 에서만 사용할 수 있습니다 `.rptdesign` 파일
* 한 머리글만 행으로 표시되는 표


열 범위가 두 개 이상인 보고서는 가져올 수 없습니다. 텍스트, CSV 또는 Excel 형식의 보고서에 하나 이상의 머리글 행이 있는 경우 첫 번째 머리글 행만 고려되고 나머지 행은 무시됩니다.
