---
permalink: online-help/concept-how-annotation-rules-work-in-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: '주석 규칙은 스토리지 오브젝트(볼륨, 클러스터 또는 SVM(스토리지 가상 머신)\)에 주석을 다는 기준을 정의합니다. 조건 그룹 또는 조건을 사용하여 주석 규칙을 정의할 수 있습니다.' 
---
= Unified Manager에서 주석 규칙이 작동하는 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
주석 규칙은 스토리지 오브젝트(볼륨, 클러스터 또는 SVM(스토리지 가상 머신)에 주석을 다는 것을 정의하는 기준입니다. 조건 그룹 또는 조건을 사용하여 주석 규칙을 정의할 수 있습니다.

* 주석 규칙을 주석에 연결해야 합니다.
* 주석 규칙에 개체 유형을 연결해야 합니다. 주석 규칙에 대해 하나의 개체 유형만 연결할 수 있습니다.
* Unified Manager는 각 모니터링 주기가 끝난 후 또는 규칙이 생성, 편집, 삭제 또는 재정렬될 때 스토리지 개체에서 주석을 추가하거나 제거합니다.
* 주석 규칙에는 하나 이상의 조건 그룹이 있을 수 있으며 각 조건 그룹에는 하나 이상의 조건이 있을 수 있습니다.
* 스토리지 객체에는 여러 주석이 있을 수 있습니다. 특정 주석에 대한 주석 규칙은 규칙 조건에서 다른 주석을 사용하여 이미 주석이 추가된 개체에 다른 주석을 추가할 수도 있습니다.




== 조건

여러 조건 그룹을 만들 수 있으며 각 조건 그룹에는 하나 이상의 조건이 있을 수 있습니다. 스토리지 객체에 주석을 달려면 주석의 주석 규칙에 정의된 조건 그룹을 모두 적용할 수 있습니다.

조건 그룹 내의 조건은 논리 AND를 사용하여 실행됩니다. 조건 그룹의 모든 조건을 충족해야 합니다. 주석 규칙을 생성하거나 수정할 때 조건 그룹의 모든 조건을 충족하는 스토리지 객체만 적용, 선택 및 주석을 달 수 있는 조건이 생성됩니다. 주석을 추가할 스토리지 오브젝트의 범위를 좁히려는 경우 조건 그룹 내에서 여러 조건을 사용할 수 있습니다.

다음 피연산자와 연산자를 사용하고 필요한 값을 지정하여 저장소 개체로 조건을 만들 수 있습니다.

|===
| 스토리지 객체 유형입니다 | 적용 가능한 피연산자 


 a| 
볼륨
 a| 
* 개체 이름
* 소유 클러스터 이름입니다
* 소유 SVM 이름
* 주석




 a| 
SVM
 a| 
* 개체 이름
* 소유 클러스터 이름입니다
* 주석




 a| 
클러스터
 a| 
* 개체 이름
* 주석


|===
스토리지 개체의 피연산자로 주석을 선택하면 ""is"" 연산자를 사용할 수 있습니다. 다른 모든 피연산자의 경우 ""is"" 또는 ""Contains""를 연산자로 선택할 수 있습니다. ""is"" 연산자를 선택하면 선택한 피연산자에 대해 제공된 값을 사용하여 피연산자 값과 정확히 일치하는 조건이 평가됩니다. "포함" 연산자를 선택하면 다음 조건 중 하나를 충족하도록 조건이 평가됩니다.

* 피연산자 값은 선택한 피연산자의 값과 정확히 일치합니다.
* 피연산자 값은 선택한 피연산자에 대해 제공된 값을 포함합니다.




== 조건이 있는 주석 규칙의 예

다음 두 가지 조건이 있는 볼륨에 대해 하나의 조건 그룹이 있는 주석 규칙을 고려합니다.

* 이름에 "vol"이 포함되어 있습니다.
* SVM 이름은 "data_svm"입니다.


이 주석 규칙은 이름에 ""vol""이 포함되어 있고 선택한 주석 및 주석 유형이 "data_svm"인 SVM에서 호스팅되는 모든 볼륨에 주석을 추가합니다.



== 조건 그룹

조건 그룹은 논리 OR를 사용하여 실행된 다음 스토리지 객체에 적용됩니다. 스토리지 객체는 주석을 추가할 조건 그룹 중 하나의 요구 사항을 충족해야 합니다. 모든 조건 그룹의 조건을 충족하는 스토리지 객체에는 주석이 추가됩니다. 조건 그룹을 사용하여 주석을 추가할 스토리지 오브젝트의 범위를 늘릴 수 있습니다.



== 조건 그룹이 있는 주석 규칙의 예

볼륨에 대해 두 개의 조건 그룹이 있는 주석 규칙을 고려합니다. 각 그룹에는 다음 두 가지 조건이 포함됩니다.

* 조건 그룹 1
+
** 이름에 "vol"이 포함되어 있습니다.
** SVM 이름은 ""data_svm"입니다. 이 조건 그룹은 이름에 ""vol""이 포함되어 있고 SVM에서 ""data_svm""이라는 이름으로 호스팅되는 모든 볼륨에 주석을 답니다.


* 조건 그룹 2
+
** 이름에 "vol"이 포함되어 있습니다.
** 데이터 우선 순위의 주석 값은 ""위험""입니다. 이 조건 그룹은 이름에 ""vol""을 포함하고 데이터 우선 순위 주석 값으로 ""위험""으로 주석 표시된 모든 볼륨에 주석을 답니다.




이러한 두 조건 그룹이 포함된 주석 규칙이 스토리지 객체에 적용되면 다음 스토리지 객체에 주석이 추가됩니다.

* 이름에 "vol"이 포함되어 있고 이름이 "data_svm"인 SVM에서 호스팅되는 모든 볼륨.
* 이름에 ""vol""이 포함되어 있고 데이터 우선 순위 주석 값이 ""critical""로 표시된 모든 볼륨.

