---
permalink: online-help/concept-options-for-improving-workload-performance-from-the-client-side.html 
sidebar: sidebar 
keywords:  
summary: 애플리케이션 또는 데이터베이스와 같은 클라이언트 워크로드가 성능 이벤트와 관련된 볼륨에 I/O를 보내고 있는지 확인하여 클라이언트 측 변경이 이벤트를 해결할 수 있는지 파악할 수 있습니다. 
---
= 클라이언트측 워크로드 성능 향상을 위한 옵션
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
애플리케이션 또는 데이터베이스와 같은 클라이언트 워크로드가 성능 이벤트와 관련된 볼륨에 I/O를 보내고 있는지 확인하여 클라이언트 측 변경이 이벤트를 해결할 수 있는지 파악할 수 있습니다.

클러스터의 볼륨에 연결된 클라이언트가 I/O 요청을 늘릴 경우 클러스터가 더 열심히 작업하여 수요를 충족시켜야 합니다. 클러스터의 특정 볼륨에 대한 입출력 요청이 많은 클라이언트를 알고 있는 경우 볼륨에 액세스하는 클라이언트 수를 조정하거나 볼륨에 대한 I/O 양을 줄여 클러스터 성능을 향상시킬 수 있습니다. 볼륨이 구성원인 QoS 정책 그룹에 제한을 적용하거나 늘릴 수도 있습니다.

클라이언트 및 해당 애플리케이션을 조사하여 클라이언트가 평소보다 더 많은 입출력을 전송하는지 여부를 확인할 수 있습니다. 이로 인해 클러스터 구성 요소에서 충돌이 발생할 수 있습니다. 이벤트 세부 정보 페이지의 시스템 진단 섹션에 구성 요소를 사용하여 상위 볼륨 워크로드가 표시됩니다. 특정 볼륨에 액세스하는 클라이언트를 알고 있는 경우 클라이언트로 이동하여 클라이언트 하드웨어 또는 애플리케이션이 예상대로 작동하지 않는지 또는 평소보다 더 많은 작업을 수행하고 있는지 확인할 수 있습니다.

MetroCluster 구성에서는 로컬 클러스터의 볼륨에 대한 쓰기 요청이 원격 클러스터의 볼륨에 미러링됩니다. 로컬 클러스터의 소스 볼륨을 원격 클러스터의 대상 볼륨과 동기화하여 유지하면 MetroCluster 구성에서 두 클러스터의 수요가 증가할 수 있습니다. 이러한 미러링된 볼륨에 대한 쓰기 요청을 줄임으로써 클러스터는 더 적은 수의 동기화 작업을 수행할 수 있으므로 다른 워크로드에 대한 성능 영향이 줄어듭니다.
