---
permalink: online-help/reference-notifications-page.html 
sidebar: sidebar 
keywords:  
summary: 이벤트가 생성되거나 사용자에게 할당된 경우 알림을 보내도록 Unified Manager 서버를 구성할 수 있습니다. 알림 메커니즘을 구성할 수도 있습니다. 예를 들어, 알림을 e-메일 또는 SNMP 트랩으로 보낼 수 있습니다. 
---
= 설정/알림 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이벤트가 생성되거나 사용자에게 할당된 경우 알림을 보내도록 Unified Manager 서버를 구성할 수 있습니다. 알림 메커니즘을 구성할 수도 있습니다. 예를 들어, 알림을 e-메일 또는 SNMP 트랩으로 보낼 수 있습니다.

OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.



== 이메일

이 영역에서 알림 알림에 대한 다음 이메일 설정을 구성할 수 있습니다.

* * 보내는 사람 주소 *
+
경고 알림을 보낼 e-메일 주소를 지정합니다. 이 값은 공유 시 보고서의 보내는 사람 주소로도 사용됩니다. 보내는 사람 주소에 ""OnCommand@localhost.com" 주소가 미리 입력된 경우, 모든 이메일 알림이 성공적으로 전송되도록 실제 작업 이메일 주소로 변경해야 합니다.





== SMTP 서버

이 영역에서 다음 SMTP 서버 설정을 구성할 수 있습니다.

* * 호스트 이름 또는 IP 주소 *
+
지정된 수신자에게 알림 알림을 보내는 데 사용되는 SMTP 호스트 서버의 호스트 이름을 지정합니다.

* * 사용자 이름 *
+
SMTP 사용자 이름을 지정합니다. SMTP 사용자 이름은 SMTP 서버에서 SMTPAUTH가 활성화된 경우에만 필요합니다.

* * 암호 *
+
SMTP 암호를 지정합니다. SMTP 사용자 이름은 SMTP 서버에서 SMTPAUTH가 활성화된 경우에만 필요합니다.

* * 포트 *
+
SMTP 호스트 서버가 경고 알림을 보내는 데 사용하는 포트를 지정합니다.

+
기본값은 25입니다.

* * STARTTLS * 를 사용합니다
+
이 상자를 선택하면 TLS/SSL 프로토콜(start_tls 및 StartTLS라고도 함)을 사용하여 SMTP 서버와 관리 서버 간의 보안 통신을 제공합니다.

* * SSL 사용 *
+
이 확인란을 선택하면 SSL 프로토콜을 사용하여 SMTP 서버와 관리 서버 간의 보안 통신이 제공됩니다.





== SNMP를 선택합니다

이 영역에서 다음 SNMP 트랩 설정을 구성할 수 있습니다.

* * 버전 *
+
필요한 보안 유형에 따라 사용할 SNMP 버전을 지정합니다. 옵션에는 버전 1, 버전 3, 인증을 사용하는 버전 3, 인증 및 암호화를 사용하는 버전 3이 포함됩니다. 기본값은 버전 1입니다.

* * 트랩 대상 호스트 *
+
관리 서버에서 보낸 SNMP 트랩을 수신하는 호스트 이름 또는 IP 주소(IPv4 또는 IPv6)를 지정합니다.

* * 아웃바운드 트랩 포트 *
+
SNMP 서버가 관리 서버에서 보내는 트랩을 수신하는 포트를 지정합니다.

+
기본값은 162입니다.

* * 커뮤니티 *
+
호스트에 액세스할 커뮤니티 문자열입니다.

* * 엔진 ID *
+
SNMP 에이전트의 고유 식별자를 지정하며 관리 서버에서 자동으로 생성됩니다. 엔진 ID는 SNMP 버전 3, 인증을 사용하는 SNMP 버전 3, 인증 및 암호화를 사용하는 SNMP 버전 3에서 사용할 수 있습니다.

* * 사용자 이름 *
+
SNMP 사용자 이름을 지정합니다. 사용자 이름은 SNMP 버전 3, 인증을 사용하는 SNMP 버전 3, 인증 및 암호화를 사용하는 SNMP 버전 3에서 사용할 수 있습니다.

* * 인증 프로토콜 *
+
사용자를 인증하는 데 사용되는 프로토콜을 지정합니다. 프로토콜 옵션에는 MD5 및 SHA가 포함됩니다. MD5가 기본값입니다. 인증 프로토콜은 인증 및 암호화 기능이 있는 SNMP 버전 3 및 SNMP 버전 3에서 사용할 수 있습니다.

* * 인증 암호 *
+
사용자를 인증할 때 사용되는 암호를 지정합니다. 인증 암호는 인증 및 암호화 기능이 있는 SNMP 버전 3 및 인증 및 SNMP 버전 3에서 사용할 수 있습니다.

* * 개인 정보 보호 프로토콜 *
+
SNMP 메시지를 암호화하는 데 사용되는 개인 정보 보호 프로토콜을 지정합니다. 프로토콜 옵션에는 AES 128과 DES가 있습니다. 기본값은 AES 128입니다. 개인 정보 보호 프로토콜은 인증 및 암호화 기능이 있는 SNMP 버전 3에서 사용할 수 있습니다.

* * 개인 정보 보호 암호 *
+
개인 정보 보호 프로토콜을 사용할 때 암호를 지정합니다. 개인 정보 보호 암호는 인증 및 암호화 기능이 있는 SNMP 버전 3에서 사용할 수 있습니다.


