---
permalink: online-help/reference-remote-authentication-page.html 
sidebar: sidebar 
keywords:  
summary: 원격 인증 페이지를 사용하여 Unified Manager 웹 UI에 로그인하려는 원격 사용자를 인증하도록 Unified Manager를 인증 서버와 통신하도록 구성할 수 있습니다. 
---
= 원격 인증 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
원격 인증 페이지를 사용하여 Unified Manager 웹 UI에 로그인하려는 원격 사용자를 인증하도록 Unified Manager를 인증 서버와 통신하도록 구성할 수 있습니다.

OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

원격 인증 활성화 확인란을 선택한 후 인증 서버를 사용하여 원격 인증을 활성화할 수 있습니다.

* * 인증 서비스 *
+
Active Directory, OpenLDAP 등의 디렉터리 서비스 공급자에서 사용자를 인증하도록 관리 서버를 구성하거나 고유한 인증 메커니즘을 지정할 수 있습니다. 원격 인증을 설정한 경우에만 인증 서비스를 지정할 수 있습니다.

+
** * Active Directory *
+
*** 관리자 이름
+
인증 서버의 관리자 이름을 지정합니다.

*** 암호
+
인증 서버에 액세스할 암호를 지정합니다.

*** 기본 고유 이름
+
인증 서버에서 원격 사용자의 위치를 지정합니다. 예를 들어 인증 서버의 도메인 이름이 ou@domain.com 이면 기본 고유 이름은 입니다 `cn=ou,dc=domain,dc=com`.

*** 중첩된 그룹 조회를 비활성화합니다
+
중첩 그룹 조회 옵션을 사용할지 여부를 지정합니다. 기본적으로 이 옵션은 비활성화되어 있습니다. Active Directory를 사용하는 경우 중첩된 그룹에 대한 지원을 비활성화하여 인증 속도를 높일 수 있습니다.

*** 보안 연결을 사용합니다
+
인증 서버와 통신하는 데 사용되는 인증 서비스를 지정합니다.



** * OpenLDAP *
+
*** 고유 이름 바인딩
+
인증 서버에서 원격 사용자를 찾기 위해 기본 고유 이름과 함께 사용되는 바인딩 고유 이름을 지정합니다.

*** 바인딩 암호
+
인증 서버에 액세스할 암호를 지정합니다.

*** 기본 고유 이름
+
인증 서버에서 원격 사용자의 위치를 지정합니다. 예를 들어 인증 서버의 도메인 이름이 ou@domain.com 이면 기본 고유 이름은 입니다 `cn=ou,dc=domain,dc=com`.

*** 보안 연결을 사용합니다
+
보안 LDAP가 LDAPS 인증 서버와 통신하는 데 사용됨을 지정합니다.



** 기타 *
+
*** 고유 이름 바인딩
+
구성한 인증 서버에서 원격 사용자를 찾기 위해 기본 고유 이름과 함께 사용되는 바인딩 고유 이름을 지정합니다.

*** 바인딩 암호
+
인증 서버에 액세스할 암호를 지정합니다.

*** 기본 고유 이름
+
인증 서버에서 원격 사용자의 위치를 지정합니다. 예를 들어 인증 서버의 도메인 이름이 ou@domain.com 이면 기본 고유 이름은 입니다 `cn=ou,dc=domain,dc=com`.

*** 프로토콜 버전
+
인증 서버에서 지원하는 LDAP(Lightweight Directory Access Protocol) 버전을 지정합니다. 프로토콜 버전을 자동으로 감지할지 또는 버전을 2나 3으로 설정할지 지정할 수 있습니다.

*** 사용자 이름 특성
+
관리 서버에서 인증할 사용자 로그인 이름이 포함된 인증 서버의 속성 이름을 지정합니다.

*** 그룹 구성원 자격 특성
+
사용자의 인증 서버에 지정된 속성 및 값을 기반으로 관리 서버 그룹 구성원 자격을 원격 사용자에게 할당하는 값을 지정합니다.

*** UGID
+
원격 사용자가 인증 서버에 groupOfUniqueNames 개체의 구성원으로 포함된 경우 이 옵션을 사용하면 해당 groupOfUniqueNames 개체의 지정된 속성에 따라 관리 서버 그룹 구성원을 원격 사용자에게 할당할 수 있습니다.

*** 중첩된 그룹 조회를 비활성화합니다
+
중첩 그룹 조회 옵션을 사용할지 여부를 지정합니다. 기본적으로 이 옵션은 비활성화되어 있습니다. Active Directory를 사용하는 경우 중첩된 그룹에 대한 지원을 비활성화하여 인증 속도를 높일 수 있습니다.

*** 회원
+
인증 서버가 그룹의 개별 구성원에 대한 정보를 저장하는 데 사용하는 속성 이름을 지정합니다.

*** 사용자 객체 클래스
+
원격 인증 서버에 있는 사용자의 개체 클래스를 지정합니다.

*** 그룹 객체 클래스
+
원격 인증 서버에 있는 모든 그룹의 객체 클래스를 지정합니다.

*** 보안 연결을 사용합니다
+
인증 서버와 통신하는 데 사용되는 인증 서비스를 지정합니다.





+
[NOTE]
====
인증 서비스를 수정하려면 기존 인증 서버를 삭제하고 새 인증 서버를 추가해야 합니다.

====




== Authentication Servers 영역

인증 서버 영역에는 관리 서버가 원격 사용자를 찾고 인증하기 위해 통신하는 인증 서버가 표시됩니다. 원격 사용자 또는 그룹에 대한 자격 증명은 인증 서버에서 관리합니다.

* * 명령 버튼 *
+
인증 서버를 추가, 편집 또는 삭제할 수 있습니다.

+
** 추가
+
인증 서버를 추가할 수 있습니다.

+
추가하려는 인증 서버가 같은 데이터베이스를 사용하는 고가용성 쌍의 일부인 경우 파트너 인증 서버를 추가할 수도 있습니다. 이렇게 하면 인증 서버 중 하나에 연결할 수 없을 때 관리 서버가 파트너와 통신할 수 있습니다.

** 편집
+
선택한 인증 서버에 대한 설정을 편집할 수 있습니다.

** 삭제
+
선택한 인증 서버를 삭제합니다.



* * 이름 또는 IP 주소 *
+
관리 서버에서 사용자를 인증하는 데 사용되는 인증 서버의 호스트 이름 또는 IP 주소를 표시합니다.

* * 포트 *
+
인증 서버의 포트 번호를 표시합니다.

* * 인증 테스트 *
+
이 단추는 원격 사용자 또는 그룹을 인증하여 인증 서버 구성을 확인합니다.

+
테스트하는 동안 사용자 이름만 지정하면 관리 서버가 인증 서버에서 원격 사용자를 검색하지만 사용자를 인증하지는 않습니다. 사용자 이름과 암호를 모두 지정하면 관리 서버가 원격 사용자를 검색하고 인증합니다.

+
원격 인증이 비활성화되어 있으면 인증을 테스트할 수 없습니다.


