---
permalink: online-help/reference-volume-relationships-inventory-report.html 
sidebar: sidebar 
keywords:  
summary: 볼륨 관계 인벤토리 보고서를 사용하면 클러스터의 스토리지 인벤토리 세부 정보를 분석하고 볼륨에 필요한 보호 수준을 파악하며 장애 소스, 패턴 및 스케줄에 따라 볼륨 세부 정보를 필터링할 수 있습니다. 
---
= 볼륨 관계 인벤토리 보고서
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨 관계 인벤토리 보고서를 사용하면 클러스터의 스토리지 인벤토리 세부 정보를 분석하고 볼륨에 필요한 보호 수준을 파악하며 장애 소스, 패턴 및 스케줄에 따라 볼륨 세부 정보를 필터링할 수 있습니다.

볼륨 관계 인벤토리 보고서는 다음 두 가지 형식으로 표시됩니다.

* SnapMirror 관계 원형 차트 및 SnapVault 관계 원형 차트
* 볼륨 관계 인벤토리 보고서 표 형식 보기




== SnapMirror 및 SnapVault 원형 차트

스토리지 시스템에 있는 볼륨 관계의 구성 세부 정보를 표시합니다.



== 볼륨 관계 인벤토리 표 형식 보기

* * 관계 상태 *
+
클러스터의 관계 상태 정보를 표시합니다.

* * 관계 상태 *
+
SnapMirror 관계의 미러 상태를 표시합니다.

* * 전송 상태 *
+
SnapMirror 관계의 상태를 표시합니다.

* * 지연 상태 *
+
볼륨의 지연 상태를 표시합니다.

* * 소스 클러스터 *
+
SnapMirror 관계에 대한 소스 클러스터의 이름을 표시합니다.

* * 소스 SVM *
+
SnapMirror 관계에 대한 소스 SVM(스토리지 가상 시스템)의 이름을 표시합니다.

* * 소스 볼륨 *
+
SnapMirror 관계에 대한 소스 볼륨의 이름을 표시합니다.

* * 대상 클러스터 *
+
SnapMirror 관계에 대한 대상 클러스터의 이름을 표시합니다.

* * 대상 SVM *
+
SnapMirror 관계에 대한 대상 SVM(스토리지 가상 시스템)의 이름을 표시합니다.

* * 대상 볼륨 *
+
SnapMirror 관계에 대한 대상 볼륨의 이름을 표시합니다.

* * 관계 유형 *
+
SnapMirror 또는 SnapVault를 비롯한 관계 유형을 표시합니다.

* * 마지막으로 성공한 업데이트 시간 *
+
마지막으로 성공한 SnapMirror 또는 SnapVault 작업의 시간을 표시합니다.

* * 마지막 전송 기간(시간) *
+
마지막 데이터 전송을 완료하는 데 걸린 시간을 표시합니다.

* * 마지막 전송 크기(MB) *
+
마지막 데이터 전송의 크기(바이트)를 표시합니다.

* * 마지막 전송 종료 시간 *
+
마지막으로 성공한 SnapMirror 또는 SnapVault 작업이 완료된 시간을 표시합니다.

* * 비정상적인 이유 *
+
관계가 좋지 않은 상태에 있는 이유.

* * 지연 기간(시간) *
+
미러의 데이터가 소스 뒤에 걸리는 시간을 표시합니다.

* * 버전에 상관없이 유연하게 복제 *
+
백업 옵션과 함께 예, 예 또는 없음을 표시합니다.


