---
permalink: online-help/reference-capacity-all-volumes-view.html 
sidebar: sidebar 
keywords:  
summary: 상태/볼륨 용량 및 활용률 페이지에서는 클러스터에서 볼륨의 용량 및 활용도에 대한 정보를 볼 수 있습니다. 이 정보를 통해 가능한 용량 위험을 이해하고 구성된 볼륨, 사용된 용량 및 사용되지 않은 용량을 볼 수 있습니다. 또한 이 정보를 통해 중복제거, 씬 프로비저닝 등의 공간 절약 기능을 사용할 수 있는 의사 결정을 내릴 수 있습니다. 
---
= 상태/볼륨 용량 및 활용도 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
상태/볼륨 용량 및 활용률 페이지에서는 클러스터에서 볼륨의 용량 및 활용도에 대한 정보를 볼 수 있습니다. 이 정보를 통해 가능한 용량 위험을 이해하고 구성된 볼륨, 사용된 용량 및 사용되지 않은 용량을 볼 수 있습니다. 또한 이 정보를 통해 중복제거, 씬 프로비저닝 등의 공간 절약 기능을 사용할 수 있는 의사 결정을 내릴 수 있습니다.

모니터링되는 모든 볼륨의 세부 정보를 쉼표로 구분된 값으로 내보내려면 * Export * 버튼을 사용합니다 (`.csv`) 파일.

* * 클러스터 *
+
클러스터 이름입니다.

* * SVM *
+
볼륨을 포함하는 SVM(스토리지 가상 시스템)의 이름입니다.

* * 볼륨 *
+
볼륨 이름입니다.

* * 총 데이터 용량 *
+
볼륨의 총 데이터 용량(사용된 용량 및 사용 가능한 용량)

* * 사용된 데이터 용량 *
+
볼륨에서 사용된 데이터 용량입니다.

* * 사용된 데이터 % *
+
볼륨에서 사용된 데이터를 백분율로 나타낸 것입니다.

* * 사용 가능한 데이터 용량 *
+
볼륨에서 사용 가능한 데이터 용량입니다.

* * 사용 가능한 데이터 % *
+
볼륨에서 사용 가능한 데이터 용량입니다.

* * 일일 성장률 % *
+
볼륨에서 24시간마다 발생하는 성장률입니다.

* * 일 대 전체 *
+
볼륨이 전체 용량에 도달하기 전까지 남은 예상 일 수입니다.

* * 공간이 가득 참 임계값 % *
+
볼륨에서 가득 찬 것으로 간주되는 공간의 비율입니다.

* * 공간이 거의 가득 참 임계값 % *
+
볼륨에서 거의 가득 찬 것으로 간주되는 공간의 비율입니다.

* * 성장률 임계값 % *
+
시스템에서 Volume Growth Rate Abnormal 이벤트를 생성하기 전에 정상적인 것으로 간주되는 볼륨의 증가율입니다.

* * 성장률 감도 임계값 *
+
체적의 증가율의 표준 편차에 적용되는 계수. 증가율이 계수 표준 편차를 초과하면 Volume Growth Rate Abnormal 이벤트가 생성됩니다.

* * 최대 한계까지 남은 일수 *
+
전체 용량에 도달하기 전에 남은 일 수입니다.

* * 스냅샷 오버플로 % *
+
스냅샷 복사본에서 사용하는 데이터 공간의 비율입니다.

* * Snapshot Reserve Used Capacity *
+
볼륨의 스냅샷 복사본이 사용하는 공간입니다.

* * 사용된 스냅숏 예비 공간 % *
+
볼륨의 스냅샷 복사본에서 사용하는 공간의 비율입니다.

* * Snapshot Reserve Available Capacity *
+
볼륨의 스냅샷 복사본에 사용할 수 있는 공간의 양입니다.

* * Snapshot Reserve Available % *
+
볼륨의 스냅샷 복사본에 사용할 수 있는 공간의 비율입니다.

* * 스냅샷 예비 공간 총 용량 *
+
볼륨의 총 스냅샷 복사본 용량을 표시합니다.

* * Snapshot 복사본 예약 최대 임계값 % *
+
스냅샷 복사본에 예약된 공간이 가득 찬 것으로 간주되는 비율입니다.

* * 스냅샷 복사본 수 임계값 *
+
너무 많은 것으로 간주되는 볼륨의 스냅샷 복사본 수입니다.

* * Snapshot 복사본의 최소 한도를 최대 임계값 * 으로 설정합니다
+
스냅샷 복사본용으로 예약된 공간이 전체 용량에 도달하기 전까지 남은 일 수입니다.

* * inode 수 *
+
볼륨의 inode 수입니다.

* * inode 사용률 % *
+
볼륨에 사용된 inode 공간의 비율입니다.

* * inode 최대 임계값 % *
+
볼륨이 모든 inode를 사용한 것으로 간주되는 비율입니다.

* * inode 거의 전체 임계값 % *
+
볼륨이 대부분의 inode를 사용한 것으로 간주되는 비율입니다.

* * 할당량 커밋 용량 *
+
볼륨의 할당량에 예약된 공간입니다.

* * 할당량 초과 할당 용량 *
+
시스템에서 볼륨 할당량 초과 커밋 이벤트를 생성하기 전에 할당량에 사용할 수 있는 공간입니다.

* * 할당량 초과 커밋 임계값 % *
+
볼륨에서 할당량에 사용된 공간이 과도하게 커밋된 것으로 간주되는 백분율입니다.

* * 할당량이 거의 초과 커밋된 임계값 % *
+
볼륨에서 할당량에 사용된 공간이 거의 커밋된 것으로 간주되는 백분율입니다.

* * 스냅샷 자동 삭제 *
+
스냅샷 복사본의 자동 삭제를 설정 또는 해제할지 여부를 나타냅니다.

* * 데이터 중복 제거 *
+
볼륨에 대해 중복 제거가 설정되었는지 여부를 나타냅니다.

* * 데이터 중복 제거 공간 절약 *
+
중복제거를 사용하여 볼륨에서 저장되는 공간의 양입니다.

* * 압축 *
+
볼륨에 대해 압축이 활성화되어 있는지 또는 비활성화되어 있는지 여부

* * 압축 공간 절약 *
+
압축을 사용하여 볼륨에서 저장한 공간 크기입니다.

* * 캐싱 정책 *
+
선택한 볼륨과 연결된 캐싱 정책입니다.

+
정책에 따라 볼륨에 대한 Flash Pool 캐싱이 수행되는 방법이 나와 있습니다. 캐시 정책에 대한 자세한 내용은 상태/볼륨 인벤토리 페이지를 참조하십시오.

* * 캐시 보존 우선순위 *
+
캐시된 풀을 유지하는 데 사용되는 우선 순위입니다.

* * 씬 프로비저닝 *
+
선택한 볼륨에 대해 공간 보장이 설정되어 있는지 여부를 나타냅니다. 유효한 값은 Yes 및 No입니다

* * Autogrow *
+
공간이 부족할 때 볼륨 크기가 자동으로 증가하는지 여부를 나타냅니다.

* * 공간 보장 *
+
볼륨과 연결된 스토리지 보증 옵션입니다.

* * 보호 역할 *
+
볼륨에 대해 설정된 보호 역할입니다.

* * 시/도 *
+
내보내는 볼륨의 상태입니다.

* * SnapLock 유형 *
+
볼륨이 SnapLock 볼륨인지 또는 비 SnapLock 볼륨인지를 나타냅니다.

* * SnapLock 만료 날짜 *
+
SnapLock 만료 날짜입니다.

* * 계층화 정책 *
+
볼륨에 대해 설정된 계층화 정책입니다. FabricPool 지원 애그리게이트에만 구축할 수 있습니다.


