---
permalink: online-help/reference-dashboards-performance-page.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager Performance Dashboard를 사용하면 모니터링 중인 모든 클러스터의 높은 성능 상태를 확인할 수 있습니다. 또한 Unified Manager가 모니터링 중인 클러스터와 통신할 수 없는 경우 대시보드/성능 페이지에 배너 메시지가 표시됩니다. 
---
= 대시보드/성능 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager Performance Dashboard를 사용하면 모니터링 중인 모든 클러스터의 높은 성능 상태를 확인할 수 있습니다. 또한 Unified Manager가 모니터링 중인 클러스터와 통신할 수 없는 경우 대시보드/성능 페이지에 배너 메시지가 표시됩니다.



== 개요

클러스터는 다음 기준을 사용하여 심각도에 따라 정렬됩니다.

. 클러스터에 연결할 수 없는 경우
. 클러스터에 하나 이상의 활성 중요 성능 이벤트가 있는 경우(빨간색 개체 아이콘)
. 클러스터에 하나 이상의 활성 경고 성능 이벤트가 있는 경우(노란색 개체 아이콘)
. 클러스터에 활성 성능 이벤트가 없는 경우(녹색 개체 아이콘) 클러스터는 최고 IOPS를 기준으로 정렬됩니다.


중요 이벤트는 사용자 정의 성능 임계값 정책의 중요 제한을 초과할 때 생성됩니다. 경고 이벤트는 사용자 정의 성능 임계값 정책의 경고 제한을 초과하거나 시스템 정의 임계값 정책 또는 동적 임계값을 초과할 때 전송됩니다.

[NOTE]
====
정렬 순서는 이벤트가 있는 개체 수가 아니라 활성(새 이벤트 또는 확인된) 이벤트의 총 수에 따라 결정됩니다. 예를 들어, 클러스터 A에 7개의 중요한 볼륨 지연 이벤트가 있는 경우 클러스터 B에는 2개의 중요 볼륨 지연 이벤트와 2개의 중요 노드 IOPS 이벤트(총 4개의 중요 이벤트)가 있으며, 클러스터 B에 2개의 빨간색 개체 아이콘이 있더라도 클러스터 A(빨간색 개체 아이콘 1개 포함)가 목록에 더 높게 표시됩니다.

====
각 클러스터에 대해 일반적으로 모니터링되는 다음과 같은 이벤트 유형이 표시됩니다.

* SVM(스토리지 가상 시스템), 볼륨 및 LUN에 대한 지연 시간 이벤트입니다
* 노드 및 SVM에 대한 IOPS 이벤트입니다
* 노드 및 SVM에 대한 MBps 이벤트
* 노드 및 애그리게이트에 대해 이벤트를 사용할 수 있는 성능 용량입니다
* 노드 및 애그리게이트의 활용률 이벤트


Unified Manager는 Aggregate의 경우 Mbps 이벤트, 볼륨의 IOPS 이벤트 등과 같은 다른 스토리지 객체와 카운터에 대한 성능 이벤트를 수신할 수 있습니다. 클러스터에 이러한 유형의 이벤트가 있는 경우 클러스터 이름 옆의 아이콘은 경고(노란색) 또는 위험(빨간색) 이벤트를 나타냅니다. 이 아이콘은 5개의 카운터 패널 아이콘 중 하나라도 노란색 또는 빨간색인 경우 이벤트가 존재함을 나타낼 수 있습니다. 이러한 이벤트 유형은 기존 카운터 패널 범주에 적합하지 않기 때문입니다.

오브젝트 아이콘을 클릭하여 해당 오브젝트에 대한 성능 인벤토리 페이지를 표시할 수 있으며 이 오브젝트에서 해당 유형의 모든 오브젝트를 볼 수 있습니다. 예를 들어, 볼륨 아이콘을 클릭하면 성능/볼륨 인벤토리 페이지가 표시되고 선택한 클러스터에 있는 모든 볼륨 목록이 최악에서 최적 성능으로 정렬됩니다.



== 성능 카운터

각 클러스터에 대해 각각 별도의 패널에 표시되는 5개의 성능 카운터가 있습니다. 이 정보는 5분 수집 기간 후 자동으로 업데이트됩니다.

|===
| 카운터 | 설명 


 a| 
지연 시간
 a| 
에서는 클러스터가 클라이언트 애플리케이션 요청에 얼마나 빠르게 응답하는지 작업(ms/op)당 밀리초 단위로 보여 줍니다. 아이콘 영역은 임계값 설정을 교차하는 지연 시간 값을 기반으로 SVM, 볼륨 또는 LUN에 활성 이벤트가 있는지 여부를 나타냅니다.



 a| 
IOPS
 a| 
에는 스토리지 시스템의 운영 속도(IOPS)가 나와 있습니다.

* 아이콘 영역은 임계값 설정에 교차하는 IOPS 수에 따라 모든 노드 또는 SVM에 활성 이벤트가 있는지 여부를 나타냅니다.
* 아래쪽 영역에는 마지막 5분 동안의 총 클러스터 IOPS가 표시됩니다.




 a| 
Mbps
 a| 
클러스터에서 또는 클러스터에서 전송되는 데이터의 양을 MB/sec(메가바이트/초) 단위로 표시합니다.

* 아이콘 영역은 어떤 노드나 SVM에 임계값 설정을 교차하는 MBPS 값을 기반으로 활성 이벤트가 있는지 여부를 나타냅니다.
* 아래쪽 영역에는 최근 5분 동안의 총 클러스터 처리량이 표시됩니다.




 a| 
사용된 성능 용량
 a| 
에는 노드나 애그리게이트에서 사용 가능한 성능 용량을 과도하게 사용하고 있는지 여부가 나와 있습니다.

* 아이콘 영역은 사용된 성능 용량이 임계값 설정을 초과하는지 여부를 기준으로 노드나 애그리게이트의 활성 이벤트가 있는지 여부를 나타냅니다.
* 하단 영역에는 가장 바쁜 노드와 가장 바쁜 집계에서 사용된 가장 높은 성능 용량이 표시됩니다.


[NOTE]
====
성능 용량 데이터는 클러스터의 노드가 ONTAP 9.0 이상 소프트웨어와 함께 설치된 경우에만 사용할 수 있습니다.

====


 a| 
활용률
 a| 
노드나 애그리게이트의 리소스가 초과 사용되고 있는지 여부를 표시합니다.

* 아이콘 영역은 임계값 설정을 교차하는 사용률 값에 따라 활성 이벤트가 노드 또는 애그리게이트에 있는지 여부를 나타냅니다.
* 하단 영역에는 가장 바쁜 노드와 가장 바쁜 집계에서 가장 높은 사용률 값이 표시됩니다.


|===
줄임표(...) 헤더 영역에서 성능 데이터가 현재 수집되고 있음을 나타냅니다.

성능 이벤트가 있는 클러스터의 경우 * 클러스터 세부 정보 보기 * 를 클릭하여 성능 클러스터 랜딩 페이지를 표시할 수 있습니다. 이 페이지에서 클러스터 및 기타 스토리지 개체에 대한 자세한 성능 정보를 볼 수 있습니다.



== 클러스터 상태 메시지

Unified Manager에서 관리하는 클러스터를 사용할 수 없게 되면 성능 카운터 위에 상태 메시지 배너가 표시됩니다. 클러스터에 연결할 수 없는 경우 상태 메시지 배너 오른쪽에 * Details * 버튼이 표시됩니다. 상태 메시지에서 * Details * 버튼을 클릭하면 문제에 대한 전체 정보를 보여주는 Cluster Data Sources 페이지로 이동할 수 있습니다. 클러스터 데이터 소스 페이지에서 클러스터를 사용할 수 없게 만든 문제를 해결하는 데 필요한 데이터를 찾을 수 있습니다.
