---
permalink: online-help/reference-event-setup-page.html 
sidebar: sidebar 
keywords:  
summary: 구성/이벤트 관리 페이지에는 비활성화된 이벤트 목록이 표시되며 연결된 개체 유형 및 이벤트 심각도와 같은 정보가 제공됩니다. 또한 이벤트를 전역적으로 비활성화하거나 활성화하는 등의 작업을 수행할 수도 있습니다. 
---
= 이벤트 구성/관리 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
구성/이벤트 관리 페이지에는 비활성화된 이벤트 목록이 표시되며 연결된 개체 유형 및 이벤트 심각도와 같은 정보가 제공됩니다. 또한 이벤트를 전역적으로 비활성화하거나 활성화하는 등의 작업을 수행할 수도 있습니다.

OnCommand 관리자 또는 스토리지 관리자 역할이 있는 경우에만 이 페이지에 액세스할 수 있습니다.



== 명령 버튼

명령 단추를 사용하여 선택한 이벤트에 대해 다음 작업을 수행할 수 있습니다.

* * 비활성화 *
+
이벤트 사용 안 함 대화 상자를 시작합니다. 이 대화 상자에서 이벤트를 사용하지 않도록 설정할 수 있습니다.

* * 활성화 *
+
이전에 비활성화하도록 선택한 이벤트를 활성화합니다.

* * EMS 이벤트 가입 *
+
모니터링 중인 클러스터에서 특정 EMS(Event Management System) 이벤트를 수신할 수 있도록 구독할 수 있는 EMS 이벤트 등록 대화 상자를 시작합니다. EMS는 클러스터에서 발생하는 이벤트에 대한 정보를 수집합니다. 가입된 EMS 이벤트에 대한 알림을 수신하면 Unified Manager 이벤트가 적절한 심각도로 생성됩니다.

* * 이벤트 보존 설정 *
+
관리 서버에서 정보, 해결된 이벤트 및 사용되지 않는 이벤트를 제거한 후 보존 기간을 지정할 수 있는 이벤트 보존 설정 대화 상자를 시작합니다. 기본 보존 값은 180일입니다.





== 목록 보기

목록 보기는 비활성화된 이벤트에 대한 정보를 표 형식으로 표시합니다. 열 필터를 사용하여 표시되는 데이터를 사용자 지정할 수 있습니다.

* * 이벤트 *
+
비활성화된 이벤트의 이름을 표시합니다.

* * 심각도 *
+
이벤트의 심각도를 표시합니다. 심각성은 Critical, Error, Warning 또는 Information 일 수 있습니다.

* * 소스 유형 *
+
이벤트가 생성되는 소스 유형을 표시합니다.


