---
permalink: online-help/reference-create-storage-virtual-machine-associations-wizard.html 
sidebar: sidebar 
keywords:  
summary: '스토리지 가상 시스템 연결 생성 마법사를 사용하면 소스 및 타겟 스토리지 가상 머신 \(SVM\)을 SnapMirror 및 SnapVault 보호 관계에 사용할 수 있도록 연결할 수 있습니다.' 
---
= 스토리지 가상 머신 연결 생성 마법사
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 가상 시스템 연결 생성 마법사를 사용하면 소스 및 타겟 스토리지 가상 머신(SVM)을 SnapMirror 및 SnapVault 보호 관계에 사용할 수 있도록 연결할 수 있습니다.



== 소스 SVM을 선택합니다

Select Source Storage Virtual Machine 패널을 사용하면 SVM 연관에서 소스 또는 1차 SVM을 선택할 수 있습니다.

* * 모두 *
+
SVM 소스에서 하나 이상의 대상 또는 보조, SVM 간에 연결을 생성할 수 있습니다. 즉, 향후에 생성된 SVM뿐만 아니라 현재 보호가 필요한 모든 기존 SVM이 지정된 대상 SVM과 연계됩니다. 예를 들어, 서로 다른 위치에 있는 여러 소스의 애플리케이션을 한 위치의 하나 이상의 대상 SVM에 백업할 수 있습니다.

* * 단일 *
+
특정 소스 SVM을 하나 이상의 타겟 SVM과 연결할 수 있습니다. 예를 들어, 데이터가 서로 분리되어 있어야 하는 여러 클라이언트에 스토리지 서비스를 제공하는 경우 이 옵션을 선택하여 특정 SVM 소스를 해당 클라이언트에만 할당된 특정 SVM 타겟에 연계합니다.

* * 없음(외부) *
+
소스 SVM과 타겟 SVM의 유연한 외부 볼륨 간의 연결을 생성할 수 있습니다.

+
** 스토리지 가상 머신
+
에는 사용 가능한 소스 SVM의 이름이 나와 있습니다

** 클러스터
+
에는 각 SVM이 상주하는 클러스터가 나와 있습니다



* * 이러한 종류의 관계를 허용합니다 *
+
연결에 대한 관계 유형을 선택할 수 있습니다.

+
** SnapMirror를 참조하십시오
+
연결 유형으로 SnapMirror 관계를 지정합니다. 이 옵션을 선택하면 선택한 소스에서 선택한 대상으로 데이터를 복제할 수 있습니다.

** SnapVault
+
SnapVault 관계를 연결 유형으로 지정합니다. 이 옵션을 선택하면 선택한 기본 위치에서 선택한 보조 위치로 백업을 수행할 수 있습니다.







== 보호 대상 을 선택합니다

Create Storage Virtual Machine Associations 마법사의 Select Protection Destinations 패널에서는 데이터를 복제 또는 복제할 위치를 선택할 수 있습니다. 클러스터당 하나의 대상 SVM에만 연관을 생성할 수 있습니다.



== 명령 버튼

명령 단추를 사용하여 다음 작업을 수행할 수 있습니다.

* * 다음 *
+
마법사의 다음 페이지로 이동합니다.

* * 뒤로 *
+
마법사의 이전 페이지로 돌아갑니다.

* * 마침 *
+
선택 사항을 적용하고 연결을 만듭니다.

* * 취소 *
+
선택 사항을 취소하고 스토리지 가상 머신 연결 생성 마법사를 닫습니다.


