---
permalink: online-help/reference-add-alert-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 알림을 생성하여 특정 이벤트가 생성될 때 알림을 받을 수 있으므로 문제를 신속하게 해결하고 환경에 미치는 영향을 최소화할 수 있습니다. 단일 리소스 또는 리소스 집합, 특정 심각도 유형의 이벤트에 대한 알림을 생성할 수 있습니다. 알림 방법 및 알림 빈도를 지정할 수도 있습니다. 
---
= 경고 추가 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
알림을 생성하여 특정 이벤트가 생성될 때 알림을 받을 수 있으므로 문제를 신속하게 해결하고 환경에 미치는 영향을 최소화할 수 있습니다. 단일 리소스 또는 리소스 집합, 특정 심각도 유형의 이벤트에 대한 알림을 생성할 수 있습니다. 알림 방법 및 알림 빈도를 지정할 수도 있습니다.

OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.



== 이름

이 영역에서 알림의 이름과 설명을 지정할 수 있습니다.

* * 경고 이름 *
+
경고 이름을 지정할 수 있습니다.

* * 경고 설명 *
+
경고에 대한 설명을 지정할 수 있습니다.





== 리소스

이 영역에서는 알림을 트리거할 동적 규칙에 따라 개별 리소스를 선택하거나 리소스를 그룹화할 수 있습니다. _dynamic rule_은 지정한 텍스트 문자열을 기준으로 필터링된 자원 집합입니다. 드롭다운 목록에서 리소스 유형을 선택하여 자원을 검색하거나 정확한 자원 이름을 지정하여 특정 자원을 표시할 수 있습니다.

스토리지 객체 세부 정보 페이지에서 알림을 생성하는 경우 스토리지 객체가 알림에 자동으로 포함됩니다.

* * 포함 *
+
경고를 트리거할 리소스를 포함할 수 있습니다. 문자열과 일치하는 리소스를 그룹화하는 텍스트 문자열을 지정하고 경고에 포함할 이 그룹을 선택할 수 있습니다. 예를 들어 이름이 ""abc"" 문자열을 포함하는 모든 볼륨을 그룹화할 수 있습니다.

* * 제외 *
+
알림을 트리거하지 않을 리소스를 제외할 수 있습니다. 예를 들어 이름이 ""xyz"" 문자열을 포함하는 모든 볼륨을 제외할 수 있습니다.

+
제외 탭은 특정 자원 유형의 모든 자원을 선택한 경우에만 표시됩니다(예: <<All Volumes>> 또는 <<All Volumes whose name contains '_xyz_'>>.

+
자원이 지정한 포함 및 제외 규칙을 모두 준수하는 경우 제외 규칙이 포함 규칙보다 우선하며 이벤트에 대해 알림이 생성되지 않습니다.





== 이벤트

이 영역에서 알림을 생성할 이벤트를 선택할 수 있습니다. 특정 심각도 또는 이벤트 집합을 기반으로 이벤트에 대한 알림을 생성할 수 있습니다.

둘 이상의 이벤트를 선택하려면 Ctrl 키를 누른 상태에서 선택해야 합니다.

* * 이벤트 심각도 *
+
심각도 유형을 기반으로 이벤트를 선택할 수 있습니다. 심각도 유형은 위험, 오류 또는 경고일 수 있습니다.

* * 이벤트 이름에 * 가 포함되어 있습니다
+
이름에 지정된 문자가 포함된 이벤트를 선택할 수 있습니다.





== 작업

이 영역에서는 알림이 트리거될 때 알릴 사용자를 지정할 수 있습니다. 알림 방법 및 알림 빈도를 지정할 수도 있습니다.

* * 이 사용자에게 알림 *
+
알림을 수신할 사용자의 이메일 주소 또는 사용자 이름을 지정할 수 있습니다.

+
사용자에 대해 지정된 전자 메일 주소를 수정하고 편집을 위해 알림을 다시 열면 수정된 전자 메일 주소가 이전에 선택한 사용자에게 더 이상 매핑되지 않으므로 이름 필드가 비어 있습니다. 또한 관리/사용자 페이지에서 선택한 사용자의 전자 메일 주소를 수정한 경우 선택한 사용자에 대해 수정된 전자 메일 주소가 업데이트되지 않습니다.

* * 알림 빈도 *
+
이벤트를 확인, 확인 또는 폐기 상태로 이동할 때까지 관리 서버가 알림을 보내는 빈도를 지정할 수 있습니다.

+
다음 알림 방법을 선택할 수 있습니다.

+
** 한 번만 알립니다
** 지정된 빈도로 알립니다
** 지정된 시간 범위 내에 지정된 빈도로 알립니다


* * SNMP 트랩 * 을 실행합니다
+
이 상자를 선택하면 SNMP 트랩을 전역적으로 구성된 SNMP 호스트로 전송할지 여부를 지정할 수 있습니다.

* * 스크립트 실행 *
+
알림에 사용자 지정 스크립트를 추가할 수 있습니다. 이 스크립트는 경고가 생성될 때 실행됩니다.





== 명령 버튼

* * 저장 *
+
알림을 생성하고 대화 상자를 닫습니다.

* * 취소 *
+
변경 내용을 취소하고 대화 상자를 닫습니다.


