---
permalink: online-help/reference-advanced-secondary-setting-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 고급 보조 설정 대화 상자를 사용하여 버전에 상관없이 유연하게 복제, 다중 복사본 백업 및 보조 볼륨에서 공간 관련 설정을 활성화할 수 있습니다. 현재 설정을 활성화 또는 비활성화하려는 경우 고급 보조 설정 대화 상자를 사용할 수 있습니다. 
---
= 고급 보조 설정 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
고급 보조 설정 대화 상자를 사용하여 버전에 상관없이 유연하게 복제, 다중 복사본 백업 및 보조 볼륨에서 공간 관련 설정을 활성화할 수 있습니다. 현재 설정을 활성화 또는 비활성화하려는 경우 고급 보조 설정 대화 상자를 사용할 수 있습니다.

공간 관련 설정은 중복제거, 데이터 압축, 자동 확장, 공간 보장과 같이 저장되는 데이터의 양을 극대화합니다.

대화 상자에는 다음 필드가 포함되어 있습니다.

* * 버전에 상관없이 유연하게 복제 * 를 활성화합니다
+
버전에 상관없이 유연하게 복제 가능한 SnapMirror를 지원합니다. 버전에 상관없이 유연한 복제를 사용하면 소스 볼륨과 타겟 볼륨 모두에서 ONTAP 8.3 이상이 실행되는 한, 타겟 볼륨이 소스 볼륨의 이전 버전인 ONTAP에서 실행 중인 경우에도 소스 볼륨의 SnapMirror를 보호할 수 있습니다.

+
** 백업을 활성화합니다
+
버전에 상관없이 유연하게 복제할 수 있는 경우 SnapMirror 소스 데이터의 여러 스냅샷 복사본도 SnapMirror 대상에 전송 및 유지됩니다.



* * 중복 제거 사용 *
+
SnapVault 관계에서 2차 볼륨의 중복제거를 지원하여 중복 데이터 블록을 제거하여 공간을 절약합니다. 절약 공간이 10% 이상, 데이터 덮어쓰기 속도가 빠른 경우에는 중복제거를 사용할 수 있습니다. 중복 제거는 가상화된 환경, 파일 공유 및 백업 데이터에 주로 사용됩니다. 이 설정은 기본적으로 비활성화되어 있습니다. 이 기능을 활성화하면 각 전송 후에 이 작업이 시작됩니다.

+
** 압축을 설정합니다
+
투명한 데이터 압축을 지원합니다. 공간 절약 효과가 10% 이상, 잠재적 오버헤드를 허용할 때, 그리고 비사용 시간 동안 압축을 완료할 수 있는 시스템 리소스가 충분할 때 압축을 사용할 수 있습니다. SnapVault 관계에서는 이 설정이 기본적으로 사용되지 않습니다. 압축은 중복제거를 선택한 경우에만 사용할 수 있습니다.

** 인라인 압축
+
데이터를 디스크에 쓰기 전에 데이터를 압축하여 공간을 즉시 절약할 수 있습니다. 피크 시간 동안 시스템의 활용률이 50%를 넘지 않고 시스템이 피크 시간 동안 새로운 쓰기와 추가 CPU를 수용할 수 있는 경우 인라인 압축을 사용할 수 있습니다. 이 설정은 ""압축 활성화""가 선택된 경우에만 사용할 수 있습니다.



* * Autogrow 사용 *
+
연결된 Aggregate에서 사용 가능한 공간이 있는 경우, 사용 가능한 공간 비율이 지정된 임계값 미만이면 대상 볼륨을 자동으로 확장할 수 있습니다.

* * 최대 크기 *
+
볼륨이 커질 수 있는 최대 비율을 설정합니다. 기본값은 소스 볼륨 크기보다 20% 더 큽니다. 현재 크기가 최대 자동 확장 비율보다 크거나 같은 경우에는 볼륨이 자동으로 확장되지 않습니다. 이 필드는 자동 확장 설정이 활성화된 경우에만 활성화됩니다.

* * 증분 크기 *
+
소스 볼륨의 최대 비율에 도달하기 전에 볼륨이 자동으로 증가하는 비율을 지정합니다.

* * 공간 보장 *
+
보조 볼륨에 충분한 공간이 할당되어 데이터 전송이 항상 성공하도록 합니다. 공간 보장 설정은 다음 중 하나일 수 있습니다.

+
** 파일
** 볼륨
** 없음 예를 들어 총 50GB의 파일을 포함하는 200GB 볼륨이 있을 수 있지만 이러한 파일은 10GB의 데이터만 저장합니다. 볼륨 보장은 소스의 컨텐츠에 관계없이 대상 볼륨에 200GB를 할당합니다. 파일 보증은 소스 파일에 충분한 공간이 확보되도록 50GB를 할당합니다. 이 시나리오에서 없음 을 선택하면 소스의 파일 데이터에 의해 사용되는 실제 공간에 대해 대상에 10GB만 할당됩니다.


+
공간 보장은 기본적으로 볼륨 으로 설정됩니다.





== 명령 버튼

명령 단추를 사용하여 다음 작업을 수행할 수 있습니다.

* * 적용 *
+
보호 구성 대화 상자에서 * 적용 * 을 클릭하면 선택한 효율성 설정을 저장하고 적용합니다.

* * 취소 *
+
선택 사항을 취소하고 고급 대상 설정 대화 상자를 닫습니다.



* 관련 정보 *

http://www.netapp.com/us/media/tr-3966.pdf["NetApp 기술 보고서 3966: NetApp 데이터 압축 및 중복제거 구축 및 구현 가이드(clustered Data ONTAP)"]
