---
permalink: online-help/reference-event-details-page.html 
sidebar: sidebar 
keywords:  
summary: 이벤트 세부 정보 페이지에서 이벤트 심각도, 영향 수준, 영향 영역 및 이벤트 소스와 같은 선택한 이벤트의 세부 정보를 볼 수 있습니다. 문제 해결을 위해 가능한 해결 방법에 대한 추가 정보도 볼 수 있습니다. 
---
= 이벤트 세부 정보 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이벤트 세부 정보 페이지에서 이벤트 심각도, 영향 수준, 영향 영역 및 이벤트 소스와 같은 선택한 이벤트의 세부 정보를 볼 수 있습니다. 문제 해결을 위해 가능한 해결 방법에 대한 추가 정보도 볼 수 있습니다.

* * 이벤트 이름 *
+
이벤트의 이름과 이벤트가 마지막으로 표시된 시간입니다.

+
비성능 이벤트의 경우 이벤트가 New 또는 Acknowledged 상태에 있는 동안에는 마지막으로 본 정보를 알 수 없으므로 숨겨집니다.

* * 이벤트 설명 *
+
이벤트에 대한 간략한 설명입니다.

+
경우에 따라 이벤트 설명에 이벤트가 트리거되는 이유가 제공됩니다.

* * 경합의 요소 *
+
동적 성능 이벤트의 경우 이 섹션에는 클러스터의 논리적 및 물리적 구성요소를 나타내는 아이콘이 표시됩니다. 구성 요소의 경합이 발생한 경우 해당 아이콘이 빨간색 원으로 강조 표시됩니다.

+
다음 구성 요소가 표시될 수 있습니다.

+
** 네트워크 *
+
클러스터의 iSCSI 프로토콜 또는 FC(Fibre Channel) 프로토콜에 의한 입출력 요청 대기 시간을 나타냅니다. 대기 시간은 클러스터가 I/O 요청에 응답하기 전에 iSCSI Ready to Transfer(R2T) 또는 FCP Transfer Ready(XFER_RDY) 트랜잭션이 완료될 때까지 기다리는 데 걸리는 시간입니다. 네트워크 구성 요소의 경합이 발생할 경우, 블록 프로토콜 계층의 높은 대기 시간이 하나 이상의 워크로드 지연 시간에 영향을 미치게 됩니다.

** * 네트워크 처리 *
+
프로토콜 계층과 클러스터 간의 I/O 처리와 관련된 클러스터의 소프트웨어 구성요소를 나타냅니다. 이벤트가 감지된 이후 네트워크 처리를 처리하는 노드가 변경되었을 수 있습니다. 네트워크 처리 구성 요소의 경합이 발생한 경우, 네트워크 처리 노드의 높은 사용률이 하나 이상의 워크로드 지연 시간에 영향을 미치고 있음을 의미합니다.

** * QoS 정책 *
+
워크로드가 구성원인 스토리지 QoS(서비스 품질) 정책 그룹을 나타냅니다. 정책 그룹 구성 요소의 경합이 발생한 경우 정책 그룹의 모든 워크로드가 설정된 처리량 제한에 따라 조절되고, 이로 인해 하나 이상의 워크로드 지연 시간이 영향을 받습니다.

** 클러스터 인터커넥트 *
+
클러스터된 노드가 물리적으로 연결된 케이블과 어댑터를 나타냅니다. 클러스터 인터커넥트 구성 요소의 경합이 발생한 경우, 클러스터 인터커넥트에서 I/O 요청이 있을 때까지 대기 시간이 길어 하나 이상의 워크로드 지연 시간에 영향을 미치게 됩니다.

** * 데이터 처리 *
+
는 클러스터와 워크로드를 포함하는 스토리지 애그리게이트 간의 I/O 처리와 관련된 클러스터의 소프트웨어 구성요소를 나타냅니다. 이벤트가 감지된 이후 데이터 처리를 처리하는 노드가 변경될 수 있습니다. 데이터 처리 구성 요소의 경합이 발생한 경우, 데이터 처리 노드의 높은 활용률이 하나 이상의 워크로드 지연 시간에 영향을 미치고 있음을 의미합니다.

** * MetroCluster 리소스 *
+
MetroCluster 구성에서 클러스터 간 데이터를 미러링하는 데 사용되는 NVRAM 및 ISL(Interswitch Link)을 비롯한 MetroCluster 리소스를 나타냅니다. MetroCluster 구성 요소의 경합이 발생한 경우, 로컬 클러스터의 워크로드로부터 높은 쓰기 처리량을 의미하거나 링크 상태 문제가 로컬 클러스터에 있는 하나 이상의 워크로드 지연 시간에 영향을 줍니다. 클러스터가 MetroCluster 구성에 없으면 이 아이콘이 표시되지 않습니다.

** * 애그리게이트 또는 SSD 애그리게이트 운영 *
+
워크로드가 실행되는 스토리지 애그리게이트를 나타냅니다. 애그리게이트 구성 요소의 경합이 발생할 경우, 애그리게이트의 활용률이 높아지면 하나 이상의 워크로드 지연 시간에 영향을 미치게 됩니다. Aggregate는 모든 HDD 또는 HDD와 SSD(Flash Pool 애그리게이트)의 혼합으로 구성됩니다. 'SSD Aggregate'는 모든 SSD(All-Flash 애그리게이트) 또는 SSD와 클라우드 계층(FabricPool 애그리게이트)의 혼합으로 구성됩니다.

** * 클라우드 지연 시간 *
+
클러스터 및 사용자 데이터가 저장되는 클라우드 계층 간의 I/O 처리와 관련된 클러스터의 소프트웨어 구성요소를 나타냅니다. 클라우드 지연 시간 구성 요소의 경합이 발생할 경우, 클라우드 계층에서 호스팅되는 볼륨의 대량 읽기가 하나 이상의 워크로드 지연 시간에 영향을 미치고 있음을 의미합니다.

** SnapMirror * 를 동기화합니다
+
SnapMirror Synchronous 관계의 기본 볼륨에서 보조 볼륨으로 사용자 데이터를 복제하는 것과 관련된 클러스터의 소프트웨어 구성요소를 나타냅니다. 동기식 SnapMirror 구성 요소의 경합이 발생한 경우, SnapMirror Synchronous 작업의 활동이 하나 이상의 워크로드 지연 시간에 영향을 미치고 있음을 의미합니다.





이벤트 정보, 시스템 진단 및 권장 조치 섹션은 기타 항목에서 설명합니다.



== 명령 버튼

명령 단추를 사용하여 다음 작업을 수행할 수 있습니다.

* * 메모 아이콘 *
+
이벤트에 대한 메모를 추가하거나 업데이트하고 다른 사용자가 남긴 모든 메모를 검토할 수 있습니다.



* 작업 메뉴 *

* * 나에게 할당 *
+
사용자에게 이벤트를 할당합니다.

* 다른 사람에게 할당 *
+
소유자 할당 대화 상자를 엽니다. 이 대화 상자에서 다른 사용자에게 이벤트를 할당하거나 다시 할당할 수 있습니다.

+
사용자에게 이벤트를 할당하면 사용자의 이름과 이벤트가 할당된 시간이 선택한 이벤트의 이벤트 목록에 추가됩니다.

+
소유권 필드를 비워 두면 이벤트 할당을 취소할 수도 있습니다.

* * 확인 *
+
반복 경고 알림을 계속 수신하지 않도록 선택한 이벤트를 확인합니다.

+
이벤트를 확인하면 선택한 이벤트의 이벤트 목록(에 의해 확인됨)에 사용자 이름과 이벤트가 추가됩니다. 이벤트를 인지하면 해당 이벤트를 관리할 책임이 있습니다.

* * 해결됨으로 표시 *
+
이벤트 상태를 Resolved 로 변경할 수 있습니다.

+
이벤트를 해결할 때 사용자 이름과 이벤트를 해결한 시간이 선택한 이벤트의 이벤트 목록(에서 해결)에 추가됩니다. 이벤트에 대한 수정 조치를 취한 후에는 해당 이벤트를 '해결됨'으로 표시해야 합니다.

* * 알림 추가 *
+
선택한 이벤트에 대한 경고를 추가할 수 있는 경고 추가 대화 상자를 표시합니다.


