---
permalink: online-help/reference-capacity-all-clusters-view.html 
sidebar: sidebar 
keywords:  
summary: 상태/클러스터 스토리지 요약 페이지에서는 모든 클러스터의 스토리지 용량 및 활용도에 대한 요약 정보를 볼 수 있습니다. 이 정보를 통해 가능한 용량 위험을 이해하고 워크로드를 재조정하려면 적절한 조치를 취할 수 있습니다. 
---
= 상태/클러스터 스토리지 요약 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
상태/클러스터 스토리지 요약 페이지에서는 모든 클러스터의 스토리지 용량 및 활용도에 대한 요약 정보를 볼 수 있습니다. 이 정보를 통해 가능한 용량 위험을 이해하고 워크로드를 재조정하려면 적절한 조치를 취할 수 있습니다.

모니터링되는 모든 클러스터의 세부 정보를 쉼표로 구분된 값으로 내보내려면 * 내보내기 * 버튼을 사용합니다 (`.csv`) 파일.

* * 클러스터 *
+
클러스터 이름입니다.

* * HA 쌍 *
+
2개의 노드를 형성하여 얻은 HA 쌍 값입니다.

* * 모델/제품군 *
+
클러스터의 모델 또는 패밀리 이름입니다.

* OS 버전 *
+
시스템에 설치된 ONTAP 버전입니다.

* * 총 물리적 용량 *
+
배열에 있는 모든 디스크의 총 물리적 용량을 표시합니다.

* * 구성되지 않은 물리적 용량 *
+
컨테이너 유형이 애그리게이트, 부분, 스페어 또는 공유 이외의 구성되지 않은 디스크 용량입니다. 이 용량은 ONTAP에서 디스크의 물리적 용량보다 항상 높습니다. 예를 들어, 2TB 디스크를 예로 들 수 있습니다. 디스크의 물리적 용량은 ONTAP에서 1.6TB이고 Unified Manager에서 구성되지 않은 물리적 용량은 1.8TB입니다.

* * 총 용량 합계 *
+
사용자가 사용할 수 있는 총 Aggregate 크기입니다. 여기에는 스냅샷 복사본 예약이 포함됩니다.

* * 사용된 총 용량 *
+
Aggregate에서 이미 사용 중인 용량입니다. 여기에는 볼륨, LUN 및 기타 스토리지 효율성 기술에서 사용하는 용량이 포함됩니다.

* * 사용되지 않은 용량 집계 *
+
Aggregate에 추가 데이터를 저장하기 위해 사용 가능한 용량입니다. 여기에는 스냅샷 복사본 예약이 포함됩니다.

* * 할당된 LUN 용량 *
+
매핑된 LUN의 용량입니다.

* * 할당되지 않은 LUN 용량 *
+
호스트에 매핑되지 않은 모든 LUN의 용량입니다.

* * 볼륨 총 용량 *
+
볼륨의 총 용량(사용된 용량 및 미사용 용량)

* * 사용된 볼륨 용량 *
+
볼륨의 사용된 용량입니다.

* * 볼륨 미사용 용량 *
+
볼륨의 미사용 용량입니다.

* * 볼륨 보호 용량 *
+
SnapMirror 및 SnapVault가 활성화된 볼륨의 용량입니다.

* * 클러스터 라이센스 클라우드 계층 합계 *
+
클라우드 계층에서 라이센스가 부여된 총 용량입니다. 이 필드는 FabricPool 라이센스가 필요한 스토리지 공급자(예: Amazon S3, Microsoft Azure Cloud, IBM Cloud Object Storage 또는 Alibaba Cloud Object Storage)에 대해 표시됩니다.

* * 클러스터 라이센스 클라우드 계층 사용 *
+
FabricPool 라이센스가 필요한 스토리지 공급자 경우 클라우드 계층의 데이터에 사용되는 공간입니다.

* * 사용된 클러스터 StorageGRID 용량 *
+
FabricPool 라이센스가 필요하지 않은 스토리지 공급자(예: StorageGRID)의 클라우드 계층 데이터에서 사용하는 공간입니다.


