---
permalink: online-help/reference-events-report.html 
sidebar: sidebar 
keywords:  
summary: 이벤트 보고서를 사용하면 특정 기간 동안의 이벤트 추세에 대한 정보를 볼 수 있습니다. 이 정보를 사용하여 구성 변경, 업그레이드 등과 같은 이전 운영 활동과 최근 활동을 비교할 수 있습니다. 또한 이 정보를 통해 진행 중인 이벤트를 확인할 수 있습니다. 
---
= 이벤트 보고서
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이벤트 보고서를 사용하면 특정 기간 동안의 이벤트 추세에 대한 정보를 볼 수 있습니다. 이 정보를 사용하여 구성 변경, 업그레이드 등과 같은 이전 운영 활동과 최근 활동을 비교할 수 있습니다. 또한 이 정보를 통해 진행 중인 이벤트를 확인할 수 있습니다.



== 이벤트 보고서 차트 보기

이벤트 보고서는 두 가지 형식으로 표시됩니다.

* 이벤트 보고서 차트 보기
* 상황 보고서 표 형식 보기


이벤트 차트는 두 가지 형식으로 표시됩니다.

* 이벤트 심각도 추세(열려 있는 모든 이벤트)
* 이벤트 상태 추세


차트는 기간 동안 열려 있는 모든 이벤트의 이벤트 심각도 추세를 보여 줍니다. 이벤트 수가 세로(y) 축에 표시되고 날짜는 가로(x) 축에 표시됩니다. 특정 지점 위에 커서를 놓으면 그래프의 특정 지점에 대한 세부 정보를 볼 수 있습니다. 세부 정보에는 이벤트 심각도, 특정 심각도 유형의 이벤트 수 및 이벤트 날짜가 표시됩니다.

표시되는 이벤트 심각도 유형은 Critical, Error 및 Warning입니다. 이벤트 심각성은 서로 다른 색으로 구별됩니다. 다른 상태에서 동일한 날짜에 동일한 수의 이벤트가 있을 수 있습니다.

* * 카운트 *
+
이벤트 수를 표시합니다.

* * 날짜 *
+
날짜를 표시합니다. x축은 이벤트가 발생한 시간부터 현재 날짜까지의 데이터를 표시합니다. 차트를 클릭하고 확대/축소하여 세부 정보를 볼 수 있습니다.



차트는 일정 기간 동안의 하루 이벤트 상태 추세를 보여 줍니다. 이벤트 수가 세로(y) 축에 표시되고 날짜는 가로(x) 축에 표시됩니다. 세부 정보에는 이벤트 상태, 특정 상태의 이벤트 수 및 이벤트 날짜가 표시됩니다.

이벤트 상태는 New, Acknowledged 및 Resolved입니다. 이벤트 상태는 서로 다른 색상으로 구분됩니다.

이 차트는 녹색으로 표시된 막대 그래프로 매일 새로 생성된 이벤트를 누적별로 보여 줍니다. 확인 및 해결된 이벤트의 수는 매일 확인 및 해결되는 것으로 표시됩니다.

차트 내에 확대/축소 기능이 제공됩니다. 이 기능을 사용하면 차트의 특정 지점을 확대하여 보다 선명한 이미지를 얻을 수 있습니다.

* * 출처 *
+
이벤트의 소스를 표시합니다.

* * 상태 *
+
이벤트의 심각도를 표시합니다. 이 열을 필터링하여 특정 심각도 유형의 이벤트를 표시할 수 있습니다. 이벤트 심각도 유형은 Critical, Error 또는 Warning입니다.

* * 시/도 *
+
새 이벤트, 확인된 이벤트, 해결된 이벤트 또는 폐기로 이벤트 상태를 표시합니다. 이 열을 필터링하여 특정 상태의 이벤트를 표시할 수 있습니다.

* * 이벤트 *
+
이벤트 이름을 표시합니다.

* * 트리거 시간 *
+
이벤트가 생성된 시간을 표시합니다. 시간과 날짜가 모두 표시됩니다.

* * 일 우수 *
+
발생한 이벤트와 해당 해결 또는 지정의 날짜 사이의 기간을 폐기로 표시합니다.

* * 소스 유형 *
+
이벤트가 연결된 오브젝트 유형(예: SVM(Storage Virtual Machine), 볼륨 또는 qtree)을 표시합니다.

* * 데이터 우선순위 *
+
스토리지 객체의 데이터 우선 순위에 따라 주석 유형을 표시합니다.

* * 영향력 수준 *
+
이벤트가 인시던트, 위험 또는 정보로 분류되는지 여부를 표시합니다.

* * 충격 영역 *
+
이벤트가 용량, 가용성, 성능, 보호 또는 구성 이벤트인지 여부를 표시합니다.

* * 할당 대상 *
+
이벤트가 할당된 사용자의 이름을 표시합니다.

* * 할당된 시간 *
+
이벤트가 사용자에게 할당된 시간을 표시합니다.

* * 참고 *
+
이벤트에 대해 추가된 메모 수를 표시합니다.

* * 에 의해 승인됨
+
이벤트를 확인한 사용자의 이름을 표시합니다. 이벤트가 확인되지 않으면 필드가 비어 있습니다.

* * 확인된 시간 *
+
이벤트가 확인된 이후 경과된 시간을 표시합니다. 경과된 시간이 주를 초과하면 이벤트가 승인되었을 때 타임스탬프가 표시됩니다.

* * 해결자 *
+
이벤트를 해결한 사용자의 이름을 표시합니다. 이벤트가 해결되지 않으면 필드가 비어 있습니다.

* * 해결 시간 *
+
이벤트가 해결된 이후 경과된 시간을 표시합니다. 경과된 시간이 주를 초과하면 이벤트가 해결된 시간이 타임스탬프에 표시됩니다.

* * Obsoleted Time(관찰 시간) *
+
이벤트 상태가 폐기로 된 시간을 표시합니다.


