---
permalink: online-help/reference-managed-objects-pane.html 
sidebar: sidebar 
keywords:  
summary: 성능 요약 정보 탭의 관리 대상 개체 창에는 클러스터에 대한 스토리지 개체 유형과 카운트의 최상위 개요가 표시됩니다. 이 창에서는 각 클러스터에 있는 개체의 상태를 추적할 수 있습니다. 
---
= 관리 개체 창
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능 요약 정보 탭의 관리 대상 개체 창에는 클러스터에 대한 스토리지 개체 유형과 카운트의 최상위 개요가 표시됩니다. 이 창에서는 각 클러스터에 있는 개체의 상태를 추적할 수 있습니다.

관리되는 개체 수는 마지막 컬렉션 기간의 시점 데이터입니다. 새 오브젝트는 15분 간격으로 검색됩니다.

개체 유형에 대해 연결된 번호를 클릭하면 해당 개체 유형에 대한 개체 성능 인벤토리 페이지가 표시됩니다. 객체 인벤토리 페이지는 이 클러스터의 객체만 표시하도록 필터링됩니다.

관리되는 개체는 다음과 같습니다.

* * 노드 *
+
클러스터의 물리적 시스템

* * 애그리게이트 *
+
보호 및 프로비저닝을 위해 단일 유닛으로 관리할 수 있는 여러 RAID(Redundant Array of Independent Disks) 그룹 집합입니다.

* 포트 *
+
네트워크의 다른 장치에 연결하는 데 사용되는 노드의 물리적 연결 지점입니다.

* SVM *
+
고유한 네트워크 주소를 통해 네트워크 액세스를 제공하는 가상 시스템. SVM은 별개의 네임스페이스에서 데이터를 제공할 수 있으며 클러스터의 나머지 부분과는 별도로 관리할 수 있습니다.

* 볼륨 *
+
지원되는 하나 이상의 액세스 프로토콜을 통해 액세스 가능한 사용자 데이터를 보유하는 논리적 엔티티입니다. 이 개수에는 FlexVol 볼륨과 FlexGroup 볼륨이 모두 포함되며 FlexGroup 구성 요소 또는 무한 확장 볼륨은 포함되지 않습니다.

* LUN *
+
FC(Fibre Channel) 논리 유닛 또는 iSCSI 논리 유닛의 식별자입니다. 논리 유닛은 일반적으로 저장소 볼륨에 해당하며 컴퓨터 운영 체제 내에서 장치로 표시됩니다.

* LIF *
+
노드에 대한 네트워크 액세스 포인트를 나타내는 논리 네트워크 인터페이스입니다. 이 개수에는 모든 LIF 유형이 포함됩니다.


