---
permalink: online-help/reference-cluster-events.html 
sidebar: sidebar 
keywords:  
summary: 클러스터 이벤트는 클러스터의 상태에 대한 정보를 제공하므로 클러스터에서 잠재적인 문제가 있는지 모니터링할 수 있습니다. 이벤트는 영향 영역별로 그룹화되며 이벤트 이름, 트랩 이름, 영향 수준, 소스 유형 및 심각도를 포함합니다. 
---
= 클러스터 이벤트입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 이벤트는 클러스터의 상태에 대한 정보를 제공하므로 클러스터에서 잠재적인 문제가 있는지 모니터링할 수 있습니다. 이벤트는 영향 영역별로 그룹화되며 이벤트 이름, 트랩 이름, 영향 수준, 소스 유형 및 심각도를 포함합니다.



== 영향 영역: 가용성

별표(*)는 Unified Manager 이벤트로 변환된 EMS 이벤트를 나타냅니다.

|===
| 이벤트 이름(트랩 이름) | 충격 수준 | 소스 유형 | 심각도입니다 


 a| 
클러스터에 스페어 디스크 부족(문서 DisksNot예비품)
 a| 
위험입니다
 a| 
클러스터
 a| 
경고



 a| 
클러스터에 연결할 수 없음(문서 클러스터연결할 수 없음)
 a| 
위험입니다
 a| 
클러스터
 a| 
오류



 a| 
클러스터 모니터링 실패(문서 클러스터 모니터링 실패)
 a| 
위험입니다
 a| 
클러스터
 a| 
경고



 a| 
클러스터 FabricPool 라이센스 용량 제한 위반(문서 ExternalCapacityTierSpaceFull)
 a| 
위험입니다
 a| 
클러스터
 a| 
경고



 a| 
NVMe - 유예 기간 시작됨 * (nvmfGracePeriodStart)
 a| 
위험입니다
 a| 
클러스터
 a| 
경고



 a| 
NVMe-of Grace Period Active * (nvmfGracePeriodActive)
 a| 
위험입니다
 a| 
클러스터
 a| 
경고



 a| 
NVMe - 유예 기간 만료 * (nvmfGracePeriodExpired)
 a| 
위험입니다
 a| 
클러스터
 a| 
경고



 a| 
개체 유지 관리 창 시작됨(objectMaintenanceWindowStarted)
 a| 
이벤트
 a| 
클러스터
 a| 
심각



 a| 
개체 유지 관리 창 종료됨(objectMaintenanceWindowEnded)
 a| 
이벤트
 a| 
클러스터
 a| 
정보



 a| 
MetroCluster 스페어 디스크 남음(document.SpareDiskLeftBehind)
 a| 
위험입니다
 a| 
클러스터
 a| 
오류



 a| 
MetroCluster 자동 비계획 전환 비활성화(문서 MccAutomaticUnplanneSwitchOverDisabled)
 a| 
위험입니다
 a| 
클러스터
 a| 
경고

|===


== 충격 영역: 용량

|===
| 이벤트 이름(트랩 이름) | 충격 수준 | 소스 유형 | 심각도입니다 


 a| 
클러스터 클라우드 계층 계획(클러스터CloudTierPlanningWarning)
 a| 
위험입니다
 a| 
클러스터
 a| 
경고



 a| 
FabricPool 공간이 거의 가득 찼습니다 *
 a| 
위험입니다
 a| 
클러스터
 a| 
오류

|===


== 충격 영역: 구성

|===
| 이벤트 이름(트랩 이름) | 충격 수준 | 소스 유형 | 심각도입니다 


 a| 
추가된 노드(해당 없음)
 a| 
이벤트
 a| 
클러스터
 a| 
정보



 a| 
제거된 노드(해당 없음)
 a| 
이벤트
 a| 
클러스터
 a| 
정보



 a| 
클러스터 제거됨(해당 없음)
 a| 
이벤트
 a| 
클러스터
 a| 
정보



 a| 
클러스터 추가 실패(해당 없음)
 a| 
이벤트
 a| 
클러스터
 a| 
오류



 a| 
클러스터 이름이 변경됨(해당 없음)
 a| 
이벤트
 a| 
클러스터
 a| 
정보



 a| 
비상 EMS 수신(해당 없음)
 a| 
이벤트
 a| 
클러스터
 a| 
심각



 a| 
Critical EMS 수신 (해당 없음)
 a| 
이벤트
 a| 
클러스터
 a| 
심각



 a| 
경고 EMS 수신(해당 없음)
 a| 
이벤트
 a| 
클러스터
 a| 
오류



 a| 
오류 EMS 수신(해당 없음)
 a| 
이벤트
 a| 
클러스터
 a| 
경고



 a| 
경고 EMS 수신(해당 없음)
 a| 
이벤트
 a| 
클러스터
 a| 
경고



 a| 
디버그 EMS 수신(해당 없음)
 a| 
이벤트
 a| 
클러스터
 a| 
경고



 a| 
EMS 수신 통지(해당 없음)
 a| 
이벤트
 a| 
클러스터
 a| 
경고



 a| 
정보 EMS 수신(해당 없음)
 a| 
이벤트
 a| 
클러스터
 a| 
경고

|===
ONTAP EMS 이벤트는 세 가지 Unified Manager 이벤트 심각도 수준으로 분류됩니다.

|===
| Unified Manager 이벤트 심각도 레벨 | ONTAP EMS 이벤트 심각도 수준 


 a| 
심각
 a| 
비상 상황

심각



 a| 
오류
 a| 
경고



 a| 
경고
 a| 
오류

경고

디버그

주의

정보 제공

|===


== 충격 영역: 성능

|===
| 이벤트 이름(트랩 이름) | 충격 수준 | 소스 유형 | 심각도입니다 


 a| 
클러스터 IOPS 중요 임계값 위반(문서 클러스터사고)
 a| 
사고
 a| 
클러스터
 a| 
심각



 a| 
클러스터 IOPS 경고 임계값 위반(문서 클러스터경고)
 a| 
위험입니다
 a| 
클러스터
 a| 
경고



 a| 
클러스터 MBPS 위험 임계값 위반(문서 클러스터ps인시던트)
 a| 
사고
 a| 
클러스터
 a| 
심각



 a| 
클러스터 MBps 경고 임계값 위반(문서 클러스터MbpsWarning)
 a| 
위험입니다
 a| 
클러스터
 a| 
경고



 a| 
클러스터 동적 임계값 위반(문서 ClusterDynamicEventWarning)
 a| 
위험입니다
 a| 
클러스터
 a| 
경고

|===