---
permalink: online-help/reference-configure-protection-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 보호 구성 대화 상자를 사용하여 클러스터의 모든 읽기, 쓰기 및 데이터 보호 볼륨에 대해 SnapMirror 및 SnapVault 관계를 생성하여 소스 볼륨 또는 기본 볼륨의 데이터가 복제되도록 할 수 있습니다. 
---
= 보호 구성 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
보호 구성 대화 상자를 사용하여 클러스터의 모든 읽기, 쓰기 및 데이터 보호 볼륨에 대해 SnapMirror 및 SnapVault 관계를 생성하여 소스 볼륨 또는 기본 볼륨의 데이터가 복제되도록 할 수 있습니다.



== 소스 탭

* * 토폴로지 뷰 *
+
만들고 있는 관계를 시각적으로 표시합니다. 토폴로지의 소스는 기본적으로 강조 표시됩니다.

* * 소스 정보 *
+
다음 정보를 포함하여 선택한 소스 볼륨에 대한 세부 정보를 표시합니다.

+
** 소스 클러스터 이름입니다
** 소스 SVM 이름
** 누적 볼륨 총 크기입니다
+
선택한 모든 소스 볼륨의 총 크기를 표시합니다.

** 사용된 누적 볼륨 크기입니다
+
선택한 모든 소스 볼륨의 사용된 누적 볼륨 크기를 표시합니다.

** 소스 볼륨
+
테이블에 다음 정보를 표시합니다.

+
*** 소스 볼륨
+
선택한 소스 볼륨의 이름을 표시합니다.

*** 유형
+
볼륨 유형을 표시합니다.

*** SnapLock 유형
+
볼륨의 SnapLock 유형을 표시합니다. Compliance, Enterprise 및 Non-SnapLock 옵션이 있습니다.

*** 스냅샷 복사본
+
기본 전송에 사용되는 스냅샷 복사본을 표시합니다. 소스 볼륨이 읽기/쓰기이면 스냅샷 복사본 열의 기본값 에 새 스냅샷 복사본이 기본적으로 생성되고 기본 전송에 사용됩니다. 소스 볼륨이 데이터 보호 볼륨인 경우 스냅샷 복사본 열의 기본값 값은 새 스냅샷 복사본이 생성되지 않고 기존의 모든 스냅샷 복사본이 타겟으로 전송됨을 나타냅니다. 스냅샷 복사본 값을 클릭하면 기본 전송에 사용할 기존 스냅샷 복사본을 선택할 수 있는 스냅샷 복사본 목록이 표시됩니다. 소스 유형이 데이터 보호인 경우 다른 기본 스냅샷 복사본을 선택할 수 없습니다.









== SnapMirror 탭

보호 관계를 위해 대상 클러스터, SVM(스토리지 가상 시스템), 애그리게이트를 지정할 수 있으며, SnapMirror 관계를 생성하면서 대상에 대한 명명 규칙을 지정할 수 있습니다. SnapMirror 정책 및 스케줄도 지정할 수 있습니다.

* * 토폴로지 뷰 *
+
만들고 있는 관계를 시각적으로 표시합니다. 토폴로지에서 SnapMirror 대상 리소스가 기본적으로 강조 표시됩니다.

* * 목적지 정보 *
+
보호 관계를 위한 대상 리소스를 선택할 수 있습니다.

+
** 고급 링크
+
SnapMirror 관계를 작성할 때 고급 대상 설정 대화 상자를 시작합니다.

** 클러스터
+
에는 보호 대상 호스트로 사용할 수 있는 클러스터가 나와 있습니다. 이 필드는 필수입니다.

** 스토리지 가상 시스템(SVM)
+
에는 선택한 클러스터에서 사용할 수 있는 SVM이 나와 있습니다. SVM 목록이 채워지기 전에 클러스터를 선택해야 합니다. 이 필드는 필수입니다.

** 집계
+
에는 선택한 SVM에서 사용 가능한 애그리게이트가 나와 있습니다. Aggregate 목록이 채워지기 전에 클러스터를 선택해야 합니다. 이 필드는 필수입니다. 집계 목록에는 다음 정보가 표시됩니다.

+
*** 순위
+
여러 애그리게이트가 목적지의 모든 요구사항을 충족할 경우, 랭킹은 다음 조건에 따라 Aggregate가 나열된 우선순위를 나타냅니다.

+
.... 장애 도메인 분리를 설정하려면 소스 볼륨 노드와 다른 노드에 있는 애그리게이트를 사용하는 것이 좋습니다.
.... 볼륨의 수가 더 적은 노드의 aggregate는 클러스터의 노드 간에 로드 밸런싱을 지원하는 데 선호됩니다.
.... 용량 밸런싱을 위해 다른 애그리게이트보다 여유 공간이 더 많은 애그리게이트가 선호됩니다. 1순위는 3가지 기준에 따라 가장 선호됨을 의미합니다.


*** 애그리게이트 이름
+
애그리게이트의 이름입니다

*** 가용 용량
*** Aggregate에서 데이터에 사용 가능한 공간입니다
*** 리소스 풀
+
Aggregate가 속한 리소스 풀의 이름입니다



** 명명 규칙
+
대상 볼륨에 적용되는 기본 명명 규칙을 지정합니다. 제공된 명명 규칙을 수락하거나 사용자 지정 명명 규칙을 만들 수 있습니다. 명명 규칙은 %C, %M, %V 및 %N과 같은 속성을 가질 수 있습니다. 여기서 %C는 클러스터 이름이고, %M은 SVM 이름이고, %V는 소스 볼륨이고, %N은 토폴로지 대상 노드 이름입니다.

+
입력한 이름이 올바르지 않으면 명명 규칙 필드가 빨간색으로 강조 표시됩니다. "미리 보기 이름" 링크를 클릭하면 입력한 명명 규칙의 미리 보기가 표시되며 텍스트 필드에 명명 규칙을 입력하면 미리 보기 텍스트가 동적으로 업데이트됩니다. 관계가 생성될 때 을 대체하여 001에서 999 사이의 접미사가 대상 이름에 추가됩니다 `nnn` 이 속성은 미리 보기 텍스트에 표시되며, 001은 먼저 할당되고 002는 두 번째로 할당됩니다.



* * 관계 설정 *
+
보호 관계에 사용되는 최대 전송 속도, SnapMirror 정책 및 스케줄을 지정할 수 있습니다.

+
** 최대 전송 속도
+
네트워크를 통해 클러스터 간에 데이터가 전송되는 최대 속도를 지정합니다. 최대 전송 속도를 사용하지 않도록 선택하는 경우 관계 간의 기본 전송은 무제한입니다. 하지만 ONTAP 8.2를 실행 중이고 운영 클러스터와 보조 클러스터가 동일한 경우에는 이 설정이 무시됩니다.

** SnapMirror 정책
+
관계에 대한 ONTAP SnapMirror 정책을 지정합니다. 기본값은 DPDefault 입니다.

** 정책을 생성합니다
+
새 SnapMirror 정책을 만들고 사용할 수 있는 SnapMirror 정책 만들기 대화 상자를 시작합니다.

** SnapMirror 일정 을 참조하십시오
+
관계에 대한 ONTAP SnapMirror 정책을 지정합니다. 사용 가능한 스케줄에는 없음, 5분, 8시간, 일별, 시간별, 매주. 기본값은 없음 으로, 관계에 연결된 일정이 없음을 나타냅니다. 일정이 없는 관계는 스토리지 서비스에 속하지 않는 한 지연 상태 값이 없습니다.

** 일정 생성
+
새 SnapMirror 일정을 만들 수 있는 일정 만들기 대화 상자를 시작합니다.







== SnapVault 탭

보호 관계를 위해 2차 클러스터, SVM 및 애그리게이트를 지정할 수 있을 뿐만 아니라, SnapVault 관계를 생성하면서 2차 볼륨의 명명 규칙을 지정할 수 있습니다. SnapVault 정책 및 스케줄을 지정할 수도 있습니다.

* * 토폴로지 뷰 *
+
만들고 있는 관계를 시각적으로 표시합니다. 토폴로지의 SnapVault 보조 리소스가 기본적으로 강조 표시됩니다.

* * 보조 정보 *
+
보호 관계에 사용할 보조 리소스를 선택할 수 있습니다.

+
** 고급 링크
+
고급 보조 설정 대화 상자를 시작합니다.

** 클러스터
+
에는 보조 보호 호스트로 사용할 수 있는 클러스터가 나와 있습니다. 이 필드는 필수입니다.

** 스토리지 가상 시스템(SVM)
+
에는 선택한 클러스터에서 사용할 수 있는 SVM이 나와 있습니다. SVM 목록이 채워지기 전에 클러스터를 선택해야 합니다. 이 필드는 필수입니다.

** 집계
+
에는 선택한 SVM에서 사용 가능한 애그리게이트가 나와 있습니다. Aggregate 목록이 채워지기 전에 클러스터를 선택해야 합니다. 이 필드는 필수입니다. 집계 목록에는 다음 정보가 표시됩니다.

+
*** 순위
+
여러 애그리게이트가 목적지의 모든 요구사항을 충족할 경우, 랭킹은 다음 조건에 따라 Aggregate가 나열된 우선순위를 나타냅니다.

+
.... 장애 도메인 분리를 설정하려면 기본 볼륨 노드와 다른 노드에 있는 애그리게이트를 사용하는 것이 좋습니다.
.... 볼륨의 수가 더 적은 노드의 aggregate는 클러스터의 노드 간에 로드 밸런싱을 지원하는 데 선호됩니다.
.... 용량 밸런싱을 위해 다른 애그리게이트보다 여유 공간이 더 많은 애그리게이트가 선호됩니다. 1순위는 3가지 기준에 따라 가장 선호됨을 의미합니다.


*** 애그리게이트 이름
+
애그리게이트의 이름입니다

*** 가용 용량
*** Aggregate에서 데이터에 사용 가능한 공간입니다
*** 리소스 풀
+
Aggregate가 속한 리소스 풀의 이름입니다



** 명명 규칙
+
보조 볼륨에 적용되는 기본 명명 규칙을 지정합니다. 제공된 명명 규칙을 수락하거나 사용자 지정 명명 규칙을 만들 수 있습니다. 명명 규칙은 %C, %M, %V 및 %N과 같은 속성을 가질 수 있습니다. 여기서 %C는 클러스터 이름이고, %M은 SVM 이름이고, %V는 소스 볼륨이고, %N은 토폴로지 보조 노드 이름입니다.

+
입력한 이름이 올바르지 않으면 명명 규칙 필드가 빨간색으로 강조 표시됩니다. "미리 보기 이름" 링크를 클릭하면 입력한 명명 규칙의 미리 보기가 표시되며 텍스트 필드에 명명 규칙을 입력하면 미리 보기 텍스트가 동적으로 업데이트됩니다. 잘못된 값을 입력하면 잘못된 정보가 미리 보기 영역에 빨간색 물음표로 표시됩니다. 관계가 생성될 때 을 대체하여 001에서 999 사이의 접미사가 보조 이름에 추가됩니다 `nnn` 이 속성은 미리 보기 텍스트에 표시되며, 001은 먼저 할당되고 002는 두 번째로 할당됩니다.



* * 관계 설정 *
+
보호 관계에 사용되는 최대 전송 속도, SnapVault 정책 및 SnapVault 스케줄을 지정할 수 있습니다.

+
** 최대 전송 속도
+
네트워크를 통해 클러스터 간에 데이터가 전송되는 최대 속도를 지정합니다. 최대 전송 속도를 사용하지 않도록 선택하는 경우 관계 간의 기본 전송은 무제한입니다. 하지만 ONTAP 8.2를 실행 중이고 운영 클러스터와 보조 클러스터가 동일한 경우에는 이 설정이 무시됩니다.

** SnapVault 정책
+
관계에 대한 ONTAP SnapVault 정책을 지정합니다. 기본값은 XDPDefault 입니다.

** 정책을 생성합니다
+
새 SnapVault 정책을 만들고 사용할 수 있는 SnapVault 정책 만들기 대화 상자를 시작합니다.

** SnapVault 일정
+
관계의 ONTAP SnapVault 스케줄을 지정합니다. 사용 가능한 스케줄에는 없음, 5분, 8시간, 일별, 시간별, 매주. 기본값은 없음 으로, 관계에 연결된 일정이 없음을 나타냅니다. 일정이 없는 관계는 스토리지 서비스에 속하지 않는 한 지연 상태 값이 없습니다.

** 일정 생성
+
SnapVault 일정을 만들 수 있는 일정 만들기 대화 상자를 시작합니다.







== 명령 버튼

명령 단추를 사용하여 다음 작업을 수행할 수 있습니다.

* * 취소 *
+
선택한 항목을 삭제하고 보호 구성 대화 상자를 닫습니다.

* * 적용 *
+
선택한 항목을 적용하고 보호 프로세스를 시작합니다.


