---
permalink: online-help/reference-aggregate-thresholds-page.html 
sidebar: sidebar 
keywords:  
summary: 애그리게이트의 구성/상태 임계값 페이지를 사용하면 모니터링되는 애그리게이트가 글로벌 상태 임계값을 구성할 수 있습니다. 옵션을 전역적으로 구성하면 모든 개체의 기본값이 수정됩니다. 그러나 개체 수준에서 기본값이 변경된 경우에는 글로벌 값이 수정되지 않습니다. 
---
= 애그리게이트에 대한 구성/상태 임계값 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
애그리게이트의 구성/상태 임계값 페이지를 사용하면 모니터링되는 애그리게이트가 글로벌 상태 임계값을 구성할 수 있습니다. 옵션을 전역적으로 구성하면 모든 개체의 기본값이 수정됩니다. 그러나 개체 수준에서 기본값이 변경된 경우에는 글로벌 값이 수정되지 않습니다.

OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

이벤트는 임계값이 위반될 때 생성됩니다. 사용자는 이러한 이벤트에 대해 수정 조치를 취할 수 있습니다.

임계값은 노드의 루트 애그리게이트에 적용할 수 없습니다.

용량, 애그리게이트 성장 및 애그리게이트 스냅샷 복사본에 대한 애그리게이트 상태 임계값을 설정할 수 있습니다.



== 용량 영역

Capacity 영역에서는 다음과 같은 총 용량 임계값 조건을 설정할 수 있습니다. 자동 행이 애그리게이트에 있는 볼륨에서 활성화된 경우, 애그리게이트 용량 임계값은 원래 볼륨 크기에 기반을 둔 것이 아니라 에 의해 설정된 최대 볼륨 크기에 따라 위반된 것으로 간주됩니다.

* * 공간이 거의 가득 찼습니다 *
+
집계가 거의 꽉 찬 것으로 간주되는 비율을 지정합니다.

+
** 기본값은 80%입니다
+
이 임계값에 대한 값은 관리 서버가 이벤트를 생성할 수 있는 전체 집계 임계값 값보다 작아야 합니다.

** 생성된 이벤트: 집계 거의 가득 참
** 이벤트 심각도: 경고


* * 공간이 가득 참 *
+
집계가 가득 찬 것으로 간주되는 비율을 지정합니다.

+
** 기본값은 90%입니다
** 생성된 이벤트: 전체 집계
** 이벤트 심각도: 오류


* * 거의 과대 과대 *
+
Aggregate가 거의 과커밋된 것으로 간주되는 비율을 지정합니다.

+
** 기본값은 95%입니다
+
이 임계값에 대한 값은 관리 서버가 이벤트를 생성할 수 있도록 집계 초과 커밋 전체 임계값 값보다 작아야 합니다.

** 생성된 이벤트: 거의 커밋되었습니다
** 이벤트 심각도: 경고


* * 과대 커밋 *
+
Aggregate가 초과 커밋된 것으로 간주되는 비율을 지정합니다.

+
** 기본값은 100%입니다
** 생성된 이벤트: OverCommitted 집계
** 이벤트 심각도: 오류


* * 완전 충전 시까지 남은 기간 *
+
Aggregate가 전체 용량에 도달하기 전까지 남은 일 수를 지정합니다.

+
** 기본값: 7
** 생성된 이벤트: 전체 시점까지 일 집계
** 이벤트 심각도: 오류






== 성장 영역

Growth(성장) 영역에서 애그리게이트 성장에 대한 다음 임계값 조건을 설정할 수 있습니다.

* * 성장률 *
+
시스템에서 애그리게이트 성장률 비정상 이벤트를 생성하기 전에 애그리게이트의 성장률이 정상으로 간주되는 비율을 지정합니다.

+
** 기본값은 1%입니다
** 생성된 이벤트: 애그리게이트 증가율 비정상
** 이벤트 심각도: 경고


* * 성장률 감도 *
+
집계 증가율의 표준 편차에 적용되는 계수를 지정합니다. 증가율이 계수 표준 편차를 초과하면 Aggregate Growth Rate Abnormal 이벤트가 생성됩니다.

+
성장률 감도 값이 낮을수록 증가율의 변화에 매우 민감함을 나타냅니다. 성장률 감도 범위는 1 ~ 5입니다.

+
** 기본값: 2


+
[NOTE]
====
글로벌 임계값 수준에서 애그리게이트의 증가율 민감도를 수정할 경우 글로벌 임계값 레벨의 볼륨에 대한 증가율 감도 역시 변경됩니다.

====




== Snapshot 복사본 영역

Snapshot 복사본 영역에서는 다음 스냅샷 예약 임계값 조건을 설정할 수 있습니다.

* * Snapshot Reserve Full(스냅숏 예비 공간 전체) *
+
Aggregate가 스냅샷 복사본에 예약된 모든 공간을 소비한 비율을 지정합니다.

+
** 기본값은 90%입니다
** 이벤트 생성: 애그리게이트 스냅샷 예약 꽉 참
** 이벤트 심각도: 경고






== 명령 버튼

* * 출하 시 기본값으로 복원 *
+
구성 설정을 출하 시 기본값으로 복원할 수 있습니다.

* * 저장 *
+
선택한 옵션에 대한 구성 설정을 저장합니다.


