---
permalink: online-help/reference-group-action-volume-thresholds-section.html 
sidebar: sidebar 
keywords:  
summary: group action-volume thresholds 섹션에서는 볼륨에 대한 그룹 수준 상태 임계값을 구성할 수 있습니다. 이러한 임계값은 그룹의 모든 볼륨에 적용됩니다. 볼륨 상태 임계값이 그룹 수준에서 구성되면 글로벌 상태 임계값은 영향을 받지 않습니다. 
---
= 그룹 작업 - 볼륨 임계값 섹션입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
group action-volume thresholds 섹션에서는 볼륨에 대한 그룹 수준 상태 임계값을 구성할 수 있습니다. 이러한 임계값은 그룹의 모든 볼륨에 적용됩니다. 볼륨 상태 임계값이 그룹 수준에서 구성되면 글로벌 상태 임계값은 영향을 받지 않습니다.

다음과 같은 볼륨 상태 임계값을 구성하여 그룹 작업을 구성할 수 있습니다.

* 용량
* 성장
* qtree 할당량
* Snapshot 복사본
* inode


글로벌 기본값은 볼륨 상태 임계값이 이러한 범주 중 하나에 대해 구성되지 않은 경우 사용됩니다. 다음에 대한 상태 임계값을 설정할 수 있습니다.

* 용량
* 성장
* qtree 할당량
* Snapshot 복사본
* inode




== 용량 섹션을 참조하십시오

다음 볼륨 용량 상태 임계값에 대한 조건을 설정할 수 있습니다.

* * 공간이 거의 가득 찼습니다 *
+
볼륨이 거의 꽉 찬 것으로 간주되는 비율을 지정합니다.

+
** 기본값은 80%입니다
+
이 임계값에 대한 값은 관리 서버에서 이벤트를 생성하기 위한 볼륨 최대 임계값 값보다 작아야 합니다.

** 생성된 이벤트: 볼륨이 거의 찼습니다
** 이벤트 심각도: 경고


* * 공간이 가득 참 *
+
볼륨이 가득 찬 것으로 간주되는 비율을 지정합니다.

+
** 기본값은 90%입니다
** 생성된 이벤트: 볼륨 꽉 참
** 이벤트 심각도: 오류


* * 과대 커밋 *
+
볼륨이 초과 커밋된 것으로 간주되는 비율을 지정합니다.

+
** 기본값은 100%입니다
** 생성된 이벤트: 볼륨 초과 커밋
** 이벤트 심각도: 오류






== 성장 섹션

볼륨 증가에 대해 다음과 같은 상태 임계값 조건을 설정할 수 있습니다.

* * 성장률 *
+
시스템에서 Volume Growth Rate Abnormal 이벤트를 생성하기 전에 볼륨의 증가율이 정상으로 간주되는 비율을 지정합니다.

+
** 기본값은 1%입니다
** 이벤트 발생: 용적 증가율 비정상
** 이벤트 심각도: 경고


* * 성장률 감도 *
+
볼륨의 증가율의 표준 편차에 적용되는 계수를 지정합니다. 증가율이 계수 표준 편차를 초과하면 Volume Growth Rate Abnormal 이벤트가 생성됩니다.

+
성장률 감도 값이 낮을수록 증가율의 변화에 매우 민감함을 나타냅니다. 성장률 감도 범위는 1 ~ 5입니다.

+
** 기본값: 2






== Qtree 할당량 섹션입니다

볼륨 할당량에 대해 다음 상태 임계값 조건을 설정할 수 있습니다.

* * 거의 과대 과대 *
+
qtree 할당량에 의해 볼륨이 거의 초과된 것으로 간주되는 비율을 지정합니다.

+
** 기본값은 95%입니다
** 생성된 이벤트: 볼륨 Qtree 할당량이 거의 커밋되었습니다
** 이벤트 심각도: 경고


* * 과대 커밋 *
+
Qtree 할당량에 의해 초과된 것으로 간주되는 볼륨 비율을 지정합니다.

+
** 기본값은 100%입니다
** 생성된 이벤트: 볼륨 Qtree 할당량이 초과 커밋되었습니다
** 이벤트 심각도: 오류






== Snapshot Copies 섹션입니다

볼륨의 스냅샷 복사본에 대해 다음과 같은 상태 임계값 조건을 설정할 수 있습니다.

* * Snapshot Reserve Full(스냅숏 예비 공간 전체) *
+
스냅샷 복사본에 예약된 공간이 가득 찬 것으로 간주되는 비율을 지정합니다.

+
** 기본값은 90%입니다
** 이벤트 생성: 볼륨 스냅샷 예약 가득 참
** 이벤트 심각도: 오류


* * 완전 충전 시까지 남은 기간 *
+
스냅샷 복사본에 예약된 공간이 전체 용량에 도달하기 전까지 남은 일 수를 지정합니다.

+
** 기본값: 7
** 이벤트 생성: 볼륨 스냅샷 예약 기간(전체 백업 시까지)
** 이벤트 심각도: 오류


* * 카운트 *
+
너무 많은 것으로 간주되는 볼륨의 스냅샷 복사본 수를 지정합니다.

+
** 기본값: 250
** 이벤트 생성: Snapshot 복사본이 너무 많습니다
** 이벤트 심각도: 오류






== inode 섹션

inode에 대해 다음과 같은 상태 임계값 조건을 설정할 수 있습니다.

* * 거의 다 찼음 *
+
볼륨이 대부분의 inode를 사용한 것으로 간주되는 비율을 지정합니다.

+
** 기본값은 80%입니다
** 이벤트 생성: inode가 거의 찼습니다
** 이벤트 심각도: 경고


* * 전체 *
+
볼륨이 모든 inode를 사용한 것으로 간주되는 비율을 지정합니다.

+
** 기본값은 90%입니다
** 이벤트 생성: inode Full
** 이벤트 심각도: 오류



