---
permalink: online-help/reference-edit-qtree-thresholds-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: Qtree의 용량과 관련된 이벤트가 생성될 때 알림을 보내도록 경고를 구성하고 이벤트에 대한 수정 조치를 수행할 수 있습니다. 예를 들어, Qtree Full 임계값의 경우 지정된 기간 동안 조건이 지속되는 경우 알림을 보내도록 알림을 구성할 수 있습니다. 
---
= 트리 임계값 편집 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
qtree의 용량과 관련된 이벤트가 생성될 때 알림을 보내도록 알림을 구성하고 이벤트에 대한 수정 조치를 수행할 수 있습니다. 예를 들어, Qtree Full 임계값의 경우 지정된 기간 동안 조건이 지속되는 경우 알림을 보내도록 알림을 구성할 수 있습니다.

OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

Qtree 임계값 편집 대화 상자에서는 선택한 qtree에 적용되는 qtree 레벨의 임계값을 구성할 수 있습니다. 임계값이 qtree 수준에서 구성되면 그룹 레벨 임계값 또는 글로벌 레벨 임계값보다 높은 우선 순위가 높습니다.

qtree 수준에서 용량에 대한 임계값 설정을 구성할 수 있습니다. qtree 임계값 유형의 그룹 작업이 구성되면 qtree 레벨에서 구성되지 않은 설정에 그룹 작업 임계값이 사용됩니다. Qtree 임계값 유형의 그룹 작업이 구성되지 않은 경우 Qtree 임계값 편집 대화 상자의 구성되지 않은 영역에 글로벌 임계값을 사용합니다.



== 용량 영역

용량 영역에서는 다음 qtree 용량 임계값 조건을 설정할 수 있습니다.

* * 공간이 거의 가득 찼습니다 *
+
qtree가 거의 가득 찬 것으로 간주되는 비율을 지정합니다. 또한 지정된 임계값에 해당하는 qtree의 크기도 표시됩니다.

+
슬라이더를 사용하여 임계값을 설정할 수도 있습니다.

* * 공간이 가득 참 *
+
qtree가 가득 찬 것으로 간주되는 비율을 지정합니다. 또한 지정된 임계값에 해당하는 qtree의 크기도 표시됩니다.

+
슬라이더를 사용하여 임계값을 설정할 수도 있습니다.





== 명령 버튼

명령 버튼을 사용하여 선택한 qtree에 대해 다음 작업을 수행할 수 있습니다.

* * 기본값으로 복원 *
+
임계값을 다음 중 하나로 복원할 수 있습니다.

+
** 그룹 값 - qtree가 그룹에 속하고 해당 그룹에 qtree 임계값 동작 유형이 있는 경우.
** 글로벌 가치이며, qtree가 그룹에 속하지 않거나 qtree 임계값 동작 유형이 없는 그룹에 속해 있는 경우.


* * 저장 *
+
모든 임계값 설정을 저장합니다.

* * 저장 후 닫기 *
+
모든 임계값 설정을 저장한 다음 대화 상자를 닫습니다.

* * 취소 *
+
임계값 설정에 대한 변경 사항을 무시하고 대화 상자를 닫습니다.


