---
permalink: online-help/reference-initialize-update-relationship-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: Initialize/Update 대화 상자를 사용하면 새 보호 관계에 대해 초기 계획을 처음 전송할 수도 있고, 이미 초기화된 상태에서 수동으로 예정되지 않은 증분 업데이트를 수행하려는 경우 관계를 업데이트할 수도 있습니다. 
---
= 초기화/업데이트 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Initialize/Update 대화 상자를 사용하면 새 보호 관계에 대해 초기 계획을 처음 전송할 수도 있고, 이미 초기화된 상태에서 수동으로 예정되지 않은 증분 업데이트를 수행하려는 경우 관계를 업데이트할 수도 있습니다.



== 전송 옵션 탭

전송 옵션 탭에서는 전송의 초기화 우선 순위를 변경하고 전송 중에 사용되는 대역폭을 변경할 수 있습니다.

* * 전송 우선순위 *
+
전송이 실행되는 우선 순위입니다. 보통 또는 낮음을 선택할 수 있습니다. 낮은 전송 우선 순위를 지정하는 정책보다 먼저 일반 전송 우선 순위를 지정하는 정책과의 관계. 기본적으로 보통이 선택되어 있습니다.

* * 최대 전송 속도 *
+
네트워크를 통해 클러스터 간에 데이터가 전송되는 최대 속도를 지정합니다. 최대 전송 속도를 사용하지 않도록 선택하는 경우 관계 간의 기본 전송은 무제한입니다. 하지만 ONTAP 8.2를 실행 중이고 운영 클러스터와 보조 클러스터가 동일한 경우에는 이 설정이 무시됩니다. 최대 전송 속도가 서로 다른 여러 관계를 선택한 경우 다음 최대 전송 속도 설정 중 하나를 지정할 수 있습니다.

+
** 개별 관계를 설정하거나 편집하는 동안 지정된 값을 사용합니다
+
이 옵션을 선택하면 초기화 및 업데이트 작업에서 각 관계의 생성 또는 편집 시 지정된 최대 전송 속도를 사용합니다. 이 필드는 전송 속도가 다른 여러 관계가 초기화되거나 업데이트되는 경우에만 사용할 수 있습니다.

** 무제한
+
관계 간 전송에 대한 대역폭 제한이 없음을 나타냅니다. 이 필드는 전송 속도가 다른 여러 관계가 초기화되거나 업데이트되는 경우에만 사용할 수 있습니다.

** 대역폭 제한
+
이 옵션을 선택하면 네트워크 대역폭이 지정한 값으로 제한됩니다. 숫자 값을 입력한 다음 초당 킬로바이트(kbps), 초당 메가바이트(Mbps), 초당 기가바이트(Gbps) 또는 초당 테라바이트(Tbps)를 선택할 수 있습니다. 지정하는 최대 전송 속도는 1kbps 이상, 4Tbps 미만이어야 합니다.







== 소스 Snapshot 복사본 탭

소스 스냅샷 복사본 탭에는 기본 전송에 사용되는 소스 스냅샷 복사본에 대한 다음 정보가 표시됩니다.

* * 소스 볼륨 *
+
해당 소스 볼륨의 이름을 표시합니다.

* * 대상 볼륨 *
+
선택한 대상 볼륨의 이름을 표시합니다.

* * 소스 유형 *
+
볼륨 유형을 표시합니다. 유형은 읽기/쓰기 또는 데이터 보호 중 하나일 수 있습니다.

* * 스냅샷 복사본 *
+
데이터 전송에 사용되는 스냅샷 복사본을 표시합니다. 스냅샷 복사본 값을 클릭하면 현재 사용 중인 보호 관계 유형과 수행 중인 작업에 따라 전송할 특정 스냅샷 복사본을 선택할 수 있는 소스 스냅샷 복사본 선택 대화 상자가 표시됩니다. 다른 스냅샷 복사본을 지정하는 옵션은 데이터 보호 유형 소스에 사용할 수 없습니다.





== 명령 버튼

명령 단추를 사용하여 다음 작업을 수행할 수 있습니다.

* * 취소 *
+
선택 사항을 취소하고 초기화/업데이트 대화 상자를 닫습니다.

* * 제출 *
+
선택 사항을 저장하고 초기화 또는 업데이트 작업을 시작합니다.


