---
permalink: online-help/reference-nfs-shares-health-fields.html 
sidebar: sidebar 
keywords:  
summary: NFS 엑스포트 보고서를 사용하면 스토리지 시스템의 볼륨에 대한 NFS 엑스포트 정책과 관련 규칙에 대한 정보를 감사할 수 있습니다. 
---
= NFS 엑스포트 보고서
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS 엑스포트 보고서를 사용하면 스토리지 시스템의 볼륨에 대한 NFS 엑스포트 정책과 관련 규칙에 대한 정보를 감사할 수 있습니다.



== NFS 내보내기는 표 형식 보기입니다

* * 클러스터 *
+
클러스터의 이름을 표시합니다.

* * 스토리지 가상 머신 *
+
NFS 엑스포트 정책을 사용하는 SVM의 이름을 표시합니다.

* * 볼륨 *
+
NFS 엑스포트 정책이 있는 볼륨의 이름을 표시합니다.

* * Qtree *
+
NFS 엑스포트 정책이 있는 볼륨의 qtree 이름을 표시합니다.

* * 볼륨 상태 *
+
볼륨의 현재 상태를 표시합니다. 상태는 오프라인, 온라인 또는 제한됨일 수 있습니다.

+
** 오프라인
+
볼륨에 대한 읽기 또는 쓰기 액세스가 허용되지 않습니다.

** 온라인
+
볼륨에 대한 읽기 및 쓰기 액세스가 허용됩니다.

** 제한
+
패리티 재구성 같은 제한된 작업은 허용되지만 데이터 액세스는 허용되지 않습니다.



* * 정크션 경로 *
+
볼륨이 마운트된 경로를 표시합니다.

* * 정크션 경로 활성화 *
+
마운트된 볼륨에 액세스할 경로가 활성 상태인지 비활성 상태인지 여부를 표시합니다.

* * 수출 정책 *
+
내보낸 볼륨에 대한 액세스 권한을 정의하는 규칙을 표시합니다.

* * 규칙 색인 *
+
인증 프로토콜 및 액세스 권한과 같은 엑스포트 정책과 관련된 규칙을 표시합니다.

* * 액세스 프로토콜 *
+
엑스포트 정책 규칙에 대해 활성화된 프로토콜을 표시합니다.

* * 클라이언트 일치 *
+
볼륨의 데이터에 액세스할 수 있는 권한이 있는 클라이언트를 표시합니다.

* * 읽기 전용 액세스 *
+
볼륨의 데이터를 읽는 데 사용되는 인증 프로토콜을 표시합니다.

* * 읽기 쓰기 권한 *
+
볼륨의 데이터를 읽거나 쓰는 데 사용되는 인증 프로토콜을 표시합니다.

* * 보안 스타일 *
+
내보낸 볼륨에 대한 액세스 권한을 표시합니다. 보안 스타일은 UNIX, Unified, NTFS 또는 Mixed일 수 있습니다.

+
** UNIX(NFS 클라이언트)
+
볼륨의 파일과 디렉토리에는 UNIX 권한이 있습니다.

** 통합
+
볼륨의 파일과 디렉토리에는 통합 보안 스타일이 있습니다.

** NTFS(CIFS 클라이언트)
+
볼륨의 파일과 디렉토리에는 Windows NTFS 권한이 있습니다.

** 혼합
+
볼륨의 파일 및 디렉토리에는 UNIX 사용 권한이나 Windows NTFS 사용 권한이 있을 수 있습니다.



* Unix 사용 권한 *
+
내보낸 볼륨에 대해 설정된 8진수 문자열 형식으로 UNIX 사용 권한 비트를 표시합니다. UNIX 스타일 사용 권한 비트와 유사합니다.


