---
permalink: online-help/reference-create-snapvault-policy-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: SnapVault 정책 생성 대화 상자에서는 SnapVault 전송의 우선 순위를 설정하는 정책을 생성할 수 있습니다. 정책을 사용하여 운영 볼륨에서 2차 볼륨으로 전송하는 효율성을 극대화할 수 있습니다. 
---
= SnapVault 정책 생성 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapVault 정책 생성 대화 상자에서는 SnapVault 전송의 우선 순위를 설정하는 정책을 생성할 수 있습니다. 정책을 사용하여 운영 볼륨에서 2차 볼륨으로 전송하는 효율성을 극대화할 수 있습니다.

* * 대상 클러스터 *
+
보호 구성 대화 상자의 SnapVault 탭에서 선택한 클러스터의 이름입니다.

* * 대상 SVM *
+
보호 구성 대화 상자의 SnapVault 탭에서 선택한 SVM의 이름입니다.

* * 정책 이름 *
+
새 정책에 대해 제공한 이름입니다. 정책 이름은 A ~ Z 문자, a ~ z, 0 ~ 9, 마침표(.), 하이픈(-), 및 밑줄(_).

* * 전송 우선순위 *
+
전송이 실행되는 우선 순위입니다. 보통 또는 낮음을 선택할 수 있습니다. 낮은 전송 우선 순위를 지정하는 정책이 있는 정책보다 먼저 실행되는 일반 전송 우선 순위를 지정하는 정책과의 관계를 전송합니다. 기본 설정은 보통입니다.

* * 설명 *
+
SnapVault 정책에 대해 최대 255자의 주석을 추가할 수 있는 선택적 필드입니다.

* * 액세스 시간 무시 *
+
액세스 시간만 변경된 파일에 대해 증분 전송을 무시할지 여부를 지정합니다.

* * 복제 레이블 *
+
테이블에 특정 복제 라벨이 정책에 포함된 ONTAP에서 선택한 스냅샷 복사본과 관련된 규칙이 나열되어 있습니다. 다음 정보 및 작업도 사용할 수 있습니다.

+
** 명령 버튼
+
명령 단추를 사용하여 다음 작업을 수행할 수 있습니다.

+
*** 추가
+
스냅샷 복사본 레이블 및 보존 개수를 생성할 수 있습니다.

*** 보존 개수를 편집합니다
+
기존 스냅샷 복사본 레이블의 보존 수를 변경할 수 있습니다. 보존 수는 1에서 251 사이의 숫자여야 합니다. 모든 규칙에 대한 모든 보존 수의 합계는 251을 초과할 수 없습니다.

*** 삭제
+
기존 스냅샷 복사본 레이블을 삭제할 수 있습니다.



** 스냅샷 복사본 레이블
+
스냅샷 복사본 레이블을 표시합니다. 로컬 스냅샷 복사본 정책이 동일한 볼륨을 하나 이상 선택하면 정책의 각 레이블에 대한 항목이 표시됩니다. 둘 이상의 로컬 스냅샷 복사본 정책이 있는 볼륨을 여러 개 선택하면 모든 정책의 모든 레이블이 테이블에 표시됩니다

** 스케줄
+
각 스냅샷 복사본 레이블과 연결된 스케줄을 표시합니다. 레이블에 둘 이상의 일정이 연결되어 있는 경우 해당 레이블의 일정이 쉼표로 구분된 목록에 표시됩니다. 레이블이 같지만 스케줄이 다른 볼륨을 여러 개 선택한 경우 스케줄에는 ""다양한""이 표시되어 둘 이상의 스케줄이 선택한 볼륨과 연결되어 있음을 나타냅니다.

** 대상 보존 수입니다
+
지정된 레이블이 SnapVault 보조 이미지에 유지되는 스냅샷 복사본의 수를 표시합니다. 일정이 여러 개인 레이블의 보존 수에는 각 레이블 및 일정 쌍의 보존 수가 표시됩니다. 둘 이상의 로컬 스냅샷 복사본 정책이 있는 볼륨을 여러 개 선택하면 보존 카운트가 비어 있습니다.




