---
permalink: online-help/reference-volume-events.html 
sidebar: sidebar 
keywords:  
summary: 볼륨 이벤트는 잠재적인 문제를 모니터링할 수 있는 볼륨 상태에 대한 정보를 제공합니다. 이벤트는 영향 영역별로 그룹화되며 이벤트 이름, 트랩 이름, 영향 수준, 소스 유형 및 심각도를 포함합니다. 
---
= 볼륨 이벤트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨 이벤트는 잠재적인 문제를 모니터링할 수 있는 볼륨 상태에 대한 정보를 제공합니다. 이벤트는 영향 영역별로 그룹화되며 이벤트 이름, 트랩 이름, 영향 수준, 소스 유형 및 심각도를 포함합니다.

별표(*)는 Unified Manager 이벤트로 변환된 EMS 이벤트를 나타냅니다.



== 영향 영역: 가용성

|===
| 이벤트 이름(트랩 이름) | 충격 수준 | 소스 유형 | 심각도입니다 


 a| 
볼륨 제한(문서 볼륨 제한)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고



 a| 
볼륨 오프라인(documVolumeOffline)
 a| 
사고
 a| 
볼륨
 a| 
심각



 a| 
부분적으로 사용 가능한 볼륨(문서 볼륨 PartiallyAvailable)
 a| 
위험입니다
 a| 
볼륨
 a| 
오류



 a| 
볼륨 마운트 해제됨(해당 없음)
 a| 
이벤트
 a| 
볼륨
 a| 
정보



 a| 
마운트된 볼륨(해당 없음)
 a| 
이벤트
 a| 
볼륨
 a| 
정보



 a| 
볼륨 다시 마운트(해당 없음)
 a| 
이벤트
 a| 
볼륨
 a| 
정보



 a| 
Volume Junction Path Inactive(문서 JunctVolumeJunctionPathInactive)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고



 a| 
볼륨 자동 크기 사용(해당 없음)
 a| 
이벤트
 a| 
볼륨
 a| 
정보



 a| 
Volume Autosize(볼륨 자동 크기) - Disabled(사용 안 함)(해당 없음)
 a| 
이벤트
 a| 
볼륨
 a| 
정보



 a| 
볼륨 자동 크기 최대 용량 수정됨(해당 없음)
 a| 
이벤트
 a| 
볼륨
 a| 
정보



 a| 
볼륨 자동 크기 증분 크기 수정됨(해당 없음)
 a| 
이벤트
 a| 
볼륨
 a| 
정보

|===


== 충격 영역: 용량

|===
| 이벤트 이름(트랩 이름) | 충격 수준 | 소스 유형 | 심각도입니다 


 a| 
씬 프로비저닝된 볼륨 공간 위험(ocumThinProvisionVolumeSpaceAtRisk)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고



 a| 
볼륨 공간이 가득 참(문서 볼륨 전체)
 a| 
위험입니다
 a| 
볼륨
 a| 
오류



 a| 
볼륨 공간이 거의 가득 참(문서 볼륨 NearlyFull)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고



 a| 
Volume Logical Space Full * (volumeLogicalSpaceFull)
 a| 
위험입니다
 a| 
볼륨
 a| 
오류



 a| 
볼륨 논리적 공간이 거의 가득 참 * (volumeLogicalSpaceNearlyFull)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고



 a| 
볼륨 논리적 공간 정상 * (volumeLogicalSpaceAllOK)
 a| 
이벤트
 a| 
볼륨
 a| 
정보



 a| 
볼륨 스냅숏 예비 공간 가득 참(문서 스냅샷전체)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고



 a| 
Snapshot 복사본이 너무 많음(문서 스냅샷모든)
 a| 
위험입니다
 a| 
볼륨
 a| 
오류



 a| 
볼륨 Qtree 할당량이 커밋됨(문서 볼륨 QtreeQuotaOverCommitted)
 a| 
위험입니다
 a| 
볼륨
 a| 
오류



 a| 
볼륨 Qtree 할당량이 거의 커밋됨(documotVolumeQtreeQuotaAlmostOverCommitted)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고



 a| 
용적 증가율 비정상(ocumVolumeGrowthRateAbnormal)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고



 a| 
가득 차기까지 남은 볼륨 일 수(ocumVolumeDaysUntilFullSoon)
 a| 
위험입니다
 a| 
볼륨
 a| 
오류



 a| 
볼륨 공간 보장 비활성화됨(해당 없음)
 a| 
이벤트
 a| 
볼륨
 a| 
정보



 a| 
볼륨 공간 보장 사용(해당 없음)
 a| 
이벤트
 a| 
볼륨
 a| 
정보



 a| 
볼륨 공간 보장 수정됨(해당 없음)
 a| 
이벤트
 a| 
볼륨
 a| 
정보



 a| 
볼륨 스냅숏 예비 기간(전체(Documents VolumeSnapshotReserveDaysUntilFullSoon)
 a| 
위험입니다
 a| 
볼륨
 a| 
오류



 a| 
FlexGroup 구성 요소 공간 문제 * (flexGroupConstitutsHaveSpaceIssues)
 a| 
위험입니다
 a| 
볼륨
 a| 
오류



 a| 
FlexGroup 구성 요소 공간 상태 모두 정상 * (flexGroupConstitutsSpaceStatusAllOK)
 a| 
이벤트
 a| 
볼륨
 a| 
정보



 a| 
FlexGroup 구성 요소 inode 문제 * (flexGroupConstitutsHaveintesIssues)
 a| 
위험입니다
 a| 
볼륨
 a| 
오류



 a| 
FlexGroup 구성 요소 inode 상태 모두 정상 * (flexGroupConstituentsInudesStatusAllOK)
 a| 
이벤트
 a| 
볼륨
 a| 
정보



 a| 
WAFL 볼륨 자동 크기 조정 실패 *
 a| 
위험입니다
 a| 
볼륨
 a| 
오류



 a| 
WAFL 볼륨 자동 크기 조정 완료 *
 a| 
이벤트
 a| 
볼륨
 a| 
정보

|===


== 충격 영역: 구성

|===
| 이벤트 이름(트랩 이름) | 충격 수준 | 소스 유형 | 심각도입니다 


 a| 
볼륨 이름 변경(해당 없음)
 a| 
이벤트
 a| 
볼륨
 a| 
정보



 a| 
검색된 볼륨(해당 없음)
 a| 
이벤트
 a| 
볼륨
 a| 
정보



 a| 
볼륨 삭제됨(해당 없음)
 a| 
이벤트
 a| 
볼륨
 a| 
정보

|===


== 충격 영역: 성능

|===
| 이벤트 이름(트랩 이름) | 충격 수준 | 소스 유형 | 심각도입니다 


 a| 
QoS 볼륨 최대 IOPS 경고 임계값 위반(문서 QosVolumeMaxIopsWarning)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고



 a| 
QoS 볼륨 최대 MBPS 경고 임계값 위반(문서 QosVolumeMaxMbpsWarning)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고



 a| 
QoS 볼륨 최대 IOPS/TB 경고 임계값 위반(문서 QosVolumeMaxIopsPerTbWarning)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고



 a| 
볼륨 IOPS 중요 임계값 위반(문서 VolumeIopsIncident)
 a| 
사고
 a| 
볼륨
 a| 
심각



 a| 
볼륨 IOPS 경고 임계값 위반(문서 볼륨 경고)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고



 a| 
볼륨 MBPS 중요 임계값 위반(문서 볼륨 Mbps인시던트)
 a| 
사고
 a| 
볼륨
 a| 
심각



 a| 
볼륨 MBps 경고 임계값 위반(문서 볼륨 MbpsWarning)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고



 a| 
볼륨 지연 시간 ms/op 중요 임계값 위반(VolumeLatencyIncident)
 a| 
사고
 a| 
볼륨
 a| 
심각



 a| 
볼륨 지연 시간 ms/op 경고 임계값 위반(VolumeLatencyWarning)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고



 a| 
볼륨 캐시 비적중 비율 위험 임계값 위반(문서 VolumeCacheMisssRatioIncident)
 a| 
사고
 a| 
볼륨
 a| 
심각



 a| 
볼륨 캐시 비적중 비율 경고 임계값 위반(문서 VolumeCacheMisssRatioWarning)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고



 a| 
볼륨 지연 시간 및 IOPS 중요 임계값 위반(문서 라티encyIsopsIncident)
 a| 
사고
 a| 
볼륨
 a| 
심각



 a| 
볼륨 지연 시간 및 IOPS 경고 임계값 위반(문서 LatencyIsopsWarning)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고



 a| 
볼륨 지연 시간 및 MBPS 위험 임계값 위반(문서 라티encyMbpsIncident)
 a| 
사고
 a| 
볼륨
 a| 
심각



 a| 
볼륨 지연 시간 및 MBPS 경고 임계값 위반(문서 LatencyMbpsWarning)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고



 a| 
볼륨 지연 시간 및 애그리게이트 성능 사용된 용량 위험 임계값 위반(문서 LatencyAggregatePerfCapacityUsedIncident)
 a| 
사고
 a| 
볼륨
 a| 
심각



 a| 
볼륨 지연 시간 및 애그리게이트 성능 사용된 용량 경고 임계값 위반(문서 LatencyAggregatePerfCapacityUsedWarning)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고



 a| 
볼륨 지연 및 애그리게이트 활용률 주요 임계값 위반(VolumeLatencyAggregateUtilationIncident)
 a| 
사고
 a| 
볼륨
 a| 
심각



 a| 
볼륨 지연 및 애그리게이트 활용률 경고 임계값 위반(VolumeLatencyAggregateUtilationWarning)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고



 a| 
볼륨 지연 시간 및 노드 성능 사용된 용량 위험 임계값 위반(문서 LatencyNodePerfCapacityUsedIncident)
 a| 
사고
 a| 
볼륨
 a| 
심각



 a| 
볼륨 지연 시간 및 노드 성능 사용된 용량 경고 임계값 위반(문서 LatencyNodePerfCapacityUsedWarning)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고



 a| 
볼륨 지연 시간 및 노드 성능 사용된 용량 - 테이크오버가 중요 임계값 위반(VolumeLatencyAggregatePerfCapacityUsedTakeOverIncident)
 a| 
사고
 a| 
볼륨
 a| 
심각



 a| 
볼륨 지연 시간 및 노드 성능 사용된 용량 - 다케오버 경고 임계값 위반(VolumeLatencyAggregatePerfCapacityUsedTakeoverWarning)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고



 a| 
볼륨 지연 시간 및 노드 활용률 주요 임계값 위반(VolumeLatencyNodeUtilationIncident)
 a| 
사고
 a| 
볼륨
 a| 
심각



 a| 
볼륨 지연 및 노드 활용률 경고 임계값 위반(VolumeLatencyNodeUtilationWarning)
 a| 
위험입니다
 a| 
볼륨
 a| 
경고

|===