---
permalink: online-help/reference-email-notification-format-page.html 
sidebar: sidebar 
keywords:  
summary: 'e-메일 알림 형식 페이지에는 할당량 관련 문제(소프트 제한값 위반 또는 하드 제한값에 도달함\)가 있을 때 사용자 또는 사용자 그룹에 전송되는 e-메일의 규칙이 표시됩니다.' 
---
= 이메일 알림 형식 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
e-메일 알림 형식 페이지에는 할당량 관련 문제(소프트 제한값 위반 또는 하드 제한값에 도달함)가 있을 때 사용자 또는 사용자 그룹에 전송되는 e-메일의 규칙이 표시됩니다.

e-메일 알림은 다음 사용자 또는 사용자 그룹 할당량 이벤트가 생성된 경우에만 전송됩니다. 사용자 또는 그룹 할당량 디스크 공간 소프트 제한값 위반, 사용자 또는 그룹 할당량 파일 개수 소프트 제한값 위반, 사용자 또는 그룹 할당량 디스크 공간 하드 제한값에 도달했거나 사용자 또는 그룹 할당량 파일 개수의 하드 제한값에 도달했습니다.

* * 보낸 사람 *
+
E-mail을 보낼 때 사용할 수 있는 E-mail 주소를 표시합니다. 기본적으로 이 주소는 설정/알림 페이지에 지정된 이메일 주소입니다.

* * 제목 *
+
알림 이메일의 제목을 표시합니다.

* * 이메일 세부 정보 *
+
알림 E-mail의 텍스트를 표시합니다. 요구 사항에 따라 텍스트를 수정할 수 있습니다. 예를 들어 할당량 특성과 관련된 정보를 제공하고 키워드 수를 줄일 수 있습니다. 그러나 키워드를 수정하면 안 됩니다.

+
유효한 키워드는 다음과 같습니다.

+
** $EVENT_NAME
+
이메일 알림을 발생시킨 이벤트 이름을 지정합니다.

** $quota_target입니다
+
할당량을 적용할 수 있는 qtree 또는 볼륨을 지정합니다.

** $quota_used_percent
+
사용자 또는 사용자 그룹에서 사용하는 디스크 하드 제한값, 디스크 소프트 제한값, 파일 하드 제한값 또는 파일 소프트 제한값의 백분율을 지정합니다.

** $quota_limit입니다
+
사용자 또는 사용자 그룹이 도달한 디스크 하드 제한이나 파일 하드 제한값을 지정하고 다음 이벤트 중 하나가 생성됩니다.

+
*** 사용자 또는 그룹 할당량 디스크 공간 하드 제한값에 도달했습니다
*** 사용자 또는 그룹 할당량 디스크 공간 소프트 제한값에 도달했습니다
*** 사용자 또는 그룹 할당량 파일 개수의 하드 제한값에 도달했습니다
*** 사용자 또는 그룹 할당량 파일 개수 소프트 제한값에 도달했습니다


** $quota_used
+
사용된 디스크 공간 또는 사용자 또는 사용자 그룹이 생성한 파일 수를 지정합니다.

** $quota_user
+
사용자 또는 사용자 그룹 이름을 지정합니다.







== 명령 버튼

명령 버튼을 사용하여 이메일 알림 형식의 변경 사항을 미리 보거나 저장하거나 취소할 수 있습니다.

* * 미리보기 *
+
알림 E-mail의 미리보기를 표시합니다.

* * 출하 시 기본값으로 복원 *
+
알림 형식을 공장 출하 시 기본값으로 복원할 수 있습니다.

* * 저장 *
+
알림 형식에 대한 변경 내용을 저장합니다.


