---
permalink: online-help/reference-volume-thresholds-page.html 
sidebar: sidebar 
keywords:  
summary: 볼륨에 대한 구성/상태 임계값 페이지에서 모니터링되는 볼륨에 대한 글로벌 상태 임계값을 구성할 수 있습니다. 개별 볼륨 또는 모든 볼륨에 대해 전역적으로 임계값을 설정할 수 있습니다. 옵션을 전역적으로 구성하면 모든 개체의 기본값이 수정됩니다. 그러나 개체 수준에서 기본값이 변경된 경우에는 글로벌 값이 수정되지 않습니다. 
---
= 볼륨에 대한 구성/상태 임계값 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨에 대한 구성/상태 임계값 페이지에서 모니터링되는 볼륨에 대한 글로벌 상태 임계값을 구성할 수 있습니다. 개별 볼륨 또는 모든 볼륨에 대해 전역적으로 임계값을 설정할 수 있습니다. 옵션을 전역적으로 구성하면 모든 개체의 기본값이 수정됩니다. 그러나 개체 수준에서 기본값이 변경된 경우에는 글로벌 값이 수정되지 않습니다.

OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

이벤트는 임계값이 위반될 때 생성됩니다. 사용자는 이러한 이벤트에 대해 수정 조치를 취할 수 있습니다.

용량, 볼륨 스냅샷 복사본, 할당량, 볼륨 증가 및 inode에 대한 임계값을 설정할 수 있습니다.



== 용량 영역

Capacity 영역에서는 다음과 같은 볼륨 용량 임계값 조건을 설정할 수 있습니다. 볼륨에 대해 Autogrow를 사용하도록 설정한 경우 원래 볼륨 크기를 기준으로 하지 않고 자동으로 설정된 최대 볼륨 크기에 따라 용량 임계값이 위반된 것으로 간주됩니다.

* * 공간이 거의 가득 찼습니다 *
+
볼륨이 거의 꽉 찬 것으로 간주되는 비율을 지정합니다.

+
** 기본값은 80%입니다
+
관리 서버에서 이벤트를 생성하려면 이 임계값에 대한 값이 볼륨 최대 임계값 값보다 작아야 합니다.

** 생성된 이벤트: 볼륨이 거의 찼습니다
** 이벤트 심각도: 경고


* * 공간이 가득 참 *
+
볼륨이 가득 찬 것으로 간주되는 비율을 지정합니다.

+
** 기본값은 90%입니다
** 생성된 이벤트: 볼륨 꽉 참
** 이벤트 심각도: 오류


* * 완전 충전 시까지 남은 기간 *
+
볼륨이 전체 용량에 도달하기 전까지 남은 일 수를 지정합니다.

+
** 기본값: 7
** 생성된 이벤트: 볼륨 일(최대
** 이벤트 심각도: 오류






== Snapshot 복사본 영역

Snapshot 복사본 영역에서는 볼륨의 스냅샷 복사본에 대해 다음과 같은 임계값 조건을 설정할 수 있습니다.

* * Snapshot Reserve Full(스냅숏 예비 공간 전체) *
+
스냅샷 복사본에 예약된 공간이 가득 찬 것으로 간주되는 비율을 지정합니다.

+
** 기본값은 90%입니다
** 이벤트 생성: 볼륨 스냅샷 예약 가득 참
** 이벤트 심각도: 오류


* * 완전 충전 시까지 남은 기간 *
+
스냅샷 복사본에 예약된 공간이 전체 용량에 도달하기 전까지 남은 일 수를 지정합니다.

+
** 기본값: 7
** 이벤트 생성: 볼륨 스냅샷 예약 기간(전체 백업 시까지)
** 이벤트 심각도: 오류


* * 카운트 *
+
너무 많은 것으로 간주되는 볼륨의 스냅샷 복사본 수를 지정합니다.

+
** 기본값: 250
** 이벤트 생성: Snapshot 복사본이 너무 많습니다
** 이벤트 심각도: 오류






== Qtree 할당량 영역

Qtree Quota 영역에서는 다음과 같은 볼륨 할당량 임계값 조건을 설정할 수 있습니다.

* * 거의 과대 과대 *
+
qtree 할당량에 의해 볼륨이 거의 초과된 것으로 간주되는 비율을 지정합니다.

+
** 기본값은 95%입니다
** 생성된 이벤트: 볼륨 Qtree 할당량이 거의 커밋되었습니다
** 이벤트 심각도: 경고


* * 과대 커밋 *
+
Qtree 할당량에 의해 초과된 것으로 간주되는 볼륨 비율을 지정합니다.

+
** 기본값은 100%입니다
** 생성된 이벤트: 볼륨 Qtree 할당량이 초과 커밋되었습니다
** 이벤트 심각도: 오류






== 성장 영역

Growth(성장) 영역에서는 볼륨 증가에 대해 다음과 같은 임계값 조건을 설정할 수 있습니다.

* * 성장률 *
+
시스템에서 Volume Growth Rate Abnormal 이벤트를 생성하기 전에 볼륨의 증가율이 정상으로 간주되는 비율을 지정합니다.

+
** 기본값은 1%입니다
** 이벤트 발생: 용적 증가율 비정상
** 이벤트 심각도: 경고


* * 성장률 감도 *
+
볼륨의 증가율의 표준 편차에 적용되는 계수를 지정합니다. 증가율이 계수 표준 편차를 초과하면 Volume Growth Rate Abnormal 이벤트가 생성됩니다.

+
성장률 감도 값이 낮을수록 체적이 증가율의 변화에 매우 민감함을 나타냅니다. 성장률 감도 범위는 1 ~ 5입니다.

+
** 기본값: 2


+
[NOTE]
====
글로벌 임계값 수준에서 볼륨의 증가율 민감도를 수정할 경우, 글로벌 임계값 수준에서 애그리게이트의 증가율 감도에도 변경 사항이 적용됩니다.

====




== inode 영역

inode 영역에서는 inode에 대해 다음과 같은 임계값 조건을 설정할 수 있습니다.

* * 거의 다 찼음 *
+
볼륨이 대부분의 inode를 사용한 것으로 간주되는 비율을 지정합니다.

+
** 기본값은 80%입니다
** 이벤트 생성: inode가 거의 찼습니다
** 이벤트 심각도: 경고


* * 전체 *
+
볼륨이 모든 inode를 사용한 것으로 간주되는 비율을 지정합니다.

+
** 기본값은 90%입니다
** 이벤트 생성: inode Full
** 이벤트 심각도: 오류






== 명령 버튼

* * 출하 시 기본값으로 복원 *
+
구성 설정을 출하 시 기본값으로 복원할 수 있습니다.

* * 저장 *
+
선택한 옵션에 대한 구성 설정을 저장합니다.


