---
permalink: online-help/reference-management-annotations-page.html 
sidebar: sidebar 
keywords:  
summary: 관리/주석 페이지에서는 Unified Manager에서 스토리지 객체에 주석을 지정하거나 주석을 편집하거나 삭제할 수 있는 주석을 만들 수 있습니다. 주석 = 값 쌍을 사용하여 스토리지 객체에 수동으로 주석을 달거나 주석 규칙을 구성할 수 있습니다. 저장 개체는 적용한 주석에 따라 동적으로 주석이 추가됩니다. 
---
= 관리/주석 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관리/주석 페이지에서는 Unified Manager에서 스토리지 객체에 주석을 지정하거나 주석을 편집하거나 삭제할 수 있는 주석을 만들 수 있습니다. 주석 = 값 쌍을 사용하여 스토리지 객체에 수동으로 주석을 달거나 주석 규칙을 구성할 수 있습니다. 저장 개체는 적용한 주석에 따라 동적으로 주석이 추가됩니다.

운영자로 로그인하면 페이지에 대한 읽기 권한만 갖게 됩니다. 스토리지 관리자 또는 Unified Manager 관리자로 로그인할 때 각 탭의 추가, 편집 또는 삭제 단추에 액세스할 수 있습니다.



== 주석 탭

주석 탭을 사용하면 Unified Manager에서 주석을 확인, 생성, 편집 또는 삭제할 수 있습니다.

* * 주석 목록 *
+
미리 정의된 주석과 사용자 정의 주석의 이름을 표시합니다. 각 주석과 관련된 주석 값의 개수도 표시됩니다. 주석 이름을 클릭하여 주석의 세부 정보를 볼 수 있습니다.





== 요약 영역

선택한 주석에 대한 다음 세부 정보를 볼 수 있습니다.

* * 설명 *
+
주석에 제공된 설명을 표시합니다.

* * 작성자 *
+
주석을 작성한 사용자의 이름을 표시합니다.

* * 만든 날짜 *
+
주석이 생성된 날짜를 표시합니다.





== 주석 = 값 쌍

선택한 주석에 사용할 수 있는 주석-값 쌍 및 관련 스토리지 객체의 목록을 표시합니다.

* * 값 *
+
주석 = 값 쌍의 이름을 표시합니다.

* * 적용 가능한 클러스터 *
+
특정 주석 = 값 쌍으로 주석이 추가된 클러스터의 수를 표시합니다. 번호를 클릭하여 클러스터 페이지를 볼 수 있습니다. 이 페이지에는 특정 값과 연결된 클러스터의 필터링된 목록이 표시됩니다.

* * 해당 SVM(스토리지 가상 머신) *
+
특정 주석 = 값 쌍으로 주석이 달린 SVM(스토리지 가상 머신) 수를 표시합니다. 번호를 클릭하여 SVM(스토리지 가상 머신) 페이지를 확인할 수 있습니다. 이 페이지에는 특정 값과 연결된 SVM(스토리지 가상 머신)의 필터링된 목록이 표시됩니다.

* * 해당 볼륨 *
+
특정 주석 = 값 쌍으로 주석이 추가된 볼륨의 수를 표시합니다. 숫자를 클릭하여 볼륨 페이지를 볼 수 있습니다. 그러면 특정 값과 연결된 볼륨의 필터링된 목록이 표시됩니다.





== 규칙을 통한 객체 연결

주석 규칙 목록과 선택한 주석에 대한 관련 저장 객체를 표시합니다.

* * 순위 *
+
스토리지 객체에 적용할 주석 규칙의 순서를 표시합니다.

* * 규칙 *
+
주석 규칙 이름을 표시합니다.

* * 대상 객체 유형 *
+
주석 규칙이 적용된 스토리지 객체의 유형을 표시합니다.

* * 관련 주석 값 *
+
스토리지 객체에 적용된 annotation = value pair을 표시합니다.

* * 적용 가능한 개체 *
+
주석 규칙에 따라 주석이 추가된 스토리지 객체의 개수를 표시합니다.





== 수동 개체 연결

수동으로 구성하고 스토리지 객체와 연결한 주석 목록을 표시합니다.

* * 주석 = 값 쌍 *
+
수동 주석의 이름과 값을 표시합니다.

* * 적용 가능한 클러스터 *
+
특정 수동 주석 값으로 주석이 추가된 클러스터의 수를 표시합니다. 번호를 클릭하여 클러스터 페이지를 볼 수 있습니다. 이 페이지에는 특정 값과 연결된 클러스터의 필터링된 목록이 표시됩니다.

* * 해당 SVM(스토리지 가상 머신) *
+
특정 수동 주석 값으로 주석이 추가된 SVM(스토리지 가상 머신) 수를 표시합니다. 번호를 클릭하여 SVM(스토리지 가상 머신) 페이지를 확인할 수 있습니다. 이 페이지에는 특정 값과 연결된 SVM(스토리지 가상 머신)의 필터링된 목록이 표시됩니다.

* * 해당 볼륨 *
+
특정 수동 주석 값으로 주석이 추가된 볼륨의 수를 표시합니다. 숫자를 클릭하여 볼륨 페이지를 볼 수 있습니다. 그러면 특정 값과 연결된 볼륨의 필터링된 목록이 표시됩니다.





== 명령 버튼

OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다. 미리 정의된 주석의 경우 값을 추가하거나 삭제할 수 없습니다.

* * 주석 추가 *
+
새 사용자 정의 주석을 작성하고 주석에 값을 지정할 수 있는 주석 추가 대화 상자를 엽니다.

* * 조치 *
+
선택한 주석 설명을 편집하거나 삭제할 수 있습니다.

* * 편집 *
+
주석 이름 및 설명을 수정할 수 있는 주석 편집 대화 상자를 엽니다.

* * 삭제 *
+
주석 값을 삭제할 수 있습니다. 주석 규칙 또는 그룹 규칙과 연결되지 않은 경우에만 값을 삭제할 수 있습니다.





== 주석 규칙 탭

Annotations Rules(주석 규칙) 탭에는 스토리지 개체에 주석을 다는 데 작성된 주석 규칙이 표시됩니다. 주석 규칙 추가, 편집, 삭제 또는 순서 변경 등의 작업을 수행할 수 있습니다. 또한 주석 규칙을 충족하는 스토리지 객체의 수를 볼 수도 있습니다.



== 명령 버튼

OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

* * 추가 *
+
스토리지 객체에 대한 주석 규칙을 생성할 수 있는 주석 규칙 추가 대화 상자를 표시합니다.

* * 편집 *
+
이전에 구성한 주석 규칙을 재구성할 수 있는 Edit Annotation Rule(주석 규칙 편집) 대화 상자를 표시합니다.

* * 삭제 *
+
선택한 주석 규칙을 삭제합니다.

* * 재주문 *
+
주석 규칙 순서를 재정렬할 수 있는 주석 규칙 순서 바꾸기 대화 상자를 표시합니다.





== 목록 보기

목록 보기에는 Unified Manager 서버에서 생성한 주석 규칙이 표 형식으로 표시됩니다. 열 필터를 사용하여 표시되는 데이터를 사용자 지정할 수 있습니다. 주석 규칙 탭의 목록 보기와 주석 탭의 관련 규칙 섹션의 목록 보기에는 다음 열이 포함됩니다.

* 순위
* 이름
* 대상 객체 유형
* 연관된 주석 값
* 적용 가능한 개체


Annotation Rules(주석 규칙) 탭, Associated Annotation(관련 주석)에 대한 추가 열이 표시됩니다. 이 탭에는 저장 개체에 적용된 주석 이름이 표시됩니다.
