---
permalink: online-help/reference-cluster-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: 스토리지 요약 보고서를 통해 HA 쌍의 스토리지 용량에 대한 요약 정보를 볼 수 있습니다. 이 정보를 통해 가능한 용량 위험을 이해하고 적절한 조치를 취하여 워크로드의 균형을 재조정할 수 있습니다. 단일 노드 클러스터 정보는 보고서에 표시되지 않습니다. 
---
= 스토리지 요약 보고서
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 요약 보고서를 통해 HA 쌍의 스토리지 용량에 대한 요약 정보를 볼 수 있습니다. 이 정보를 통해 가능한 용량 위험을 이해하고 적절한 조치를 취하여 워크로드의 균형을 재조정할 수 있습니다. 단일 노드 클러스터 정보는 보고서에 표시되지 않습니다.



== 스토리지 요약 보고서 차트 보기

스토리지 요약 보고서는 다음 두 가지 형식으로 표시됩니다.

* 스토리지 요약 보고서 차트 보기
* 스토리지 요약 보고서 표 형식 보기


이 차트에는 일정 기간 동안의 애그리게이트 가용 용량 및 미사용 데이터 용량의 용량 추세가 표시됩니다. 총 데이터 용량은 세로(y) 축에 표시되고 클러스터 이름은 수평(x) 축에 표시됩니다. 따라서 차트의 각 막대는 하나의 클러스터를 나타냅니다. 특정 지점 위에 커서를 놓으면 그래프의 특정 지점에 대한 세부 정보를 볼 수 있습니다.

* * 클러스터 이름 *
+
클러스터 이름을 표시합니다.

* * HA 쌍 *
+
두 노드를 형성하여 얻은 HA 쌍 값을 표시합니다.

* * 모델 *
+
모델 이름을 표시합니다.

* OS 버전 *
+
사용된 ONTAP의 버전을 표시합니다.

* * 총 물리적 용량 *
+
배열에 있는 모든 디스크의 총 물리적 용량을 표시합니다.

* * 구성되지 않은 물리적 용량 *
+
컨테이너 유형이 애그리게이트, 부분, 스페어 또는 공유 이외의 디스크 구성되지 않은 용량을 표시합니다. 이 용량은 ONTAP에서 디스크의 물리적 용량보다 항상 높습니다. 예를 들어, 2TB 디스크를 예로 들 수 있습니다. 디스크의 물리적 용량은 ONTAP에서 1.6TB이고 Unified Manager에서 구성되지 않은 물리적 용량은 1.8TB입니다.

* * 총 용량 합계 *
+
사용자가 사용할 수 있는 총 애그리게이트 크기를 표시합니다. 여기에는 스냅샷 복사본 예약이 포함됩니다.

* * 사용된 총 용량 *
+
애그리게이트에 이미 사용 중인 용량을 표시합니다. 여기에는 볼륨, LUN 및 기타 스토리지 효율성 기술에서 사용하는 용량이 포함됩니다.

* * 사용되지 않은 용량 집계 *
+
애그리게이트에 추가 데이터를 저장하기 위해 사용 가능한 용량을 표시합니다. 여기에는 스냅샷 복사본 예약이 포함됩니다.

* * 할당된 LUN 용량 *
+
매핑된 LUN의 용량을 표시합니다.

* * 할당되지 않은 LUN 용량 *
+
호스트에 매핑되지 않은 모든 LUN의 용량을 표시합니다.

* * 볼륨 총 용량 *
+
볼륨의 총 용량을 표시합니다(사용된 용량 및 미사용 용량).

* * 사용된 볼륨 용량 *
+
볼륨의 사용된 용량을 표시합니다.

* * 볼륨 미사용 용량 *
+
볼륨의 미사용 용량을 표시합니다.

* * 볼륨 보호 용량 *
+
SnapMirror 및 SnapVault가 활성화된 볼륨의 용량을 표시합니다.

* * 클러스터 라이센스 클라우드 계층 합계 *
+
클라우드 계층에서 라이센스가 부여된 총 용량을 표시합니다. 이 필드는 FabricPool 라이센스가 필요한 스토리지 공급자(예: Amazon S3, IBM Cloud Object Storage, Microsoft Azure Cloud 또는 Alibaba Cloud Object Storage)에 대해 표시됩니다.

* * 클러스터 라이센스 클라우드 계층 사용 *
+
FabricPool 라이센스가 필요한 스토리지 공급자의 클라우드 계층 데이터에 사용되는 공간을 표시합니다.

* * 사용된 클러스터 StorageGRID 용량 *
+
FabricPool 라이센스가 필요하지 않은 스토리지 공급자(예: StorageGRID)의 클라우드 계층 데이터에 사용되는 공간을 표시합니다.


