---
permalink: online-help/reference-management-station-events.html 
sidebar: sidebar 
keywords:  
summary: 관리 스테이션 이벤트는 Unified Manager가 설치된 서버의 상태에 대한 정보를 제공하므로 사용자가 잠재적인 문제를 모니터링할 수 있습니다. 이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형 및 심각도를 포함합니다. 
---
= 관리 스테이션 이벤트입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관리 스테이션 이벤트는 Unified Manager가 설치된 서버의 상태에 대한 정보를 제공하므로 사용자가 잠재적인 문제를 모니터링할 수 있습니다. 이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형 및 심각도를 포함합니다.



== 충격 영역: 구성

|===
| 이벤트 이름(트랩 이름) | 충격 수준 | 소스 유형 | 심각도입니다 


 a| 
Unified Manager 서버 디스크 공간이 거의 가득 참(문서 UnifiedManagerDiskSpaceNearlyFull)
 a| 
위험입니다
 a| 
관리 스테이션
 a| 
경고



 a| 
Unified Manager Server 디스크 공간이 가득 참(문서 UnifiedManagerDiskSpaceFull)
 a| 
사고
 a| 
관리 스테이션
 a| 
심각



 a| 
Unified Manager Server 메모리 부족(문서 UnifiedManagerMemoryLow)
 a| 
위험입니다
 a| 
관리 스테이션
 a| 
경고



 a| 
Unified Manager Server의 메모리가 거의 없음(문서:EvtUnifiedManagerMemoryAlmostOut)
 a| 
사고
 a| 
관리 스테이션
 a| 
심각

|===


== 충격 영역: 성능

|===
| 이벤트 이름(트랩 이름) | 충격 수준 | 소스 유형 | 심각도입니다 


 a| 
성능 데이터 분석이 영향을 받음(documtUnifiedManagerDataMissingAnalyze)
 a| 
위험입니다
 a| 
관리 스테이션
 a| 
경고



 a| 
성능 데이터 수집이 영향을 받음(document.UnifiedManagerDataMissingCollection)
 a| 
사고
 a| 
관리 스테이션
 a| 
심각

|===
[NOTE]
====
이 마지막 2가지 성능 이벤트는 Unified Manager 7.2에만 사용할 수 있습니다. 이러한 이벤트 중 하나가 새 상태에 있는 경우, 새 버전의 Unified Manager 소프트웨어로 업그레이드하면 이벤트가 자동으로 삭제되지 않습니다. 이벤트를 수동으로 Resolved 상태로 이동해야 합니다.

====