---
permalink: online-help/reference-rules-to-generate-user-and-group-quota-email-address-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 사용자 및 그룹 할당량 이메일 주소 생성 규칙 페이지에서는 클러스터, SVM, 볼륨, Qtree, 사용자, 애플리케이션 등과 관련된 사용자 할당량을 기준으로 이메일 주소를 지정하는 규칙을 또는 사용자 그룹. 할당량이 침해되면 지정된 e-메일 주소로 알림이 전송됩니다. 
---
= 사용자 및 그룹 할당량 이메일 주소 생성 규칙 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용자 및 그룹 할당량 이메일 주소 생성 규칙 페이지에서는 클러스터, SVM, 볼륨, Qtree, 사용자, 애플리케이션 등과 관련된 사용자 할당량을 기준으로 이메일 주소를 지정하는 규칙을 또는 사용자 그룹. 할당량이 침해되면 지정된 e-메일 주소로 알림이 전송됩니다.



== 규칙 영역

할당량 이메일 주소에 대한 규칙을 정의해야 합니다. 규칙을 설명하기 위해 설명을 추가할 수도 있습니다.



== 규칙 정의 방법

규칙을 실행할 순서대로 입력해야 합니다. 첫 번째 규칙의 조건이 충족되면 이 규칙에 따라 이메일 주소가 생성됩니다. 조건이 충족되지 않으면 다음 규칙에 대한 조건이 고려됩니다. 각 줄에는 별도의 규칙이 나열됩니다. 기본 규칙은 목록의 마지막 규칙입니다. 규칙의 우선 순위 순서를 변경할 수 있습니다. 그러나 기본 규칙의 순서는 변경할 수 없습니다.

예를 들어, 이메일 주소 qtree1@xyz.com 를 사용하여 qtree1 에 대한 할당량 위반 알림을 받고 다른 모든 qtree에 대해 이메일 주소 admin@xyz.com 를 사용하려면 규칙이 다음 순서로 나열되어야 합니다.

* ($qtree =='qtree1')인 경우 qtree1@xyz.com 으로 제출하시기 바랍니다
* ($qtree == *)인 경우 admin@xyz.com 으로 제출하시기 바랍니다


지정한 규칙에 대한 조건이 충족되지 않으면 기본 규칙이 사용됩니다.

($USER_OR_GROUP===*)인 경우 $USER_OR_GROUP@$domain

두 명 이상의 사용자가 동일한 할당량을 사용하는 경우 사용자 이름이 쉼표로 구분된 값으로 표시되며 이 규칙은 할당량에 적용되지 않습니다.



== 설명을 추가하는 방법

규칙을 설명하기 위해 설명을 추가할 수 있습니다. 각 설명의 시작 시에 #을 사용해야 하며 각 줄에는 별도의 설명이 나열됩니다.



== 규칙 구문

규칙 구문은 다음 중 하나여야 합니다.

* (_valid variable** operator_*)인 경우, _email ID_@_domain name_
+
`if` 은(는) 키워드이며 소문자로 되어 있습니다. 연산자는 == 입니다. e-메일 ID에는 모든 문자, 유효한 변수 $USER_OR_GROUP, $USER 또는 $GROUP 또는 문자 및 유효한 변수 $USER_OR_GROUP, $USER 또는 $GROUP의 조합이 포함될 수 있습니다. 도메인 이름에는 임의의 문자, 유효한 변수 $domain 또는 임의의 문자와 유효한 변수 $domain의 조합이 포함될 수 있습니다. 유효한 변수는 대문자나 소문자일 수 있지만 둘 다 함께 사용할 수는 없습니다. 예를 들어 $domain과 $domain은 유효하지만 $Domain은 유효한 변수가 아닙니다.

* (_valid variable** operator_'_string_')인 경우, _email ID_@_domain name_
+
`if` 는 키워드이며 소문자입니다. 연산자는 일 수 있습니다 `contains` 또는 ==. e-메일 ID에는 모든 문자, 유효한 변수 $USER_OR_GROUP, $USER 또는 $GROUP 또는 문자 및 유효한 변수 $USER_OR_GROUP, $USER 또는 $GROUP의 조합이 포함될 수 있습니다. 도메인 이름에는 임의의 문자, 유효한 변수 $domain 또는 임의의 문자와 유효한 변수 $domain의 조합이 포함될 수 있습니다. 유효한 변수는 대문자나 소문자일 수 있지만 둘 다 함께 사용할 수는 없습니다. 예를 들어 $domain과 $domain은 유효하지만 $Domain은 유효한 변수가 아닙니다.





== 명령 버튼

명령 단추를 사용하면 생성된 규칙을 저장, 확인 또는 취소할 수 있습니다.

* * 검증 *
+
생성된 규칙의 구문을 검증합니다. 유효성 검사 중에 오류가 발생하면 오류를 생성하는 규칙과 오류 메시지가 함께 표시됩니다.

* * 출하 시 기본값으로 복원 *
+
주소 규칙을 출하 시 기본값으로 복원할 수 있습니다.

* * 저장 *
+
규칙 구문의 유효성을 검사하고 오류가 없는 경우 규칙을 저장합니다. 유효성 검사 중에 오류가 발생하면 오류를 생성하는 규칙과 오류 메시지가 함께 표시됩니다.


