---
permalink: online-help/reference-management-groups-page.html 
sidebar: sidebar 
keywords:  
summary: '관리/그룹 페이지에서는 Unified Manager에서 그룹을 생성하여 스토리지 객체를 쉽게 관리할 수 있습니다. 그룹은 그룹에 대해 생성한 그룹 규칙에 따라 정의되는 스토리지 오브젝트\(클러스터, 볼륨 및 SVM\)의 동적 컬렉션입니다.' 
---
= 관리/그룹 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관리/그룹 페이지에서는 Unified Manager에서 그룹을 생성하여 스토리지 객체를 쉽게 관리할 수 있습니다. 그룹은 그룹에 대해 생성한 그룹 규칙에 따라 정의되는 스토리지 오브젝트(클러스터, 볼륨 및 SVM)의 동적 컬렉션입니다.

관리/그룹 페이지에는 그룹, 그룹 규칙 및 그룹 작업을 추가, 삭제 또는 편집할 수 있는 탭이 포함되어 있습니다. 운영자로 로그인하면 페이지에 대한 읽기 권한만 갖게 됩니다. 스토리지 관리자 또는 Unified Manager 관리자로 로그인할 때 각 탭의 추가, 편집 또는 삭제 단추에 액세스할 수 있습니다.



== 그룹 탭

그룹 탭에는 생성한 그룹의 이름과 설명이 표시됩니다. 그룹 추가, 편집 또는 삭제 등의 작업을 수행할 수 있습니다. 또한 이 탭에는 그룹에 연결된 그룹 규칙 및 그룹 작업 수, 클러스터 수, SVM 및 그룹의 볼륨이 표시됩니다.



== 명령 버튼

* * 추가 *
+
그룹을 추가하고 그룹에 대한 이름과 설명을 제공할 수 있는 그룹 추가 대화 상자를 표시합니다.

+
나중에 그룹에 그룹 규칙을 적용하여 스토리지 객체를 포함할 수도 있습니다.

* * 편집 *
+
선택한 그룹의 이름과 설명을 편집할 수 있는 그룹 편집 대화 상자를 표시합니다.

* * 삭제 *
+
선택한 그룹을 삭제합니다.





== 목록 보기

목록 보기는 Unified Manager에서 생성한 그룹을 표 형식으로 표시합니다. 열 필터를 사용하여 표시되는 데이터를 사용자 지정할 수 있습니다. 기본적으로 목록은 그룹 이름별로 정렬됩니다.

* * 이름 *
+
그룹의 이름을 표시합니다.

* * 설명 *
+
그룹에 대한 설명을 표시합니다.

* * 관련 규칙 *
+
그룹에 추가된 규칙 수를 표시합니다.

* * 관련 작업 *
+
그룹에 추가된 그룹 작업 수를 표시합니다.

* * 적용 가능한 클러스터 *
+
그룹에 포함된 클러스터 수를 표시합니다.

* * 해당 SVM *
+
그룹에 포함된 SVM의 수를 표시합니다.

* * 해당 볼륨 *
+
그룹에 포함된 볼륨의 수를 표시합니다.





== 그룹 규칙 탭

그룹 규칙 탭에는 스토리지 객체를 포함하도록 그룹에 대해 생성한 그룹 규칙이 표시됩니다. 그룹 규칙을 추가, 편집 또는 삭제하는 등의 작업을 수행할 수 있습니다. 또한 이 탭에는 그룹 규칙이 생성되는 그룹 이름과 규칙이 적용되는 스토리지 객체가 표시됩니다. 그룹 규칙을 충족하는 스토리지 객체의 수도 볼 수 있습니다.



== 명령 버튼

* * 추가 *
+
스토리지 객체에 대한 그룹 규칙을 생성할 수 있는 그룹 규칙 추가 대화 상자를 표시합니다.

* * 편집 *
+
이전에 구성된 그룹 규칙을 재구성할 수 있는 그룹 규칙 편집 대화 상자를 표시합니다.

* * 삭제 *
+
선택한 그룹 규칙을 삭제합니다.





== 목록 보기

목록 보기에는 특정 스토리지 오브젝트(클러스터, 볼륨 또는 SVM)에 대해 생성한 그룹 규칙과 정의된 그룹 규칙을 충족하는 스토리지 객체 수가 표 형식으로 표시됩니다.

* * 이름 *
+
규칙 이름을 표시합니다.

* * 관련 그룹 *
+
그룹 규칙이 정의된 그룹의 이름을 표시합니다.

* * 대상 객체 유형 *
+
그룹 규칙이 적용되는 스토리지 객체의 유형을 표시합니다.

* * 적용 가능한 개체 *
+
그룹 규칙에 따라 그룹에 포함된 스토리지 객체의 수를 표시합니다.





== 그룹 작업 탭

그룹 작업 탭에는 그룹에 대해 정의한 그룹 작업의 이름 및 유형이 표시됩니다. 그룹 작업을 추가, 편집, 삭제 또는 재배열하는 등의 작업을 수행할 수 있습니다. 이 탭에는 그룹 작업이 적용된 그룹의 이름도 표시됩니다.



== 명령 버튼

* * 추가 *
+
스토리지 객체 그룹에 대한 그룹 작업을 생성할 수 있는 작업 추가 대화 상자를 표시합니다. 예를 들어, 그룹에 있는 스토리지 오브젝트의 임계값 수준을 설정할 수 있습니다.

* * 편집 *
+
이전에 구성된 그룹 작업을 재구성할 수 있는 작업 편집 대화 상자를 표시합니다.

* * 삭제 *
+
선택한 그룹 작업을 삭제합니다.

* * 재주문 *
+
그룹 작업의 순서를 다시 정렬하려면 그룹 작업 순서 바꾸기 대화 상자를 표시합니다.





== 목록 보기

목록 보기는 Unified Manager 서버에서 그룹에 대해 생성한 그룹 작업을 표 형식으로 표시합니다. 열 필터를 사용하여 표시되는 데이터를 사용자 지정할 수 있습니다.

* * 순위 *
+
그룹의 스토리지 객체에 적용할 그룹 작업의 순서를 표시합니다.

* * 이름 *
+
그룹 작업의 이름을 표시합니다.

* * 관련 그룹 *
+
그룹 작업이 정의된 그룹의 이름을 표시합니다.

* * 작업 유형 *
+
그룹의 스토리지 객체에 대해 수행할 수 있는 그룹 작업 유형을 표시합니다.

+
그룹에 대해 동일한 작업 유형의 그룹 작업을 여러 개 만들 수 없습니다. 예를 들어, 그룹에 대한 볼륨 임계값을 설정하는 그룹 작업을 생성할 수 있습니다. 그러나 동일한 그룹에 대해 다른 그룹 작업을 생성하여 볼륨 임계값을 변경할 수는 없습니다.

* * 설명 *
+
그룹 작업에 대한 설명을 표시합니다.


