---
permalink: online-help/reference-edit-vserver-with-infinite-volume-thresholds-dialog-box-iv.html 
sidebar: sidebar 
keywords:  
summary: 무한 확장 볼륨 임계값을 사용하여 SVM 편집 대화 상자를 사용하여 조직의 요구사항에 따라 무한 확장 볼륨을 가진 각 SVM의 기본 임계값을 수정할 수 있습니다. 기본 임계값은 이벤트가 트리거되기 전에 SVM에서 도달해야 하는 활동 레벨을 나타냅니다. 
---
= 무한 확장 볼륨 임계값을 사용하여 SVM 편집 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
무한 확장 볼륨 임계값을 사용하여 SVM 편집 대화 상자를 사용하여 조직의 요구사항에 따라 무한 확장 볼륨을 지원하는 각 SVM의 기본 임계값을 수정할 수 있습니다. 기본 임계값은 이벤트가 트리거되기 전에 SVM에서 도달해야 하는 활동 레벨을 나타냅니다.



== 용량

Capacity 영역에서는 무한 확장 볼륨을 사용하여 선택한 SVM에 대한 용량 임계값 조건을 설정할 수 있습니다.

* * 공간이 거의 가득 찼습니다 *
+
무한 확장 볼륨을 가진 SVM이 거의 가득 찬 것으로 간주되는 비율을 지정합니다. 또한 무한 확장 볼륨의 해당 공간(GB, MB 또는 TB)도 표시합니다. 예를 들어, 10GB의 무한 확장 볼륨이 있고 공간이 거의 가득 참 임계값이 80%인 경우 다음과 같은 정보가 표시됩니다(10GB).

+
슬라이더를 사용하여 임계값을 설정할 수도 있습니다.

* * 공간이 가득 참 *
+
무한 확장 볼륨을 가진 SVM이 가득 찬 것으로 간주되는 비율을 지정합니다. 또한 무한 확장 볼륨의 해당 공간(GB, MB 또는 TB)도 표시합니다. 예를 들어, 10GB의 무한 확장 볼륨이 있고 Space Full 임계값이 90%인 경우 다음 정보가 표시됩니다(9GB/10GB).

+
슬라이더를 사용하여 임계값을 설정할 수도 있습니다.

* * 스냅샷 사용 제한 *
+
무한 확장 볼륨의 스냅샷 복사본에 예약된 공간의 제한(백분율)을 지정합니다.





== 명령 버튼

명령 단추를 사용하여 다음 작업을 수행할 수 있습니다.

* * 글로벌 기본값으로 복원 *
+
임계값 설정을 글로벌 수준에서 설정된 현재 값으로 복원할 수 있습니다.

* * 저장 *
+
모든 임계값 설정을 저장합니다.

* * 저장 후 닫기 *
+
모든 임계값 설정을 저장하고 무한 확장 볼륨 임계값을 사용하여 SVM 편집 대화 상자를 닫습니다.

* * 취소 *
+
임계값 설정에 대한 변경 사항을 무시하고 무한 확장 볼륨 임계값을 사용하여 SVM 편집 대화 상자를 닫습니다.


