---
permalink: online-help/reference-manage-report-schedules-dialog-box-um-6-2.html 
sidebar: sidebar 
keywords:  
summary: 보고서 일정 관리 대화 상자에서 기존 보고서 일정을 보거나 수정하거나 삭제할 수 있으며 보고서에 대한 새 일정을 추가할 수 있습니다. 
---
= Manage Report Schedules(보고서 일정 관리) 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
보고서 일정 관리 대화 상자에서 기존 보고서 일정을 보거나 수정하거나 삭제할 수 있으며 보고서에 대한 새 일정을 추가할 수 있습니다.



== 속성

기존 일정을 선택하거나 보고서에 대한 새 일정을 만들 수 있습니다. 보고서 일정을 보거나 수정하거나 삭제할 수 있습니다.

* * 왼쪽 창 *
+
** 별표 이름 *
+
기존 스케줄을 표시합니다. 일정을 클릭하면 오른쪽 창에서 일정 세부 정보를 볼 수 있습니다. 첫 번째 로그인의 경우 기존 일정이 없습니다.

** * 일정 추가 *
+
오른쪽 창에 새 일정 양식이 표시됩니다. 이제 새 일정을 추가할 수 있습니다.



* * 오른쪽 창 *
+
** 별표 이름 *
+
스케줄 이름을 표시합니다.

** * 받는 사람 이메일 주소 *
+
보고서를 보내야 하는 사용자의 이메일 주소를 표시합니다. 쉼표로 구분하여 둘 이상의 이메일 주소를 입력할 수 있습니다.

** * 보고서 형식 *
+
보고서를 제공해야 하는 형식을 표시합니다. PDF 옵션이 기본 보고서 형식으로 선택됩니다. XHTML 형식을 선택한 경우 지원되는 웹 브라우저를 사용하여 전자 메일로 보낸 보고서를 엽니다.

** * 주파수 *
+
보고서 예약 빈도를 표시합니다.

** * 보고서 범주 *
+
보고서 범주 그룹을 표시합니다. 목록에서 보고서 범주를 선택하면 사용 가능한 보고서 열에 해당 보고서 범주에 속하는 보고서가 표시됩니다.

** * 사용 가능한 보고서 *
+
선택한 보고서 범주에 속하는 보고서만 표시합니다.

** * 선택한 보고서 *
+
일정을 적용하도록 선택한 보고서를 표시합니다. Available Reports 열에서 필요한 보고서를 선택할 수 있습니다. 보고서를 하나 이상 선택해야 합니다







== 명령 버튼

명령 단추를 사용하여 다음 작업을 수행할 수 있습니다.

* * 일정 추가 *
+
새 일정을 추가할 수 있습니다.

* * 일정 삭제 *
+
현재 보고 있는 스케줄을 삭제할 수 있습니다. 새 일정을 만들 때 이 단추를 사용할 수 없습니다.

* * 저장 *
+
보거나 수정하거나 추가할 일정을 저장합니다.

* * 저장 후 닫기 *
+
보고, 수정 또는 추가할 일정을 저장하고 Manage Report Schedules(보고서 일정 관리) 대화 상자를 닫습니다.

* * 취소 *
+
일정을 저장할 메시지를 표시하는 동안 Manage Report Schedules(보고서 일정 관리) 대화 상자를 닫습니다.


