---
permalink: online-help/reference-node-performance-information-page.html 
sidebar: sidebar 
keywords:  
summary: 성능/노드 정보 페이지를 사용하여 노드의 물리적 및 논리적 특성 목록을 봅니다. 이 정보는 성능 관련 질문에 답변하는 데 도움이 될 수 있습니다. 
---
= 성능/노드 정보 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능/노드 정보 페이지를 사용하여 노드의 물리적 및 논리적 특성 목록을 봅니다. 이 정보는 성능 관련 질문에 답변하는 데 도움이 될 수 있습니다.



== 노드 특성

* * IP 주소 *
+
노드 관리 LIF의 IPv4 또는 IPv6 주소입니다.

* FQDN *
+
노드 관리 LIF의 FQDN(정규화된 도메인 이름)입니다.

* OS 버전 *
+
노드에 설치된 ONTAP 소프트웨어의 버전입니다.

* * 모델/제품군 *
+
노드의 플랫폼 모델 번호입니다.

* * 용량(사용 가능/총) *
+
노드에 사용할 수 있는 총 스토리지 용량(GB)과 현재 사용 가능한 스토리지 크기입니다.

* * 클러스터 *
+
이 노드가 속하는 클러스터의 이름입니다. 이름을 클릭하여 성능/클러스터 탐색기 페이지에 클러스터 세부 정보를 표시할 수 있습니다.

* * HA 파트너 *
+
해당하는 경우 HA 파트너 노드의 이름입니다. 이름을 클릭하여 성능/노드 탐색기 페이지에 파트너 노드 세부 정보를 표시할 수 있습니다.

* * 애그리게이트 *
+
이 노드의 애그리게이트 수입니다. 번호를 클릭하여 Performance/Aggregate Inventory 페이지에 애그리게이트를 표시할 수 있습니다.

+
[NOTE]
====
인벤토리 페이지에 루트 애그리게이트가 포함되어 있지 않기 때문에 여기에 나열된 숫자가 Performance/Aggregate Inventory 페이지의 번호와 일치하지 않을 수 있습니다.

====
* 포트 *
+
이 노드의 포트 수입니다. 번호를 클릭하여 성능/포트 인벤토리 페이지에 포트를 표시할 수 있습니다.

+
[NOTE]
====
인벤토리 페이지에 노드 관리 포트가 포함되어 있지 않으므로 여기에 나열된 번호가 성능/포트 인벤토리 페이지의 번호와 일치하지 않을 수 있습니다.

====
* * 연락처/위치 *
+
가능한 경우 이 노드에 대해 문의할 관리자의 이름 및 노드 위치입니다.

* * 코어 수/속도 *
+
사용 가능한 경우 컨트롤러의 CPU 코어 수와 CPU 코어 속도입니다.

* RAM *
+
사용 가능한 경우 컨트롤러에서 사용 가능한 총 메모리.





== 플래시 장치

[NOTE]
====
Flash Cache 데이터는 노드에 대해서만 표시되며 Flash Cache 모듈이 노드에 설치된 경우에만 표시됩니다.

====
* * 슬롯 번호 *
+
Flash Cache 모듈이 설치된 슬롯 번호입니다.

* * 상태 *
+
모듈의 작동 상태 유효한 값:

+
** 온라인
** offline_failed.(오프라인
** offline_threshold 를 선택합니다


* * 모델/제품군 *
+
모듈의 모델 번호입니다.

* * 펌웨어 개정 *
+
모듈에 설치된 펌웨어 버전입니다.

* * 용량 *
+
설치된 Flash Cache 모듈의 크기입니다.


