---
permalink: online-help/reference-constituent-volume-performance-information-page.html 
sidebar: sidebar 
keywords:  
summary: 성능/구성 볼륨 정보 페이지를 사용하여 FlexGroup 구성 볼륨의 물리적 속성 및 논리적 속성 목록을 볼 수 있습니다. 이 정보는 성능 관련 질문에 답변하는 데 도움이 될 수 있습니다. 
---
= 성능/구성 볼륨 정보 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능/구성 볼륨 정보 페이지를 사용하여 FlexGroup 구성 볼륨의 물리적 속성 및 논리적 속성 목록을 볼 수 있습니다. 이 정보는 성능 관련 질문에 답변하는 데 도움이 될 수 있습니다.



== 구성요소 볼륨 특성

* * 유형 *
+
읽기-쓰기(RW) 또는 데이터 보호(DP) 등 구성요소의 유형입니다.

* * 스타일 *
+
볼륨의 스타일이며 FlexGroup 볼륨의 구성요소 볼륨입니다.

* * 클러스터 *
+
이 FlexGroup 구성요소 볼륨이 속해 있는 클러스터의 이름입니다. 이름을 클릭하여 성능/클러스터 탐색기 페이지에 클러스터 세부 정보를 표시할 수 있습니다.

* * 집계 *
+
이 FlexGroup 구성요소 볼륨이 상주하는 애그리게이트의 이름입니다. 이름을 클릭하여 성능/집계 탐색기 페이지에 집계 세부 정보를 표시할 수 있습니다.

* * FlexGroup *
+
이 구성요소가 속하는 FlexGroup 볼륨의 이름입니다. 이름을 클릭하여 성능/FlexGroup 탐색기 페이지에 FlexGroup 볼륨 세부 정보를 표시할 수 있습니다.

* * 스토리지 가상 머신 *
+
이 FlexGroup 구성요소 볼륨이 속한 SVM의 이름입니다. 이름을 클릭하여 성능/SVM 탐색기 페이지에서 SVM 세부 정보를 표시할 수 있습니다.

* * 계층화 정책 *
+
볼륨에 설정된 계층화 정책입니다. 이 정책은 볼륨이 FabricPool 애그리게이트에 구축되는 경우에만 적용됩니다. 사용 가능한 정책은 다음과 같습니다.

+
** 없음. 이 볼륨의 데이터는 항상 성능 계층에 유지됩니다.
** 스냅샷만. 스냅샷 데이터만 클라우드 계층으로 자동으로 이동됩니다. 다른 모든 데이터는 성능 계층에 유지됩니다.
** 백업. 데이터 보호 볼륨에서 전송된 모든 사용자 데이터는 클라우드 계층에서 시작되지만, 나중에 클라이언트 읽기로 인해 핫 데이터가 성능 계층으로 이동할 수 있습니다.
** 자동. ONTAP에서 데이터가 "핫" 또는 "콜드" 데이터라고 결정하면 이 볼륨의 데이터가 성능 계층과 클라우드 계층 간에 자동으로 이동됩니다.


* * RAID 유형 *
+
이 구성요소가 상주하는 애그리게이트에 사용되고 있는 이중화 유형입니다. 가능한 유형:

+
** RAID0
** RAID4
** RAID-DP
** RAID-TEC


* * 용량(사용 가능/총) *
+
구성요소에서 사용 가능한 총 스토리지 용량(GB) 및 현재 사용 가능한 스토리지 크기입니다.


