---
permalink: online-help/reference-edit-relationship-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 기존 보호 관계를 편집하여 최대 전송 속도, 보호 정책 또는 보호 스케줄을 변경할 수 있습니다. 
---
= 관계 편집 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 보호 관계를 편집하여 최대 전송 속도, 보호 정책 또는 보호 스케줄을 변경할 수 있습니다.



== 목적지 정보

* * 대상 클러스터 *
+
선택한 대상 클러스터의 이름입니다.

* * 대상 SVM *
+
선택한 SVM의 이름입니다

* * 관계 설정 *
+
보호 관계에 사용되는 최대 전송 속도, SnapMirror 정책 및 스케줄을 지정할 수 있습니다.

+
** 최대 전송 속도
+
네트워크를 통해 클러스터 간에 기본 데이터가 전송되는 최대 속도를 지정합니다. 이 옵션을 선택하면 네트워크 대역폭이 지정한 값으로 제한됩니다. 숫자 값을 입력한 다음 초당 킬로바이트(kbps), 초당 메가바이트(Mbps), 초당 기가바이트(Gbps) 또는 초당 테라바이트(Tbps)를 선택할 수 있습니다. 지정하는 최대 전송 속도는 1kbps 이상, 4Tbps 미만이어야 합니다. 최대 전송 속도를 사용하지 않도록 선택하는 경우 관계 간의 기본 전송은 무제한입니다. 운영 클러스터와 보조 클러스터가 동일한 경우 이 설정이 비활성화됩니다.

** SnapMirror 정책
+
관계에 대한 ONTAP SnapMirror 정책을 지정합니다. 기본값은 DPDefault 입니다.

** 정책을 생성합니다
+
새 SnapMirror 정책을 만들고 사용할 수 있는 SnapMirror 정책 만들기 대화 상자를 시작합니다.

** SnapMirror 일정 을 참조하십시오
+
관계에 대한 ONTAP SnapMirror 정책을 지정합니다. 사용 가능한 스케줄에는 없음, 5분, 8시간, 일별, 시간별, 매주. 기본값은 없음 으로, 관계에 연결된 일정이 없음을 나타냅니다. 일정이 없는 관계는 스토리지 서비스에 속하지 않는 한 지연 상태 값이 없습니다.

** 일정 생성
+
새 SnapMirror 일정을 만들 수 있는 일정 만들기 대화 상자를 시작합니다.







== 명령 버튼

명령 단추를 사용하여 다음 작업을 수행할 수 있습니다.

* * 취소 *
+
선택한 항목을 삭제하고 보호 구성 대화 상자를 닫습니다.

* * 제출 *
+
선택 사항을 적용하고 관계 편집 대화 상자를 닫습니다.


