---
permalink: online-help/reference-create-schedule-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 일정 생성 대화 상자에서는 SnapMirror 및 SnapVault 관계 전송에 대한 기본 또는 고급 보호 일정을 생성할 수 있습니다. 데이터 업데이트가 자주 발생하므로 데이터 전송 빈도를 높이기 위해 새 일정을 만들거나, 데이터가 자주 변경되지 않는 경우 일정을 덜 자주 만들 수 있습니다. 
---
= 일정 생성 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
일정 생성 대화 상자에서는 SnapMirror 및 SnapVault 관계 전송에 대한 기본 또는 고급 보호 일정을 생성할 수 있습니다. 데이터 업데이트가 자주 발생하므로 데이터 전송 빈도를 높이기 위해 새 일정을 만들거나, 데이터가 자주 변경되지 않는 경우 일정을 덜 자주 만들 수 있습니다.

SnapMirror Synchronous 관계에 대한 일정을 구성할 수 없습니다.

* * 대상 클러스터 *
+
보호 구성 대화 상자의 SnapVault 탭 또는 SnapMirror 탭에서 선택한 클러스터의 이름입니다.

* 별표 이름 *
+
일정에 대해 제공한 이름입니다. 일정 이름은 A ~ Z 문자, a ~ z, 0 ~ 9 및 다음 특수 문자로 구성될 수 있습니다. @#$%{캐럿} & * () _ -. 일정 이름에는 다음 문자가 포함될 수 없습니다.<>

* * 기본 또는 고급 *
+
사용할 스케줄 모드입니다.

+
기본 모드는 다음과 같은 요소를 포함합니다.

+
** 반복합니다
+
예약된 전송이 수행되는 빈도. 매시간, 매일, 매주 중에서 선택할 수 있습니다.

** 일
+
매주 반복 을 선택하면 전송이 이루어지는 주의 일입니다.

** 시간
+
Daily(매일) 또는 Weekly(매주) 를 선택하면 전송이 이루어지는 시간.



+
고급 모드에는 다음 요소가 포함됩니다.

+
** 개월
+
월을 나타내는 쉼표로 구분된 숫자 목록입니다. 유효한 값은 0에서 11 사이의 값이며 0은 1월을 나타내는 등의 값을 나타냅니다. 이 요소는 선택 사항입니다. 필드를 비워 두면 매월 전송이 수행됩니다.

** 일
+
월을 나타내는 쉼표로 구분된 숫자 목록입니다. 유효한 값은 1부터 31까지입니다. 이 요소는 선택 사항입니다. 필드를 비워 두면 해당 월의 매일 전송이 수행됩니다.

** 평일
+
요일을 나타내는 쉼표로 구분된 숫자 목록입니다. 유효한 값은 0에서 6 사이의 값이며 0은 일요일을 나타냅니다. 이 요소는 선택 사항입니다. 필드를 비워 두면 매일 전송이 수행됨을 의미합니다. 요일을 지정했지만 요일을 지정하지 않은 경우 매일 아니라 지정된 요일에만 전송이 수행됩니다.

** 시간
+
일 시간 수를 나타내는 쉼표로 구분된 숫자 목록입니다. 유효한 값은 0부터 23까지이며 0은 자정을 나타냅니다. 이 요소는 선택 사항입니다.

** 분
+
시간 단위의 분을 나타내는 쉼표로 구분된 숫자 목록입니다. 유효한 값은 0에서 59 사이입니다. 이 요소는 필수입니다.




