---
permalink: online-help/reference-logical-interface-events.html 
sidebar: sidebar 
keywords:  
summary: LIF 이벤트는 LIF 상태에 대한 정보를 제공하므로 잠재적 문제를 모니터링할 수 있습니다. 이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형 및 심각도를 포함합니다. 
---
= 논리 인터페이스(LIF) 이벤트입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
LIF 이벤트는 LIF 상태에 대한 정보를 제공하므로 잠재적 문제를 모니터링할 수 있습니다. 이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형 및 심각도를 포함합니다.



== 영향 영역: 가용성

|===
| 이벤트 이름(트랩 이름) | 충격 수준 | 소스 유형 | 심각도입니다 


 a| 
LIF 상태 다운(ocumEvtLifStatusDown)
 a| 
위험입니다
 a| 
인터페이스
 a| 
오류



 a| 
LIF 페일오버를 수행할 수 없습니다(문서 수명실패.
 a| 
위험입니다
 a| 
인터페이스
 a| 
경고



 a| 
LIF가 홈 포트에 없습니다(문서 수명문서 홈 포트).
 a| 
위험입니다
 a| 
인터페이스
 a| 
경고

|===


== 충격 영역: 구성

|===
| 이벤트 이름(트랩 이름) | 충격 수준 | 소스 유형 | 심각도입니다 


 a| 
LIF 경로가 구성되지 않음(해당 없음)
 a| 
이벤트
 a| 
인터페이스
 a| 
정보

|===


== 충격 영역: 성능

|===
| 이벤트 이름(트랩 이름) | 충격 수준 | 소스 유형 | 심각도입니다 


 a| 
네트워크 LIF MBPS 중요 위반 임계값(문서 네트워크 수명인시던트)
 a| 
사고
 a| 
인터페이스
 a| 
심각



 a| 
네트워크 LIF MBps 경고 임계값 위반(문서 네트워크 수명경고)
 a| 
위험입니다
 a| 
인터페이스
 a| 
경고



 a| 
FCP LIF MBps 중요 임계값 위반(문서 FcpLifmbpsIncident)
 a| 
사고
 a| 
인터페이스
 a| 
심각



 a| 
FCP LIF MBps 경고 임계값 위반(문서 FcpLifmbpsWarning)
 a| 
위험입니다
 a| 
인터페이스
 a| 
경고



 a| 
FCP LIF MBps 중요 임계값 위반(문서 NvmfcLifmpsIncident)
 a| 
사고
 a| 
인터페이스
 a| 
심각



 a| 
FCP LIF MBps 경고 임계값 위반(문서 NvmfcLifmpsWarning)
 a| 
위험입니다
 a| 
인터페이스
 a| 
경고

|===