---
permalink: online-help/reference-snapvault-relationship-events.html 
sidebar: sidebar 
keywords:  
summary: SnapVault 관계 이벤트는 잠재적 문제를 모니터링할 수 있도록 SnapVault 관계 상태에 대한 정보를 제공합니다. 이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형 및 심각도를 포함합니다. 
---
= SnapVault 관계 이벤트입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapVault 관계 이벤트는 잠재적 문제를 모니터링할 수 있도록 SnapVault 관계 상태에 대한 정보를 제공합니다. 이벤트는 영향 영역별로 그룹화되며 이벤트 및 트랩 이름, 영향 수준, 소스 유형 및 심각도를 포함합니다.



== 충격 영역: 보호

|===
| 이벤트 이름(트랩 이름) | 충격 수준 | 소스 유형 | 심각도입니다 


 a| 
비동기 볼트 비정상(문서 SnapVaultRelationshipUnHealthy)
 a| 
위험입니다
 a| 
SnapMirror 관계
 a| 
경고



 a| 
비동기 볼트 끊어진 부분(document SnapVaultRelationshipStateBrokenoff)
 a| 
위험입니다
 a| 
SnapMirror 관계
 a| 
오류



 a| 
비동기 볼트 초기화 실패(문서 SnapVaultRelationshipInitializeFailed)
 a| 
위험입니다
 a| 
SnapMirror 관계
 a| 
오류



 a| 
비동기 볼트 업데이트 실패(문서 SnapVaultRelationshipUpdateFailed)
 a| 
위험입니다
 a| 
SnapMirror 관계
 a| 
오류



 a| 
비동기 볼트 지연 오류(ocumEvtSnapVaultRelationshipLagError)
 a| 
위험입니다
 a| 
SnapMirror 관계
 a| 
오류



 a| 
비동기 볼트 지연 경고(문서 SnapCenter VaultRelationshipLagWarning)
 a| 
위험입니다
 a| 
SnapMirror 관계
 a| 
경고



 a| 
비동기 볼트 재동기화 실패(문서 SnapvaultRelationshipResyncFailed)
 a| 
위험입니다
 a| 
SnapMirror 관계
 a| 
오류

|===