---
permalink: online-help/reference-setup-workflow-automation-page.html 
sidebar: sidebar 
keywords:  
summary: 설정/워크플로우 자동화 페이지에서 OnCommand Workflow Automation를 Unified Manager와 통합하도록 설정을 구성할 수 있습니다. 설정을 추가, 수정 또는 삭제할 수도 있습니다. 
---
= 설정/워크플로우 자동화 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
설정/워크플로우 자동화 페이지에서 OnCommand Workflow Automation를 Unified Manager와 통합하도록 설정을 구성할 수 있습니다. 설정을 추가, 수정 또는 삭제할 수도 있습니다.

OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.



== Unified Manager 데이터베이스 사용자

이 영역에서 Unified Manager와 Workflow Automation을 페어링하는 데 필요한 데이터베이스 사용자의 자격 증명을 입력할 수 있습니다.

* * 이름 *
+
Unified Manager 데이터베이스의 데이터에 액세스하는 데 사용할 수 있는 데이터베이스 사용자의 사용자 이름을 지정할 수 있습니다. 기본적으로 데이터베이스 사용자는 선택되지 않습니다. 드롭다운 목록에서 데이터베이스 사용자를 선택할 수 있습니다.

* * 암호 *
+
지정된 사용자 이름에 대한 암호를 지정할 수 있습니다.





== OnCommand Workflow Automation 자격 증명

이 영역에서 Unified Manager와 페어링하는 데 필요한 Workflow Automation 계정의 자격 증명을 입력할 수 있습니다.

* * 호스트 이름 또는 IP 주소 *
+
Unified Manager와 페어링하는 데 사용되는 Workflow Automation 호스트 서버의 이름 또는 IP 주소를 지정합니다.

* * 포트 *
+
Workflow Automation 호스트 서버의 필요한 포트 번호(443)를 표시합니다.

* * 사용자 이름 *
+
Workflow Automation에 로그인하는 데 사용할 수 있는 사용자 이름을 지정할 수 있습니다.

* * 암호 *
+
지정된 사용자 이름에 대한 암호를 지정할 수 있습니다.





== 명령 버튼

명령 단추를 사용하여 설정 옵션을 제거, 저장 또는 취소할 수 있습니다.

* * 설정 제거 *
+
Workflow Automation 설정을 Unified Manager에서 제거합니다.

* * 저장 *
+
선택한 옵션에 대한 구성 설정을 저장합니다.


