---
permalink: online-help/reference-dashboard-page.html 
sidebar: sidebar 
keywords:  
summary: '대시보드/개요 페이지에는 클러스터, 애그리게이트, SVM(스토리지 가상 머신)과 같은 스토리지 오브젝트의 상태가 그래프로 표시됩니다. 생성되는 가용성, 용량, 성능 및 보호 관련 이벤트에 따라 이러한 스토리지 객체는 양호, 위험 또는 인시던트 또는 보호 관련 이벤트에 대한 정상, 경고 또는 오류로 분류됩니다.' 
---
= 대시보드/개요 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
대시보드/개요 페이지에는 클러스터, 애그리게이트, SVM(스토리지 가상 머신)과 같은 스토리지 오브젝트의 상태가 그래프로 표시됩니다. 생성되는 가용성, 용량, 성능 및 보호 관련 이벤트에 따라 이러한 스토리지 객체는 양호, 위험 또는 인시던트 또는 보호 관련 이벤트에 대한 정상, 경고 또는 오류로 분류됩니다.



== 클러스터에 연결할 수 없음 표시줄

클러스터에 연결할 수 없는 경우 Unified Manager에서 모든 페이지 상단의 표시줄에 세부 정보를 표시합니다. 모든 클러스터에 연결할 수 있는 경우 이 창이 숨겨집니다.

F5 키를 눌러 창에 표시된 정보를 새로 고칠 수 있습니다. 이 작업을 수행하면 창에 현재 연결할 수 없는 클러스터에 대한 최신 정보가 표시됩니다. 예를 들어 Cluster Not Reachable 이벤트가 있는 클러스터가 제거되거나 이벤트의 상태가 Obsolete인 경우 창을 새로 고치면 이벤트에 대한 정보가 제거됩니다.

세부 정보 * 버튼을 클릭하면 연결할 수 없는 클러스터에 대한 자세한 정보를 볼 수 있습니다. 그러면 이벤트 인벤토리 페이지가 열립니다. 이 표시줄이 닫힌 후에는 Unified Manager에 다시 로그인할 때만 다시 표시됩니다.



== 개요 영역

* * 가용성 창 *
+
Unified Manager에서 모니터링하는 클러스터, 애그리게이트 및 SVM의 가용성에 대한 정보를 표시합니다. 스토리지 객체는 정상, 위험 또는 인시던트로 분류됩니다. 예를 들어, 스페어 디스크가 없는 클러스터의 상태는 위험 으로 표시됩니다.

+
이 창에는 각 범주의 스토리지 객체 수도 표시됩니다. 개체 합계를 클릭하면 해당 개체의 페이지로 이동합니다. 예를 들어 클러스터 합계를 클릭하면 상태/클러스터 인벤토리 페이지로 이동합니다. 열의 맨 위에 있는 숫자를 클릭하면 Events inventory 페이지로 이동합니다.

* * 용량 창 *
+
Unified Manager에서 모니터링하는 애그리게이트 및 SVM의 용량에 대한 정보를 표시합니다. 스토리지 객체는 정상, 위험 또는 인시던트로 분류됩니다. 예를 들어 사용된 용량이 전체 임계값에 도달한 애그리게이트의 상태가 위험 으로 표시됩니다.

+
이 창에는 각 범주의 스토리지 객체 수도 표시됩니다.

* * 성능 창 *
+
Unified Manager에서 모니터링하는 클러스터, SVM 및 볼륨의 성능에 대한 정보를 표시합니다. 생성되는 성능 관련 인시던트에 따라 스토리지 객체가 상태, 위험 또는 인시던트로 분류됩니다. 예를 들어, 워크로드에 대한 입출력 응답 시간이 최대 임계값에 도달한 볼륨의 상태는 Have Incidents로 표시됩니다.

+
이 창에는 Unified Manager에서 모니터링하는 총 클러스터, SVM 및 볼륨의 수도 표시됩니다. 개체 합계를 클릭하면 해당 개체의 페이지로 이동합니다. 예를 들어, 클러스터 합계를 클릭하면 성능/클러스터 인벤토리 페이지로 이동합니다.

* * 보호 창 *
+
Unified Manager에서 모니터링하는 보호 관계에 대한 정보를 표시합니다. 보호 관계는 양호, 경고 또는 오류로 분류됩니다. 예를 들어 지연 기간이 지연 경고 임계값을 초과하는 관계가 Warning 으로 표시됩니다.

+
또한 이 창에는 각 보호 범주에 있는 총 스토리지 객체 수가 표시됩니다. 지연 상태, 비동기식 볼트, 비동기식 미러 또는 동기식 범주에 대한 링크를 클릭하면 보호/볼륨 관계 페이지에서 해당 개체의 필터링된 목록으로 이동합니다.


