---
permalink: online-help/reference-types-of-performance-counter-charts.html 
sidebar: sidebar 
keywords:  
summary: 선택한 스토리지 개체의 카운터 값을 표시하는 표준 성능 차트가 있습니다. 각 분석 결과 카운터 차트는 읽기, 쓰기 및 기타 범주로 구분된 총 값을 표시합니다. 또한 일부 분석 카운터 차트는 확대/축소 보기에 차트가 표시될 때 추가 세부 정보를 표시합니다. 
---
= 성능 카운터 차트의 유형입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
선택한 스토리지 개체의 카운터 값을 표시하는 표준 성능 차트가 있습니다. 각 분석 결과 카운터 차트는 읽기, 쓰기 및 기타 범주로 구분된 총 값을 표시합니다. 또한 일부 분석 카운터 차트는 확대/축소 보기에 차트가 표시될 때 추가 세부 정보를 표시합니다.

다음 표에서는 사용 가능한 성능 카운터 차트를 보여 줍니다.

|===
| 사용 가능한 차트 | 차트 설명 


 a| 
이벤트
 a| 
루트 개체에 대한 통계 차트와 관련된 중요, 오류, 경고 및 정보 이벤트를 표시합니다. 성능 이벤트와 함께 상태 이벤트가 표시되어 성능이 영향을 받을 수 있는 이유를 완벽하게 파악할 수 있습니다.



 a| 
지연 시간 - 합계
 a| 
애플리케이션 요청에 응답하는 데 필요한 밀리초 수입니다. 평균 지연 시간 값은 I/O 가중치입니다.



 a| 
지연 시간 - 분류
 a| 
지연 시간 합계에 표시된 것과 동일한 정보이지만 성능 데이터가 읽기, 쓰기 및 기타 지연 시간으로 분리되어 있습니다.이 차트 옵션은 선택된 오브젝트가 SVM, 노드, 애그리게이트, 볼륨, LUN인 경우에만 적용됩니다. 네임스페이스입니다.



 a| 
지연 시간 - 클러스터 구성 요소
 a| 
지연 시간 합계에 표시되는 것과 동일한 정보이지만 성능 데이터가 클러스터 구성 요소별로 지연 시간으로 분리되어 있습니다.이 차트 옵션은 선택한 오브젝트가 볼륨일 때만 적용됩니다.



 a| 
IOPS - 합계
 a| 
초당 처리되는 입출력 작업 수입니다.



 a| 
IOPS - 분류
 a| 
IOPS Total에 표시된 것과 동일한 정보이지만, 성능 데이터는 읽기, 쓰기 및 기타 IOPS로 구분됩니다. Zoom(확대/축소) 보기에 표시된 볼륨 차트는 ONTAP에서 구성된 경우 QoS 최소 및 최대 처리량 값을 표시합니다.

이 차트 옵션은 선택한 오브젝트가 SVM, 노드, 애그리게이트, 볼륨, LUN인 경우에만 적용됩니다. 네임스페이스입니다.



 a| 
IOPS - 프로토콜
 a| 
IOPS Total에 표시된 것과 동일한 정보이지만 성능 데이터는 CIFS, NFS, FCP, NVMe 및 iSCSI 프로토콜 트래픽에 대한 개별 차트로 구분됩니다. 이 차트 옵션은 선택한 개체가 SVM 인 경우에만 적용됩니다.



 a| 
IOPS/TB - 합계
 a| 
워크로드에서 소비하는 총 공간(TB)을 기준으로 초당 처리되는 입출력 작업의 수입니다. I/O 밀도라고도 하는 이 카운터는 지정된 스토리지 용량으로 제공할 수 있는 성능을 측정합니다. Zoom 보기에 표시되면 ONTAP에서 구성한 경우 볼륨 차트에 QoS 예상 및 최대 처리량 값이 표시됩니다.

이 차트 옵션은 선택한 개체가 볼륨일 때만 적용됩니다.



 a| 
Mbps - 전체
 a| 
오브젝트에서 초당 전송된 데이터 크기(MB)입니다.



 a| 
Mbps - 고장
 a| 
MBps 차트에 표시된 것과 동일한 정보이지만 디스크 읽기, Flash Cache 읽기, 쓰기 등으로 구분된 MBPS 데이터의 경우 Zoom 보기에 표시되는 볼륨 차트는 ONTAP에 구성된 경우 QoS 최대 처리량 값을 표시합니다.

이 차트 옵션은 선택한 오브젝트가 SVM, 노드, 애그리게이트, 볼륨, LUN인 경우에만 적용됩니다. 네임스페이스입니다.

[NOTE]
====
Flash Cache 데이터는 노드에 대해서만 표시되며 Flash Cache 모듈이 노드에 설치된 경우에만 표시됩니다.

====


 a| 
사용된 성능 용량 - 합계
 a| 
노드 또는 애그리게이트에 사용되고 있는 성능 용량의 비율입니다.

[NOTE]
====
성능 용량 데이터는 클러스터의 노드가 ONTAP 9.0 이상 소프트웨어와 함께 설치된 경우에만 사용할 수 있습니다.

====


 a| 
사용된 성능 용량 - 분류
 a| 
성능 용량 사용 데이터를 사용자 프로토콜과 시스템 백그라운드 프로세스로 분리합니다. 또한 여유 성능 용량이 표시됩니다.



 a| 
사용 가능한 IOPS - 합계
 a| 
이 개체에서 현재 사용 가능한(사용 가능) 초당 입출력 작업 수입니다. 이 수치는 Unified Manager에서 해당 객체가 수행할 수 있는 총 IOPS에서 현재 사용된 IOPS를 뺀 결과입니다. 이 차트 옵션은 선택한 개체가 노드 또는 집합인 경우에만 적용됩니다.

[NOTE]
====
사용 가능한 IOPS 데이터는 클러스터의 노드가 ONTAP 9.0 이상 소프트웨어와 함께 설치된 경우에만 사용할 수 있습니다.

====


 a| 
Utilization - 총
 a| 
사용 중인 개체의 사용 가능한 리소스 백분율입니다. 활용률은 노드의 노드 활용률, 애그리게이트의 디스크 활용률, 포트의 대역폭 활용률을 나타냅니다. 이 차트 옵션은 선택한 객체가 노드, 애그리게이트 또는 포트일 때만 적용됩니다.



 a| 
캐시 비적중 비율 - 합계
 a| 
캐시에서 반환되지 않고 디스크에서 반환된 클라이언트 애플리케이션의 읽기 요청 비율입니다. 이 차트 옵션은 선택한 개체가 볼륨일 때만 적용됩니다.

|===