---
permalink: online-help/reference-resynchronize-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 재동기화 대화 상자를 사용하면 이전에 중단된 SnapMirror 또는 SnapVault 관계의 데이터를 재동기화한 다음 대상이 읽기/쓰기 볼륨으로 만들어진 후에 다시 동기화할 수 있습니다. 소스 볼륨에서 필요한 공통 스냅샷 복사본이 삭제되어 SnapMirror 또는 SnapVault 업데이트가 실패하는 경우에도 재동기화할 수 있습니다. 
---
= 대화 상자를 다시 동기화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
재동기화 대화 상자를 사용하면 이전에 중단된 SnapMirror 또는 SnapVault 관계의 데이터를 재동기화한 다음 대상이 읽기/쓰기 볼륨으로 만들어진 후에 다시 동기화할 수 있습니다. 소스 볼륨에서 필요한 공통 스냅샷 복사본이 삭제되어 SnapMirror 또는 SnapVault 업데이트가 실패하는 경우에도 재동기화할 수 있습니다.



== 재동기화 옵션 탭

재동기화 옵션 탭에서는 재동기화하려는 보호 관계에 대한 전송 우선 순위 및 최대 전송 속도를 설정할 수 있습니다.

* * 전송 우선순위 *
+
전송이 실행되는 우선 순위입니다. 보통 또는 낮음을 선택할 수 있습니다. 낮은 전송 우선 순위를 지정하는 정책이 있는 정책보다 먼저 일반 전송 우선 순위를 지정하는 정책과의 관계입니다.

* * 최대 전송 속도 *
+
네트워크를 통해 클러스터 간에 데이터가 전송되는 최대 속도를 지정합니다. 이 옵션을 선택하면 네트워크 대역폭이 지정한 값으로 제한됩니다. 숫자 값을 입력한 다음 킬로바이트/초(kbps), 초당 메가바이트(Mbps), 초당 기가바이트(Gbps) 또는 Tbps를 선택할 수 있습니다. 최대 전송 속도를 사용하지 않도록 선택하는 경우 관계 간의 기본 전송은 무제한입니다. 하지만 ONTAP 8.2를 실행 중이고 운영 클러스터와 보조 클러스터가 동일한 경우 이 설정이 사용되지 않습니다.





== 소스 Snapshot 복사본 탭

소스 스냅샷 복사본 탭에는 기본 전송에 사용되는 소스 스냅샷 복사본에 대한 다음 정보가 표시됩니다.

* * 소스 볼륨 *
+
해당 소스 볼륨의 이름을 표시합니다.

* * 대상 볼륨 *
+
선택한 대상 볼륨의 이름을 표시합니다.

* * 소스 유형 *
+
읽기/쓰기 또는 데이터 보호와 같은 볼륨 유형을 표시합니다.

* * 스냅샷 복사본 *
+
데이터 전송에 사용되는 스냅샷 복사본을 표시합니다. 스냅샷 복사본 값을 클릭하면 현재 사용 중인 보호 관계 유형과 수행 중인 작업에 따라 전송할 특정 스냅샷 복사본을 선택할 수 있는 소스 스냅샷 복사본 선택 대화 상자가 표시됩니다.





== 명령 버튼

* * 제출 *
+
재동기화 프로세스를 시작하고 재동기화 대화 상자를 닫습니다.

* * 취소 *
+
선택 사항을 취소하고 재동기화 대화 상자를 닫습니다.


