---
permalink: online-help/reference-edit-volume-thresholds-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 볼륨의 용량과 관련된 이벤트가 생성될 때 알림을 보내도록 알림을 구성하고 이벤트에 대한 수정 조치를 수행할 수 있습니다. 예를 들어 볼륨 최대 임계값에 대해 지정된 기간 동안 조건이 지속되는 경우 알림을 보내도록 알림을 구성할 수 있습니다. 
---
= Edit Volume Thresholds(볼륨 임계값 편집) 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨의 용량과 관련된 이벤트가 생성될 때 알림을 보내도록 알림을 구성하고 이벤트에 대한 수정 조치를 수행할 수 있습니다. 예를 들어 볼륨 최대 임계값에 대해 지정된 기간 동안 조건이 지속되는 경우 알림을 보내도록 알림을 구성할 수 있습니다.

OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

Edit Volume Thresholds(볼륨 임계값 편집) 대화 상자에서는 선택한 볼륨에 적용되는 볼륨 레벨 임계값을 구성할 수 있습니다. 볼륨 레벨에서 임계값을 구성하면 그룹 수준 임계값 또는 글로벌 수준 임계값보다 높은 우선 순위가 높습니다.

볼륨 레벨에서 용량, 스냅샷 복사본, qtree 할당량, 증가 및 inode에 대한 임계값 설정을 구성할 수 있습니다. 볼륨 임계값 유형의 그룹 작업이 구성되면 볼륨 레벨에서 구성되지 않은 설정에 그룹 작업 임계값이 사용됩니다. 볼륨 임계값 유형의 그룹 작업이 구성되지 않은 경우 Edit Volume Thresholds(볼륨 임계값 편집) 대화 상자의 영역에서 글로벌 임계값을 사용합니다.



== 용량 영역

Capacity 영역에서는 다음 볼륨 용량 임계값 조건을 설정할 수 있습니다.

* * 공간이 거의 가득 찼습니다 *
+
볼륨이 거의 꽉 찬 것으로 간주되는 비율을 지정합니다. 또한 지정된 임계값에 해당하는 볼륨의 크기도 표시됩니다.

+
슬라이더를 사용하여 임계값을 설정할 수도 있습니다.

* * 공간이 가득 참 *
+
볼륨이 가득 찬 것으로 간주되는 비율을 지정합니다. 또한 지정된 임계값에 해당하는 볼륨의 크기도 표시됩니다.

+
슬라이더를 사용하여 임계값을 설정할 수도 있습니다.

* * 완전 충전 시까지 남은 기간 *
+
볼륨이 전체 용량에 도달하기 전까지 남은 일 수를 지정합니다.





== Snapshot 복사본

Snapshot 복사본 영역에서는 볼륨의 스냅샷 복사본에 대해 다음과 같은 임계값 조건을 설정할 수 있습니다.

* * Snapshot Reserve Full(스냅숏 예비 공간 전체) *
+
스냅샷 복사본에 예약된 공간이 가득 찬 것으로 간주되는 비율을 지정합니다.

* * 완전 충전 시까지 남은 기간 *
+
스냅샷 복사본에 예약된 공간이 전체 용량에 도달하기 전까지 남은 일 수를 지정합니다.

* * 카운트 *
+
너무 많은 것으로 간주되는 볼륨의 스냅샷 복사본 수를 지정합니다.





== Qtree 할당량 영역

Qtree Quota 영역에서는 선택한 볼륨에 대해 다음 qtree 할당량 임계값 조건을 설정할 수 있습니다.

* * 거의 과대 과대 *
+
볼륨이 qtree 할당량에 의해 거의 초과된 것으로 간주되는 비율을 지정합니다.

* * 과대 커밋 *
+
qtree 할당량에 의해 초과 커밋된 것으로 간주되는 볼륨을 백분율로 지정합니다.





== 성장 영역

Growth(성장) 영역에서는 볼륨 증가에 대해 다음 임계값 조건을 설정할 수 있습니다.

* * 성장률 *
+
시스템에서 Volume Growth Rate Abnormal 이벤트를 생성하기 전에 볼륨의 증가율이 정상으로 간주되는 비율을 지정합니다.

* * 성장률 감도 *
+
볼륨의 증가율의 표준 편차에 적용되는 계수를 지정합니다. 증가율이 계수 표준 편차를 초과하면 Volume Growth Rate Abnormal 이벤트가 생성됩니다.

+
성장률 감도 값이 낮을수록 체적이 증가율의 변화에 매우 민감함을 나타냅니다.

+
[NOTE]
====
글로벌 임계값 수준에서 볼륨의 증가율 민감도를 수정할 경우, 글로벌 임계값 수준에서 애그리게이트의 증가율 감도에도 변경 사항이 적용됩니다.

====




== inode 영역

inode 영역에서는 inode에 대해 다음과 같은 임계값 조건을 설정할 수 있습니다.

* * 거의 다 찼음 *
+
볼륨이 대부분의 inode를 사용한 것으로 간주되는 비율을 지정합니다.

+
슬라이더를 사용하여 임계값을 설정할 수도 있습니다.

* * 전체 *
+
볼륨이 모든 inode를 사용한 것으로 간주되는 비율을 지정합니다.

+
슬라이더를 사용하여 임계값을 설정할 수도 있습니다.





== 명령 버튼

명령 단추를 사용하여 선택한 볼륨에 대해 다음 작업을 수행할 수 있습니다.

* * 기본값으로 복원 *
+
임계값을 다음 중 하나로 복원할 수 있습니다.

+
** 그룹 값 - 볼륨이 그룹에 속해 있고 해당 그룹에 볼륨 임계값 동작 유형이 있는 경우
** 글로벌 값 - 볼륨이 그룹에 속하지 않거나 볼륨 임계값 동작 유형이 없는 그룹에 속해 있는 경우


* * 저장 *
+
모든 임계값 설정을 저장합니다.

* * 저장 후 닫기 *
+
모든 임계값 설정을 저장한 다음 대화 상자를 닫습니다.

* * 취소 *
+
임계값 설정에 대한 변경 사항을 무시하고 대화 상자를 닫습니다.


