---
permalink: online-help/reference-edit-alert-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 경고가 연결된 리소스, 이벤트, 스크립트 및 알림 옵션을 비롯한 알림 속성을 편집할 수 있습니다. 
---
= 알림 편집 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
경고가 연결된 리소스, 이벤트, 스크립트 및 알림 옵션을 비롯한 알림 속성을 편집할 수 있습니다.



== 이름

이 영역에서 알림의 이름과 설명을 편집할 수 있습니다.

* * 경고 이름 *
+
경고 이름을 편집할 수 있습니다.

* * 경고 설명 *
+
경고에 대한 설명을 지정할 수 있습니다.

* * 경고 상태 *
+
경고를 활성화 또는 비활성화할 수 있습니다.





== 리소스

이 영역에서는 알림을 트리거할 동적 규칙에 따라 개별 리소스를 선택하거나 리소스를 그룹화할 수 있습니다. 드롭다운 목록에서 리소스 유형을 선택하여 자원을 검색하거나 정확한 자원 이름을 지정하여 특정 자원을 표시할 수 있습니다.

* * 포함 *
+
경고를 트리거할 리소스를 포함할 수 있습니다. 문자열과 일치하는 리소스를 그룹화하는 텍스트 문자열을 지정하고 경고에 포함할 이 그룹을 선택할 수 있습니다. 예를 들어 이름이 ""vol0"" 문자열을 포함하는 모든 볼륨을 그룹화할 수 있습니다.

* * 제외 *
+
알림을 트리거하지 않을 리소스를 제외할 수 있습니다. 예를 들어 이름이 ""xyz"" 문자열을 포함하는 모든 볼륨을 제외할 수 있습니다.

+
[NOTE]
====
제외 탭은 특정 자원 유형의 모든 자원(예: <<All Volumes>> 또는 <<All Volumes whose name contains '_xyz_'>>.

====




== 이벤트

이 영역에서 알림을 트리거할 이벤트를 선택할 수 있습니다. 특정 심각도 또는 이벤트 세트에 따라 이벤트에 대한 알림을 트리거할 수 있습니다.

* * 이벤트 심각도 *
+
심각도 유형을 기반으로 이벤트를 선택할 수 있습니다. 심각도 유형은 위험, 오류 또는 경고일 수 있습니다.

* * 이벤트 이름에 * 가 포함되어 있습니다
+
지정한 문자가 포함된 이름의 이벤트를 선택할 수 있습니다.





== 작업

이 영역에서 알림 방법 및 알림 빈도를 지정할 수 있습니다.

* * 이 사용자에게 알림 *
+
이메일 주소 또는 사용자 이름을 편집하거나 알림을 수신할 새 이메일 주소 또는 사용자 이름을 지정할 수 있습니다.

* * 알림 빈도 *
+
이벤트를 확인, 해결 또는 폐기 상태로 이동할 때까지 관리 서버가 알림을 보내는 빈도를 편집할 수 있습니다.

+
다음 알림 방법을 선택할 수 있습니다.

+
** 한 번만 알립니다
** 지정된 빈도로 알립니다
** 지정된 시간 범위 내에 지정된 빈도로 알립니다


* * SNMP 트랩 * 을 실행합니다
+
SNMP 트랩을 전역적으로 구성된 SNMP 호스트로 전송할지 여부를 지정할 수 있습니다.

* * 스크립트 실행 *
+
스크립트를 경고와 연결할 수 있습니다. 이 스크립트는 경고가 생성될 때 실행됩니다.





== 명령 버튼

* * 저장 *
+
변경 사항을 저장하고 대화 상자를 닫습니다.

* * 취소 *
+
변경 내용을 취소하고 대화 상자를 닫습니다.


