---
permalink: online-help/reference-volume-data-protection-configuration-report.html 
sidebar: sidebar 
keywords:  
summary: '볼륨 데이터 보호 구성 보고서를 사용하면 노드 또는 클러스터에서 보호되지 않는 볼륨 및 SVM(스토리지 가상 머신)을 확인할 수 있습니다. 이 정보를 통해 시스템의 데이터 보호 위험을 이해하고 시스템의 보호된 볼륨 및 보호되지 않은 볼륨에 대한 세부 정보를 볼 수 있습니다.' 
---
= 볼륨 데이터 보호 구성 보고서
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨 데이터 보호 구성 보고서를 사용하면 노드 또는 클러스터에서 사용되는 보호되지 않는 볼륨 및 SVM(스토리지 가상 머신)을 확인할 수 있습니다. 이 정보를 통해 시스템의 데이터 보호 위험을 이해하고 시스템의 보호된 볼륨 및 보호되지 않은 볼륨에 대한 세부 정보를 볼 수 있습니다.

Volume Data Protection Configuration(볼륨 데이터 보호 구성) 보고서는 다음 두 가지 형식으로 표시됩니다.

* 보호된 볼륨 및 보호되지 않은 볼륨 원형 차트
* 보호되지 않은 볼륨 데이터 표 형식 보기




== 보호된 볼륨 및 보호되지 않은 볼륨 원형 차트

시스템에서 보호된 볼륨 및 보호되지 않은 볼륨의 상대적 비율을 표시합니다.



== 보호되지 않은 볼륨 데이터 표 형식 보기

* * 클러스터 *
+
클러스터 이름을 표시합니다.

* * 스토리지 가상 머신 *
+
볼륨이 포함된 SVM(스토리지 가상 시스템)의 이름을 표시합니다.

* * 볼륨 *
+
볼륨 이름을 표시합니다.

* * 총 데이터 용량(GB) *
+
총 데이터 용량(사용된 용량 및 사용 가능한 용량)을 GB 단위로 표시합니다.

* * 사용된 데이터 용량(GB) *
+
사용된 데이터 용량(GB)을 표시합니다.

* * 사용된 데이터 % *
+
사용된 데이터 용량을 백분율로 표시합니다.

* * 사용 가능한 데이터 용량(GB) *
+
사용 가능한 데이터 용량(GB)을 표시합니다.

* * 사용 가능한 데이터 % *
+
사용 가능한 데이터 용량을 백분율로 표시합니다.

* * Snapshot Reserve Used Capacity(GB) *
+
스냅샷 예약 공간(GB)의 스냅샷 복사본에서 사용하는 공간의 크기를 표시합니다.

* * 사용된 스냅숏 예비 공간 % *
+
스냅샷 보존의 스냅샷 복사본이 사용하는 공간의 양을 백분율로 표시합니다.

* * Snapshot Reserve Available Capacity(GB) *
+
스냅샷 복사본에 사용할 수 있는 공간 크기(GB)를 표시합니다.

* * Snapshot Reserve Available % *
+
스냅샷 복사본에 사용할 수 있는 공간의 양을 백분율로 표시합니다.

* * 스냅샷 예비 공간 총 용량(GB) *
+
애그리게이트의 총 스냅샷 예약 용량(GB)을 표시합니다.

* * 일 대 전체 *
+
Aggregate가 전체 용량에 도달하기 전까지 남은 예상 일 수를 표시합니다.

* * 공간이 가득 참 임계값 % *
+
Aggregate가 가득 찬 비율을 표시합니다.

* * 공간이 거의 가득 참 임계값 % *
+
집계가 거의 꽉 찬 비율을 표시합니다.

* * 일일 성장률 % *
+
볼륨에서 24시간마다 발생하는 증가율을 표시합니다.

* * 총 inode 수 *
+
볼륨의 총 inode 수를 표시합니다.

* * inode 사용률 *
+
볼륨에서 사용되는 inode 공간을 지정합니다.

* * 할당량 커밋 용량 *
+
볼륨에 예약된 공간을 표시합니다.

* * 할당량 초과 할당 용량(GB) *
+
시스템에서 볼륨 할당량 초과 커밋 이벤트를 생성하기 전에 사용할 수 있는 공간 크기(GB)를 표시합니다.

* * 스냅샷 자동 삭제 *
+
스냅샷 복사본의 자동 삭제를 설정 또는 해제할지 여부를 표시합니다.

* * 데이터 중복 제거 *
+
볼륨에 대해 중복 제거가 설정되었는지 여부를 표시합니다.

* * 데이터 중복 제거 공간 절약(GB) *
+
중복 제거(GB)를 사용하여 볼륨에 저장된 공간의 크기를 표시합니다.

* * 압축 *
+
볼륨에 대한 압축이 활성화되어 있는지 또는 비활성화되어 있는지 여부를 표시합니다.

* * 압축 공간 절약(GB) *
+
압축(GB)을 사용하여 볼륨에 저장된 공간을 표시합니다.

* * 씬 프로비저닝 *
+
선택한 볼륨에 대해 공간 보장이 설정되어 있는지 여부를 표시합니다. 유효한 값은 Yes 및 No입니다

* * Autogrow *
+
FlexVol 볼륨이 공간 부족 시 자동으로 크기가 증가하는지 여부를 표시합니다.

* * 공간 보장 *
+
볼륨이 Aggregate에서 사용 가능한 블록을 제거할 때 FlexVol 볼륨 설정 컨트롤을 표시합니다.

* * 시/도 *
+
내보내는 볼륨의 상태를 표시합니다.

* * SnapLock 유형 *
+
볼륨이 SnapLock 볼륨인지 또는 비 SnapLock 볼륨인지를 나타냅니다.

* * 만료 날짜 *

