---
permalink: online-help/reference-dynamic-performance-event-chart-details.html 
sidebar: sidebar 
keywords:  
summary: 동적 성능 이벤트의 경우 이벤트 세부 정보 페이지의 시스템 진단 섹션에 경합 중인 클러스터 구성 요소의 사용 또는 지연 시간이 가장 긴 최상위 워크로드가 나열됩니다. 성능 통계는 이벤트가 마지막으로 분석된 시간까지 성능 이벤트가 감지된 시간을 기준으로 합니다. 또한 차트에는 경합 중인 클러스터 구성 요소에 대한 기간별 성능 통계도 표시됩니다. 
---
= 동적 성능 이벤트 차트 세부 정보
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
동적 성능 이벤트의 경우 이벤트 세부 정보 페이지의 시스템 진단 섹션에 경합 중인 클러스터 구성 요소의 사용 또는 지연 시간이 가장 긴 최상위 워크로드가 나열됩니다. 성능 통계는 이벤트가 마지막으로 분석된 시간까지 성능 이벤트가 감지된 시간을 기준으로 합니다. 또한 차트에는 경합 중인 클러스터 구성 요소에 대한 기간별 성능 통계도 표시됩니다.

예를 들어, 구성 요소의 사용률이 높은 워크로드를 식별하여 사용률이 낮은 구성 요소로 이동할 워크로드를 결정할 수 있습니다. 워크로드를 이동하면 현재 구성 요소에 대한 작업 양이 줄어들고 구성 요소의 경합이 발생할 수 있습니다. 이 섹션의 의 시간 및 날짜 범위는 이벤트가 감지되어 마지막으로 분석된 시간입니다. 활성 이벤트(새 이벤트 또는 확인된 이벤트)의 경우 마지막으로 분석된 시간이 계속 업데이트됩니다.

지연 시간 및 활동 차트에는 커서를 차트 위에 놓으면 최상위 워크로드의 이름이 표시됩니다. 차트 오른쪽의 워크로드 유형 메뉴를 클릭하면 _Sharks_, _bullies_, 또는 _inuss_ 등의 이벤트 역할에 따라 워크로드를 정렬할 수 있으며 경합 중인 클러스터 구성 요소의 지연 시간 및 사용 현황에 대한 세부 정보를 표시합니다. 실제 값을 예상 값과 비교하여 워크로드가 예상 지연 시간 또는 사용 범위를 벗어난 시점을 확인할 수 있습니다. 을 참조하십시오 xref:concept-types-of-workloads-monitored-by-unified-manager.adoc[Unified Manager에서 모니터링하는 워크로드].

[NOTE]
====
지연 시간이 최대 편차로 정렬되면 사용자 정의 워크로드에만 지연 시간이 적용되므로 시스템 정의 워크로드가 표에 표시되지 않습니다. 지연 시간이 매우 짧은 워크로드는 테이블에 표시되지 않습니다.

====
동적 성능 임계값에 대한 자세한 내용은 를 참조하십시오 xref:reference-performance-event-analysis-and-notification.adoc[이벤트 정의]. Unified Manager에서 워크로드의 순위를 결정하고 정렬 순서를 결정하는 방법에 대한 자세한 내용은 을 참조하십시오 xref:concept-how-unified-manager-determines-the-performance-impact-for-an-incident.adoc[Unified Manager에서 이벤트에 대한 성능 영향을 확인하는 방법].

그래프의 데이터는 이벤트를 마지막으로 분석하기 전에 24시간 동안의 성능 통계를 보여줍니다. 각 워크로드의 실제 값과 예상 값은 워크로드가 발생한 시간을 기준으로 합니다. 예를 들어, 이벤트가 감지된 후 워크로드가 이벤트에 포함될 수 있으므로 이벤트 감지 시 성능 통계가 값과 일치하지 않을 수 있습니다. 기본적으로 워크로드는 지연 시간의 최대(최고) 편차별로 정렬됩니다.

[NOTE]
====
Unified Manager에서는 최대 30일간 5분간 기간별 성능 및 이벤트 데이터를 유지할 수 있으므로, 30일이 경과되지 않은 경우 성능 데이터가 표시되지 않습니다.

====
* * 워크로드 정렬 열 *
+
** * 지연 시간 차트 *
+
마지막 분석 동안 워크로드의 지연 시간에 이벤트가 미치는 영향을 표시합니다.

** * 구성 요소 사용 열 *
+
경합하는 클러스터 구성 요소의 워크로드 사용에 대한 세부 정보를 표시합니다. 그래프에서 실제 사용량은 파란색 선입니다. 빨간색 막대는 감지 시간부터 마지막으로 분석된 시간까지 이벤트 지속 시간을 강조 표시합니다. 자세한 내용은 을 참조하십시오 xref:reference-workload-performance-measurement-values.adoc[워크로드 성능 측정].

+
[NOTE]
====
네트워크 구성요소의 경우, 네트워크 성능 통계는 클러스터 외부의 활동에서 얻을 수 있기 때문에 이 열은 표시되지 않습니다.

====
** * 구성 요소 사용 *
+
QoS 정책 그룹 구성 요소에 대한 네트워크 처리, 데이터 처리 및 집계 구성 요소 또는 작업 내역(백분율)의 사용률 기록을 표시합니다. 네트워크 또는 상호 연결 구성 요소에 대한 차트는 표시되지 않습니다. 통계를 가리켜 특정 시점의 사용 통계를 볼 수 있습니다.

** * 총 쓰기 MBps 기록 *
+
MetroCluster 리소스 구성 요소의 경우 MetroCluster 구성에서 파트너 클러스터로 미러링되는 모든 볼륨 워크로드의 총 쓰기 처리량(MB/sec)을 표시합니다.

** * 이벤트 기록 *
+
경합이 발생한 부품의 과거 이벤트를 나타내기 위해 빨간색 음영으로 표시된 선을 표시합니다. 사용되지 않는 이벤트의 경우 선택한 이벤트가 감지되기 전과 해결된 이후에 발생한 이벤트가 차트에 표시됩니다.




