---
permalink: online-help/reference-aggregate-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: Aggregate Capacity and Utilization 보고서를 사용하면 클러스터에서 애그리게이트의 용량 및 활용률에 대한 정보를 볼 수 있습니다. 이 정보를 통해 가능한 용량 위험을 이해하고 애그리게이트의 구성, 사용 및 미사용 용량을 확인할 수 있습니다. 
---
= Capacity and Utilization(용량 및 활용도 집계) 보고서
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aggregate Capacity and Utilization 보고서를 사용하면 클러스터에서 애그리게이트의 용량 및 활용률에 대한 정보를 볼 수 있습니다. 이 정보를 통해 가능한 용량 위험을 이해하고 애그리게이트의 구성, 사용 및 미사용 용량을 확인할 수 있습니다.



== 집계 용량 및 활용도 보고서 표 형식 보기

* * 클러스터 *
+
클러스터 이름을 표시합니다.

* * HA 쌍 *
+
두 노드를 형성하여 얻은 HA 쌍 값을 표시합니다.

* * 집계 *
+
애그리게이트 이름을 표시합니다.

* * 총 데이터 용량(GB) *
+
총 데이터 용량을 표시합니다(사용된 용량과 사용 가능한 용량을 더한 용량).

* * 사용된 데이터 용량(GB) *
+
사용된 데이터 용량을 표시합니다.

* * 사용된 데이터 % *
+
사용된 데이터 용량을 백분율로 표시합니다.

* * 사용 가능한 데이터 용량(GB) *
+
사용 가능한 데이터 용량을 표시합니다.

* * 사용 가능한 데이터 % *
+
사용 가능한 데이터 용량을 백분율로 표시합니다.

* * 일일 성장률 % *
+
볼륨에서 24시간마다 발생하는 증가율을 표시합니다.

* * 일 대 전체 *
+
Aggregate가 전체 용량에 도달하기 전까지 남은 예상 일 수를 표시합니다.

* * 공간이 가득 참 임계값 *
+
Aggregate가 가득 찬 비율을 표시합니다.

* * 공간이 거의 가득 참 임계값 *
+
집계가 거의 꽉 찬 비율을 표시합니다.

* * 성장률 임계값 *
+
시스템이 Aggregate Growth Rate Abnormal 이벤트를 생성하기 전에 애그리게이트의 성장률이 정상으로 간주됩니다.

* * 성장률 감도 임계값 *
+
볼륨의 증가율의 표준 편차에 적용되는 계수를 지정합니다. 증가율이 계수 표준 편차를 초과하면 Volume Growth Rate Abnormal 이벤트가 생성됩니다.

* * 최대 한계까지 남은 일수 *
+
Aggregate가 전체 용량에 도달하기 전까지 남은 일 수를 지정합니다.

* * 스냅샷 예비 공간 총 용량(GB) *
+
애그리게이트의 총 스냅샷 예약 용량을 표시합니다.

* * Snapshot Reserve Used Capacity(GB) *
+
스냅숏 예비 공간의 스냅샷 복사본이 사용하는 공간을 표시합니다.

* * 사용된 스냅숏 예비 공간 % *
+
스냅샷 예약의 스냅샷 복사본이 사용하는 공간의 양을 백분율로 표시합니다.

* * Snapshot Reserve Available Capacity(GB) *
+
스냅샷 복사본에 사용할 수 있는 공간의 크기를 표시합니다.

* * Snapshot Reserve Available % *
+
스냅샷 복사본에 사용할 수 있는 공간의 양을 백분율로 표시합니다.

* * Snapshot 복사본 예약 최대 임계값 *
+
Aggregate가 스냅샷 복사본에 예약된 모든 공간을 소비한 비율을 지정합니다.

* * 초과 커밋 용량 % *
+
애그리게이트 구매의사를 백분율로 표시합니다.

* * 초과 커밋 임계값 % *
+
Aggregate가 초과 커밋된 비율을 표시합니다.

* * 거의 커밋된 임계값 % *
+
Aggregate가 거의 커밋된 비율을 표시합니다.

* * 유형 *
+
집계 유형을 표시합니다.

+
** HDD
** 하이브리드
+
HDD와 SSD를 결합하지만 Flash Pool은 활성화되지 않았습니다.

** 하이브리드(Flash Pool)
+
HDD와 SSD의 결합과 Flash Pool이 설정되었습니다.

** SSD를 지원합니다
** SSD(FabricPool)
+
SSD와 클라우드 계층을 결합합니다

** VMDisk(SDS)
+
가상 머신 내의 가상 디스크

** VMDisk(FabricPool)
+
가상 디스크와 클라우드 계층을 결합합니다

** FlexArray(LUN) 표준 디스크 및 SSD 디스크의 경우, 모니터링되는 스토리지 시스템이 8.3 이전 버전의 ONTAP를 실행 중인 경우 이 열은 비어 있습니다.


* * RAID 유형 *
+
RAID 구성 유형을 표시합니다.

* * 집계 상태 *
+
Aggregate의 현재 상태를 표시합니다.

* * SnapLock 유형 *
+
Aggregate가 SnapLock Aggregate인지 아니면 비 SnapLock Aggregate인지 나타냅니다.

* * 사용된 클라우드 계층 공간(GB) *
+
클라우드 계층에서 현재 사용 중인 데이터 용량의 양을 표시합니다.

* * 클라우드 계층 *
+
ONTAP에서 생성한 클라우드 계층의 이름을 표시합니다.


