---
permalink: online-help/reference-edit-aggregate-thresholds-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: Aggregate의 용량과 관련된 이벤트가 생성될 때 알림을 보내도록 알림을 구성하고 이벤트에 대한 수정 조치를 수행할 수 있습니다. 예를 들어 전체 집계 임계값의 경우 지정된 기간 동안 조건이 지속되는 경우 알림을 보내도록 알림을 구성할 수 있습니다. 
---
= 집계 임계값 편집 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aggregate의 용량과 관련된 이벤트가 생성될 때 알림을 보내도록 알림을 구성하고 이벤트에 대한 수정 조치를 수행할 수 있습니다. 예를 들어 전체 집계 임계값의 경우 지정된 기간 동안 조건이 지속되는 경우 알림을 보내도록 알림을 구성할 수 있습니다.

OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

애그리게이트 임계값 편집 대화 상자에서는 선택한 애그리게이트에 적용되는 애그리게이트 레벨 임계값을 구성할 수 있습니다. 집계 수준 임계값을 구성하는 경우 글로벌 수준 임계값보다 높은 우선 순위가 높습니다. 애그리게이트 레벨에서 용량, 증가 및 스냅샷 복사본에 대한 임계값 설정을 구성할 수 있습니다. 이러한 설정이 구성되어 있지 않으면 글로벌 임계값이 적용됩니다.

[NOTE]
====
임계값은 노드의 루트 애그리게이트에 적용할 수 없습니다.

====


== 용량 영역

Capacity 영역에서는 다음과 같은 총 용량 임계값 조건을 설정할 수 있습니다.

* * 공간이 거의 가득 찼습니다 *
+
집계가 거의 가득 찬 것으로 간주되는 비율을 지정합니다. 또한 지정된 임계값에 해당하는 애그리게이트의 크기도 표시됩니다.

+
슬라이더를 사용하여 임계값을 설정할 수도 있습니다.

* * 공간이 가득 참 *
+
집계가 가득 찬 것으로 간주되는 비율을 지정합니다. 또한 지정된 임계값에 해당하는 애그리게이트의 크기도 표시됩니다.

+
슬라이더를 사용하여 임계값을 설정할 수도 있습니다.

* * 거의 과대 과대 *
+
Aggregate가 거의 과커밋된 것으로 간주되는 비율을 지정합니다.

* * 과대 커밋 *
+
Aggregate가 초과 커밋된 것으로 간주되는 비율을 지정합니다.

* * 완전 충전 시까지 남은 기간 *
+
Aggregate가 전체 용량에 도달하기 전까지 남은 일 수를 지정합니다.





== 성장 영역

Growth(성장) 영역에서 애그리게이트 성장에 대한 다음 임계값 조건을 설정할 수 있습니다.

* * 성장률 *
+
시스템에서 애그리게이트 성장률 비정상 이벤트를 생성하기 전에 애그리게이트의 성장률이 정상으로 간주되는 비율을 지정합니다.

* * 성장률 감도 *
+
집계 증가율의 표준 편차에 적용되는 계수를 지정합니다. 증가율이 계수 표준 편차를 초과하면 Aggregate Growth Rate Abnormal 이벤트가 생성됩니다.

+
성장률 감도 값이 낮을수록 증가율의 변화에 매우 민감함을 나타냅니다.

+
[NOTE]
====
글로벌 임계값 수준에서 애그리게이트의 증가율 민감도를 수정할 경우 글로벌 임계값 레벨의 볼륨에 대한 증가율 감도 역시 변경됩니다.

====




== Snapshot 복사본 영역

Snapshot 복사본 영역에서는 다음 스냅샷 예약 임계값 조건을 설정할 수 있습니다.

* * Snapshot Reserve Full(스냅숏 예비 공간 전체) *
+
Aggregate가 스냅샷 복사본에 예약된 모든 공간을 소비한 비율을 지정합니다.

+
슬라이더를 사용하여 임계값을 설정할 수도 있습니다.





== 명령 버튼

명령 버튼을 사용하여 선택한 애그리게이트에 대해 다음 작업을 수행할 수 있습니다.

* * 기본값으로 복원 *
+
집계 수준 임계값을 글로벌 값으로 복원할 수 있습니다.

* * 저장 *
+
모든 임계값 설정을 저장합니다.

* * 저장 후 닫기 *
+
모든 임계값 설정을 저장한 다음 대화 상자를 닫습니다.

* * 취소 *
+
임계값 설정에 대한 변경 사항을 무시하고 대화 상자를 닫습니다.


