---
permalink: online-help/reference-select-source-snapshot-copy-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 소스 스냅샷 복사본 선택 대화 상자를 사용하여 보호 관계 간에 데이터를 전송할 특정 스냅샷 복사본을 선택하거나 기본 동작을 선택할 수 있습니다. 기본 동작은 관계를 초기화, 업데이트 또는 재동기화할지 여부 및 관계가 SnapMirror인지 SnapVault인지 여부에 따라 달라집니다. 
---
= 소스 스냅샷 복사본 대화 상자를 선택합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
소스 스냅샷 복사본 선택 대화 상자를 사용하여 보호 관계 간에 데이터를 전송할 특정 스냅샷 복사본을 선택하거나 기본 동작을 선택할 수 있습니다. 기본 동작은 관계를 초기화, 업데이트 또는 재동기화할지 여부 및 관계가 SnapMirror인지 SnapVault인지 여부에 따라 달라집니다.



== 기본값

SnapVault 및 SnapMirror 관계의 전송을 초기화, 업데이트 및 재동기화하는 데 사용할 스냅샷 복사본을 결정하는 기본 동작을 선택할 수 있습니다.

SnapVault 전송을 수행하는 경우 각 작업의 기본 동작은 다음과 같습니다.

|===
| 작동 | 소스가 읽기/쓰기입니다 SnapVault | 소스가 데이터 보호(DP)일 때의 기본 SnapVault 동작 


 a| 
초기화
 a| 
새 스냅샷 복사본을 생성하고 전송합니다.
 a| 
마지막으로 내보낸 스냅샷 복사본을 전송합니다.



 a| 
업데이트
 a| 
정책에 지정된 대로 레이블이 지정된 Snapshot 복사본만 전송합니다.
 a| 
마지막으로 내보낸 스냅샷 복사본을 전송합니다.



 a| 
재동기화
 a| 
는 최신 공통 스냅샷 복사본 이후에 생성된 레이블이 지정된 모든 스냅샷 복사본을 전송합니다.
 a| 
레이블이 지정된 최신 스냅샷 복사본을 전송합니다.

|===
SnapMirror 전송을 수행하는 경우 각 작업의 기본 동작은 다음과 같습니다.

|===
| 작동 | 기본 SnapMirror 동작입니다 | SnapMirror와 SnapMirror 캐스케이드의 두 번째 홉이면 기본 SnapMirror 동작입니다 


 a| 
초기화
 a| 
새 스냅샷 복사본을 생성하고 이 복사본과 새 스냅샷 복사본 이전에 생성된 모든 스냅샷 복사본을 전송합니다.
 a| 
모든 스냅샷 복사본을 소스에서 전송



 a| 
업데이트
 a| 
새 스냅샷 복사본을 생성하고 이 복사본과 새 스냅샷 복사본 이전에 생성된 모든 스냅샷 복사본을 전송합니다.
 a| 
모든 스냅샷 복사본을 전송합니다.



 a| 
재동기화
 a| 
새 스냅샷 복사본을 생성한 다음 소스에서 모든 스냅샷 복사본을 전송합니다.
 a| 
2차 볼륨에서 3차 볼륨으로 모든 스냅샷 복사본을 전송하고, 최신 공통 스냅샷 복사본을 생성한 후 추가한 모든 데이터를 삭제합니다.

|===


== 기존 스냅샷 복사본

해당 작업에 스냅샷 복사본을 선택할 수 있는 경우 목록에서 기존 스냅샷 복사본을 선택할 수 있습니다.

* * 스냅샷 복사본 *
+
전송을 위해 선택할 수 있는 기존 스냅샷 복사본을 표시합니다.

* * 만든 날짜 *
+
스냅샷 복사본이 생성된 날짜와 시간을 표시합니다. 스냅샷 복사본은 가장 최근 항목 부터 가장 최근 항목, 가장 최근 항목 목록 맨 위에 나열됩니다.



SnapVault 전송을 수행 중인 경우 소스에서 타겟으로 전송할 기존 스냅샷 복사본을 선택하려면 각 작업에 대한 동작은 다음과 같습니다.

|===
| 작동 | 스냅샷 복사본을 지정할 때의 SnapVault 동작 | 계단식 배열 내 스냅샷 복사본을 지정할 때의 SnapVault 동작 


 a| 
초기화
 a| 
지정된 스냅샷 복사본을 전송합니다.
 a| 
데이터 보호 볼륨에 대해서는 소스 스냅샷 복사본 선택이 지원되지 않습니다.



 a| 
업데이트
 a| 
지정된 스냅샷 복사본을 전송합니다.
 a| 
데이터 보호 볼륨에 대해서는 소스 스냅샷 복사본 선택이 지원되지 않습니다.



 a| 
재동기화
 a| 
선택한 스냅샷 복사본을 전송합니다.
 a| 
데이터 보호 볼륨에 대해서는 소스 스냅샷 복사본 선택이 지원되지 않습니다.

|===
SnapMirror 전송을 수행 중인 경우 소스에서 타겟으로 전송할 기존 스냅샷 복사본을 선택하려면 각 작업에 대한 동작은 다음과 같습니다.

|===
| 작동 | 스냅샷 복사본을 지정할 때의 SnapMirror 동작 | 계단식 배열 스냅샷 복사본을 지정할 때의 SnapMirror 동작 


 a| 
초기화
 a| 
소스의 모든 스냅샷 복사본을 지정된 스냅샷 복사본으로 전송합니다.
 a| 
데이터 보호 볼륨에 대해서는 소스 스냅샷 복사본 선택이 지원되지 않습니다.



 a| 
업데이트
 a| 
소스의 모든 스냅샷 복사본을 지정된 스냅샷 복사본으로 전송합니다.
 a| 
데이터 보호 볼륨에 대해서는 소스 스냅샷 복사본 선택이 지원되지 않습니다.



 a| 
재동기화
 a| 
소스에서 선택한 스냅샷 복사본으로 모든 스냅샷 복사본을 전송한 다음, 최신 공통 스냅샷 복사본을 생성한 후 추가한 데이터를 삭제합니다.
 a| 
데이터 보호 볼륨에 대해서는 소스 스냅샷 복사본 선택이 지원되지 않습니다.

|===


== 명령 버튼

명령 단추를 사용하여 다음 작업을 수행할 수 있습니다.

* * 제출 *
+
선택 항목을 제출하고 소스 스냅샷 복사본 선택 대화 상자를 닫습니다.

* * 취소 *
+
선택한 내용을 취소하고 소스 스냅샷 복사본 선택 대화 상자를 닫습니다.


