---
permalink: online-help/reference-user-defined-threshold-policies-page-opm.html 
sidebar: sidebar 
keywords:  
summary: 구성/성능 임계값 페이지를 사용하여 현재 정의된 모든 성능 임계값 정책을 볼 수 있습니다. 또한 이 페이지에서는 임계값 정책을 생성, 클론 복제, 편집 및 삭제할 수 있는 기능도 제공합니다. 
---
= 구성/성능 임계값 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
구성/성능 임계값 페이지를 사용하여 현재 정의된 모든 성능 임계값 정책을 볼 수 있습니다. 또한 이 페이지에서는 임계값 정책을 생성, 클론 복제, 편집 및 삭제할 수 있는 기능도 제공합니다.

성능 임계값 정책 목록은 정책 이름의 알파벳순으로 정렬됩니다. 열 머리글을 클릭하여 해당 열을 기준으로 정책을 정렬할 수 있습니다. 특정 정책을 찾는 경우 필터 및 검색 메커니즘을 사용하여 인벤토리 목록에 나타나는 임계값 정책 목록을 구체화할 수 있습니다.



== 필터 및 검색 표시줄

필터링 * 버튼을 사용하면 특정 기준에 맞는 정책만 표시하여 임계값 정책 목록을 구체화할 수 있습니다.

검색 * 버튼을 사용하면 전체 또는 일부 정책 이름을 입력하여 특정 정책을 검색하여 인벤토리 목록에 나타나는 임계값 정책 목록을 구체화할 수 있습니다.



== 명령 버튼

* * 생성 *
+
새 성능 임계값 정책을 생성합니다.

* * 클론 *
+
선택한 정책의 복사본을 기반으로 새 성능 임계값 정책을 생성합니다.

* * 편집 *
+
선택한 성능 임계값 정책을 수정합니다. 정책을 사용하는 모든 스토리지 객체가 수정된 정책을 사용하도록 업데이트됩니다.

* * 삭제 *
+
선택한 성능 임계값 정책을 삭제합니다. 정책을 사용하는 모든 스토리지 객체에서 정책이 제거됩니다. 연결된 개체 열에서 항목을 클릭하여 현재 이 정책을 사용 중인 개체를 볼 수 있습니다.





== 임계값 정책 목록

* * 정책 이름 *
+
임계값 정책의 이름을 표시합니다. 정책 이름 위에 커서를 놓으면 정책의 세부 정보를 볼 수 있습니다.

* * 설명 *
+
임계값 정책에 대한 간단한 설명을 표시합니다.

* * 첫 번째 조건 *
+
정의된 성능 카운터, 경고 트리거 값 및 중요 트리거 값을 포함하여 임계값 정책의 기본 조건을 표시합니다. 조건 이름 위에 커서를 놓으면 조건의 세부 정보를 볼 수 있습니다.

* * 두 번째 조건 *
+
정의된 경우 보조 임계값 정책 조건을 표시합니다. 조건 이름 위에 커서를 놓으면 조건의 세부 정보를 볼 수 있습니다. 두 번째 조건이 정의되지 않은 경우 이 열은 비어 있습니다.

+
[NOTE]
====
두 번째 조건이 정의되면 두 조건이 모두 위반될 때만 이벤트가 생성됩니다.

====
* * 관련 개체 *
+
임계값 정책을 적용할 수 있는 스토리지 오브젝트의 유형과 정책을 사용하는 오브젝트 수를 표시합니다. 이 필드는 하나 이상의 개체에 정책을 할당할 때까지 비어 있습니다.

+
열 머리글을 클릭하여 볼륨, LUN, 애그리게이트 등과 같은 개체 유형별로 정책을 정렬할 수 있습니다. 정책 이름을 클릭하여 현재 임계값 정책을 사용 중인 객체로 채워진 인벤토리 페이지를 표시할 수 있습니다.


