---
permalink: online-help/reference-types-of-system-defined-performance-threshold-policies.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager는 클러스터 성능을 모니터링하고 이벤트를 자동으로 생성하는 몇 가지 표준 임계값 정책을 제공합니다. 이러한 정책은 기본적으로 사용하도록 설정되어 있으며 모니터링되는 성능 임계값이 위반될 때 경고 또는 정보 이벤트를 생성합니다. 
---
= 시스템 정의 성능 임계값 정책의 유형입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager는 클러스터 성능을 모니터링하고 이벤트를 자동으로 생성하는 몇 가지 표준 임계값 정책을 제공합니다. 이러한 정책은 기본적으로 사용하도록 설정되어 있으며 모니터링되는 성능 임계값이 위반될 때 경고 또는 정보 이벤트를 생성합니다.

[NOTE]
====
Cloud Volumes ONTAP, ONTAP Edge 또는 ONTAP Select 시스템에서는 시스템 정의 성능 임계값 정책이 사용되지 않습니다.

====
시스템 정의 성능 임계값 정책에서 불필요한 이벤트를 수신하는 경우 구성/이벤트 관리 페이지에서 개별 정책을 비활성화할 수 있습니다.



== 노드 임계값 정책

기본적으로 시스템 정의 노드 성능 임계값 정책은 Unified Manager가 모니터링하는 클러스터의 모든 노드에 할당됩니다.

* * 노드 리소스가 과도하게 활용됨 *
+
단일 노드가 운영 효율성 한계를 초과하여 작동하고 따라서 워크로드 지연 시간에 영향을 미칠 수 있는 상황을 식별합니다. 이것은 경고 이벤트입니다.

+
ONTAP 8.3.x 및 이전 버전의 소프트웨어로 설치된 노드의 경우 CPU 및 RAM 리소스(노드 활용률)의 85% 이상을 30분 이상 사용하는 노드를 찾습니다.

+
ONTAP 9.0 이상 소프트웨어가 설치된 노드의 경우 30분 이상 성능 용량의 100% 이상을 사용하는 노드를 찾습니다.

* * 노드 HA Pair 초과 활용 *
+
HA 쌍 노드가 HA 쌍 운영 효율성 한계를 초과하여 작동하는 상황을 식별합니다. 이것은 정보 이벤트입니다.

+
ONTAP 8.3.x 및 이전 버전의 소프트웨어로 설치된 노드의 경우 HA 쌍의 두 노드에 대한 CPU 및 RAM 사용량을 보면 됩니다. 두 노드의 결합된 노드 활용률이 1시간 이상 140%를 초과하면 컨트롤러 페일오버가 워크로드 지연 시간에 영향을 미칩니다.

+
ONTAP 9.0 이상 소프트웨어가 설치된 노드의 경우 HA 쌍 중 두 노드에 사용된 성능 값을 기준으로 이 작업을 수행합니다. 두 노드에서 사용하는 결합된 성능 용량이 1시간 이상 200%를 초과하면 컨트롤러 페일오버가 워크로드 지연 시간에 영향을 미칩니다.

* * 노드 디스크 조각화 *
+
Aggregate의 디스크 또는 디스크가 조각화되어 주요 시스템 서비스가 느려지고 노드의 워크로드 지연 시간에 영향을 줄 수 있는 상황을 식별합니다.

+
노드의 모든 애그리게이트에서 특정 읽기 및 쓰기 작업 비율을 살펴보면 이 작업이 수행됩니다. 이 정책은 SyncMirror 재동기화 중에 또는 디스크 스크럽 작업 중에 오류가 발견된 경우에도 트리거될 수 있습니다. 이것은 경고 이벤트입니다.

+
[NOTE]
====
"'노드 디스크 조각화' 정책은 HDD 전용 애그리게이트를 분석하지만, Flash Pool, SSD, FabricPool 애그리게이트는 분석되지 않습니다.

====




== 임계값 정책을 집계합니다

시스템 정의 애그리게이트의 성능 임계값 정책은 기본적으로 Unified Manager가 모니터링하는 클러스터의 모든 애그리게이트로 할당됩니다.

* * 과도하게 사용된 디스크 집계 *
+
애그리게이트는 운영 효율성 한계를 초과하여 작동하는 상황을 식별하여 워크로드 지연 시간에 영향을 줄 수 있습니다. 이 방법을 통해 aggregate에서 디스크가 30분 이상 95% 이상 활용되는 애그리게이트를 찾을 수 있습니다. 이 다중 조건 정책은 다음 분석을 수행하여 문제의 원인을 파악합니다.

+
** 현재 백그라운드 유지 관리 작업을 진행 중인 aggregate의 디스크가 있습니까?
+
디스크 재구성, 디스크 스크럽, SyncMirror 재동기화 및 재패리티가 디스크에 실행될 수 있는 일부 백그라운드 유지 관리 작업입니다.

** 디스크 쉘프 파이버 채널 인터커넥트에 통신 병목 현상이 있습니까?
** Aggregate에 사용 가능한 용량이 너무 적습니까? 세 하위 정책 중 하나 이상의 정책이 위반된 것으로 간주되는 경우에만 이 정책에 대해 경고 이벤트가 발생합니다. Aggregate의 디스크가 95% 이상 사용된 경우 성능 이벤트가 트리거되지 않습니다.




[NOTE]
====
"'Aggregate disks over-활용되는' 정책은 HDD 전용 애그리게이트 및 Flash Pool(하이브리드) 애그리게이트를 분석하며, SSD와 FabricPool 애그리게이트는 분석되지 않습니다.

====


== QoS 임계값 정책

시스템 정의 QoS 성능 임계값 정책은 ONTAP QoS 최대 처리량 정책(IOPS, IOPS/TB 또는 Mbps)이 구성된 모든 워크로드에 할당됩니다. Unified Manager는 워크로드 처리량 값이 구성된 QoS 값보다 15% 적은 경우 이벤트를 트리거합니다.

* * QoS 최대 IOPS 또는 MBps 임계값 *
+
QoS 최대 IOPS 또는 MBPS 처리량 제한을 초과했으며 워크로드 지연 시간에 영향을 주는 볼륨 및 LUN을 식별합니다. 이것은 경고 이벤트입니다.

+
단일 워크로드가 정책 그룹에 할당되면 이전 시간의 각 수집 기간 동안 할당된 QoS 정책 그룹에 정의된 최대 처리량 임계값을 초과한 워크로드를 찾습니다.

+
여러 워크로드가 단일 QoS 정책을 공유하는 경우 정책에 있는 모든 워크로드의 IOPS 또는 MBPS를 추가하고 이 총계를 임계값을 확인하여 이를 수행합니다.

* * QoS 최대 IOPS/TB 또는 IOPS/TB, 블록 크기 임계값 *
+
적응형 QoS 최대 IOPS/TB 처리량 한도(또는 블록 크기 제한이 있는 IOPS/TB)를 초과했으며 워크로드 지연 시간에 영향을 주는 볼륨을 식별합니다. 이것은 경고 이벤트입니다.

+
이렇게 하려면 적응형 QoS 정책에 정의된 최대 IOPS/TB 임계값을 각 볼륨의 크기를 기준으로 QoS 최대 IOPS 값으로 변환한 다음, 이전 시간의 각 성능 수집 기간 동안 QoS 최대 IOPS를 초과한 볼륨을 찾습니다.

+
[NOTE]
====
이 정책은 클러스터가 ONTAP 9.3 이상 소프트웨어와 함께 설치된 경우에만 볼륨에 적용됩니다.

====
+
적응형 QoS 정책에 ""블록 크기"" 요소가 정의된 경우 각 볼륨의 크기를 기준으로 임계값이 QoS 최대 MBPS 값으로 변환됩니다. 그런 다음 이전 시간 동안 각 성능 수집 기간 동안 QoS 최대 MBps를 초과한 볼륨을 찾습니다.

+
[NOTE]
====
이 정책은 클러스터가 ONTAP 9.5 이상 소프트웨어와 함께 설치된 경우에만 볼륨에 적용됩니다.

====

