---
permalink: online-help/reference-setup-autosupport-page.html 
sidebar: sidebar 
keywords:  
summary: 설정/AutoSupport 페이지에서 AutoSupport 설명을 보거나, 주기적 AutoSupport을 설정하거나, 주문형 AutoSupport 메시지를 보낼 수 있습니다. 
---
= 설정/AutoSupport 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
설정/AutoSupport 페이지에서 AutoSupport 설명을 보거나, 주기적 AutoSupport을 설정하거나, 주문형 AutoSupport 메시지를 보낼 수 있습니다.



== 정보 영역

* * 시스템 ID *
+
이 Unified Manager 서버의 시스템 ID를 표시합니다.





== Periodic AutoSupport 영역

문제 진단 및 해결을 위해 정기적으로 생성되는 특정 사전 정의된 메시지를 기술 지원 부서에 전달할 수 있습니다.

* * Periodic AutoSupport 사용 *
+
주기적 AutoSupport 기능을 활성화하려는 경우를 나타냅니다.





== On-Demand AutoSupport 영역

주문형 메시지를 생성하여 기술 지원 부서, 지정된 이메일 수신자 또는 두 가지 모두로 보낼 수 있습니다.

* * 기술 지원 부서로 전송 *
+
발생한 문제에 대해 기술 지원 부서에 요청 시 메시지를 전송함을 나타냅니다.

* * 이메일 수신자에게 전송 *
+
발생한 문제에 대해 지정된 수신자에게 주문형 메시지를 보내려는 경우를 나타냅니다.

* * AutoSupport 생성 및 전송 *
+
발생한 문제에 대해 기술 지원 부서, 지정된 전자 메일 수신자 또는 둘 다에 요청 시 메시지를 생성하여 보냅니다.





== HTTP 프록시 영역입니다

환경에서 Unified Manager 서버로부터 직접 액세스할 수 없는 경우 AutoSupport 콘텐츠를 지원하도록 인터넷 액세스를 제공하는 프록시를 지정할 수 있습니다.

* * HTTP 프록시 사용 *
+
HTTP 프록시로 사용 중인 서버를 식별하려면 이 확인란을 선택합니다.

+
프록시 서버의 호스트 이름 또는 IP 주소와 서버 연결에 사용되는 포트 번호를 입력합니다.

* * 인증 사용 *
+
HTTP 프록시로 사용 중인 서버에 액세스하기 위한 인증 정보를 제공해야 하는 경우 이 확인란을 선택합니다.

+
HTTP 프록시로 인증하는 데 필요한 사용자 이름과 암호를 입력합니다.



[NOTE]
====
기본 인증만 제공하는 HTTP 프록시는 지원되지 않습니다.

====