---
permalink: online-help/reference-qtree-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: Qtree Capacity and Utilization 보고서를 사용하면 시스템 qtree의 용량 및 사용률을 분석하여 클러스터 용량 감소로 인해 발생할 수 있는 위험을 파악할 수 있습니다. 
---
= Qtree 용량 및 활용률 보고서
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Qtree Capacity and Utilization 보고서를 사용하면 시스템 qtree의 용량 및 활용률을 분석하여 클러스터 용량 감소로 인해 발생할 수 있는 위험을 파악할 수 있습니다.



== Qtree 용량 및 활용률 보고서 표 형식 보기

* * 클러스터 *
+
qtree가 포함된 클러스터의 이름을 표시합니다.

* * 스토리지 가상 머신 *
+
qtree가 포함된 스토리지 가상 시스템(SVM) 이름을 표시합니다.

* * 볼륨 *
+
qtree가 포함된 볼륨의 이름을 표시합니다.

* * Qtree *
+
qtree의 이름이 표시됩니다.

* * 할당량 유형 *
+
사용자, 사용자 그룹 또는 qtree에 대한 할당량인지 여부를 지정합니다.

* * 사용자 또는 그룹 *
+
사용자 또는 사용자 그룹의 이름을 표시합니다. 각 사용자 및 사용자 그룹에 대한 행이 여러 개 있습니다. 할당량 유형이 qtree인 경우 _not applicable_이 표시됩니다. 할당량이 설정되어 있지 않으면 열이 비어 있는 것입니다.

* * 사용된 디스크 % *
+
사용된 디스크 공간의 비율을 표시합니다. 디스크 하드 제한값이 설정된 경우 이 값은 디스크 하드 제한값을 기준으로 합니다. 디스크 하드 제한없이 할당량이 설정된 경우 이 값은 볼륨 데이터 공간을 기준으로 합니다. 할당량이 설정되어 있지 않거나 qtree가 속한 볼륨에서 할당량이 꺼져 있는 경우, _Not Applicable_이 표시됩니다.

* * 디스크 하드 제한값 *
+
qtree에 할당된 최대 디스크 공간을 표시합니다. Unified Manager에서는 이 제한에 도달하고 추가 디스크 쓰기가 허용되지 않을 경우 중요한 이벤트를 생성합니다. 디스크 하드 제한없이 할당량이 설정되어 있거나, 할당량이 설정되어 있지 않거나, qtree가 속한 볼륨에서 할당량이 꺼져 있는 경우 이 값은 _Unlimited_로 표시됩니다.

* * 디스크 소프트 제한값 *
+
경고 이벤트가 생성되기 전에 qtree에 할당된 디스크 공간을 표시합니다. 이 값은 디스크 소프트 제한값 없이 할당량이 설정되어 있거나, 할당량이 설정되어 있지 않거나, qtree가 속한 볼륨에서 할당량이 꺼져 있는 경우 _Unlimited_로 표시됩니다.

* * 사용된 파일 % *
+
qtree에 사용된 파일의 백분율을 표시합니다. 파일 하드 제한값이 설정된 경우 이 값은 파일 하드 제한값을 기준으로 합니다. 할당량이 설정되어 있지 않거나 파일 하드 제한없이 할당량이 설정되어 있거나 qtree가 속한 볼륨에서 할당량이 꺼져 있는 경우 이 값은 _Not Applicable_으로 표시됩니다.

* * 파일 하드 제한값 *
+
Qtree에서 허용되는 파일 수의 하드 제한값을 표시합니다. 파일 하드 제한없이 할당량이 설정되어 있거나, 할당량이 설정되어 있지 않거나, qtree가 속한 볼륨에서 할당량이 꺼져 있는 경우 이 값은 _Unlimited_로 표시됩니다.

* * 파일 소프트 제한값 *
+
Qtree에서 허용되는 파일 수의 소프트 제한값을 표시합니다. 파일 소프트 제한값 없이 할당량이 설정된 경우, 할당량이 설정되지 않은 경우 또는 qtree가 속한 볼륨에서 할당량이 꺼져 있는 경우 이 값은 _Unlimited_로 표시됩니다.


