---
permalink: online-help/task-responding-to-a-system-defined-qos-policy-group-performance-event.html 
sidebar: sidebar 
keywords:  
summary: 'Unified Manager에서 워크로드 처리량(IOPS, IOPS/TB 또는 MBps\)이 정의된 ONTAP QoS 정책 설정을 초과하고 워크로드 지연 시간에 영향을 미치는 경우 QoS 정책 경고 이벤트를 생성합니다. 많은 워크로드가 지연 시간의 영향을 받기 전에 이러한 시스템 정의 이벤트를 통해 잠재적 성능 문제를 해결할 수 있습니다.' 
---
= QoS 정책 그룹 성능 이벤트에 응답
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager는 워크로드 처리량(IOPS, IOPS/TB 또는 MBps)이 정의된 ONTAP QoS 정책 설정을 초과하고 워크로드 지연 시간에 영향을 미칠 경우 QoS 정책 경고 이벤트를 생성합니다. 많은 워크로드가 지연 시간의 영향을 받기 전에 이러한 시스템 정의 이벤트를 통해 잠재적 성능 문제를 해결할 수 있습니다.



== 시작하기 전에

* 운영자, OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 새로운 성능 이벤트, 확인된 이벤트 또는 사용되지 않는 성능 이벤트가 있어야 합니다.




== 이 작업에 대해

Unified Manager는 이전 시간의 각 성능 수집 기간 동안 워크로드 처리량이 정의된 QoS 정책 설정을 초과할 경우 QoS 정책 위반에 대한 경고 이벤트를 생성합니다. 각 수집 기간 동안 짧은 기간 동안만 워크로드 처리 성능이 QoS 임계값을 초과할 수 있지만 Unified Manager에서는 차트에 수집 기간 동안 ""평균"" 처리량만 표시합니다. 따라서 워크로드의 처리량이 차트에 표시된 정책 임계값을 넘을 수 없는 경우 QoS 이벤트가 발생할 수 있습니다.

System Manager 또는 ONTAP 명령을 사용하여 다음 작업을 비롯한 정책 그룹을 관리할 수 있습니다.

* 워크로드에 대한 새 정책 그룹 생성
* 정책 그룹에서 워크로드 추가 또는 제거
* 정책 그룹 간에 워크로드 이동
* 정책 그룹의 처리량 제한을 변경합니다
* 워크로드를 다른 Aggregate 또는 노드로 이동




== 단계

. 이벤트에 대한 정보를 보려면 * 이벤트 * 세부 정보 페이지를 표시합니다.
. 이벤트를 발생시킨 임계값 위반을 설명하는 * Description * 을 검토합니다.
+
예를 들어 ""vol1_NFS1에서 1,352 IOPS의 IOPS 값이 경고 이벤트를 트리거하여 워크로드에 대한 잠재적인 성능 문제를 식별했습니다." 메시지는 볼륨 vol1_NFS1에서 QoS Max IOPS 이벤트가 발생했음을 나타냅니다.

. 이벤트 발생 시기 및 이벤트 활성 기간에 대한 자세한 내용은 * 이벤트 정보 * 섹션을 참조하십시오.
+
또한 QoS 정책의 처리량을 공유하는 볼륨 또는 LUN의 경우 가장 높은 IOPS 또는 MBPS를 소비하는 상위 3개 워크로드의 이름을 확인할 수 있습니다.

. System Diagnosis * 섹션에서 총 평균 IOPS 또는 MBps(이벤트에 따라 다름)에 대한 차트와 지연 시간에 대한 차트의 두 차트를 검토합니다. 이렇게 정렬하면 워크로드가 QoS 최대 제한에 근접했을 때 지연 시간에 가장 영향을 미치는 클러스터 구성 요소를 확인할 수 있습니다.
+
공유 QoS 정책 이벤트의 경우 처리량 차트에 상위 3개 워크로드가 표시됩니다. QoS 정책을 공유하는 워크로드가 3개 이상이면 추가 워크로드가 ""기타 워크로드" 범주에 추가됩니다. 또한 지연 시간 차트에는 QoS 정책에 포함되는 모든 워크로드의 평균 지연 시간이 표시됩니다.

+
적응형 QoS 정책 이벤트의 경우 IOPS 및 MBPS 차트는 볼륨 크기에 따라 ONTAP이 할당된 IOPS/TB 임계값 정책에서 변환한 IOPS 또는 MBPS 값을 표시합니다.

. 제안 조치 * 섹션에서 제안 사항을 검토하고 작업 부하 대기 시간의 증가를 방지하기 위해 수행해야 할 조치를 결정합니다.
+
필요한 경우 * 도움말 * 버튼을 클릭하여 성능 이벤트 해결을 위해 수행할 수 있는 권장 조치에 대한 자세한 내용을 확인하십시오.


