---
permalink: online-help/task-adding-clusters.html 
sidebar: sidebar 
keywords:  
summary: 클러스터를 모니터링할 수 있도록 OnCommand Unified Manager에 클러스터를 추가할 수 있습니다. 여기에는 발생할 수 있는 문제를 찾아 해결할 수 있도록 클러스터의 상태, 용량, 성능, 구성 등과 같은 클러스터 정보를 가져오는 기능도 포함됩니다. 
---
= 클러스터 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터를 모니터링할 수 있도록 OnCommand Unified Manager에 클러스터를 추가할 수 있습니다. 여기에는 발생할 수 있는 문제를 찾아 해결할 수 있도록 클러스터의 상태, 용량, 성능, 구성 등과 같은 클러스터 정보를 가져오는 기능도 포함됩니다.



== 시작하기 전에

* OnCommand 관리자 역할 또는 스토리지 관리자 역할이 있어야 합니다.
* 클러스터에 대한 호스트 이름 또는 클러스터 관리 IP 주소(IPv4 또는 IPv6)가 있어야 합니다.
+
호스트 이름을 사용할 때는 클러스터 관리 LIF의 클러스터 관리 IP 주소로 해석해야 합니다. 노드 관리 LIF를 사용하면 작업이 실패합니다.

* 클러스터에 액세스하려면 사용자 이름과 암호가 있어야 합니다.
+
이 계정에는 응용 프로그램 액세스 권한이 _ontapi_, _ssh_ 및 _http_로 설정된 _admin_역할이 있어야 합니다.

* 클러스터에 구성할 프로토콜 유형(HTTP 또는 HTTPS)과 클러스터에 연결하는 데 사용되는 포트 번호를 알고 있어야 합니다.
* Unified Manager 서버에 적절한 공간이 있어야 합니다. 90% 이상의 공간이 이미 사용된 경우 서버에 클러스터를 추가할 수 없습니다.


[NOTE]
====
Unified Manager NAT IP 주소를 사용하여 NAT/방화벽 뒤에 있는 클러스터를 추가할 수 있습니다. 연결된 모든 Workflow Automation 또는 SnapProtect 시스템은 NAT/방화벽 뒤에 있어야 하며 SnapProtect API 호출은 NAT IP 주소를 사용하여 클러스터를 식별해야 합니다.

====


== 이 작업에 대해

* MetroCluster 구성의 각 클러스터는 별도로 추가해야 합니다.
* Unified Manager의 단일 인스턴스에서 특정 수의 노드를 지원할 수 있습니다. 지원되는 노드 수를 초과하는 환경을 모니터링해야 하는 경우, 일부 클러스터를 모니터링하려면 Unified Manager의 추가 인스턴스를 설치해야 합니다.
* Unified Manager의 각 인스턴스가 다른 LIF를 통해 연결되도록 클러스터에 두 번째 클러스터 관리 LIF를 구성한 경우, Unified Manager의 두 인스턴스를 통해 단일 클러스터를 모니터링할 수 있습니다.




== 단계

. 왼쪽 탐색 창에서 * 구성 * > * 클러스터 데이터 소스 * 를 클릭합니다.
. 구성/클러스터 데이터 소스 * 페이지에서 * 추가 * 를 클릭합니다.
. 클러스터 추가 * 대화 상자에서 필요에 따라 값을 지정한 다음 * 제출 * 을 클릭합니다.
. HTTPS를 선택한 경우 다음 단계를 수행하십시오.
+
.. 호스트 인증 * 대화 상자에서 * 인증서 보기 * 를 클릭하여 클러스터에 대한 인증서 정보를 봅니다.
.. 예 * 를 클릭합니다.
+
Unified Manager는 처음에 클러스터를 추가할 때만 인증서를 확인합니다. Unified Manager에서는 ONTAP에 대한 각 API 호출의 인증서를 확인하지 않습니다.

+
인증서가 만료된 경우 새 클러스터를 추가할 수 없습니다. 먼저 SSL 인증서를 갱신한 다음 클러스터를 추가해야 합니다.







== 결과

새 클러스터의 모든 객체가 검색되고(약 15분), Unified Manager가 이전 15일 동안 기간별 성능 데이터를 수집하기 시작합니다. 이러한 통계는 데이터 연속성 수집 기능을 사용하여 수집됩니다. 이 기능은 클러스터를 추가한 직후 2주 이상의 클러스터 성능 정보를 제공합니다. 데이터 연속성 수집 주기가 완료되면 기본적으로 5분마다 실시간 클러스터 성능 데이터가 수집됩니다.

[NOTE]
====
15일간의 성능 데이터 수집은 CPU를 많이 사용하므로 데이터 연속성 수집 폴이 너무 많은 클러스터에서 동시에 실행되지 않도록 새 클러스터를 추가하는 시차를 두는 것이 좋습니다. 또한, 데이터 연속성 수집 기간 동안 Unified Manager를 다시 시작하면 수집이 중단되고 성능 차트의 누락된 시간 간격이 표시됩니다.

====
[TIP]
====
클러스터를 추가할 수 없다는 오류 메시지가 표시되면 다음 문제가 있는지 확인하십시오.

* 두 시스템의 시계가 동기화되지 않고 Unified Manager HTTPS 인증서 시작 날짜가 클러스터의 날짜보다 이후인 경우 NTP 또는 이와 유사한 서비스를 사용하여 시계가 동기화되었는지 확인해야 합니다.
* 클러스터가 최대 EMS 알림 대상 수에 도달하면 Unified Manager 주소를 추가할 수 없습니다. 기본적으로 클러스터에 20개의 EMS 알림 대상만 정의할 수 있습니다.


====