---
permalink: online-help/task-initializing-or-updating-protection-relationships.html 
sidebar: sidebar 
keywords:  
summary: 보호/볼륨 관계 페이지에서 새 보호 관계에 대한 초기 계획을 처음으로 전송하거나, 이미 초기화된 관계로 즉시 전송하기 위해 예정되지 않은 수동 증분 업데이트를 수행하려는 경우 관계를 업데이트할 수 있습니다. 
---
= 보호/볼륨 관계 페이지에서 보호 관계를 초기화하거나 업데이트합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
보호/볼륨 관계 페이지에서 새 보호 관계에 대한 초기 계획을 처음으로 전송하거나, 이미 초기화된 관계로 즉시 전송하기 위해 예정되지 않은 수동 증분 업데이트를 수행하려는 경우 관계를 업데이트할 수 있습니다.



== 시작하기 전에

* OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* OnCommand Workflow Automation를 설정해야 합니다.




== 단계

. 보호/볼륨 관계 * 페이지에서 볼륨을 마우스 오른쪽 단추로 클릭하고 업데이트하거나 초기화할 관계가 있는 볼륨을 하나 이상 선택한 다음 도구 모음에서 * 초기화/업데이트 * 를 클릭합니다.
+
Initialize/Update(초기화/업데이트) 대화 상자가 표시됩니다.

. 전송 옵션 * 탭에서 전송 우선 순위 및 최대 전송 속도를 선택합니다.
. 소스 스냅샷 복사본 * 을 클릭한 다음 * 스냅샷 복사본 * 열에서 * 기본값 * 을 클릭합니다.
+
소스 스냅샷 복사본 선택 대화 상자가 표시됩니다.

. 기본 스냅샷 복사본을 전송하지 않고 기존 스냅샷 복사본을 지정하려면 * 기존 스냅샷 복사본 * 을 클릭하고 목록에서 스냅샷 복사본을 선택합니다.
. 제출 * 을 클릭합니다.
+
Initialize/Update(초기화/업데이트) 대화 상자로 돌아갑니다.

. 초기화하거나 업데이트할 소스를 두 개 이상 선택한 경우 기존 스냅샷 복사본을 지정할 다음 소스에 대해 * 기본값 * 을 클릭합니다.
. 초기화 또는 업데이트 작업을 시작하려면 * 제출 * 을 클릭하십시오.
+
초기화 또는 업데이트 작업이 시작되고 보호/볼륨 관계 페이지로 돌아가며 페이지 상단에 작업 링크가 표시됩니다.

. 각 초기화 또는 업데이트 작업의 상태를 추적하려면 * 상태/볼륨 * 재고 페이지에서 * 작업 보기 * 를 클릭합니다.
+
필터링된 작업 목록이 표시됩니다.

. 세부 정보를 보려면 각 작업을 클릭합니다.
. 브라우저의 * 뒤로 * 화살표를 클릭하여 * 보호/볼륨 관계 * 페이지로 돌아갑니다.
+
모든 작업이 성공적으로 완료되면 초기화 또는 업데이트 작업이 완료됩니다.


