---
permalink: online-help/task-identifying-lifs-with-the-most-connections-using-the-cli.html 
sidebar: sidebar 
keywords:  
summary: 데이터 LIF의 로드 또는 처리량이 많을 경우 데이터 LIF를 마이그레이션할 수 있습니다. LIF 마이그레이션 여부를 결정하기 위해 LIF의 로드, 포트의 연결 수, 노드의 처리량 및 CPU 사이클을 표시할 수 있습니다. 
---
= CLI를 사용하여 가장 많이 연결되는 LIF 식별
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 LIF의 로드 또는 처리량이 많을 경우 데이터 LIF를 마이그레이션할 수 있습니다. LIF 마이그레이션 여부를 결정하기 위해 LIF의 로드, 포트의 연결 수, 노드의 처리량 및 CPU 사이클을 표시할 수 있습니다.



== 단계

. 클러스터 관리자로 CLI에 액세스합니다.
. 다음 명령을 입력하여 권한 수준을 고급으로 설정합니다. `set -privilege advanced`
+
고급 모드에서 CLI를 사용하는 방법에 대한 자세한 내용은 _시스템 관리 참조_를 참조하십시오.

. 각 LIF의 중량을 확인하려면 다음 명령을 입력합니다. `network interface lif-weights show`
+
사용 중인 LIF는 가장 체중이 낮은 LIF입니다.

. 노드에서 활성 연결을 찾으려면 다음 명령을 입력합니다. `network connections active show-clients`
+
노드별로 가장 높은 클라이언트 수를 확인합니다.

+
[listing]
----
cluster1::> network connections active show-clients
Node    Client IP Address     Count
------  -----------------     ------
node1   192.0.2.253               12
        192.0.2.252                9
        192.0.2.251               12

node2   192.0.2.250               12
        192.0.2.252                9
        192.0.2.253                9

node3   customer.example.com       2
        customer.example.net       2
        customer.example.org       2
----
. 노드 및 SVM에서 LIF로 활성 연결을 찾으려면 다음 명령을 입력합니다. `network connections active show-lifs`
+
LIF당 가장 높은 클라이언트 수를 확인하십시오.

+
[listing]
----
cluster1::> network connections active show-lifs
Node      Vserver Name  Interface Name  Count
--------  ------------  --------------- ------
node1
          vs1           clus1              30

node2
          vs2           clus1              30

node3
          vs3           lif1                2
          vs4           clus1              30
----
. 동일한 홈 포트와 홈 노드를 공유하고 있는 LIF에서 대부분의 연결이 있는 LIF를 확인하십시오.
. 최상의 데이터 포트를 선택하려면 다음을 입력합니다. `statistics show -object port`
+
statistics 명령은 이더넷 포트에 대한 처리량 및 대역폭 정보를 제공합니다. 각 행에는 고유한 정보가 들어 있는 별도의 카운터가 있습니다. value 는 카운터가 마지막으로 지워진 이후(ONTAP가 마지막으로 시작된 이후) 개체 유형의 값입니다.

+
[listing]
----
cluster1::> statistics show -object port
Object: port
Instance: e0a
Start-time: 10/11/2013 13:51:41
End-time: 10/11/2013 13:51:41
Node: node1

    Counter                                           Value
    -------------------------------------------------------
    recv-data                                            0B
    recv-packets                                         0
    recv-mcasts                                          0
    recv-errors                                          0
    recv-dropped                                         0
    sent-data                                            0B
    sent-packets                                         0
    sent-mcasts                                          0
    sent-errors                                          0
    collisions                                           0
----

