---
permalink: online-help/task-viewing-fabricpool-capacity-information.html 
sidebar: sidebar 
keywords:  
summary: 상태 인벤토리에서 클러스터, 애그리게이트 및 볼륨의 FabricPool 용량 정보 및 이러한 개체에 대한 세부 정보 페이지를 볼 수 있습니다. 또한 집계 용량 및 활용도 보고서에서 FabricPool 정보를 볼 수도 있습니다. 
---
= FabricPool 용량 정보 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
상태 인벤토리에서 클러스터, 애그리게이트 및 볼륨의 FabricPool 용량 정보 및 이러한 개체에 대한 세부 정보 페이지를 볼 수 있습니다. 또한 집계 용량 및 활용도 보고서에서 FabricPool 정보를 볼 수도 있습니다.



== 이 작업에 대해

이 페이지에는 로컬 성능 계층 및 클라우드 계층에서 사용 가능한 용량, 두 계층에서 사용 중인 용량, 애그리게이트가 클라우드 계층에 연결된 용량 등의 정보가 표시됩니다. 어떤 볼륨이 특정 정보를 클라우드 계층으로 이동하여 FabricPool 기능을 구현할지,



== 단계

. 다음 중 하나를 수행합니다.
+
|===
| 용량 정보를 보려면... | 수행할 작업... 


 a| 
클러스터
 a| 
.. 상태/클러스터 인벤토리 페이지에서 클러스터를 클릭합니다.
.. 상태/클러스터 세부 정보 페이지에서 * 구성 * 탭을 클릭합니다.
+
이 화면에는 이 클러스터가 연결된 모든 클라우드 계층의 이름이 표시됩니다.





 a| 
애그리게이트
 a| 
.. 상태/집계 인벤토리 페이지에서 유형 필드가 "SSD(FabricPool)"로 표시되는 애그리게이트를 클릭합니다.
.. 상태/애그리게이트 세부 정보 페이지에서 * 용량 * 탭을 클릭합니다.
+
이 화면에는 총 용량과 사용된 공간 및 사용 가능한 클라우드 계층이 표시됩니다.

.. 디스크 정보 * 탭을 클릭합니다.
+
디스플레이에 클라우드 계층의 이름과 사용 가능한 공간이 표시됩니다.

.. Configuration * 탭을 클릭합니다.
+
디스플레이에 클라우드 계층의 이름 및 오브젝트 저장소에 대한 기타 자세한 정보가 표시됩니다.





 a| 
볼륨
 a| 
.. Health/Volumes Inventory 페이지에서 "Tiering Policy" 필드에 정책 이름이 표시되는 볼륨을 클릭합니다.
.. 상태/볼륨 세부 정보 페이지에서 * 구성 * 탭을 클릭합니다.
+
이 화면에는 볼륨에 할당된 FabricPool 계층화 정책의 이름이 표시됩니다.



|===




== 작업을 마친 후

FabricPool Aggregate에 대한 자세한 내용은 _ONTAP 9 디스크 및 집계 전원 가이드_를 참조하십시오.

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["ONTAP 9 디스크 및 애그리게이트 전원 가이드"]
