---
permalink: online-help/task-editing-user-and-group-quota-email-addresses.html 
sidebar: sidebar 
keywords:  
summary: '클러스터, SVM(Storage Virtual Machine), 볼륨, Qtree, 사용자 또는 사용자 그룹과 연결된 사용자 할당량을 기준으로 이메일 주소를 수정할 수 있습니다. 사용자 및 그룹 할당량 이메일 주소 생성 규칙 대화 상자에서 지정한 규칙에 의해 생성된 이메일 주소를 무시하려면 이메일 주소를 수정할 수 있습니다.' 
---
= 사용자 및 그룹 할당량 이메일 주소 편집
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터, SVM(스토리지 가상 머신), 볼륨, Qtree, 사용자 또는 사용자 그룹과 연결된 사용자 할당량을 기준으로 이메일 주소를 수정할 수 있습니다. 사용자 및 그룹 할당량 이메일 주소 생성 규칙 대화 상자에서 지정한 규칙에 의해 생성된 이메일 주소를 무시하려면 이메일 주소를 수정할 수 있습니다.



== 시작하기 전에

* 운영자, OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 을(를) 검토해야 합니다 xref:reference-rules-to-generate-user-and-group-quota-email-address-dialog-box.adoc[규칙 작성 지침].




== 이 작업에 대해

전자 메일 주소를 편집하는 경우 사용자 및 그룹 할당량 전자 메일 주소를 생성하는 규칙이 더 이상 할당량에 적용되지 않습니다. 지정한 규칙에 의해 생성된 이메일 주소로 알림을 보내려면 이메일 주소를 삭제하고 변경 내용을 저장해야 합니다.



== 단계

. 왼쪽 탐색 창에서 * 상태 * > * SVM * 을 클릭합니다.
. Health/Storage Virtual Machines * 인벤토리 페이지에서 SVM을 선택한 다음 * 사용자 및 그룹 할당량 * 탭을 클릭합니다.
. 탭 행 아래에 있는 * 이메일 주소 편집 * 을 클릭합니다.
. 이메일 주소 편집 * 대화 상자에서 적절한 조치를 수행합니다.
+
|===
| 만약... | 그러면... 


 a| 
지정한 규칙에 의해 생성된 이메일 주소로 알림을 전송하고자 합니다
 a| 
.. 이메일 주소 * 필드에서 이메일 주소를 삭제합니다.
.. 저장 * 을 클릭합니다.
.. F5 키를 눌러 전자 메일 주소 편집 대화 상자를 다시 로드하여 브라우저를 새로 고칩니다. 지정한 규칙에 의해 생성된 이메일 주소는 * 이메일 주소 * 필드에 표시됩니다.




 a| 
알림을 지정된 이메일 주소로 전송하려는 경우
 a| 
.. 이메일 주소 * 필드에서 이메일 주소를 수정합니다.
.. 저장 * 을 클릭합니다. 사용자 및 그룹 할당량 e-메일 주소를 생성하는 규칙은 더 이상 할당량에 적용되지 않습니다.


|===

