---
permalink: online-help/task-creating-a-snapmirror-relationship-with-version-flexible-replication.html 
sidebar: sidebar 
keywords:  
summary: 버전에 상관없이 유연하게 복제할 수 있는 SnapMirror 관계를 구축할 수 있습니다. 버전에 상관없이 유연하게 복제를 수행하면 소스 볼륨과 타겟 볼륨이 서로 다른 버전의 ONTAP에서 실행되는 경우에도 SnapMirror 보호를 구현할 수 있습니다. 
---
= 버전에 상관없이 유연하게 복제 가능한 SnapMirror 관계 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
버전에 상관없이 유연하게 복제할 수 있는 SnapMirror 관계를 구축할 수 있습니다. 버전에 상관없이 유연하게 복제를 수행하면 소스 볼륨과 타겟 볼륨이 서로 다른 버전의 ONTAP에서 실행되는 경우에도 SnapMirror 보호를 구현할 수 있습니다.



== 시작하기 전에

* OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* Workflow Automation을 설정해야 합니다.
* 소스 및 타겟 SVM에는 각각 SnapMirror 라이센스가 활성화되어 있어야 합니다.
* 버전에 상관없이 유연하게 복제를 지원하는 ONTAP 소프트웨어 버전에서 소스 및 타겟 SVM을 각각 실행해야 합니다.




== 이 작업에 대해

버전에 상관없이 복제 가능한 SnapMirror를 사용하면 모든 스토리지가 ONTAP의 단일 버전에서 실행되는 것이 아닌 이기종 스토리지 환경에서도 SnapMirror 보호를 구현할 수 있습니다. 하지만 버전에 상관없이 유연한 복제를 통해 SnapMirror에서 수행되는 미러링 작업은 기존 블록 복제 SnapMirror와 마찬가지로 빠르게 실행되지 않습니다.



== 단계

. 보호할 볼륨에 대한 * 보호 구성 * 대화 상자를 표시합니다.
+
** 상태/볼륨 세부 정보 페이지의 보호 탭을 보고 있는 경우 보호할 볼륨 이름이 있는 토폴로지 뷰를 마우스 오른쪽 버튼으로 클릭하고 메뉴에서 * 보호 * > * SnapMirror * 를 선택합니다.
** 상태/볼륨 인벤토리 페이지를 보고 있는 경우 보호할 볼륨을 찾아 마우스 오른쪽 단추로 클릭한 다음 메뉴에서 * 보호 * > * SnapMirror * 를 선택합니다. 보호 구성 대화 상자가 표시됩니다.


. SnapMirror * 탭을 보려면 * SnapMirror * 를 클릭하십시오.
. 보호 구성 * 대화 상자에서 * 대상 정보 * 영역과 * 관계 설정 * 영역을 완료합니다.
+
보호할 소스 볼륨보다 이전 버전의 ONTAP에서 실행되는 타겟 SVM을 지정하고 이전 버전에서 유연한 복제를 지원하는 경우 이 작업은 버전에 상관없이 유연한 복제를 통해 SnapMirror를 자동으로 구성합니다.

. 소스 볼륨과 동일한 버전의 ONTAP에서 실행되는 타겟 SVM을 지정했지만 버전에 상관없이 유연한 복제로 SnapMirror를 구성하려면 * 고급 * 을 클릭하여 버전에 상관없이 복제를 활성화한 다음 * 적용 * 을 클릭합니다.
. 적용 * 을 클릭합니다.
+
상태/볼륨 세부 정보 페이지로 돌아갑니다.

. 상태/볼륨 * 세부 정보 페이지 상단의 보호 구성 작업 링크를 클릭합니다.
+
보호/작업 세부 정보 페이지에 작업 작업 및 세부 정보가 표시됩니다.

. 보호/작업 * 세부 정보 페이지에서 * 새로 고침 * 을 클릭하여 보호 구성 작업과 관련된 작업 목록 및 작업 세부 정보를 업데이트하고 작업 완료 시기를 결정합니다.
. 작업 작업이 완료되면 브라우저에서 * Back * 을 클릭하여 * Health/Volume * 세부 정보 페이지로 돌아갑니다.
+
새 관계가 상태/볼륨 세부 정보 페이지 토폴로지 보기에 표시됩니다.


