---
permalink: online-help/task-moving-workloads-to-a-different-aggregate.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager를 사용하면 현재 워크로드가 있는 애그리게이트보다 덜 사용되는 애그리게이트를 식별할 수 있으며, 그런 다음 선택한 볼륨 또는 LUN을 해당 애그리게이트로 이동할 수 있습니다. 고성능 워크로드를 사용량이 낮은 Aggregate로 이동하거나 플래시 스토리지를 지원하는 Aggregate를 이동하면 워크로드가 보다 효율적으로 수행됩니다. 
---
= 워크로드를 다른 애그리게이트로 이동
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 사용하면 현재 워크로드가 있는 애그리게이트보다 덜 사용되는 애그리게이트를 식별할 수 있으며, 그런 다음 선택한 볼륨 또는 LUN을 해당 애그리게이트로 이동할 수 있습니다. 고성능 워크로드를 사용량이 낮은 Aggregate로 이동하거나 플래시 스토리지를 지원하는 Aggregate를 이동하면 워크로드가 보다 효율적으로 수행됩니다.



== 시작하기 전에

* 운영자, OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 현재 성능 문제가 있는 애그리게이트의 이름을 기록해야 합니다.
* Aggregate가 이벤트를 수신한 날짜 및 시간을 기록해야 합니다.
* ""p-SDT-clus1-AG-2542""와 같은 이벤트 ID를 기록해야 합니다.
* Unified Manager에서 성능 데이터를 한 달 이상 수집 및 분석해야 합니다.




== 이 작업에 대해

다음 단계를 수행하면 고성능 워크로드를 사용률이 낮은 Aggregate로 이동할 수 있도록 다음 리소스를 식별할 수 있습니다.

* 활용되지 않는 동일한 클러스터의 애그리게이트
* 현재 애그리게이트에서 가장 높은 성능을 보이는 볼륨




== 단계

. 가장 활용도가 낮은 클러스터 내 애그리게이트 식별:
+
.. 이벤트 * 세부 정보 페이지에서 애그리게이트로 구성된 클러스터의 이름을 클릭합니다.
+
클러스터 세부 정보가 성능/클러스터 랜딩 페이지에 표시됩니다.

.. 요약 * 페이지의 * 관리되는 개체 * 창에서 * 집계 * 를 클릭합니다.
+
이 클러스터의 애그리게이트 목록이 표시됩니다.

.. Utilization * 열을 클릭하여 가장 적게 사용된 순서대로 애그리게이트를 정렬합니다.
+
또한 * 가용 용량 * 이 가장 큰 애그리게이트를 식별할 수 있습니다. 다음은 워크로드를 이동할 수 있는 잠재적 애그리게이트 목록입니다.

.. 워크로드를 이동할 애그리게이트의 이름을 기록합니다.


. 이벤트를 수신한 애그리게이트로부터 고성능 볼륨을 식별합니다.
+
.. 성능 문제가 있는 애그리게이트를 클릭합니다.
+
집계 세부 정보는 성능/집계 탐색기 페이지에 표시됩니다.

.. 시간 범위 * 선택기에서 * 최근 30일 * 을 선택한 다음 * 범위 적용 * 을 클릭합니다.
+
이렇게 하면 기본 72시간보다 더 긴 성능 기록 기간을 볼 수 있습니다. 지난 72시간 동안 많은 리소스를 사용하는 볼륨을 일관성 있게 이동하려고 합니다.

.. 보기 및 비교 * 컨트롤에서 이 집계 * 의 * 볼륨 을 선택합니다.
+
이 애그리게이트에 있는 FlexVol 볼륨 및 FlexGroup 구성 볼륨 목록이 표시됩니다.

.. 볼륨을 가장 높은 MBps로 정렬한 다음 가장 높은 IOPS로 정렬하여 가장 높은 성능을 보이는 볼륨을 확인합니다.
.. 다른 aggregate로 이동하려는 볼륨의 이름을 기록합니다.


. 사용률이 낮은 것으로 확인된 aggregate로 고성능 볼륨을 이동합니다.
+
OnCommand 시스템 관리자, OnCommand Workflow Automation, ONTAP 명령 또는 이러한 툴의 조합을 사용하여 이동 작업을 수행할 수 있습니다.





== 작업을 마친 후

며칠 후 이 노드나 집합으로부터 동일한 유형의 이벤트를 받고 있는지 확인하십시오.
