---
permalink: online-help/task-aborting-an-active-data-protection-transfer-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: 진행 중인 SnapMirror 복제를 중지하려는 경우 활성 데이터 보호 전송을 중단할 수 있습니다. 기본 전송이 아닌 경우 전송에 대한 재시작 체크포인트를 지울 수도 있습니다. 볼륨 이동 같은 다른 작업과 충돌하는 경우 전송을 중단할 수 있습니다. 
---
= 상태/볼륨 세부 정보 페이지에서 활성 데이터 보호 전송을 중단합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
진행 중인 SnapMirror 복제를 중지하려는 경우 활성 데이터 보호 전송을 중단할 수 있습니다. 기본 전송이 아닌 경우 전송에 대한 재시작 체크포인트를 지울 수도 있습니다. 볼륨 이동 같은 다른 작업과 충돌하는 경우 전송을 중단할 수 있습니다.



== 시작하기 전에

* OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* Workflow Automation을 설정해야 합니다.




== 이 작업에 대해

중단 작업은 다음 경우에 표시되지 않습니다.

* RBAC 설정에서 이 작업을 허용하지 않는 경우(예: 운영자 권한만 있는 경우
* 볼륨 ID를 알 수 없는 경우(예: 인터클러스터 관계가 있고 대상 클러스터가 아직 검색되지 않은 경우


기본 전송에 대해 재시작 체크포인트를 지울 수 없습니다.



== 단계

. 상태/볼륨 * 세부 정보 페이지의 * 보호 * 탭에서 중단하려는 데이터 전송에 대한 토폴로지 뷰의 관계를 마우스 오른쪽 버튼으로 클릭하고 * 중단 * 을 선택합니다.
+
전송 중단 대화 상자가 표시됩니다.

. 기본 전송이 아닌 전송에 대해 재시작 체크포인트를 지우려면 * 체크포인트 지우기 * 를 선택합니다.
. 계속 * 을 클릭합니다.
+
전송 중단 대화 상자가 닫히고 중단 작업의 상태가 작업 세부 정보에 대한 링크와 함께 상태/볼륨 세부 정보 페이지 맨 위에 표시됩니다.

. 자세한 내용을 보거나 작업 진행률을 보려면 * 상세 정보 보기 * 링크를 클릭하여 * 보호/작업 * 상세 정보 페이지로 이동하십시오.
. 각 작업 작업을 클릭하여 세부 정보를 봅니다.
. 브라우저의 뒤로 화살표를 클릭하여 * 상태/볼륨 * 세부 정보 페이지로 돌아갑니다.
+
모든 작업 작업이 성공적으로 완료되면 중단 작업이 완료됩니다.


