---
permalink: online-help/task-initializing-or-updating-protection-relationships-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: 새 보호 관계에 대해 최초 베이스라인 전송을 수행하거나, 이미 초기화된 상태에서 데이터를 즉시 전송하기 위해 예정되지 않은 수동 증분 업데이트를 수행하려는 경우 관계를 업데이트할 수 있습니다. 
---
= 상태/볼륨 세부 정보 페이지에서 보호 관계를 초기화 또는 업데이트합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새 보호 관계에 대해 최초 베이스라인 전송을 수행하거나, 이미 초기화된 상태에서 데이터를 즉시 전송하기 위해 예정되지 않은 수동 증분 업데이트를 수행하려는 경우 관계를 업데이트할 수 있습니다.



== 시작하기 전에

* OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* OnCommand Workflow Automation를 설정해야 합니다.




== 단계

. 상태/볼륨 * 세부 정보 페이지의 * 보호 * 탭에서 초기화하거나 업데이트할 보호 관계를 토폴로지에서 찾은 다음 마우스 오른쪽 단추로 클릭합니다.
. 메뉴에서 * Initialize/Update * 를 선택합니다.
+
또는 * Actions * 메뉴에서 * Relationship * > * Initialize/Update * 를 선택하여 현재 세부 정보를 보고 있는 관계를 초기화하거나 업데이트합니다.

+
Initialize/Update(초기화/업데이트) 대화 상자가 표시됩니다.

. 전송 옵션 * 탭에서 전송 우선 순위 및 최대 전송 속도를 선택합니다.
. 소스 스냅샷 복사본 * 을 클릭한 다음 * 스냅샷 복사본 * 열에서 * 기본값 * 을 클릭합니다.
+
소스 스냅샷 복사본 선택 대화 상자가 표시됩니다.

. 기본 스냅샷 복사본을 전송하지 않고 기존 스냅샷 복사본을 지정하려면 * 기존 스냅샷 복사본 * 을 클릭하고 목록에서 스냅샷 복사본을 선택합니다.
. 제출 * 을 클릭합니다.
+
Initialize/Update(초기화/업데이트) 대화 상자로 돌아갑니다.

. 초기화하거나 업데이트할 소스를 두 개 이상 선택한 경우 기존 스냅샷 복사본을 지정할 다음 읽기/쓰기 소스에 대해 * 기본값 * 을 클릭합니다.
+
데이터 보호 볼륨에 대해 다른 스냅샷 복사본을 선택할 수는 없습니다.

. 초기화 또는 업데이트 작업을 시작하려면 * 제출 * 을 클릭하십시오.
+
초기화 또는 업데이트 작업이 시작되고 상태/볼륨 세부 정보 페이지로 돌아가며 페이지 상단에 작업 링크가 표시됩니다.

. 각 초기화 또는 업데이트 작업의 상태를 추적하려면 * 상태/볼륨 * 세부 정보 페이지에서 * 작업 보기 * 를 클릭합니다.
+
필터링된 작업 목록이 표시됩니다.

. 세부 정보를 보려면 각 작업을 클릭합니다.
. 브라우저의 뒤로 화살표를 클릭하여 * 상태/볼륨 * 세부 정보 페이지로 돌아갑니다.
+
모든 작업 작업이 성공적으로 완료되면 초기화 또는 업데이트 작업이 완료됩니다.


