---
permalink: online-help/task-responding-to-user-defined-performance-threshold-events.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager를 사용하면 성능 카운터가 사용자 정의 경고 또는 중요 임계값을 초과하여 성능 이벤트를 조사할 수 있습니다. Unified Manager를 사용하여 클러스터 구성 요소의 상태를 검사하여 구성 요소에서 감지된 최근 상태 이벤트가 성능 이벤트에 기여했는지 확인할 수도 있습니다. 
---
= 사용자 정의 성능 임계값 이벤트에 응답
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 사용하면 성능 카운터가 사용자 정의 경고 또는 중요 임계값을 초과하여 성능 이벤트를 조사할 수 있습니다. Unified Manager를 사용하여 클러스터 구성 요소의 상태를 검사하여 구성 요소에서 감지된 최근 상태 이벤트가 성능 이벤트에 기여했는지 확인할 수도 있습니다.



== 시작하기 전에

* 운영자, OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 새 성능 이벤트 또는 사용되지 않는 성능 이벤트가 있어야 합니다.




== 단계

. 이벤트에 대한 정보를 보려면 * 이벤트 * 세부 정보 페이지를 표시합니다.
. 이벤트를 발생시킨 임계값 위반을 설명하는 * Description * 을 검토합니다.
+
예를 들어 "'456 ms/op의 지연 시간 값이 400 ms/op의 임계값 설정에 따라 경고 이벤트를 트리거했습니다' 메시지는 객체에 대한 지연 경고 이벤트가 발생했음을 나타냅니다.

. 정책 이름 위에 커서를 올려 놓으면 이벤트를 트리거한 임계값 정책에 대한 세부 정보가 표시됩니다.
+
여기에는 정책 이름, 평가 중인 성능 카운터, 중요 이벤트 또는 경고 이벤트로 간주하기 위해 위반되어야 하는 카운터 값, 카운터가 값을 초과해야 하는 기간이 포함됩니다.

. 이벤트 트리거 시간 * 을 메모하여 이 이벤트에 영향을 줄 수 있는 다른 이벤트가 동시에 발생했는지 여부를 조사할 수 있습니다.
. 아래 옵션 중 하나를 따라 이벤트를 추가로 조사하여 성능 문제를 해결하기 위해 조치를 수행해야 하는지 여부를 확인합니다.
+
|===
| 옵션을 선택합니다 | 가능한 조사 조치 


 a| 
원본 개체 이름을 클릭하여 해당 개체의 탐색기 페이지를 표시합니다.
 a| 
이 페이지에서는 오브젝트 세부 정보를 확인하고 이 오브젝트를 다른 유사한 스토리지 오브젝트와 비교하여 다른 스토리지 오브젝트의 성능 문제가 동시에 있는지 확인할 수 있습니다. 예를 들어, 같은 애그리게이트의 다른 볼륨에도 성능 문제가 있는지 확인합니다.



 a| 
클러스터 이름을 클릭하여 클러스터 요약 페이지를 표시합니다.
 a| 
이 페이지에서는 이 객체가 상주하는 클러스터에 대한 세부 정보를 볼 수 있어 다른 성능 문제가 동시에 발생했는지 여부를 확인할 수 있습니다.

|===

