---
permalink: online-help/task-analyzing-a-performance-incident-on-a-remote-cluster-in-a-metrocluster-configuration.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager를 사용하여 MetroCluster 구성에서 원격 클러스터의 동적 성능 이벤트를 분석할 수 있습니다. 분석을 통해 원격 클러스터의 이벤트로 인해 파트너 클러스터의 이벤트가 발생했는지 여부를 확인할 수 있습니다. 
---
= MetroCluster 구성에서 원격 클러스터에 대한 동적 성능 이벤트 분석
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 사용하여 MetroCluster 구성에서 원격 클러스터의 동적 성능 이벤트를 분석할 수 있습니다. 분석을 통해 원격 클러스터의 이벤트로 인해 파트너 클러스터의 이벤트가 발생했는지 여부를 확인할 수 있습니다.



== 시작하기 전에

* 운영자, OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* MetroCluster 구성에서 로컬 클러스터의 성능 이벤트를 분석하고 이벤트 감지 시간을 확인해야 합니다.
* 성능 이벤트와 관련된 로컬 클러스터와 파트너 클러스터의 상태를 확인하고 파트너 클러스터의 이름을 얻어야 합니다.




== 단계

. 파트너 클러스터를 모니터링 중인 Unified Manager 인스턴스에 로그인합니다.
. 왼쪽 탐색 창에서 * 이벤트 * 를 클릭하여 이벤트 목록을 표시합니다.
. Time Range * 선택기에서 * Last Hour * 를 선택한 다음 * Apply Range * 를 클릭합니다.
. 필터링 * 선택기의 왼쪽 드롭다운 메뉴에서 * 클러스터 * 를 선택하고 텍스트 필드에 파트너 클러스터의 이름을 입력한 다음 * 필터 적용 * 을 클릭합니다.
+
지난 1시간 동안 선택한 클러스터에 대한 이벤트가 없을 경우 이는 이벤트가 파트너에 감지된 시간 동안 클러스터에서 성능 문제가 발생하지 않았음을 나타냅니다.

. 선택한 클러스터에 지난 1시간 동안 감지된 이벤트가 있는 경우 이벤트 감지 시간과 로컬 클러스터의 이벤트에 대한 이벤트 감지 시간을 비교합니다.
+
이러한 이벤트로 인해 워크로드가 불룩하게 발생하여 데이터 처리 구성 요소에서 경합이 발생하는 경우, 이러한 불리 중 하나 이상이 로컬 클러스터에서 이벤트를 유발했을 수 있습니다. 이벤트를 클릭하여 분석하고 이벤트 세부 정보 페이지에서 해결 시 제안된 작업을 검토할 수 있습니다.

+
대규모 워크로드가 관련되지 않은 경우 로컬 클러스터에서 성능 이벤트가 발생하지는 않았습니다.


