---
permalink: online-help/task-restoring-a-mysql-database-backup-on-red-hat-enterprise-linux-or-centos.html 
sidebar: sidebar 
keywords: Unified Manager 
summary: 데이터 손실 또는 데이터 손상이 발생할 경우 Unified Manager를 최소한의 데이터 손실로 이전의 안정적인 상태로 복원할 수 있습니다. Unified Manager 데이터베이스를 로컬 또는 원격 Red Hat Enterprise Linux 또는 CentOS 시스템으로 복원할 수 있습니다. 
---
= Linux 시스템에서 데이터베이스 백업을 복원합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 손실 또는 데이터 손상이 발생할 경우 Unified Manager를 최소한의 데이터 손실로 이전의 안정적인 상태로 복원할 수 있습니다. Unified Manager 데이터베이스를 로컬 또는 원격 Red Hat Enterprise Linux 또는 CentOS 시스템으로 복원할 수 있습니다.



== 시작하기 전에

* 서버에 Unified Manager가 설치되어 있어야 합니다.
* Unified Manager가 설치된 Linux 호스트에 대한 루트 사용자 자격 증명이 있어야 합니다.
* Unified Manager 백업 파일과 데이터베이스 저장소 디렉터리의 내용을 복구 작업을 수행할 시스템에 복사해야 합니다.
+
백업 파일을 기본 디렉토리에 복사하는 것이 좋습니다 `/data/ocum-backup`. 데이터베이스 리포지토리 파일을 에 복사해야 합니다 `/database-dumps-repo` 하위 디렉토리 아래에 있습니다 `/ocum-backup` 디렉토리.

* 백업 파일은 이어야 합니다 `.7z` 유형.




== 이 작업에 대해

복원 기능은 플랫폼별 및 버전에 따라 다릅니다. Unified Manager 백업은 동일한 Unified Manager 버전에서만 복원할 수 있습니다. Linux 백업 파일 또는 가상 어플라이언스 백업 파일을 Red Hat Enterprise Linux 또는 CentOS 시스템으로 복원할 수 있습니다.

[TIP]
====
백업 폴더 이름에 공백이 포함된 경우 절대 경로 또는 상대 경로를 큰따옴표로 묶어야 합니다.

====


== 단계

. 새 서버로 복원을 수행하는 경우 Unified Manager를 설치한 후 설치가 완료될 때 UI를 실행하거나 클러스터, 사용자 또는 인증 설정을 구성하지 마십시오. 백업 파일은 복원 프로세스 중에 이 정보를 채웁니다.
. Unified Manager가 설치된 호스트에 루트 사용자로 로그인합니다.
. Unified Manager가 VCS 설정에 설치되어 있는 경우 Veritas Operations Manager를 사용하여 Unified Manager ocie 및 ocieau 서비스를 중지합니다.
. 명령 프롬프트에서 백업을 복원합니다. `um backup restore -f <backup_file_path>/<backup_file_name>`
+
`um backup restore -f /data/ocum-backup/UM_9.4.N151113.1348_backup_rhel_02-20-2018-04-45.7z`





== 작업을 마친 후

복원 작업이 완료되면 Unified Manager에 로그인할 수 있습니다.
