---
permalink: online-help/task-creating-a-snapvault-protection-relationship-from-the-health-volumes-page.html 
sidebar: sidebar 
keywords:  
summary: '상태/볼륨 인벤토리 페이지를 사용하여 동일한 스토리지 가상 머신(SVM\)에서 하나 이상의 볼륨에 대한 SnapVault 관계를 생성하여 보호를 위해 데이터 백업을 지원할 수 있습니다.' 
---
= 상태/볼륨 인벤토리 페이지에서 SnapVault 보호 관계 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
상태/볼륨 인벤토리 페이지를 사용하여 동일한 SVM(스토리지 가상 머신)에서 하나 이상의 볼륨에 대한 SnapVault 관계를 생성하여 보호를 위한 데이터 백업을 지원할 수 있습니다.



== 시작하기 전에

OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.



== 이 작업에 대해

다음과 같은 경우에는 * Protect * 메뉴가 표시되지 않습니다.

* RBAC 설정에서 이 작업을 허용하지 않는 경우(예: 운영자 권한만 있는 경우
* 볼륨 ID를 알 수 없는 경우(예: 인터클러스터 관계가 있고 대상 클러스터가 아직 검색되지 않은 경우




== 단계

. 왼쪽 탐색 창에서 * 상태 * > * 볼륨 * 을 클릭합니다.
. 상태/볼륨 * 재고 페이지에서 보호할 볼륨을 마우스 오른쪽 단추로 클릭하고 * 보호 * 를 선택합니다.
+
또는 동일한 SVM(스토리지 가상 시스템)에서 여러 보호 관계를 생성하려면 상태/볼륨 인벤토리 페이지에서 볼륨을 하나 이상 선택하고 도구 모음에서 * 보호 * 를 클릭합니다.

. 메뉴에서 * SnapVault * 를 선택합니다.
+
보호 구성 대화 상자가 시작됩니다.

. SnapVault * 를 클릭하여 * SnapVault * 탭을 보고 보조 볼륨 정보를 구성합니다.
. 고급 * 을 클릭하여 필요에 따라 중복제거, 압축, 자동 확장, 공간 보장을 설정하고 * 적용 * 을 클릭합니다.
. SnapVault* 탭의 * 대상 정보 * 영역과 * 관계 설정 * 영역을 입력합니다.
. 적용 * 을 클릭합니다.
+
상태/볼륨 인벤토리 페이지로 돌아갑니다.

. 상태/볼륨 * 인벤토리 페이지 상단의 보호 구성 작업 링크를 클릭합니다.
+
보호 관계를 하나만 생성하는 경우 보호/작업 세부 정보 페이지가 표시되지만 둘 이상의 보호 관계를 생성하는 경우 보호 작업과 관련된 모든 작업의 필터링된 목록이 표시됩니다.

. 다음 중 하나를 수행합니다.
+
** 작업이 하나뿐인 경우 * 새로 고침 * 을 클릭하여 보호 구성 작업과 관련된 작업 목록 및 작업 세부 정보를 업데이트하고 작업이 완료되는 시점을 결정합니다.
** 작업이 두 개 이상인 경우:
+
... 작업 목록에서 작업을 클릭합니다.
... 보호 구성 작업과 관련된 작업 목록 및 작업 세부 정보를 업데이트하고 작업이 완료되는 시점을 확인하려면 * 새로 고침 * 을 클릭합니다.
... 필터링된 목록으로 돌아가 다른 작업을 보려면 * 뒤로 * 버튼을 사용합니다.





