---
permalink: online-help/task-moving-workloads-to-a-different-node.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager를 사용하면 현재 실행 중인 워크로드가 있는 노드보다 사용량이 적은 다른 노드의 애그리게이트를 식별할 수 있으며, 선택한 볼륨을 해당 애그리게이트로 이동할 수 있습니다. 사용량이 적은 노드의 aggregate로 고성능 워크로드를 이동하면 두 노드의 워크로드를 더 효율적으로 처리할 수 있습니다. 
---
= 워크로드를 다른 노드로 이동
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 사용하면 현재 실행 중인 워크로드가 있는 노드보다 사용량이 적은 다른 노드의 애그리게이트를 식별할 수 있으며, 선택한 볼륨을 해당 애그리게이트로 이동할 수 있습니다. 사용량이 적은 노드의 aggregate로 고성능 워크로드를 이동하면 두 노드의 워크로드를 더 효율적으로 처리할 수 있습니다.



== 시작하기 전에

* 운영자, OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 현재 성능 문제가 있는 노드의 이름을 기록해야 합니다.
* 성능 이벤트를 수신한 날짜 및 시간을 기록해야 합니다.
* 이벤트 ID를 기록해야 합니다. 예를 들어 "'p-SDT-clus1-nod-6982'"를 기록해야 합니다.
* Unified Manager에서 성능 데이터를 한 달 이상 수집 및 분석해야 합니다.




== 이 작업에 대해

이 절차를 사용하면 고성능 워크로드를 사용률이 낮은 노드로 이동할 수 있도록 다음 리소스를 식별할 수 있습니다.

* 동일한 클러스터에 있는 노드 중 사용 가능한 성능 용량이 가장 큰 노드
* 새 노드의 aggregate에서 사용 가능한 성능 용량이 가장 많습니다
* 현재 노드에서 가장 높은 성능을 보이는 볼륨입니다




== 단계

. 사용 가능한 성능 용량이 가장 큰 클러스터 노드를 식별합니다.
+
.. 이벤트 세부 정보 * 페이지에서 노드가 상주하는 클러스터의 이름을 클릭합니다.
+
클러스터 세부 정보가 성능/클러스터 랜딩 페이지에 표시됩니다.

.. 요약 * 탭의 * 관리 개체 * 창에서 * 노드 * 를 클릭합니다.
+
이 클러스터의 노드 목록이 표시됩니다.

.. Performance Capacity Used * 열을 클릭하여 사용된 최소 비율별로 노드를 정렬합니다.
+
이 목록에는 워크로드를 이동할 수 있는 잠재적 노드 목록이 나와 있습니다.

.. 워크로드를 이동할 노드의 이름을 기록합니다.


. 가장 활용도가 낮은 새 노드의 애그리게이트 식별:
+
.. 왼쪽 탐색 창에서 * 성능 * > * 집계 * 를 클릭합니다.
+
성능/집계 페이지가 표시됩니다.

.. 필터링 * 을 클릭하고 왼쪽 드롭다운 메뉴에서 * 노드 * 를 선택한 다음 텍스트 필드에 노드 이름을 입력하고 * 필터 적용 * 을 클릭합니다.
+
성능/애그리게이트 페이지는 이 노드에서 사용할 수 있는 애그리게이트 목록과 함께 다시 표시됩니다.

.. Performance Capacity Used * 열을 클릭하여 가장 적게 사용된 순서대로 애그리게이트를 정렬합니다.
+
다음은 워크로드를 이동할 수 있는 잠재적 애그리게이트 목록입니다.

.. 워크로드를 이동할 애그리게이트의 이름을 기록합니다.


. 이벤트를 수신한 노드에서 고성능 워크로드 파악:
+
.. 이벤트의 * 이벤트 세부 정보 * 페이지로 돌아갑니다.
.. 영향을 받는 볼륨 * 필드에서 볼륨 수에 대한 링크를 클릭합니다.
+
성능/볼륨 페이지는 해당 노드에 있는 볼륨의 필터링된 목록과 함께 표시됩니다.

.. Total Capacity * 열을 클릭하여 할당된 최대 공간으로 볼륨을 정렬합니다.
+
이동할 수 있는 잠재적 볼륨 목록이 표시됩니다.

.. 이동할 볼륨의 이름과 해당 볼륨이 있는 현재 애그리게이트의 이름을 기록합니다.


. 새 노드에서 최대 가용 성능 용량이 있는 것으로 확인된 애그리게이트로 볼륨을 이동합니다.
+
OnCommand 시스템 관리자, OnCommand Workflow Automation, ONTAP 명령 또는 이러한 툴의 조합을 사용하여 이동 작업을 수행할 수 있습니다.





== 작업을 마친 후

며칠 후 이 노드나 집합으로부터 동일한 유형의 이벤트를 받고 있는지 확인할 수 있습니다.
