---
permalink: online-help/task-exporting-storage-data-as-reports.html 
sidebar: sidebar 
keywords:  
summary: '데이터를 쉼표로 구분된 값 \(.csv\) 파일로 내보내고 내보낸 데이터를 사용하여 보고서를 작성할 수 있습니다. 예를 들어 해결되지 않은 10개의 중요 이벤트가 있는 경우 이벤트 인벤토리 페이지에서 데이터를 내보내서 보고서를 만든 다음 적절한 조치를 취할 수 있습니다.' 
---
= 보고를 위해 CSV 파일로 데이터를 내보내는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터를 쉼표로 구분된 값으로 내보낼 수 있습니다 (`.csv`) 파일을 생성하고 내보낸 데이터를 사용하여 보고서를 작성합니다. 예를 들어 해결되지 않은 10개의 중요 이벤트가 있는 경우 이벤트 인벤토리 페이지에서 데이터를 내보내서 보고서를 만든 다음 적절한 조치를 취할 수 있습니다.



== 시작하기 전에

운영자, OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.



== 이 작업에 대해

데이터를 로 내보낼 수 있습니다 `.csv` 상태 및 성능 인벤토리 페이지와 이벤트 인벤토리 페이지에서 파일을 가져옵니다.

무한 확장 볼륨의 구성요소에 대해서는 엑스포트 기능이 지원되지 않습니다. -- 구성요소에 대한 세부 정보를 로 내보낼 수 없습니다 `.csv` 파일.



== 단계

. 다음 작업 중 하나를 수행합니다.
+
|===
| 내보내려는 경우... | 수행할 작업... 


 a| 
이벤트 세부 정보
 a| 
이벤트 * 를 클릭합니다.



 a| 
스토리지 객체 인벤토리 세부 정보입니다
 a| 
왼쪽 탐색 메뉴에서 * 상태 * 또는 * 성능 * 을 클릭한 다음 스토리지 객체를 선택합니다.



 a| 
스토리지 용량 및 보호 기록 세부 정보
 a| 
상태 * > * 애그리게이트 * 또는 * 상태 * > * 볼륨 * 을 클릭한 다음 단일 애그리게이트 또는 볼륨을 선택합니다.



 a| 
Qtree 또는 NFS에서는 SVM에 대한 정보를 내보냅니다
 a| 
상태 * > * SVM * 을 클릭하고 단일 SVM을 선택한 다음 * qtree * 또는 * NFS 엑스포트 * 탭을 선택합니다.



 a| 
스토리지 객체 10가지 성능 세부 정보
 a| 
성능 * > * 클러스터 * 를 클릭한 다음 클러스터를 선택하고 * 우수 성과 * 탭을 선택합니다. 그런 다음 스토리지 오브젝트 및 성능 카운터를 선택합니다.

|===
. 내보내기 * 버튼을 클릭합니다.
. 내보내기 요청을 확인하려면 * CSV로 내보내기 * 를 클릭합니다.
+
Top Performers 탭과 SVM 세부 정보 페이지에서 보고 있는 단일 클러스터 또는 데이터 센터의 모든 클러스터에 대한 통계 보고서를 다운로드할 수 있습니다.

+
파일이 다운로드됩니다.

. 를 엽니다 `.csv` 파일을 선택합니다.

