---
permalink: online-help/task-excluding-disaster-recovery-destination-volumes-from-generating-alerts.html 
sidebar: sidebar 
keywords:  
summary: 볼륨 경고를 구성할 때 경고 대화 상자에서 볼륨 또는 볼륨 그룹을 식별하는 문자열을 지정할 수 있습니다. 그러나 SVM에 대한 재해 복구를 구성했다면 소스 볼륨과 타겟 볼륨의 이름이 동일하므로 두 볼륨에 대한 알림이 제공됩니다. 
---
= 알림 생성에서 재해 복구 대상 볼륨 제외
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨 경고를 구성할 때 경고 대화 상자에서 볼륨 또는 볼륨 그룹을 식별하는 문자열을 지정할 수 있습니다. 그러나 SVM에 대한 재해 복구를 구성했다면 소스 볼륨과 타겟 볼륨의 이름이 동일하므로 두 볼륨에 대한 알림이 제공됩니다.



== 시작하기 전에

OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.



== 이 작업에 대해

대상 SVM의 이름이 인 볼륨을 제외하고 재해 복구 대상 볼륨에 대한 알림을 비활성화할 수 있습니다. 볼륨 이벤트의 식별자에는 SVM 이름과 볼륨 이름이 ""<svm_name>:/<volume_name>"" 형식으로 포함되어 있으므로 이러한 ID가 가능합니다.

아래 예에서는 1차 SVM ""VS1""에서 볼륨 ""vol1""에 대한 경고를 생성하는 방법을 보여 주지만 SVM ""VS1-DR""에서 이름이 같은 볼륨에서 알림이 생성되지 않도록 합니다.

경고 추가 대화 상자에서 다음 단계를 수행합니다.



== 단계

. 이름 * 을 클릭하고 알림의 이름과 설명을 입력합니다.
. 리소스 * 를 클릭한 다음 * 포함 * 탭을 선택합니다.
+
.. 드롭다운 목록에서 * Volume * 을 선택한 다음 를 입력합니다 `vol1` 이름에 ""vol1"이 포함된 볼륨을 표시하기 위한 * * 포함 * 필드에서.
.. 를 선택합니다<<All Volumes whose name contains 'vol1'>>* Available Resources * 영역에서 * Selected Resources * 영역으로 이동합니다.


. Exclude * (제외 *) 탭을 선택하고 * Volume * (볼륨 *)을 선택한 후 를 입력합니다 `vs1-dr` 이름 포함 * 필드에서 * 추가 * 를 클릭합니다.
+
SVM ""VS1-DR""에서 볼륨 ""vol1""에 대한 알림이 생성되지 않습니다.

. Events * 를 클릭하고 볼륨에 적용할 이벤트 또는 이벤트를 선택합니다.
. Actions * 를 클릭한 다음 * Alert these users * 필드에서 경고 이메일을 수신할 사용자의 이름을 선택합니다.
. SNMP 트랩을 실행하고 스크립트를 실행하도록 이 페이지의 다른 옵션을 구성한 다음 * 저장 * 을 클릭합니다.

