---
permalink: online-help/task-viewing-event-details-in-the-performance-explorer-events-timeline.html 
sidebar: sidebar 
keywords:  
summary: 성능 탐색기의 이벤트 일정 창에서 모든 이벤트와 관련 세부 정보를 볼 수 있습니다. 이 방법은 지정된 시간 범위 동안 루트 개체에서 발생한 모든 상태 및 성능 이벤트를 빠르고 효율적으로 보는 방법으로 성능 문제를 해결할 때 유용할 수 있습니다. 
---
= 이벤트 타임라인에서 이벤트 세부 정보 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능 탐색기의 이벤트 일정 창에서 모든 이벤트와 관련 세부 정보를 볼 수 있습니다. 이 방법은 지정된 시간 범위 동안 루트 개체에서 발생한 모든 상태 및 성능 이벤트를 빠르고 효율적으로 보는 방법으로 성능 문제를 해결할 때 유용할 수 있습니다.



== 이 작업에 대해

이벤트 타임라인 창에는 선택한 시간 범위 동안 루트 개체에서 발생한 중요, 오류, 경고 및 정보 이벤트가 표시됩니다. 각 이벤트 심각도에는 고유한 타임라인이 있습니다. 단일 및 여러 이벤트는 시각표에서 이벤트 점으로 표시됩니다. 이벤트 점 위에 커서를 놓으면 이벤트 세부 정보를 볼 수 있습니다. 여러 이벤트의 시각적 세분화를 높이려면 시간 범위를 줄일 수 있습니다. 이렇게 하면 여러 이벤트가 단일 이벤트로 분산되므로 각 이벤트를 별도로 보고 조사할 수 있습니다.

이벤트 시각표의 각 성능 이벤트 점은 이벤트 타임라인 아래에 표시되는 카운터 차트 추세선의 해당 급증을 사용하여 세로로 배열됩니다. 따라서 이벤트와 전체 성능 간에 직접적인 시각적 상관 관계가 형성됩니다. 상태 이벤트는 타임라인에도 표시되지만 이러한 유형의 이벤트가 성능 차트 중 하나에서 급증한 것과 반드시 일치하지는 않습니다.



== 단계

. 이벤트 시각표 * 창에서 타임라인의 이벤트 점 위에 커서를 놓으면 해당 이벤트 지점의 이벤트 또는 이벤트 요약을 볼 수 있습니다.
+
팝업 대화 상자에는 이벤트 유형, 이벤트가 발생한 날짜 및 시간, 상태 및 이벤트 기간에 대한 정보가 표시됩니다.

. 하나의 이벤트 또는 여러 이벤트에 대한 전체 이벤트 세부 정보 보기:
+
|===
| 수행할 작업... | 이... 


 a| 
단일 이벤트에 대한 세부 정보를 봅니다
 a| 
* 팝업 대화 상자에서 이벤트 세부 정보 * 를 봅니다.



 a| 
여러 이벤트에 대한 세부 정보를 봅니다
 a| 
* 팝업 대화 상자에서 이벤트 세부 정보 * 를 봅니다.

[NOTE]
====
다중 이벤트 대화 상자에서 단일 이벤트를 클릭하면 해당 이벤트 세부 정보 페이지가 표시됩니다.

====
|===

