---
permalink: online-help/task-disabling-unwanted-events.html 
sidebar: sidebar 
keywords:  
summary: 모든 이벤트는 기본적으로 활성화됩니다. 사용자 환경에서 중요하지 않은 이벤트에 대한 알림이 발생하지 않도록 이벤트를 전역적으로 비활성화할 수 있습니다. 알림 수신을 다시 시작하려는 경우 비활성화된 이벤트를 활성화할 수 있습니다. 
---
= 이벤트 비활성화 또는 활성화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모든 이벤트는 기본적으로 활성화됩니다. 사용자 환경에서 중요하지 않은 이벤트에 대한 알림이 발생하지 않도록 이벤트를 전역적으로 비활성화할 수 있습니다. 알림 수신을 다시 시작하려는 경우 비활성화된 이벤트를 활성화할 수 있습니다.



== 시작하기 전에

OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.



== 이 작업에 대해

이벤트를 사용하지 않도록 설정하면 시스템에서 이전에 생성된 이벤트가 사용되지 않는 것으로 표시되고 이러한 이벤트에 대해 구성된 알림이 트리거되지 않습니다. 비활성화된 이벤트를 활성화하면 다음 모니터링 주기부터 이러한 이벤트에 대한 알림이 생성됩니다.

개체에 대한 이벤트를 사용하지 않도록 설정하는 경우(예: `vol offline` 이벤트). 그런 다음 나중에 이벤트를 활성화해도 Unified Manager는 이벤트가 비활성 상태일 때 오프라인 상태가 된 개체에 대한 새 이벤트를 생성하지 않습니다. Unified Manager는 이벤트가 다시 활성화된 후 오브젝트 상태가 변경된 경우에만 새 이벤트를 생성합니다.



== 단계

. 왼쪽 탐색 창에서 * 구성 * > * 이벤트 관리 * 를 클릭합니다.
. 구성/이벤트 관리 * 페이지에서 다음 옵션 중 하나를 선택하여 이벤트를 비활성화하거나 활성화합니다.
+
|===
| 원하는 작업 | 다음을 수행하십시오. 


 a| 
이벤트를 비활성화합니다
 a| 
.. 비활성화 * 를 클릭합니다.
.. 이벤트 사용 안 함 대화 상자에서 이벤트 심각도를 선택합니다.
.. 이벤트 일치 열에서 이벤트 심각도에 따라 비활성화할 이벤트를 선택한 다음 오른쪽 화살표를 클릭하여 해당 이벤트를 이벤트 사용 안 함 열로 이동합니다.
.. 저장 후 닫기 * 를 클릭합니다.
.. 비활성화된 이벤트가 구성/이벤트 관리 페이지의 목록 보기에 표시되는지 확인합니다.




 a| 
이벤트 활성화
 a| 
.. 활성화할 이벤트 또는 이벤트의 확인란을 선택합니다.
.. 사용 * 을 클릭합니다.


|===

