---
permalink: online-help/task-restoring-a-mysql-database-backup-on-windows.html 
sidebar: sidebar 
keywords:  
summary: 데이터 손실 또는 데이터 손상이 발생할 경우 복원 기능을 사용하여 최소한의 손실로 Unified Manager를 이전의 안정적인 상태로 복원할 수 있습니다. restore 명령을 사용하여 Unified Manager 데이터베이스를 로컬 Windows 시스템 또는 원격 Windows 시스템으로 복원할 수 있습니다. 
---
= Windows에서 데이터베이스 백업을 복원합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 손실 또는 데이터 손상이 발생할 경우 복원 기능을 사용하여 최소한의 손실로 Unified Manager를 이전의 안정적인 상태로 복원할 수 있습니다. restore 명령을 사용하여 Unified Manager 데이터베이스를 로컬 Windows 시스템 또는 원격 Windows 시스템으로 복원할 수 있습니다.



== 시작하기 전에

* 서버에 Unified Manager가 설치되어 있어야 합니다.
* Windows 관리자 권한이 있어야 합니다.
* Unified Manager 백업 파일과 데이터베이스 저장소 디렉터리의 내용을 복구 작업을 수행할 시스템에 복사해야 합니다.
+
백업 파일을 기본 디렉토리에 복사하는 것이 좋습니다 `\ProgramData\NetApp\OnCommandAppData\ocum\backup`. 데이터베이스 리포지토리 파일을 에 복사해야 합니다 `\database_dumps_repo` 하위 디렉토리 아래에 있습니다 `\backup` 디렉토리.

* 백업 파일은 이어야 합니다 `.7z` 유형.




== 이 작업에 대해

복원 기능은 플랫폼별 및 버전에 따라 다릅니다. Unified Manager 백업은 동일한 Unified Manager 버전에서만 복원할 수 있고 Windows 백업은 Windows 플랫폼에서만 복원할 수 있습니다.

[TIP]
====
폴더 이름에 공백이 포함된 경우 백업 파일의 절대 경로 또는 상대 경로를 큰따옴표로 묶어야 합니다.

====


== 단계

. 새 서버로 복원을 수행하는 경우 Unified Manager를 설치한 후 설치가 완료될 때 UI를 실행하거나 클러스터, 사용자 또는 인증 설정을 구성하지 마십시오. 백업 파일은 복원 프로세스 중에 이 정보를 채웁니다.
. Unified Manager 콘솔에 관리자로 로그인합니다. `um cli login -u maint_username`
. 명령 프롬프트에서 백업을 복원합니다. `um backup restore -f <backup_file_path>/<backup_file_name>`
+
`um backup restore -f \ProgramData\NetApp\OnCommandAppData\ocum\backup\UM_9.4.N151118.2300_backup_windows_02-20-2018-02-51.7z`





== 작업을 마친 후

복원 작업이 완료되면 Unified Manager에 로그인할 수 있습니다.
