---
permalink: online-help/task-creating-storage-virtual-machine-svm-associations.html 
sidebar: sidebar 
keywords:  
summary: '스토리지 가상 시스템 연결 생성 마법사를 사용하면 파트너 보호 애플리케이션에서 소스 스토리지 가상 시스템 \(SVM\)을 타겟 SVM과 연결하여 SnapMirror 및 SnapVault 관계에 사용할 수 있습니다. 파트너 애플리케이션은 대상 볼륨의 초기 프로비저닝 시 이러한 연결을 사용하여 선택할 리소스를 결정합니다.' 
---
= SVM 연결 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 가상 시스템 연결 생성 마법사를 사용하면 파트너 보호 애플리케이션에서 소스 스토리지 가상 시스템(SVM)을 타겟 SVM과 연결하여 SnapMirror 및 SnapVault 관계에 사용할 수 있습니다. 파트너 애플리케이션은 대상 볼륨의 초기 프로비저닝 시 이러한 연결을 사용하여 선택할 리소스를 결정합니다.



== 시작하기 전에

* 연결하려는 SVM이 이미 존재해야 합니다.
* OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.




== 이 작업에 대해

모든 소스 SVM 및 관계 유형의 경우 각 타겟 클러스터에서 하나의 대상 SVM만 선택할 수 있습니다.

삭제 및 생성 기능을 사용하여 연결을 변경하면 이후 프로비저닝 작업에만 영향을 줍니다. 기존 타겟 볼륨은 이동하지 않습니다.



== 단계

. 왼쪽 탐색 창에서 * 보호 * > * SVM 협회 * 를 클릭합니다.
. Protection/Storage Virtual Machine Associations * 페이지에서 * Create * 를 클릭합니다.
+
스토리지 가상 머신 연결 생성 마법사가 시작됩니다.

. 다음 소스 중 하나를 선택합니다.
+
** * 모두 *
+
1차 SVM 소스에서 하나 이상의 대상 SVM으로 연결을 생성하려는 경우 이 옵션을 선택합니다. 즉, 향후에 생성된 SVM뿐만 아니라 현재 보호가 필요한 모든 기존 SVM이 지정된 대상 SVM과 연계됩니다. 예를 들어, 서로 다른 위치에 있는 여러 소스의 애플리케이션을 한 위치의 하나 이상의 대상 SVM에 백업할 수 있습니다.

** * 단일 *
+
하나 이상의 타겟 SVM과 연결된 특정 소스 SVM을 선택하려면 이 옵션을 선택하십시오. 예를 들어, 데이터가 서로 분리되어 있어야 하는 여러 클라이언트에 스토리지 서비스를 제공하는 경우 이 옵션을 선택하여 특정 SVM 소스를 해당 클라이언트에만 할당된 특정 SVM 타겟에 연계합니다.

** * 없음(외부) *
+
소스 SVM과 타겟 SVM의 유연한 외부 볼륨 간의 연결을 생성하려는 경우 이 옵션을 선택합니다.



. 생성할 보호 관계 유형 중 하나 또는 둘 모두를 선택합니다.
+
** * SnapMirror *
** * SnapVault *


. 다음 * 을 클릭합니다.
. 하나 이상의 SVM 보호 대상을 선택합니다.
. 마침 * 을 클릭합니다.

