---
permalink: online-help/task-creating-user-defined-performance-threshold-policies.html 
sidebar: sidebar 
keywords:  
summary: 성능 카운터가 특정 값을 초과할 때 알림이 전송되도록 스토리지 객체에 대한 성능 임계값 정책을 생성합니다. 이벤트 알림에서 클러스터에 성능 문제가 발생한 것을 확인할 수 있습니다. 
---
= 사용자 정의 성능 임계값 정책 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능 카운터가 특정 값을 초과할 때 알림이 전송되도록 스토리지 객체에 대한 성능 임계값 정책을 생성합니다. 이벤트 알림에서 클러스터에 성능 문제가 발생한 것을 확인할 수 있습니다.



== 시작하기 전에

OnCommand 관리자 역할이 있어야 합니다.



== 이 작업에 대해

임계값 정책 생성 페이지에서 임계값을 입력하여 성능 임계값 정책을 생성합니다. 이 페이지의 모든 정책 값을 정의하여 새 정책을 생성하거나 기존 정책의 복사본을 만들고 복사본의 값(_cloning_)을 변경할 수 있습니다.

유효한 임계값은 숫자로 0.001에서 10,000,000 사이, 백분율의 경우 0.001에서 100 사이, 사용된 성능 용량의 백분율 값은 0.001에서 200 사이입니다.

[NOTE]
====
현재 릴리즈에서는 카운터 값이 임계값 설정을 초과할 때 이벤트를 전송하는 임계값을 제공합니다. 카운터 값이 임계값 설정 아래로 떨어지면 이벤트를 전송하는 임계값을 설정할 수 없습니다.

====


== 단계

. 왼쪽 탐색 창에서 * 구성 * > * 성능 임계값 * 을 선택합니다.
+
구성/성능 임계값 페이지가 표시됩니다.

. 새 정책을 구축할지 또는 비슷한 정책을 클론 복제하고 클론 복제된 버전을 수정할지 여부에 따라 적절한 버튼을 클릭합니다.
+
|===
| 대상... | 클릭... 


 a| 
새 정책을 생성합니다
 a| 
* 생성 *



 a| 
기존 정책의 클론을 생성합니다
 a| 
기존 정책을 선택하고 * Clone * 을 클릭합니다

|===
+
임계값 정책 생성 페이지 또는 클론 임계값 정책 페이지가 표시됩니다.

. 특정 스토리지 개체에 설정할 성능 카운터 임계값을 지정하여 임계값 정책을 정의합니다.
+
.. 스토리지 객체 유형을 선택하고 정책의 이름과 설명을 지정합니다.
.. 추적할 성능 카운터를 선택하고 Warning 및 Critical 이벤트를 정의하는 제한 값을 지정합니다.
+
최소한 하나의 경고 또는 하나의 위험 한도를 정의해야 합니다. 두 가지 제한 유형을 모두 정의할 필요는 없습니다.

.. 필요한 경우 보조 성능 카운터를 선택하고 Warning 및 Critical 이벤트에 대한 제한 값을 지정합니다.
+
보조 카운터를 포함하면 두 카운터가 모두 임계값을 위반하고 이벤트가 보고되기 전에 제한 값을 초과해야 합니다. 조합 정책을 사용하여 특정 개체 및 카운터만 구성할 수 있습니다.

.. 이벤트를 전송하기 위해 제한 값을 위반해야 하는 기간을 선택합니다.


+
기존 정책을 복제할 때 정책의 새 이름을 입력해야 합니다.

. 저장 * 을 클릭하여 정책을 저장합니다.
+
구성/성능 임계값 페이지로 돌아갑니다. 페이지 맨 위에 있는 성공 메시지는 임계값 정책이 생성되었음을 확인하고 스토리지 개체에 새 정책을 즉시 적용할 수 있도록 해당 개체 유형에 대한 인벤토리 페이지에 대한 링크를 제공합니다.





== 작업을 마친 후

현재 스토리지 객체에 새 임계값 정책을 적용하려면 * Go to object_type now * 링크를 클릭하여 인벤토리 페이지로 이동할 수 있습니다.
