---
permalink: online-help/task-creating-a-snapmirror-protection-relationship-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: 상태/볼륨 세부 정보 페이지를 사용하여 보호 목적으로 데이터 복제를 사용하도록 SnapMirror 관계를 만들 수 있습니다. SnapMirror 복제를 사용하면 소스의 데이터 손실 발생 시 대상 볼륨에서 데이터를 복원할 수 있습니다. 
---
= 상태/볼륨 세부 정보 페이지에서 SnapMirror 보호 관계 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
상태/볼륨 세부 정보 페이지를 사용하여 보호 목적으로 데이터 복제를 사용하도록 SnapMirror 관계를 만들 수 있습니다. SnapMirror 복제를 사용하면 소스의 데이터 손실 발생 시 대상 볼륨에서 데이터를 복원할 수 있습니다.



== 시작하기 전에

* OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* Workflow Automation을 설정해야 합니다.




== 이 작업에 대해

다음과 같은 경우에는 * Protect * 메뉴가 표시되지 않습니다.

* RBAC 설정에서 이 작업을 허용하지 않는 경우(예: 운영자 권한만 있는 경우
* 볼륨이 FlexGroup 볼륨인 경우
* 볼륨 ID를 알 수 없는 경우(예: 인터클러스터 관계가 있고 대상 클러스터가 아직 검색되지 않은 경우


성능에 영향을 주지 않고 최대 10개의 보호 작업을 동시에 수행할 수 있습니다. 11 ~ 30개의 작업을 동시에 실행할 경우 성능에 약간의 영향을 줄 수 있습니다. 30개 이상의 작업을 동시에 실행하는 것은 권장되지 않습니다.



== 단계

. 상태/볼륨 * 세부 정보 페이지의 * 보호 * 탭에서 보호할 볼륨의 이름을 마우스 오른쪽 버튼으로 토폴로지 뷰에서 클릭합니다.
. 메뉴에서 * 보호 * > * SnapMirror * 를 선택합니다.
+
보호 구성 대화 상자가 표시됩니다.

. SnapMirror * 탭을 보고 대상 정보를 구성하려면 * SnapMirror * 를 클릭합니다.
. 필요에 따라 * 고급 * 을 클릭하여 공간 보장을 설정한 다음 * 적용 * 을 클릭합니다.
. 보호 구성 * 대화 상자에서 * 대상 정보 * 영역과 * 관계 설정 * 영역을 완료합니다.
. 적용 * 을 클릭합니다.
+
상태/볼륨 세부 정보 페이지로 돌아갑니다.

. 상태/볼륨 * 세부 정보 페이지 상단의 보호 구성 작업 링크를 클릭합니다.
+
작업의 작업과 세부 정보가 보호/작업 세부 정보 페이지에 표시됩니다.

. 보호/작업 * 세부 정보 페이지에서 * 새로 고침 * 을 클릭하여 보호 구성 작업과 관련된 작업 목록 및 작업 세부 정보를 업데이트하고 작업 완료 시기를 결정합니다.
. 작업 작업이 완료되면 브라우저에서 * Back * 을 클릭하여 * Health/Volume * 세부 정보 페이지로 돌아갑니다.
+
새 관계가 상태/볼륨 세부 정보 페이지 토폴로지 보기에 표시됩니다.





== 결과

구성 중에 지정한 대상 SVM에 따라, 고급 설정에서 지정한 옵션에 따라 SnapMirror 관계가 달라질 수 있습니다.

* 소스 볼륨과 동일한 버전 또는 최신 버전의 ONTAP에서 실행되는 타겟 SVM을 지정한 경우 블록 복제 기반 SnapMirror 관계가 기본 결과입니다.
* 소스 볼륨과 동일한 버전 또는 최신 버전의 ONTAP(버전 8.3 이상)에서 실행되는 타겟 SVM을 지정했지만 고급 설정에서 버전에 상관없이 유연한 복제를 사용하도록 설정한 경우, 버전에 상관없이 유연한 복제를 사용하는 SnapMirror 관계가 됩니다.
* 이전 버전의 ONTAP 8.3에서 실행되는 대상 SVM이나 이전 버전의 소스 볼륨보다 더 높은 버전을 사용하여 유연한 복제를 지원하는 경우에는 버전에 상관없이 유연한 복제를 사용하는 SnapMirror 관계가 자동으로 이루어집니다.

