---
permalink: online-help/task-responding-to-a-system-defined-node-resources-overutilized-performance-event.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager에서는 단일 노드가 운영 효율성 한계를 초과하여 작동하고 워크로드 지연 시간에 영향을 줄 수 있는 경우 노드 리소스가 과도하게 사용되는 경고 이벤트를 생성합니다. 많은 워크로드가 지연 시간의 영향을 받기 전에 이러한 시스템 정의 이벤트를 통해 잠재적 성능 문제를 해결할 수 있습니다. 
---
= 노드 리소스가 과도하게 사용된 성능 이벤트에 응답
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager에서는 단일 노드가 운영 효율성 한계를 초과하여 작동하고 워크로드 지연 시간에 영향을 줄 수 있는 경우 노드 리소스가 과도하게 사용되는 경고 이벤트를 생성합니다. 많은 워크로드가 지연 시간의 영향을 받기 전에 이러한 시스템 정의 이벤트를 통해 잠재적 성능 문제를 해결할 수 있습니다.



== 시작하기 전에

* 운영자, OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 새 성능 이벤트 또는 사용되지 않는 성능 이벤트가 있어야 합니다.




== 이 작업에 대해

Unified Manager에서는 성능 용량의 100% 이상을 30분 이상 사용하는 노드를 찾으므로 노드 리소스가 과도하게 사용된 정책 위반에 대한 경고 이벤트를 생성합니다.

System Manager 또는 ONTAP 명령을 사용하여 다음 작업을 포함하여 이러한 유형의 성능 문제를 해결할 수 있습니다.

* 시스템 리소스를 과도하게 사용하는 볼륨 또는 LUN에 QoS 정책 생성 및 적용
* 워크로드가 적용된 정책 그룹의 QoS 최대 처리량 제한을 줄입니다
* 워크로드를 다른 Aggregate 또는 노드로 이동
* 노드에 디스크를 추가하거나 더 빠른 CPU와 더 많은 RAM이 있는 노드로 업그레이드하여 용량을 늘릴 수 있습니다




== 단계

. 이벤트에 대한 정보를 보려면 * 이벤트 * 세부 정보 페이지를 표시합니다.
. 이벤트를 발생시킨 임계값 위반을 설명하는 * Description * 을 검토합니다.
+
예를 들어, ""Perf. Simplicity-02의 139%의 Capacity Used Value는 데이터 처리 유닛에서 발생 가능한 성능 문제를 파악하기 위한 경고 이벤트를 발생시켰습니다.""노드 심플리시티-02의 성능 용량이 과도하게 사용되고 노드 성능에 영향을 미친다는 것을 나타냅니다.

. System Diagnosis * 섹션에서 노드에 사용된 성능 용량에 대한 차트 1개, 최상위 워크로드에 사용되는 평균 스토리지 IOPS에 대한 차트 1개, 상위 워크로드의 지연 시간에 대한 차트 1개를 검토합니다. 이렇게 정렬하면 노드에서 지연 시간의 원인이 되는 워크로드를 확인할 수 있습니다.
+
IOPS 차트 위로 커서를 이동하면 QoS 정책이 적용된 워크로드와 적용되지 않는 워크로드를 확인할 수 있습니다.

. 제안 조치 * 섹션에서 제안 사항을 검토하고 작업 부하 대기 시간의 증가를 방지하기 위해 수행해야 할 조치를 결정합니다.
+
필요한 경우 * 도움말 * 버튼을 클릭하여 성능 이벤트 해결을 위해 수행할 수 있는 권장 조치에 대한 자세한 내용을 확인하십시오.


