---
permalink: qsg-windows.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, Windows QSG, quick installation, Windows installer 
summary: Linux 플랫폼의 Unified Manager에 대한 빠른 시작 가이드 
---
= Windows 설치를 위한 빠른 시작 지침
:allow-uri-read: 




== 시스템 요구 사항

* 운영 체제: Microsoft Windows Server 2012, 2012 R2 및 2016 64비트 Standard 및 Datacenter Edition
* RAM: 12GB
* CPU: 총 9572MHz
* 사용 가능한 디스크 공간: 설치 디렉토리를 위한 100GB 디스크 공간, MySQL 데이터 디렉토리를 위한 50GB의 디스크 공간


시스템 요구 사항에 대한 자세한 내용은 을 참조하십시오 link:install/reference-windows-software-and-installation-requirements.html["Windows 소프트웨어 및 설치 요구 사항"] 및 link:http://mysupport.netapp.com/matrix["상호 운용성 매트릭스"].



== OnCommand Unified Manager 설치 중



=== 설치 프로그램을 다운로드합니다

. 를 다운로드합니다 `OnCommandUnifiedManager-9.5RC1.exes` 설치 패키지.
. 설치 파일을 대상 시스템의 디렉토리에 복사합니다.




=== Unified Manager를 설치합니다

Microsoft .NET 4.5.2 이상이 설치되어 있어야 합니다. Unified Manager는 설치 과정에서 다른 필수 타사 패키지를 설치합니다. 종속 소프트웨어 패키지에 대한 자세한 내용은 를 참조하십시오 link:install/concept-installing-upgrading-and-removing-unified-manager-software.html["Windows에서 Unified Manager 소프트웨어 설치, 업그레이드 및 제거"].

. 기본 로컬 관리자 계정을 사용하여 Windows에 로그인합니다.
. 설치 파일을 다운로드한 디렉토리에서 마우스 오른쪽 버튼을 클릭하여 Unified Manager 실행 파일(.exe)을 관리자로 실행합니다.
. 메시지가 표시되면 사용자 이름과 암호를 입력하여 Unified Manager 유지보수 사용자를 생성합니다.
. 데이터베이스 연결 마법사에서 MySQL 루트 암호를 입력합니다.
. 나머지 메시지에 따라 설치를 완료합니다.
. 설치가 끝나면 * Finish * 를 클릭하면 Unified Manager 웹 UI가 표시됩니다.

