---
permalink: qsg-linux.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, Linux QSG, RHEL QSG, quick installation 
summary: Linux 플랫폼의 Unified Manager에 대한 빠른 시작 가이드 
---
= Linux 설치를 위한 빠른 시작 지침
:allow-uri-read: 




== 시스템 요구 사항

* 운영 체제: Red Hat Enterprise Linux 또는 CentOS 64비트 버전 7.x 아키텍처, OS 설치 프로그램의 소프트웨어 선택 옵션에서 "GUI가 있는 서버" 기본 환경을 사용하여 설치
* RAM: 12GB
* CPU: 총 9572MHz
* 사용 가능한 디스크 공간: /opt의 경우 100GB, 루트 파티션의 경우 50GB


시스템 요구 사항에 대한 자세한 내용은 을 참조하십시오 link:install/reference-red-hat-and-centos-software-and-installation-requirements.html["Red Hat Enterprise Linux 및 CentOS 소프트웨어 및 설치 요구 사항"] 및 link:http://mysupport.netapp.com/matrix["상호 운용성 매트릭스"].



== OnCommand Unified Manager 설치 중



=== 설치 프로그램을 다운로드합니다

. 를 다운로드합니다 `OnCommandUnifiedManager-rhel7-9.5RC1.zip` 설치 패키지.
. 설치 파일을 다운로드한 디렉토리에서 다음을 실행합니다.
+
`# unzip OnCommandUnifiedManager-rhel7-9.5RC1.zip`





=== 리포지토리 구성을 확인합니다

Red Hat Enterprise Linux 또는 CentOS 리포지토리를 구성하는 절차는 사이트에 따라 다릅니다. 설치 패키지에 포함된 pre_install_check.sh 스크립트를 사용하여 운영 체제가 올바르게 구성되었는지 확인할 수 있습니다. 시스템이 인터넷에 연결되어 있는 경우 Red Hat Enterprise Linux 및 MySQL 리포지토리를 설정하는 지침이 자동으로 제공됩니다. 인터넷에 연결되지 않은 시스템에 를 설치하는 방법에 대한 자세한 내용은 을 참조하십시오 link:install/concept-install-upgrade-and-remove-unified-manager-software.html["Red Hat 또는 CentOS에서 Unified Manager 소프트웨어 설치, 업그레이드 및 제거"].

`# ./pre_install_check.sh`



=== Unified Manager를 설치합니다

Unified Manager에서는 를 사용합니다 `yum` 소프트웨어 및 종속 소프트웨어를 설치하는 유틸리티입니다. 여러 조직에서 Red Hat Enterprise Linux 또는 CentOS의 이미지가 다양하기 때문에 설치된 패키지는 이미지에 있는 소프트웨어에 따라 다릅니다. 를 클릭합니다 `yum` 유틸리티는 설치할 종속 소프트웨어 패키지를 결정합니다. 종속 소프트웨어 패키지에 대한 자세한 내용은 를 참조하십시오 link:install/concept-install-upgrade-and-remove-unified-manager-software.html["Red Hat 또는 CentOS에서 Unified Manager 소프트웨어 설치, 업그레이드 및 제거"].

루트 사용자 또는 sudo를 사용하여 설치 파일의 압축이 풀린 디렉토리에서 다음 명령을 실행합니다.

`# yum install *.rpm`

또는

`% sudo yum install *.rpms`

설치가 끝나면 Unified Manager 웹 UI에 연결할 정보가 표시됩니다. 웹 UI에 연결할 수 없는 경우 포트 443을 화이트리스트해야 할 수 있습니다. 자세한 내용은 기술 지원 팀에 문의하십시오.
