---
permalink: performance-checker/concept-understanding-the-um-recommendations-to-tier-data-to-the-cloud.html 
sidebar: sidebar 
keywords:  
summary: '성능/볼륨 인벤토리 페이지에는 비활성 상태인 볼륨에 저장된 사용자 데이터의 크기와 관련된 정보가 표시됩니다. 경우에 따라 Unified Manager에서 FabricPool 지원 애그리게이트의 클라우드 계층(클라우드 공급자 또는 StorageGRID\)에 비활성 데이터를 계층화함으로써 이점이 있는 특정 볼륨을 식별합니다.' 
---
= 데이터를 클라우드에 계층화하도록 Unified Manager의 권장 사항 이해
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능/볼륨 인벤토리 페이지에는 비활성(콜드) 볼륨에 저장된 사용자 데이터의 크기와 관련된 정보가 표시됩니다. 경우에 따라 Unified Manager에서 FabricPool 지원 애그리게이트의 클라우드 계층(클라우드 공급자 또는 StorageGRID)에 비활성 데이터를 계층화함으로써 이점을 얻을 수 있는 특정 볼륨을 식별합니다.

[NOTE]
====
FabricPool는 ONTAP 9.2에서 소개된 것으로, ONTAP 소프트웨어 9.2 이전 버전을 사용하는 경우 데이터를 계층화하려면 ONTAP 소프트웨어를 업그레이드해야 하는 Unified Manager의 권장사항이 됩니다. 또한 `auto` 계층화 정책은 ONTAP 9.4에 도입되었으며 따라서 을 사용하는 것이 좋습니다 `auto` 계층화 정책을 사용하려면 ONTAP 9.4 이상으로 업그레이드해야 합니다.

====
성능/볼륨 인벤토리 페이지에 있는 다음 세 개의 필드에서는 비활성 데이터를 클라우드 계층으로 이동하여 스토리지 시스템의 디스크 사용률을 높이고 성능 계층의 공간을 절약할 수 있는지 여부에 대한 정보를 제공합니다.

* * 계층화 정책 *
+
계층화 정책은 볼륨의 데이터가 성능 계층에 유지되는지 또는 일부 데이터가 성능 계층에서 클라우드 계층으로 이동되는지 여부를 결정합니다.

+
이 필드의 값은 볼륨이 현재 FabricPool 애그리게이트에 없는 경우에도 볼륨에 설정된 계층화 정책을 나타냅니다. 계층화 정책은 볼륨이 FabricPool 애그리게이트에 있는 경우에만 적용됩니다.

* * 콜드 데이터 *
+
콜드 데이터는 비활성(콜드) 상태인 볼륨에 저장된 사용자 데이터의 크기를 표시합니다.

+
ONTAP 9.4 이상 소프트웨어를 사용하는 경우에만 여기에 값이 표시됩니다. 볼륨을 배포하는 데 사용되는 애그리게이트에 가 있어야 하기 때문입니다 `inactive data reporting` 매개 변수를 로 설정합니다 `enabled`, 및 을 사용하는 볼륨의 경우 최소 냉각 일 임계값 이 충족되었습니다 `snapshot-only` 또는 `auto` 계층화 정책 참조). 그렇지 않으면 값이 ""N/A""로 표시됩니다.

* * 클라우드 권장사항 *
+
볼륨의 데이터 활동에 대한 정보가 충분히 수집되면 Unified Manager에서 아무런 조치가 필요하지 않는지, 아니면 비활성 데이터를 클라우드 계층으로 계층화하여 성능 계층의 공간을 절약할 수 있는지 확인할 수 있습니다.



[NOTE]
====
콜드 데이터 필드는 15분마다 업데이트되지만, 콜드 데이터 분석이 볼륨에 대해 수행되는 7일마다 클라우드 권장 사항 필드가 업데이트됩니다. 따라서 필드 간에 정확한 양의 콜드 데이터가 다를 수 있습니다. 클라우드 권장 사항 필드에는 분석이 실행된 날짜가 표시됩니다.

====
비활성 데이터 보고가 활성화되면 Cold Data(콜드 데이터) 필드에 정확한 양의 비활성 데이터가 표시됩니다. 비활성 데이터 보고 기능이 없으면 Unified Manager는 성능 통계를 사용하여 데이터가 볼륨에 비활성 상태인지 확인합니다. 이 경우 비활성 데이터의 양은 Cold Data(콜드 데이터) 필드에 표시되지 않지만, 커서를 * Tier * 라는 단어 위로 가져가면 클라우드 권장 사항을 볼 수 있습니다.

다음과 같은 클라우드 권장 사항이 표시됩니다.

* * 학습 *. 권장 사항을 만들 데이터가 충분하지 않습니다.
* * 계층 *. 분석 결과, 볼륨에 비활성(콜드) 데이터가 포함되어 있고 해당 데이터를 클라우드 계층으로 이동하도록 볼륨을 구성해야 합니다. 경우에 따라 먼저 볼륨을 FabricPool 지원 애그리게이트로 이동해야 할 수 있습니다. 볼륨이 이미 FabricPool 애그리게이트에 있는 경우에는 계층화 정책만 변경하면 됩니다.
* * 작업 없음 *. 볼륨에 비활성 데이터가 거의 없거나 FabricPool 애그리게이트에 "자동" 계층화 정책으로 이미 설정되어 있거나 볼륨이 데이터 보호 볼륨입니다. 이 값은 볼륨이 오프라인이거나 MetroCluster 구성에서 사용 중일 때도 표시됩니다.


볼륨을 이동하거나 볼륨 계층화 정책 또는 애그리게이트 비활성 데이터 보고 설정을 변경하려면 OnCommand System Manager, ONTAP CLI 명령 또는 이러한 툴의 조합을 사용합니다.

OnCommand 관리자 또는 스토리지 관리자 역할로 Unified Manager에 로그인한 경우, * 계층 * 이라는 단어 위에 커서를 올리면 클라우드 권장 사항에서 * 볼륨 구성 * 링크를 사용할 수 있습니다. 이 버튼을 클릭하여 System Manager에서 Volumes 페이지를 열어 권장 사항을 변경합니다.
