---
permalink: performance-checker/concept-understanding-counter-charts.html 
sidebar: sidebar 
keywords:  
summary: 카운터 차트 창의 차트를 사용하면 루트 개체 및 상호 연결된 개체 표에서 추가한 개체의 성능 데이터를 보고 비교할 수 있습니다. 이를 통해 성능 추세를 파악하고 성능 문제를 격리 및 해결할 수 있습니다. 
---
= 카운터 차트 이해
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
카운터 차트 창의 차트를 사용하면 루트 개체 및 상호 연결된 개체 표에서 추가한 개체의 성능 데이터를 보고 비교할 수 있습니다. 이를 통해 성능 추세를 파악하고 성능 문제를 격리 및 해결할 수 있습니다.

기본적으로 표시되는 카운터 차트는 이벤트, 지연 시간, IOPS 및 MBPS입니다. 활용도, 사용된 성능 용량, 사용 가능한 IOPS, IOPS/TB 및 캐시 비적중 비율 중에서 선택할 수 있는 옵션 차트입니다. 또한 지연 시간, IOPS, MBps 및 사용된 성능 용량 차트에 대한 총 값 또는 분석 값을 표시하도록 선택할 수 있습니다.

성능 탐색기에는 스토리지 개체에서 해당 카운터 차트를 모두 지원하는지 여부와 같은 특정 카운터 차트가 기본적으로 표시됩니다. 카운터가 지원되지 않으면 카운터 차트가 비어 있고 메시지가 표시됩니다 `Not applicable for <object>` 가 표시됩니다.

차트는 비교 창에서 선택한 모든 개체와 루트 개체의 성능 추세를 표시합니다. 각 차트의 데이터는 다음과 같이 정렬됩니다.

* * X 축 *
+
지정된 기간을 표시합니다. 시간 범위를 지정하지 않은 경우 기본값은 이전 72시간 기간입니다.

* * Y 축 *
+
선택한 오브젝트 또는 오브젝트에 고유한 카운터 단위를 표시합니다.



추세 선 색상은 비교 창에 표시된 개체 이름의 색상과 일치합니다. 추세 선 위에 커서를 놓으면 해당 지점에 대한 시간 및 값에 대한 세부 정보를 볼 수 있습니다.

차트 내의 특정 기간을 조사하려면 다음 방법 중 하나를 사용합니다.

* 카운터 차트 창을 확장하여 페이지 너비를 넓히려면 * < * 버튼을 사용합니다.
* 커서를 사용하여(돋보기로 전환 시) 차트에서 해당 영역에 초점을 맞추고 확대할 기간을 선택합니다. 차트 확대/축소 원래대로를 클릭하여 차트를 기본 시간 값으로 되돌릴 수 있습니다.
* 확대/축소 보기 * 버튼을 사용하면 확장된 세부 정보와 임계값 표시기가 포함된 큰 단일 카운터 차트를 표시할 수 있습니다.


[NOTE]
====
때때로 추세선의 간격이 표시됩니다. 격차의 경우 Unified Manager가 스토리지 시스템에서 성능 데이터를 수집하지 못했거나 Unified Manager가 중단되었을 수 있습니다.

====