---
permalink: performance-checker/concept-types-of-workloads-monitored-by-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager를 사용하여 사용자 정의 워크로드와 시스템 정의라는 두 가지 유형의 워크로드의 성능을 모니터링할 수 있습니다. 
---
= Unified Manager에서 모니터링하는 워크로드의 유형입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 사용하여 사용자 정의 워크로드와 시스템 정의라는 두 가지 유형의 워크로드의 성능을 모니터링할 수 있습니다.

* * _ 사용자 정의 워크로드 _ *
+
애플리케이션에서 클러스터로 I/O 처리량 이러한 프로세스는 읽기 및 쓰기 요청과 관련된 프로세스입니다. FlexVol 볼륨 또는 FlexGroup 볼륨은 사용자 정의 워크로드입니다.

+
[NOTE]
====
Unified Manager는 클러스터의 워크로드 활동만 모니터링합니다. 애플리케이션, 클라이언트 또는 애플리케이션과 클러스터 간의 경로는 모니터링하지 않습니다.

====
+
다음 중 하나 이상이 워크로드에 대해 참인 경우 Unified Manager에서 모니터링할 수 없습니다.

+
** 읽기 전용 모드의 데이터 보호(DP) 복사본입니다. (ONTAP 8.3 이상을 사용하는 경우 DP 볼륨에서 사용자 생성 트래픽을 모니터링합니다.)
** 무한 확장 볼륨입니다.
** 오프라인 데이터 클론입니다.
** MetroCluster 구성에서 미러링된 볼륨입니다.


* *_시스템 정의 워크로드_ *
+
다음을 비롯하여 스토리지 효율성, 데이터 복제 및 시스템 상태와 관련된 내부 프로세스:

+
** 중복 제거와 같은 스토리지 효율성
** RAID 재구성, 디스크 스크러빙 등을 포함하는 디스크 상태
** SnapMirror 복사본과 같은 데이터 복제 기능을 제공합니다
** 관리 활동
** 다양한 WAFL 작업을 포함하는 파일 시스템 상태입니다
** WAFL 스캔과 같은 파일 시스템 스캐너입니다
** 오프로드 스토리지 효율성 작업을 VMware 호스트에서 수행하는 등의 복제 오프로드
** 볼륨 이동, 데이터 압축 등과 같은 시스템 상태입니다
** 모니터링되지 않은 볼륨




시스템 정의 워크로드의 성능 데이터는 해당 워크로드에서 사용되는 클러스터 구성 요소의 경합이 발생한 경우에만 GUI에 표시됩니다. 예를 들어, GUI에서 성능 데이터를 보기 위해 시스템 정의 워크로드의 이름을 검색할 수 없습니다. 같은 유형의 시스템 정의 워크로드가 여러 개 표시되면 워크로드 이름에 문자가 추가됩니다. 이 서신은 지원 담당자가 사용하도록 제작되었습니다.
