---
permalink: performance-checker/concept-collecting-data-and-monitoring-workload-performance.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager는 5분마다 워크로드 작업을 수집 및 분석하여 성능 이벤트를 식별하고, 15분마다 구성 변경을 감지합니다. 이 기능은 5분 동안의 기간별 성능 및 이벤트 데이터를 최대 30일까지 유지하며 이 데이터를 사용하여 모니터링되는 모든 워크로드에 대해 예측 가능한 범위를 예측합니다. 
---
= 데이터 수집 및 워크로드 성능 모니터링
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager는 5분마다 워크로드 작업을 수집 및 분석하여 성능 이벤트를 식별하고, 15분마다 구성 변경을 감지합니다. 이 기능은 5분 동안의 기간별 성능 및 이벤트 데이터를 최대 30일까지 유지하며 이 데이터를 사용하여 모니터링되는 모든 워크로드에 대해 예측 가능한 범위를 예측합니다.

[NOTE]
====
이 장에서는 동적 임계값의 작동 방식과 이러한 임계값을 사용하여 작업 부하 성능을 모니터링하는 방법에 대해 설명합니다. 이 장은 사용자 정의 또는 시스템 정의 성능 임계값 위반으로 인한 통계 또는 이벤트에는 적용되지 않습니다.

====
Unified Manager에서 분석을 시작하려면 최소 3일간의 워크로드 활동을 수집해야 하며, 이에 따라 입출력 응답 시간 및 작업의 예상 범위가 성능/볼륨 세부 정보 페이지와 이벤트 세부 정보 페이지에 표시될 수 있습니다. 이 활동이 수집되는 동안 예상 범위에 워크로드 활동에서 발생하는 모든 변경 사항이 표시되지 않습니다. Unified Manager는 3일간의 활동을 수집한 후 24시간마다 오전 12시에 예상 범위를 조정하여 워크로드 활동 변경사항을 반영하고 보다 정확한 성능 임계값을 설정합니다.

Unified Manager가 볼륨을 모니터링하는 처음 4일 동안 마지막 데이터 수집 이후 24시간이 지난 경우 성능/볼륨 세부 정보 페이지의 차트에 해당 볼륨의 예상 범위가 표시되지 않습니다. 마지막 컬렉션 이전에 감지된 이벤트는 계속 사용할 수 있습니다.

[NOTE]
====
DST(일광 절약 시간)는 시스템 시간을 변경하여 모니터링되는 작업 부하에 대한 예상 성능 통계 범위를 변경합니다. Unified Manager가 즉시 예상 범위를 수정하기 시작하는데, 완료까지 약 15일이 걸립니다. 이때 Unified Manager를 계속 사용할 수 있지만 Unified Manager에서 이벤트를 감지하는 데 예상 범위가 사용되므로 일부 이벤트는 정확하지 않을 수 있습니다. 시간 변경 전에 감지된 이벤트는 영향을 받지 않습니다. 클러스터 또는 Unified Manager 서버에서 시간을 수동으로 변경하면 이벤트 분석 결과에도 영향을 줍니다.

====