---
permalink: performance-checker/concept-roles-of-workloads-involved-in-a-performance-incident.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager에서는 역할을 사용하여 성능 이벤트에서 워크로드가 어떻게 관여하는지 파악합니다. 희생자, 폭리, 상어 등의 역할을 합니다. 사용자 정의 워크로드는 동시에 피해자이고 괴롭히는 상어가 될 수 있습니다. 
---
= 성능 이벤트와 관련된 워크로드의 역할
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager에서는 역할을 사용하여 성능 이벤트에서 워크로드가 어떻게 관여하는지 파악합니다. 희생자, 폭리, 상어 등의 역할을 합니다. 사용자 정의 워크로드는 동시에 피해자이고 괴롭히는 상어가 될 수 있습니다.

|===
| 역할 | 설명 


 a| 
피해자
 a| 
클러스터 구성 요소를 과도하게 사용하는 bullies라는 다른 워크로드로 인해 성능이 저하된 사용자 정의 워크로드 사용자 정의 워크로드만 피해자로 식별됩니다. Unified Manager는 이벤트 중에 실제 지연 시간이 예상 지연 시간 범위에서 크게 늘어난 지연 시간 차이를 기준으로 피해자의 워크로드를 식별합니다.



 a| 
괴롭습니다
 a| 
클러스터 구성 요소를 과도하게 사용하여 피해자라고 하는 다른 워크로드의 성능을 저하시킨 사용자 정의 또는 시스템 정의 워크로드입니다. Unified Manager에서는 클러스터 구성 요소의 사용 편차에 따라 대규모 워크로드를 식별하며, 이벤트 중에는 예상 사용 범위에서 실제 사용량이 크게 증가했습니다.



 a| 
상어
 a| 
이벤트에 관여하는 모든 워크로드에 비해 클러스터 구성 요소를 가장 많이 사용하는 사용자 정의 워크로드입니다. Unified Manager에서는 이벤트 중에 클러스터 구성 요소를 사용하여 shark 워크로드를 식별합니다.

|===
클러스터의 워크로드는 네트워크 및 데이터 처리를 위한 스토리지 애그리게이트 및 CPU와 같은 여러 클러스터 구성 요소를 공유할 수 있습니다. 볼륨과 같은 워크로드가 클러스터 구성 요소의 사용량을 구성 요소가 워크로드 수요를 효율적으로 충족할 수 없는 시점으로 증가하면 구성 요소의 경합이 발생합니다. 클러스터 구성 요소를 과도하게 사용하는 워크로드는 부담스러운 워크로드와 이러한 구성 요소를 공유하며 성능에 큰 영향을 미치는 다른 워크로드는 이 피해자들입니다. 중복 제거 또는 Snapshot 복사본과 같은 시스템 정의 워크로드의 작업도 ""불링""으로 에스컬레이션될 수 있습니다.

Unified Manager에서 이벤트를 감지하면 해당 이벤트를 발생시킨 대규모 워크로드, 경합하는 클러스터 구성 요소, 워크로드가 폭증하여 성능이 저하된 워크로드를 비롯하여 관련된 모든 워크로드와 클러스터 구성 요소를 파악합니다.

[NOTE]
====
Unified Manager에서 대규모 워크로드를 식별할 수 없는 경우 피해자 워크로드와 관련된 클러스터 구성 요소에 대한 알림만 제공됩니다.

====
Unified Manager를 사용하면 워크로드가 불룩한 경우 이를 식별하고 동일한 워크로드가 불룩한 워크로드가 되는 시기를 파악할 수 있습니다. 워크로드는 그 자체로 부담스러운 것이 될 수 있습니다. 예를 들어, 정책 그룹 제한으로 인해 성능이 높은 워크로드의 임계치가 조절되면 정책 그룹의 모든 워크로드가 그 자체를 포함하여 제한됩니다. 지속적인 성과 이벤트의 피해자 또는 괴롭히는 워크로드는 역할을 변경하거나 더 이상 이벤트에 참가하지 않을 수 있습니다. 성능/볼륨 세부 정보 페이지의 이벤트 목록 테이블에서 선택한 볼륨이 참가자 역할을 변경하면 역할 변경 날짜와 시간이 표시됩니다.
