---
permalink: performance-checker/reference-performance-data-that-can-be-sent-to-an-external-server.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager는 모니터링 하는 모든 클러스터에서 다양한 성능 데이터를 수집합니다. 특정 데이터 그룹을 외부 서버로 보낼 수 있습니다. 
---
= 외부 서버로 보낼 수 있는 성능 데이터
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager는 모니터링 하는 모든 클러스터에서 다양한 성능 데이터를 수집합니다. 특정 데이터 그룹을 외부 서버로 보낼 수 있습니다.

차트로 작성할 성능 데이터에 따라 다음 통계 그룹 중 하나를 보내도록 선택할 수 있습니다.

|===
| 통계 그룹 | 데이터 포함 | 세부 정보 


 a| 
성능 모니터
 a| 
다음 객체에 대한 높은 수준의 성능 통계:

* LUN을 클릭합니다
* 볼륨

 a| 
이 그룹은 모니터링되는 모든 클러스터의 모든 LUN 및 볼륨에 대해 총 IOPS 또는 지연 시간을 제공합니다.

이 그룹은 가장 적은 수의 통계를 제공합니다.



 a| 
리소스 활용률
 a| 
다음 객체에 대한 리소스 활용도 통계:

* 노드
* 애그리게이트

 a| 
이 그룹은 모니터링되는 모든 클러스터에서 노드에 대한 활용도 통계를 제공하고 물리적 리소스를 집계합니다.

또한 성능 모니터 그룹에서 수집된 통계도 제공합니다.



 a| 
드릴다운
 a| 
추적된 모든 객체에 대해 낮은 레벨의 읽기/쓰기 및 프로토콜별 통계:

* 노드
* 애그리게이트
* LUN을 클릭합니다
* 볼륨
* 디스크
* LIF
* 포트/NIC

 a| 
이 그룹은 모니터링되는 모든 클러스터에서 추적된 7개의 객체 유형 모두에 대해 읽기/쓰기 및 프로토콜별 분석 기능을 제공합니다.

또한 Performance Monitor 그룹과 Resource Utilization 그룹에서 수집된 통계도 제공합니다.

이 그룹은 가장 많은 수의 통계를 제공합니다.

|===
[NOTE]
====
스토리지 시스템에서 클러스터 또는 클러스터 객체의 이름이 변경되면 기존 객체와 새 객체 모두 외부 서버("metric_path"라고 함)의 성능 데이터를 포함합니다. 두 오브젝트는 동일한 오브젝트와 연관되지 않습니다. 예를 들어, 볼륨 이름을 ""volume1_acct"에서 ""acct_vol1""로 변경하면 이전 볼륨에 대한 이전 성능 데이터와 새 볼륨에 대한 새 성능 데이터가 표시됩니다.

====
외부 데이터 공급자에 보낼 수 있는 모든 성능 카운터 목록은 기술 자료 문서를 참조하십시오.

https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Infrastructure_Management%2FActive_IQ_Unified_Manager%2FWhat_are_the_ActiveIQ_Unified_Manager_performance_counters_that_can_be_exported_to_an_External_Data_Provider%253F["Unified Manager 성능 카운터를 외부 데이터 공급자로 내보낼 수 있습니다"]
