---
permalink: performance-checker/reference-performance-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: 이 페이지에서는 선택한 FlexVol 볼륨, FlexGroup 볼륨 또는 FlexGroup 구성요소 워크로드에 대한 모든 I/O 활동 및 작업에 대한 자세한 성능 통계를 제공합니다. 볼륨에 대한 통계 및 이벤트를 볼 특정 기간을 선택할 수 있습니다. 이 이벤트는 I/O 성능에 영향을 줄 수 있는 성능 이벤트 및 변경 사항을 식별합니다. 
---
= 성능/볼륨 세부 정보 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 페이지에서는 선택한 FlexVol 볼륨, FlexGroup 볼륨 또는 FlexGroup 구성요소 워크로드에 대한 모든 I/O 활동 및 작업에 대한 자세한 성능 통계를 제공합니다. 볼륨에 대한 통계 및 이벤트를 볼 특정 기간을 선택할 수 있습니다. 이 이벤트는 I/O 성능에 영향을 줄 수 있는 성능 이벤트 및 변경 사항을 식별합니다.



== 기록 데이터 차트

선택한 볼륨에 대한 성능 분석 기록 데이터를 플롯합니다. 슬라이더를 클릭하고 끌어 시간 프레임을 지정할 수 있습니다. 슬라이더는 시간 프레임 창을 증가 및 감소시킵니다. 기간 창 밖의 데이터는 회색으로 표시됩니다. 차트 아래쪽에 있는 슬라이더를 사용하여 기록 데이터 간에 시간 프레임 창을 이동할 수 있습니다. 표시된 차트 및 이벤트를 포함한 전체 페이지는 기간 창 내에서 사용할 수 있는 데이터를 반영합니다. Unified Manager는 이 페이지에 최대 30일간의 기간별 데이터를 보존합니다.

[NOTE]
====
기록 데이터 차트에서 화면 해상도에 따라 1일 이상의 기간을 선택하면 차트에 응답 시간 및 IOPS의 최대값이 일 수에 걸쳐 표시됩니다.

====


== 옵션

* * 시간 선택기 *
+
전체 페이지에 대한 볼륨 성능 통계를 볼 시간 범위를 지정합니다. 1일(* 1d *) ~ 30일(* 30d *) 또는 * 사용자 정의 * 를 클릭하여 사용자 정의 범위를 선택할 수 있습니다. 사용자 지정 범위의 경우 시작 및 종료 날짜를 선택한 다음 * 업데이트 * 를 클릭하여 전체 페이지를 업데이트할 수 있습니다.

+
[NOTE]
====
이벤트 세부 정보 페이지에서 볼륨의 이름 링크를 클릭하여 성능/볼륨 세부 정보 페이지에 액세스하면 기본적으로 현재 날짜 1일 또는 5일 전과 같은 시간 범위가 자동으로 선택됩니다. 기록 데이터 차트에서 슬라이더를 이동하면 시간 범위가 사용자 지정 범위로 변경되지만 * 사용자 지정 * 시간 선택기는 선택되지 않습니다. 기본 시간 선택기는 선택된 상태로 유지됩니다.

====
* *** 데이터 분리 기준 ***
+
선택한 볼륨에 대한 보다 자세한 성능 통계를 표시하기 위해 성능/볼륨 세부 정보 페이지에 추가할 수 있는 차트 목록을 제공합니다.


