---
permalink: performance-checker/reference-components-of-the-node-failover-planning-page.html 
sidebar: sidebar 
keywords:  
summary: 성능/노드 장애 조치 계획 페이지의 구성 요소는 그리드 및 비교 창에 표시됩니다. 이 섹션에서는 노드 페일오버가 테이크오버 노드의 성능에 미치는 영향을 평가할 수 있습니다. 
---
= 노드 장애 조치 계획 페이지의 구성 요소입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능/노드 장애 조치 계획 페이지의 구성 요소는 그리드 및 비교 창에 표시됩니다. 이 섹션에서는 노드 페일오버가 테이크오버 노드의 성능에 미치는 영향을 평가할 수 있습니다.



== 성능 통계 그리드

성능/노드 장애 조치 계획 페이지에는 지연 시간, IOPS, 활용도 및 사용된 성능 용량에 대한 통계가 포함된 그리드가 표시됩니다.

[NOTE]
====
이 페이지와 성능/노드 성능 탐색기 페이지에 표시되는 IOPS 값이 동일하지 않을 수 있습니다.

====
그리드에서 각 노드에는 다음 역할 중 하나가 할당됩니다.

* 기본
+
파트너가 장애가 발생할 경우 HA 파트너에게 인계되는 노드입니다. 루트 개체는 항상 기본 노드입니다.

* 파트너
+
페일오버 시나리오에서 장애가 발생한 노드입니다.

* 예상 인수
+
운영 노드와 동일합니다. 이 노드에 대해 표시되는 성능 통계는 장애가 발생한 파트너가 테이크오버한 후 테이크오버 노드의 성능을 보여줍니다.



[NOTE]
====
테이크오버 노드의 워크로드는 페일오버 후 두 노드의 결합된 워크로드와 동일하나, 예상 테이크오버에 대한 통계는 운영 노드와 파트너 노드의 통계를 합하지 않습니다. 예를 들어 운영 노드의 지연 시간이 2ms/op 이고 파트너 노드의 지연 시간이 3ms/op인 경우 예상 테이크오버의 지연 시간은 4ms/opp일 수 있습니다. 이 값은 Unified Manager에서 수행하는 계산입니다.

====
파트너 노드의 이름을 클릭하여 루트 객체가 되도록 할 수 있습니다. 성능/노드 성능 탐색기 페이지가 표시되면 * 장애 조치 계획 * 탭을 클릭하여 이 노드 장애 시나리오에서 성능이 어떻게 변경되는지 확인할 수 있습니다. 예를 들어, Node1이 기본 노드이고 Node2가 파트너 노드인 경우 Node2를 클릭하여 기본 노드로 설정할 수 있습니다. 이렇게 하면 장애가 발생한 노드에 따라 예상 성능이 어떻게 변경되는지 확인할 수 있습니다.



== 비교 창

다음 목록에서는 기본적으로 비교 창에 표시되는 구성 요소에 대해 설명합니다.

* * 이벤트 차트 *
+
성능/노드 성능 탐색기 페이지의 형식과 동일한 형식으로 표시됩니다. 운영 노드에만 해당됩니다.

* * 카운터 차트 *
+
이 표에는 그리드에 표시된 성능 카운터에 대한 기간별 통계가 표시됩니다. 각 차트에서 예상 테이크오버에 대한 그래프는 특정 시간에 페일오버가 발생한 경우의 예상 성능을 보여 줍니다.

+
예를 들어, Utilization 차트가 오전 11시에 예상 테이크오버에 대해 73%를 표시한다고 가정해 보겠습니다 2월 8일. 해당 시점에 페일오버가 발생한 경우 테이크오버 노드의 활용률은 73%였습니다.

+
기간별 통계를 사용하면 페일오버를 시작할 최적의 시간을 찾아 테이크오버 노드의 오버로드 가능성을 최소화할 수 있습니다. 테이크오버 노드의 예상 성능이 허용되는 경우에만 페일오버를 예약할 수 있습니다.



기본적으로 루트 객체와 파트너 노드에 대한 통계가 비교 창에 표시됩니다. 성능/노드 성능 탐색기 페이지와 달리 이 페이지에는 통계 비교를 위해 객체를 추가할 수 있는 * 추가 * 버튼이 표시되지 않습니다.

성능/노드 성능 탐색기 페이지에서 수행하는 것과 동일한 방식으로 비교 창을 사용자 지정할 수 있습니다. 다음 목록에서는 차트를 사용자 지정하는 예를 보여 줍니다.

* 노드 이름을 클릭하여 카운터 차트에서 노드의 통계를 표시하거나 숨깁니다.
* 확대/축소 보기 * 를 클릭하여 새 창에 특정 카운터에 대한 세부 차트를 표시합니다.

