---
permalink: performance-checker/reference-performance-statistics-displayed-in-the-data-breakdown-charts.html 
sidebar: sidebar 
keywords:  
summary: 그래프를 사용하여 볼륨의 성능 추세를 볼 수 있습니다. 또한 읽기 및 쓰기 통계, 네트워크 프로토콜 작업, QoS 정책 그룹이 지연 시간에 미치는 영향, 캐시 스토리지에 대한 읽기 및 쓰기 비율, 워크로드에서 사용하는 총 클러스터 CPU 시간 및 특정 클러스터 구성 요소를 볼 수 있습니다. 
---
= 성능 통계는 데이터 분석 차트에 표시됩니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그래프를 사용하여 볼륨의 성능 추세를 볼 수 있습니다. 또한 읽기 및 쓰기 통계, 네트워크 프로토콜 작업, QoS 정책 그룹이 지연 시간에 미치는 영향, 캐시 스토리지에 대한 읽기 및 쓰기 비율, 워크로드에서 사용하는 총 클러스터 CPU 시간 및 특정 클러스터 구성 요소를 볼 수 있습니다.

이 보기는 현재 날짜의 최대 30일 동안의 통계를 표시합니다. 기록 데이터 차트에서 화면 해상도에 따라 1일 이상의 기간을 선택하면 차트에 지연 시간 및 IOPS의 최대값이 일 수에 걸쳐 표시됩니다.

[NOTE]
====
나열된 모든 차트 옵션을 선택하거나 선택을 취소하려면 * 모두 선택 * 확인란을 사용할 수 있습니다.

====
* * 지연 시간 *
+
다음 차트는 선택한 워크로드에 대한 지연 시간 또는 응답 시간 정보를 상세히 보여 줍니다.

+
** * 클러스터 구성 요소 *
+
선택한 볼륨에서 사용되는 각 클러스터 구성 요소에 사용된 시간의 그래프를 표시합니다.

+
이 차트를 통해 각 구성 요소가 총 지연 시간과 관련하여 지연 시간에 미치는 영향을 파악할 수 있습니다. 각 부품 옆의 확인란을 사용하여 그래프를 표시하거나 숨길 수 있습니다.

+
QoS 정책 그룹의 경우 사용자 정의 정책 그룹에 대해서만 데이터가 표시됩니다. 기본 정책 그룹과 같은 시스템 정의 정책 그룹에 대해 0이 표시됩니다.

** * 읽기/쓰기 지연 시간 *
+
선택한 기간 동안 선택한 볼륨 워크로드의 성공적인 읽기 및 쓰기 요청 지연 시간 그래프를 표시합니다.

+
쓰기 요청은 주황색 줄이며 읽기 요청은 파란색 선입니다. 요청은 클러스터의 모든 워크로드가 아니라 선택한 볼륨 워크로드의 지연 시간에 따라 다릅니다.

+
[NOTE]
====
읽기 및 쓰기 통계가 지연 시간 차트에 표시되는 총 지연 시간 통계에 항상 추가되는 것은 아닙니다. 이는 Unified Manager가 워크로드에 대한 읽기 및 쓰기 통계를 수집하고 분석하는 방식을 기준으로 예상한 동작입니다.

====
** * 정책 그룹 영향 *
+
QoS 정책 그룹의 처리량 제한에 영향을 받은 선택한 볼륨 워크로드의 지연 시간 비율을 보여주는 그래프를 표시합니다.

+
워크로드가 임계치를 조절하면 특정 시점에 임계치 조절이 지연 시간에 얼마나 영향을 주었는지 백분율로 표시됩니다. 백분율 값은 임계치 조절 정도를 나타냅니다.

+
*** 0% = 임계치 조절 없음
*** > 0% = 임계치 조절
*** > 20% = 임계치 조절 클러스터에서 더 많은 작업을 처리할 수 있는 경우 정책 그룹 제한을 늘려 임계치 조절을 줄일 수 있습니다. 또 다른 옵션은 워크로드를 사용량이 적은 Aggregate로 이동하는 것입니다.




+
[NOTE]
====
이 차트는 처리량 제한이 설정된 사용자 정의 QoS 정책 그룹의 워크로드에 대해서만 표시됩니다. 워크로드가 기본 정책 그룹 같은 시스템 정의 정책 그룹에 속하는지 또는 QoS 제한이 없는 정책 그룹에 속하는지 표시하지 않습니다. QoS 정책 그룹의 경우 커서를 정책 그룹 이름에 지정하여 처리량 제한과 마지막으로 수정한 시간을 표시할 수 있습니다. 연결된 클러스터를 Unified Manager에 추가하기 전에 정책 그룹을 수정한 경우, 마지막으로 수정한 시간은 Unified Manager가 클러스터를 처음 검색한 날짜와 시간입니다.

====
* IOPS *
+
다음 차트는 선택한 워크로드에 대한 IOPS 데이터를 상세하게 보여 줍니다.

+
** * 읽기/쓰기/기타 *
+
선택한 기간 동안 초당 읽기 및 쓰기 IOPS 수와 기타 IOPS의 수를 보여 주는 그래프를 표시합니다.

+
기타 IOPS는 클라이언트가 읽기 또는 쓰기가 아닌 프로토콜 작업입니다. 예를 들어 NFS 환경에서는 GetAttr, SetAttr 또는 fsstat 같은 메타데이터 작업이 될 수 있습니다. CIFS 환경에서는 속성 조회, 디렉토리 목록 또는 바이러스 백신 검사가 될 수 있습니다. 쓰기 IOPS는 주황색 선으로, 읽기 요청은 파란색 선으로 표시됩니다. 요청은 클러스터의 모든 작업이 아니라 선택한 볼륨 워크로드에 대한 모든 작업에 적용됩니다.



* Mbps *
+
다음 차트는 선택한 워크로드에 대한 처리량 데이터를 상세히 보여 줍니다.

+
** * 캐시 적중률 *
+
선택한 기간 동안 캐시에서 처리된 클라이언트 애플리케이션의 읽기 요청 백분율 그래프를 표시합니다.

+
Flash Cache 카드 또는 Flash Pool 애그리게이트의 SSD(Solid State Drive)에 캐시가 사용될 수 있습니다. 캐시 적중은 캐시에서 읽혀집니다. 주황색 캐시 누락은 애그리게이트의 디스크에서 읽은 상태입니다. 요청은 클러스터의 모든 워크로드가 아니라 선택한 볼륨 워크로드에 따라 다릅니다.

+
볼륨 캐시 사용에 대한 자세한 내용은 Unified Manager 상태 페이지 및 OnCommand System Manager에서 확인할 수 있습니다.



* * 구성 요소 *
+
다음 차트는 선택한 워크로드에서 사용하는 클러스터 구성 요소별 데이터를 상세하게 보여 줍니다.

+
** * 클러스터 CPU 시간 *
+
선택한 워크로드에서 사용하는 클러스터의 모든 노드에 대한 CPU 사용 시간(ms) 그래프를 표시합니다.

+
그래프에는 네트워크 처리 및 데이터 처리를 위한 총 CPU 사용 시간이 표시됩니다. 선택한 워크로드에 연결되어 있으며 데이터 처리에 동일한 노드를 사용 중인 시스템 정의 워크로드에 대한 CPU 시간도 포함됩니다. 이 차트를 사용하여 워크로드가 클러스터의 CPU 리소스가 많이 소비되는지 여부를 확인할 수 있습니다. 또한 지연 시간 차트 아래의 읽기/쓰기 지연 시간 차트 또는 IOPS 차트 아래의 읽기/쓰기/기타 차트와 함께 차트를 사용하여 시간에 따른 워크로드 활동의 변경이 클러스터 CPU 활용도에 미치는 영향을 파악할 수 있습니다.

** * 디스크 활용률 *
+
선택한 기간 동안 스토리지 애그리게이트의 데이터 디스크 활용률 백분율을 보여 주는 그래프가 표시됩니다.

+
활용률에는 선택한 볼륨 워크로드의 디스크 읽기 및 쓰기 요청만 포함됩니다. 캐시의 읽기는 포함되지 않습니다. 활용률은 디스크의 일부 워크로드가 아니라 선택한 볼륨 워크로드에 따라 다릅니다. 모니터링되는 볼륨이 볼륨 이동에 참여하는 경우 이 차트의 활용률 값은 볼륨이 이동되는 타겟 애그리게이트에 대한 것입니다.




