---
permalink: performance-checker/task-adding-alerts-for-performance-events.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager에서 수신한 다른 이벤트처럼 개별 성능 이벤트에 대한 알림을 구성할 수 있습니다. 또한 모든 성능 이벤트를 동일하게 처리하고 동일한 사용자에게 이메일을 전송하려는 경우, 중요한 이벤트 또는 경고 성능 이벤트가 트리거될 때 단일 알림을 생성할 수 있습니다. 
---
= 성능 이벤트에 대한 알림 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager에서 수신한 다른 이벤트처럼 개별 성능 이벤트에 대한 알림을 구성할 수 있습니다. 또한 모든 성능 이벤트를 동일하게 처리하고 동일한 사용자에게 이메일을 전송하려는 경우, 중요한 이벤트 또는 경고 성능 이벤트가 트리거될 때 단일 알림을 생성할 수 있습니다.



== 시작하기 전에

OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.



== 이 작업에 대해

아래 예는 모든 중요한 지연 시간, IOPS 및 MBPS 이벤트에 대한 이벤트를 생성하는 방법을 보여줍니다. 이 동일한 방법을 사용하여 모든 성능 카운터와 모든 경고 이벤트에서 이벤트를 선택할 수 있습니다.



== 단계

. 왼쪽 탐색 창에서 * 구성 * > * 알림 * 을 클릭합니다.
. 구성/경고 * 페이지에서 * 추가 * 를 클릭합니다.
. 경고 추가 * 대화 상자에서 * 이름 * 을 클릭하고 경고의 이름과 설명을 입력합니다.
. 리소스 * 페이지에서 리소스를 선택하지 마십시오.
+
리소스를 선택하지 않으면 모든 클러스터, 애그리게이트, 볼륨 등에 경고가 적용되고 해당 이벤트가 수신됩니다.

. 이벤트 * 를 클릭하고 다음 작업을 수행합니다.
+
.. 이벤트 심각도 목록에서 * 긴급 * 을 선택합니다.
.. 이벤트 이름 포함 필드에 를 입력합니다 `latency` 그런 다음 화살표를 클릭하여 일치하는 모든 이벤트를 선택합니다.
.. 이벤트 이름 포함 필드에 를 입력합니다 `iops` 그런 다음 화살표를 클릭하여 일치하는 모든 이벤트를 선택합니다.
.. 이벤트 이름 포함 필드에 를 입력합니다 `mbps` 그런 다음 화살표를 클릭하여 일치하는 모든 이벤트를 선택합니다.


. Actions * 를 클릭한 다음 * Alert these users * 필드에서 경고 이메일을 수신할 사용자의 이름을 선택합니다.
. SNMP 탭을 실행하고 스크립트를 실행할 수 있도록 이 페이지의 다른 옵션을 구성합니다.
. 저장 * 을 클릭합니다.

