---
permalink: performance-checker/task-changing-the-performance-statistics-collection-interval.html 
sidebar: sidebar 
keywords: Unified Manager 
summary: 성능 통계에 대한 기본 수집 간격은 5분입니다. 대규모 클러스터의 컬렉션이 기본 시간 내에 마중되지 않으면 이 간격을 10 또는 15분으로 변경할 수 있습니다. 이 설정은 Unified Manager의 이 인스턴스가 모니터링하는 모든 클러스터의 통계 모음에 영향을 줍니다. 
---
= 성능 통계 수집 주기 변경
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능 통계에 대한 기본 수집 간격은 5분입니다. 대규모 클러스터의 컬렉션이 기본 시간 내에 마중되지 않으면 이 간격을 10 또는 15분으로 변경할 수 있습니다. 이 설정은 Unified Manager의 이 인스턴스가 모니터링하는 모든 클러스터의 통계 모음에 영향을 줍니다.



== 시작하기 전에

Unified Manager 서버의 유지보수 콘솔에 로그인하려면 사용자 ID와 암호가 필요합니다.



== 이 작업에 대해

성능 통계 수집 시간이 정시에 완료하지 못하는 문제는 배너 메시지로 표시됩니다 `Unable to consistently collect from cluster <cluster_name>` 또는 `Data collection is taking too long on cluster <cluster_name>`.

통계 수집 문제로 인해 필요한 경우에만 수집 간격을 변경해야 합니다. 다른 이유로 이 설정을 변경하지 마십시오.

[NOTE]
====
이 값을 5분의 기본 설정에서 변경하면 Unified Manager에서 보고하는 성능 이벤트의 수와 빈도에 영향을 줄 수 있습니다. 예를 들어, 시스템 정의 성능 임계값은 정책이 30분 동안 초과될 때 이벤트를 트리거합니다. 5분 컬렉션을 사용하는 경우 6개의 연속 컬렉션에 대해 정책을 초과해야 합니다. 15분 컬렉션의 경우 두 수집 기간 동안 정책을 초과해야 합니다.

====
클러스터 데이터 소스 페이지 하단의 메시지는 현재 통계 데이터 수집 간격을 나타냅니다.



== 단계

. SSH를 사용하여 Unified Manager 호스트에 대한 유지보수 사용자로 로그인합니다.
+
Unified Managermaintenance 콘솔 프롬프트가 표시됩니다.

. 성능 폴링 간격 구성 * 이라고 표시된 메뉴 옵션의 번호를 입력한 다음 Enter 키를 누릅니다.
. 메시지가 표시되면 유지보수 사용자 암호를 다시 입력합니다.
. 설정할 새 폴링 간격의 숫자를 입력한 다음 Enter 키를 누릅니다.




== 작업을 마친 후

Unified Manager 수집 간격을 10분 또는 15분으로 변경하고, 외부 데이터 공급자(예: Graphite)에 현재 연결되어 있는 경우, 데이터 공급자의 전송 간격을 Unified Manager 수집 간격보다 크거나 같도록 변경해야 합니다.
