---
permalink: performance-checker/task-logging-in-to-the-gui.html 
sidebar: sidebar 
keywords:  
summary: 지원되는 웹 브라우저를 사용하여 Unified Manager UI에 로그인할 수 있습니다. 
---
= UI에 로그인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
지원되는 웹 브라우저를 사용하여 Unified Manager UI에 로그인할 수 있습니다.



== 시작하기 전에

* 웹 브라우저는 최소 요구 사항을 충족해야 합니다.
+
에서 상호 운용성 매트릭스 를 참조하십시오 http://mysupport.netapp.com/matrix["mysupport.netapp.com/matrix"] 를 참조하십시오.

* Unified Manager 서버의 IP 주소 또는 URL이 있어야 합니다.




== 이 작업에 대해

24시간 동안 사용하지 않으면 세션에서 자동으로 로그아웃됩니다.



== 단계

. 웹 브라우저에 URL을 입력합니다 `URL` Unified Manager 서버의 IP 주소 또는 FQDN(정규화된 도메인 이름)입니다.
+
** IPv4의 경우: `+https://URL/+`
** IPv6의 경우: `https://[URL]/`서버에서 자체 서명된 디지털 인증서를 사용하는 경우 브라우저에서 인증서를 신뢰할 수 없다는 경고를 표시할 수 있습니다. 액세스를 계속할 위험을 확인하거나 서버 인증을 위해 CA(인증 기관) 서명 디지털 인증서를 설치할 수 있습니다.


. 로그인 화면에서 사용자 이름과 암호를 입력합니다.
+
SAML 인증을 사용하여 Unified Manager 사용자 인터페이스에 로그인할 수 있는 경우 Unified Manager 로그인 페이지 대신 IdP(Identity Provider) 로그인 페이지에 자격 증명을 입력합니다.

+
대시보드/개요 페이지가 표시됩니다.

+
[NOTE]
====
Unified Manager 서버가 초기화되지 않은 경우 새 브라우저 창에 첫 번째 환경 마법사가 표시됩니다. 이메일 알림을 보낼 초기 이메일 수신자, 이메일 통신을 처리할 SMTP 서버, AutoSupport가 Unified Manager 설치에 대한 정보를 기술 지원 부서에 보낼 수 있도록 설정되어 있는지 여부를 입력해야 합니다. 이 정보를 완료하면 Unified Manager UI가 나타납니다.

====

