---
permalink: performance-checker/task-configuring-a-connection-between-a-unified-manager-server-and-an-external-data-provider.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager에서 클러스터 성능 데이터를 외부 서버로 보낼 수 있습니다. 전송되는 통계 데이터의 유형 및 데이터가 전송되는 간격을 지정할 수 있습니다. 
---
= Unified Manager 서버에서 외부 데이터 공급자로의 연결 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager에서 클러스터 성능 데이터를 외부 서버로 보낼 수 있습니다. 전송되는 통계 데이터의 유형 및 데이터가 전송되는 간격을 지정할 수 있습니다.



== 시작하기 전에

* Unified Manager 서버의 유지보수 콘솔에 로그인할 수 있는 권한이 있는 사용자 ID가 있어야 합니다.
* 외부 데이터 공급자에 대한 다음 정보가 있어야 합니다.
+
** 서버 이름 또는 IP 주소(IPv4 또는 IPv6)
** 서버 기본 포트(기본 포트 2003을 사용하지 않는 경우)


* Unified Manager 서버에서 통계 데이터를 수신할 수 있도록 원격 서버 및 타사 소프트웨어를 구성해야 합니다.
* 전송할 통계 그룹을 알아야 합니다.
+
** Performance_indicator: 성능 모니터 통계
** resource_Utilization: 리소스 활용도 및 성능 모니터 통계
** 드릴다운: 모든 통계


* 통계를 전송할 시간 간격(5, 10 또는 15분)을 알아야 합니다
+
기본적으로 Unified Manager는 5분 간격으로 통계를 수집합니다. 전송 간격을 10분(또는 15분)으로 설정하면 각 전송 중에 전송되는 데이터 양이 기본 5분 간격을 사용할 때보다 2배(또는 3배) 더 커집니다.

+
[NOTE]
====
Unified Manager 성능 수집 간격을 10 또는 15분으로 변경하는 경우 전송 간격을 Unified Manager 수집 간격보다 크거나 같게 변경해야 합니다.

====




== 이 작업에 대해

하나의 Unified Manager 서버와 하나의 외부 데이터 공급자 서버 간에 연결을 구성할 수 있습니다.



== 단계

. Unified Manager 서버의 유지보수 콘솔에 유지보수 사용자로 로그인합니다.
+
Unified Managermaintenance 콘솔 프롬프트가 표시됩니다.

. 유지보수 콘솔에서 * 외부 데이터 공급자 * 메뉴 옵션의 번호를 입력합니다.
+
External Server Connection(외부 서버 연결) 메뉴가 표시됩니다.

. 서버 연결 추가/수정 * 메뉴 옵션의 번호를 입력합니다.
+
현재 서버 연결 정보가 표시됩니다.

. 메시지가 표시되면 를 입력합니다 `y` 를 눌러 계속합니다.
. 메시지가 표시되면 대상 서버의 IP 주소 또는 이름과 서버 포트 정보(기본 포트 2003과 다른 경우)를 입력합니다.
. 메시지가 표시되면 를 입력합니다 `y` 입력한 정보가 올바른지 확인합니다.
. 아무 키나 눌러 외부 서버 연결 메뉴로 돌아갑니다.
. Modify Server Configuration *(서버 구성 수정 *) 메뉴 옵션의 번호를 입력합니다.
+
현재 서버 구성 정보가 표시됩니다.

. 메시지가 표시되면 를 입력합니다 `y` 를 눌러 계속합니다.
. 메시지가 표시되면 전송할 통계 유형, 통계가 전송되는 시간 간격 및 지금 통계 전송 활성화 여부를 입력합니다.
+
|===
| ... | 입력... 


 a| 
통계 그룹 ID이다
 a| 
`0` -performance_indicator(기본값)

`1` -resource_Utilization을 참조하십시오

`2` 드릴 다운



 a| 
공급업체 태그
 a| 
외부 서버에 통계를 저장할 폴더의 설명 이름입니다. 기본 이름은 "'NetApp-performance''이지만 다른 값을 입력할 수 있습니다.

점선으로 표시된 표기법을 사용하여 계층적 폴더 구조를 정의할 수 있습니다. 예를 들어, 를 입력합니다 `stats.performance.netapp` 이 통계는 * stats * > * performance * > * netapp * 에 있습니다.



 a| 
전송 간격입니다
 a| 
`5` (기본값), `10`, 또는 `15` 분



 a| 
활성화/비활성화합니다
 a| 
`0` -비활성화

`1` -활성화(기본값)

|===
. 메시지가 표시되면 를 입력합니다 `y` 입력한 정보가 올바른지 확인합니다.
. 아무 키나 눌러 외부 서버 연결 메뉴로 돌아갑니다.
. 유형 `x` 를 눌러 유지보수 콘솔을 종료합니다.




== 결과

연결을 구성한 후에는 선택한 성능 데이터가 지정한 시간 간격에 따라 대상 서버로 전송됩니다. 메트릭이 Graphite에 표시되기 전에 몇 분 정도 걸립니다. 메트릭 계층에서 새 메트릭을 보려면 브라우저를 새로 고쳐야 할 수 있습니다.
