---
permalink: performance-checker/task-viewing-workload-qos-minimum-and-maximum-settings.html 
sidebar: sidebar 
keywords:  
summary: '성능 탐색기 차트에서 볼륨 또는 LUN에 대한 ONTAP 정의 서비스 품질\(QoS\) 정책 설정을 볼 수 있습니다. 최대 처리량 설정은 경쟁 워크로드가 시스템 리소스에 미치는 영향을 제한합니다. 처리량 최소 설정은 중요 워크로드가 서로 경합하는 워크로드에 대한 요구 사항에 관계없이 최소 처리량 목표를 충족하도록 보장합니다.' 
---
= 워크로드 QoS 최소 및 최대 설정 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능 탐색기 차트에서 볼륨 또는 LUN에 대한 ONTAP 정의 서비스 품질(QoS) 정책 설정을 볼 수 있습니다. 최대 처리량 설정은 경쟁 워크로드가 시스템 리소스에 미치는 영향을 제한합니다. 처리량 최소 설정은 중요 워크로드가 서로 경합하는 워크로드에 대한 요구 사항에 관계없이 최소 처리량 목표를 충족하도록 보장합니다.



== 이 작업에 대해

QoS 처리량 "최소" 및 "최대" IOPS 및 MBPS 설정은 ONTAP에서 구성한 경우에만 카운터 차트에 표시됩니다. 최소 처리량 설정은 ONTAP 9.2 이상 소프트웨어를 실행하는 시스템, AFF 시스템에서만 사용할 수 있으며 지금은 IOPS에만 설정할 수 있습니다.

적응형 QoS 정책은 ONTAP 9.3부터 사용할 수 있으며 IOPS 대신 IOPS/TB를 사용하여 표현됩니다. 이러한 정책은 볼륨 크기, 워크로드 당 QoS 정책 값을 자동으로 조정하므로 볼륨 크기에 따라 IOPS와 TB의 비율을 유지합니다. 적응형 QoS 정책 그룹은 볼륨에만 적용할 수 있습니다. QoS 용어인 ''예상됨'''과 ''피크''는 QoS 정책 적용에 최소값과 최대값이 아닌 적응성 QoS 정책에 사용됩니다.

Unified Manager에서는 이전 시간의 각 성능 수집 기간 동안 워크로드 처리량이 정의된 QoS 최대 정책 설정을 초과할 경우 QoS 정책 위반에 대한 경고 이벤트를 생성합니다. 각 수집 기간 동안 짧은 기간 동안만 워크로드 처리 성능이 QoS 임계값을 초과할 수 있지만 Unified Manager는 차트에 수집 기간 동안 ""평균"" 처리량을 표시합니다. 따라서 워크로드의 처리량이 차트에 표시된 정책 임계값을 넘을 수 없는 동안 QoS 이벤트가 발생할 수 있습니다.



== 단계

. 선택한 볼륨 또는 LUN에 대한 * Performance Explorer * 페이지에서 QoS 상한 및 하한 설정을 보려면 다음 작업을 수행하십시오.
+
|===
| 원하는 작업 | 수행할 작업... 


 a| 
IOPS 한도 보기(QoS 최대)
 a| 
IOPS 합계 또는 분석 차트에서 * 확대/축소 보기 * 를 클릭합니다.



 a| 
MBps Ceiling(최대 QoS) 보기
 a| 
MBps Total 또는 Breakdown 차트에서 * Zoom View * 를 클릭합니다.



 a| 
IOPS 최저값 보기(QoS min)
 a| 
IOPS 합계 또는 분석 차트에서 * 확대/축소 보기 * 를 클릭합니다.



 a| 
IOPS/TB 한도 보기(QoS 피크)
 a| 
볼륨의 경우 IOPS/TB 차트에서 * Zoom View * 를 클릭합니다.



 a| 
IOPS/TB 설치 공간 보기(QoS 예상)
 a| 
볼륨의 경우 IOPS/TB 차트에서 * Zoom View * 를 클릭합니다.

|===
+
점선으로 표시된 수평선은 ONTAP에 설정된 최대 또는 최소 처리량 값을 나타냅니다. QoS 값에 대한 변경 사항이 구현된 시점을 확인할 수도 있습니다.

. QoS 설정과 비교하여 특정 IOPS 및 MBps 값을 보려면 커서를 차트 영역으로 이동하여 팝업 창을 확인합니다.




== 작업을 마친 후

특정 볼륨 또는 LUN의 IOPS 또는 MBPS가 매우 높고 시스템 리소스를 강조하는 경우, System Manager 또는 ONTAP CLI를 사용하여 QoS 설정을 조정하여 해당 워크로드가 다른 워크로드의 성능에 영향을 미치지 않도록 할 수 있습니다.

QoS 설정 조정에 대한 자세한 내용은 _ONTAP 9 성능 모니터링 전원 가이드_를 참조하십시오.

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-perf-mon/home.html["ONTAP 9 성능 모니터링 전원 가이드"]
