---
permalink: performance-checker/task-identifying-trends-of-i-o-response-time-on-cluster-components.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager를 사용하면 볼륨 워크로드에 대해 모니터링되는 모든 클러스터 구성 요소의 성능 동향을 볼 수 있습니다. 시간이 지남에 따라 어느 구성 요소가 가장 많이 사용되었는지, 가장 높은 사용률이 읽기 요청인지 또는 쓰기 요청인지, 그리고 사용량이 워크로드 응답 시간에 어떤 영향을 미치는지 확인할 수 있습니다. 
---
= 클러스터 구성 요소의 입출력 응답 시간 추세 파악
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 사용하면 볼륨 워크로드에 대해 모니터링되는 모든 클러스터 구성 요소의 성능 동향을 볼 수 있습니다. 시간이 지남에 따라 어느 구성 요소가 가장 많이 사용되었는지, 가장 높은 사용률이 읽기 요청인지 또는 쓰기 요청인지, 그리고 사용량이 워크로드 응답 시간에 어떤 영향을 미치는지 확인할 수 있습니다.



== 시작하기 전에

* 운영자, OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 분석할 볼륨 또는 관련 LUN의 이름을 식별해야 합니다.
* 30일 동안의 성능 통계를 표시하려면 Unified Manager가 클러스터에서 최소 30일 동안의 성능 통계를 수집 및 분석해야 합니다.




== 이 작업에 대해

클러스터 구성 요소의 성능 추세를 파악하면 관리자가 클러스터를 과도하게 사용하거나 사용하지 않는 여부를 결정하는 데 도움이 됩니다.

이벤트 세부 정보 페이지를 보고 있는 경우 볼륨의 이름을 클릭하여 성능/볼륨 세부 정보 페이지로 직접 이동할 수 있습니다.



== 단계

. 검색 * 표시줄에 볼륨의 이름을 입력합니다.
+
볼륨의 이름이 검색 결과에 표시됩니다.

. 볼륨의 이름을 클릭합니다.
+
볼륨이 Performance/Volume Details(성능/볼륨 세부 정보) 페이지에 표시됩니다.

. 기록 데이터 차트에서 * 30d * 를 클릭하여 최근 30일 동안의 기록 데이터를 표시합니다.
. 데이터 분리 기준 * 을 클릭합니다.
. 지연 시간 * 에서 *** 클러스터 구성 요소 *** 및 *** 읽기/쓰기 지연 시간 *** 을 선택합니다.
. 제출 * 을 클릭합니다.
+
두 차트 모두 지연 시간 차트 아래에 표시됩니다.

. 클러스터 구성 요소 * 차트를 검토하십시오.
+
이 차트는 클러스터 구성 요소별 총 응답 시간을 보여 줍니다. 애그리게이트에서의 응답 시간이 가장 높습니다.

. 클러스터 구성 요소 * 차트를 * 지연 시간 * 차트와 비교합니다.
+
지연 시간 차트에는 애그리게이트의 응답 시간 급증 상황에 맞춰 총 응답 시간의 급증이 표시됩니다. 30일 시간 프레임 끝에는 성능 임계값이 초과된 부분이 몇 개 있습니다.

. 읽기/쓰기 지연 시간 * 차트를 검토하십시오.
+
이 차트는 읽기 요청에 비해 쓰기 요청의 응답 시간이 더 길다는 것을 보여 줍니다. 즉, 클라이언트 애플리케이션이 쓰기 요청을 이행하기 위해 평소보다 더 오래 기다리고 있음을 나타냅니다.

. 읽기/쓰기 지연 시간 * 차트를 * 지연 시간 * 차트와 비교하십시오.
+
또한 클러스터 구성 요소 차트의 aggregate에 맞춰 총 응답 시간이 급격하게 증가해도 읽기/쓰기 지연 시간 차트의 쓰기와 정렬됩니다. 관리자는 워크로드를 사용하는 클라이언트 애플리케이션이 처리되어야 하는지 또는 애그리게이트가 초과 사용되고 있는지 여부를 결정해야 합니다.


