---
permalink: performance-checker/task-investigating-perceived-slow-response-time-for-a-workload.html 
sidebar: sidebar 
keywords:  
summary: 'Unified Manager를 사용하여 클러스터 작업이 볼륨 워크로드의 응답 시간(지연 시간\)을 느리게 하는 원인이 될 수 있는지 확인할 수 있습니다.' 
---
= 작업 부하에 대한 느린 응답 시간 인식 조사
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 사용하여 클러스터의 작업이 볼륨 워크로드의 응답 시간(지연 시간)을 지연시키는 원인이 되었는지 확인할 수 있습니다.



== 시작하기 전에

* 운영자, OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 분석할 볼륨 또는 관련 LUN의 이름을 식별해야 합니다.
* Unified Manager가 클러스터에서 최소 5일간의 성능 통계를 수집 및 분석해야 합니다.




== 이 작업에 대해

이벤트 세부 정보 페이지를 보고 있는 경우 볼륨의 이름을 클릭하여 성능/볼륨 세부 정보 페이지로 직접 이동할 수 있습니다.



== 단계

. 검색 * 표시줄에 볼륨의 이름을 입력합니다.
+
볼륨의 이름이 검색 결과에 표시됩니다.

. 볼륨의 이름을 클릭합니다.
+
볼륨이 Performance/Volume Details(성능/볼륨 세부 정보) 페이지에 표시됩니다.

. 기록 데이터 차트에서 * 5d * 를 클릭하여 마지막 5일간의 기록 데이터를 표시합니다.
. IOPS * 차트를 검토하여 다음 질문에 답하십시오.
+
** 활동 중 극적인 급증이 있습니까?
** 활동에 극적인 감소 효과가 있습니까?
** 운영 패턴이 비정상적으로 변경되었습니까? 작업이 급격하게 증가하거나 감소하지 않으며 이 시간 동안 클러스터 구성이 변경되지 않은 경우 스토리지 관리자가 다른 워크로드가 볼륨 성능에 영향을 주지 않는지 확인할 수 있습니다.


. 데이터 나누기 기준 * 메뉴의 * IOPS * 아래에서 ***읽기/쓰기/기타*** 를 선택합니다.
. 제출 * 을 클릭합니다.
+
읽기/쓰기/기타 차트는 IOPS 차트 아래에 표시됩니다.

. 읽기/쓰기/기타 * 차트를 검토하여 볼륨의 읽기 또는 쓰기 양이 급격하게 증가하거나 감소하는지 확인하십시오.
+
읽기 또는 쓰기 작업이 급격하게 증가하거나 감소하지 않으면 스토리지 관리자가 클러스터의 I/O가 정상적으로 작동하고 있는지 확인할 수 있습니다. 네트워크 또는 연결된 클라이언트에 성능 문제가 있을 수 있습니다.


