---
permalink: health-checker/concept-common-unified-manager-administrative-workflows-and-tasks.html 
sidebar: sidebar 
keywords:  
summary: 'Unified Manager와 관련된 몇 가지 일반적인 관리 워크플로우 및 작업으로는 모니터링할 스토리지 클러스터 선택, 데이터 가용성, 용량 및 보호에 부정적인 영향을 미치는 조건 진단, 보호 관계 생성, 손실된 데이터 복원, 무한 확장 볼륨 구성 및 관리, 기술 지원 팀에 진단 데이터 번들링 및 전송\(필요한 경우\).' 
---
= 공통 Unified Manager 상태 워크플로우 및 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager와 관련된 몇 가지 일반적인 관리 워크플로우 및 작업으로는 모니터링할 스토리지 클러스터 선택, 데이터 가용성, 용량 및 보호에 부정적인 영향을 미치는 조건 진단, 보호 관계 생성, 손실된 데이터 복원, 무한 확장 볼륨 구성 및 관리, 기술 지원 팀에 진단 데이터 번들링 및 전송(필요한 경우)

스토리지 관리자는 Unified Manager를 사용하여 대시보드를 확인하고, 관리되는 스토리지 클러스터의 전체 용량, 가용성 및 보호 상태를 평가한 다음, 발생할 수 있는 특정 문제를 신속하게 식별, 검색, 진단 및 할당하여 해결할 수 있습니다.

관리되는 스토리지 개체의 스토리지 용량, 데이터 가용성 또는 보호 안정성에 영향을 미치는 클러스터, SVM(스토리지 가상 시스템), 볼륨, FlexGroup 볼륨 또는 보호 관계와 관련된 가장 중요한 문제는 대시보드/개요 페이지의 시스템 상태 그래프 및 이벤트에 표시됩니다. 중요한 문제가 식별되면 이 페이지에서는 적절한 문제 해결 워크플로를 지원하는 링크를 제공합니다.

WFA(OnCommand Workflow Automation)와 같은 관련 관리 도구가 포함된 워크플로우에 Unified Manager를 포함하여 스토리지 리소스를 직접 구성할 수도 있습니다.

이 문서에서는 다음과 같은 관리 작업과 관련된 일반적인 워크플로에 대해 설명합니다.

* 가용성 문제 진단 및 관리
+
하드웨어 장애 또는 스토리지 리소스 구성 문제로 인해 대시보드/개요 페이지에 데이터 가용성 이벤트가 표시되는 경우 스토리지 관리자는 포함된 링크를 따라 영향을 받는 스토리지 리소스에 대한 연결 정보를 확인하고 문제 해결 조언을 확인하고 다른 관리자에게 문제 해결을 할당할 수 있습니다.

* 성능 인시던트 구성 및 모니터링
+
OnCommand 관리자는 모니터링 중인 스토리지 시스템 리소스의 성능을 모니터링하고 관리할 수 있습니다. 자세한 내용은 클러스터 성능 관리를 위한 _Unified Manager 워크플로우 가이드 를 참조하십시오.

* 볼륨 용량 문제 진단 및 관리
+
볼륨 스토리지 용량 문제가 대시보드/개요 페이지에 표시되는 경우 스토리지 관리자는 포함된 링크를 따라 영향을 받는 볼륨의 스토리지 용량과 관련된 현재 및 과거 추세를 확인하고 문제 해결 조언을 확인하고 다른 관리자에게 문제 해결 방법을 할당할 수 있습니다.

* 보호 관계 문제 구성, 모니터링 및 진단
+
보호 관계를 생성 및 구성한 후 스토리지 관리자는 대시보드/개요 페이지에서 보호 관계와 관련된 잠재적인 문제를 볼 수 있으며 포함된 링크를 따라 보호 관계의 현재 상태, 영향을 받는 관계에 대한 현재 및 기간별 보호 작업 성공 정보를 볼 수 있습니다. 문제 해결 조언을 제공하고 문제 해결을 다른 관리자에게 할당합니다. 스토리지 관리자는 SnapMirror 및 SnapVault 관계를 구성하고 관리할 수도 있습니다.

* 백업 파일을 생성하고 백업 파일에서 데이터를 복원합니다.
* 스토리지 객체를 주석과 연관
+
스토리지 객체를 주석과 연결하여 스토리지 관리자는 스토리지 객체와 관련된 이벤트를 필터링하고 볼 수 있으므로 스토리지 관리자가 이벤트와 관련된 문제의 우선 순위를 지정하고 해결할 수 있습니다.

* 기술 지원 팀에 지원 번들 보내기
+
스토리지 관리자는 유지 관리 콘솔을 사용하여 지원 번들을 검색하고 기술 지원에 보낼 수 있습니다. 문제가 AutoSupport 메시지가 제공하는 것보다 더 자세한 진단 및 문제 해결이 필요한 경우 지원 번들을 기술 지원 부서에 보내야 합니다.

* 가져올 새 보고서 만들기
+
스토리지 관리자는 새로 만들 수 있습니다 `.rptdesign` 비즈니스 인텔리전스 및 보고 도구(BIRT)용 Eclipse 플러그인을 사용하여 파일. 이러한 보고서를 Unified Manager UI로 가져오고 보고서 페이지에서 볼 수 있습니다.

+
보고서 페이지에 표시되는 보고서는 스토리지 객체의 현재 상태를 제공합니다. 현재 사용량을 기준으로 스토리지 조달 관련 결정을 내리는 것과 같은 중요한 결정을 내릴 수 있습니다. 이러한 보고서는 볼륨, 디스크 쉘프 및 애그리게이트와 같은 스토리지 개체에 대한 자세한 뷰를 제공합니다.

+
Unified Manager UI의 보고서 페이지에서는 생성한 보고서에 대한 자세한 정보를 볼 수 있습니다. 보고서 페이지에서 특정 보고서를 검색하고, 보고서를 저장하고, 보고서를 삭제할 수 있습니다. 이 페이지에서 보고서를 예약, 공유 및 가져올 수도 있습니다.

* 무한 확장 볼륨 생성, 구성, 모니터링 및 보호
+
스토리지 관리자는 Workflow Automation 툴을 사용하여 무한 확장 볼륨에 대한 스토리지 클래스를 생성, 구성, 정의한 후 Unified Manager를 사용하여 해당 볼륨 및 스토리지 클래스에 대한 데이터 정책을 모니터링, 알림 임계값 설정 및 정의할 수 있습니다. 선택적으로 스토리지 관리자는 WFA 및 Unified Manager를 사용하여 무한 확장 볼륨에 대한 데이터 보호를 설정할 수 있습니다.


