---
permalink: health-checker/concept-how-group-rules-work-for-groups.html 
sidebar: sidebar 
keywords:  
summary: '그룹 규칙은 스토리지 오브젝트(볼륨, 클러스터 또는 SVM\)를 특정 그룹에 포함할 수 있도록 정의하는 기준입니다. 조건 그룹 또는 조건을 사용하여 그룹에 대한 그룹 규칙을 정의할 수 있습니다.' 
---
= 그룹 규칙이 그룹에 대해 작동하는 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그룹 규칙은 스토리지 오브젝트(볼륨, 클러스터 또는 SVM)를 특정 그룹에 포함할 수 있도록 정의하는 기준입니다. 조건 그룹 또는 조건을 사용하여 그룹에 대한 그룹 규칙을 정의할 수 있습니다.

* 그룹 규칙을 그룹에 연결해야 합니다.
* 그룹 규칙에 대한 개체 유형을 연결해야 합니다. 그룹 규칙에 대해 하나의 개체 유형만 연결됩니다.
* 스토리지 객체는 각 모니터링 주기 이후 또는 규칙을 생성, 편집 또는 삭제할 때 그룹에서 추가 또는 제거됩니다.
* 그룹 규칙에는 하나 이상의 조건 그룹이 있을 수 있으며 각 조건 그룹에는 하나 이상의 조건이 있을 수 있습니다.
* 스토리지 객체는 생성한 그룹 규칙에 따라 여러 그룹에 속할 수 있습니다.




== 조건

여러 조건 그룹을 만들 수 있으며 각 조건 그룹에는 하나 이상의 조건이 있을 수 있습니다. 그룹에 포함할 스토리지 객체를 지정하기 위해 그룹의 그룹 규칙에 정의된 모든 조건 그룹을 적용할 수 있습니다.

조건 그룹 내의 조건은 논리 AND를 사용하여 실행됩니다. 조건 그룹의 모든 조건을 충족해야 합니다. 그룹 규칙을 생성하거나 수정할 때 조건 그룹의 모든 조건을 충족하는 스토리지 객체만 적용, 선택 및 그룹화하는 조건이 생성됩니다. 그룹에 포함할 스토리지 오브젝트의 범위를 좁히려는 경우 조건 그룹 내에서 여러 조건을 사용할 수 있습니다.

다음 피연산자와 연산자를 사용하고 필요한 값을 지정하여 저장소 개체로 조건을 만들 수 있습니다.

|===
| 스토리지 객체 유형입니다 | 적용 가능한 피연산자 


 a| 
볼륨
 a| 
* 개체 이름
* 소유 클러스터 이름입니다
* 소유 SVM 이름
* 주석




 a| 
SVM
 a| 
* 개체 이름
* 소유 클러스터 이름입니다
* 주석




 a| 
클러스터
 a| 
* 개체 이름
* 주석


|===
스토리지 개체의 피연산자로 주석을 선택하면 ""is"" 연산자를 사용할 수 있습니다. 다른 모든 피연산자의 경우 ""is"" 또는 ""Contains""를 연산자로 선택할 수 있습니다.

* 피연산자
+
Unified Manager의 피연산자 목록은 선택한 개체 형식을 기반으로 변경됩니다. 이 목록에는 오브젝트 이름, 소유 클러스터 이름, SVM 이름 소유, Unified Manager에 정의한 주석이 포함됩니다.

* 운영자
+
연산자 목록은 조건에 대해 선택한 피연산자를 기준으로 변경됩니다. Unified Manager에서 지원되는 운영자는 "is"와 "Contains"입니다.

+
""is"" 연산자를 선택하면 선택한 피연산자에 대해 제공된 값과 피연산자 값의 정확한 일치에 대한 조건이 계산됩니다.

+
"포함" 연산자를 선택하면 다음 조건 중 하나를 충족하도록 조건이 평가됩니다.

+
** 피연산자 값은 선택한 피연산자에 대해 제공된 값과 정확히 일치합니다
** 피연산자 값은 선택한 피연산자에 대해 제공된 값을 포함합니다


* 값
+
값 필드는 선택한 피연산자에 따라 변경됩니다.





== 조건이 있는 그룹 규칙의 예

다음 두 가지 조건이 있는 볼륨의 조건 그룹을 고려합니다.

* 이름에 "vol"이 포함되어 있습니다.
* SVM 이름은 "data_svm"입니다.


이 조건 그룹은 이름에 ""vol""이 포함되어 있고 이름이 ""data_svm""인 SVM에서 호스팅되는 모든 볼륨을 선택합니다.



== 조건 그룹

조건 그룹은 논리 OR를 사용하여 실행된 다음 스토리지 객체에 적용됩니다. 스토리지 객체가 그룹에 포함될 조건 그룹 중 하나를 만족해야 합니다. 모든 조건 그룹의 스토리지 객체가 결합됩니다. 조건 그룹을 사용하여 그룹에 포함할 스토리지 개체의 범위를 늘릴 수 있습니다.



== 조건 그룹이 있는 그룹 규칙의 예

볼륨별로 다음 두 가지 조건을 포함하는 두 개의 조건 그룹을 고려합니다.

* 조건 그룹 1
+
** 이름에 "vol"이 포함되어 있습니다.
** SVM 이름이 ""data_svm"" 조건 그룹 1은 이름에 "vol"이 포함된 모든 볼륨을 선택하고 SVM에서 "data_svm"이라는 이름으로 호스팅됩니다.


* 조건 그룹 2
+
** 이름에 "vol"이 포함되어 있습니다.
** 데이터 우선 순위의 주석 값은 ""위험"" 조건 그룹 2는 이름에 ""vol""을 포함하고 데이터 우선 순위 주석 값으로 ""위험""으로 주석이 붙은 모든 볼륨을 선택합니다.




이러한 두 조건 그룹이 포함된 그룹 규칙이 스토리지 객체에 적용되는 경우 선택한 그룹에 다음 스토리지 객체가 추가됩니다.

* 이름에 "vol"이 포함되어 있고 "data_svm"이라는 이름의 SVM에서 호스팅되는 모든 볼륨.
* 이름에 ""vol""이 포함되어 있고 데이터 우선 순위 주석 값 ""critical""이 주석으로 표시된 모든 볼륨.

