---
permalink: health-checker/reference-network-configuration-menu.html 
sidebar: sidebar 
keywords:  
summary: 네트워크 구성 메뉴를 사용하여 네트워크 설정을 관리할 수 있습니다. Unified Manager 사용자 인터페이스를 사용할 수 없는 경우 이 메뉴를 사용해야 합니다. 
---
= 네트워크 구성 메뉴
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
네트워크 구성 메뉴를 사용하여 네트워크 설정을 관리할 수 있습니다. Unified Manager 사용자 인터페이스를 사용할 수 없는 경우 이 메뉴를 사용해야 합니다.

[NOTE]
====
Unified Manager가 Red Hat Enterprise Linux, CentOS 또는 Microsoft Windows에 설치된 경우에는 이 메뉴를 사용할 수 없습니다.

====
다음 메뉴를 선택할 수 있습니다.

* * IP 주소 설정 표시 *
+
IP 주소, 네트워크, 브로드캐스트 주소, 넷마스크, 게이트웨이를 포함하여 가상 어플라이언스에 대한 현재 네트워크 설정을 표시합니다. DNS 서버가 있습니다.

* * IP 주소 설정 변경 *
+
IP 주소, 넷마스크, 게이트웨이 또는 DNS 서버를 포함하여 가상 어플라이언스에 대한 네트워크 설정을 변경할 수 있습니다. 유지보수 콘솔을 사용하여 네트워크 설정을 DHCP에서 정적 네트워킹으로 전환하는 경우 호스트 이름을 편집할 수 없습니다. 변경 사항을 적용하려면 * 변경 사항 커밋 * 을 선택해야 합니다.

* * 도메인 이름 검색 설정 표시 *
+
호스트 이름을 확인하는 데 사용되는 도메인 이름 검색 목록을 표시합니다.

* * 도메인 이름 검색 설정 변경 *
+
호스트 이름을 확인할 때 검색할 도메인 이름을 변경할 수 있습니다. 변경 사항을 적용하려면 * 변경 사항 커밋 * 을 선택해야 합니다.

* * 정적 라우트 표시 *
+
현재 정적 네트워크 경로를 표시합니다.

* * 정적 라우트 변경 *
+
정적 네트워크 경로를 추가하거나 삭제할 수 있습니다. 변경 사항을 적용하려면 * 변경 사항 커밋 * 을 선택해야 합니다.

+
** * 루트 추가 *
+
정적 경로를 추가할 수 있습니다.

** * 루트 삭제 *
+
정적 라우트를 삭제할 수 있습니다.

** * 뒤로 *
+
기본 메뉴 * 로 돌아갑니다.

** * 종료 *
+
유지보수 콘솔을 종료합니다.



* * 네트워크 인터페이스 비활성화 *
+
사용 가능한 네트워크 인터페이스를 비활성화합니다. 하나의 네트워크 인터페이스만 사용할 수 있는 경우에는 비활성화할 수 없습니다. 변경 사항을 적용하려면 * 변경 사항 커밋 * 을 선택해야 합니다.

* * 네트워크 인터페이스 사용 *
+
사용 가능한 네트워크 인터페이스를 활성화합니다. 변경 사항을 적용하려면 * 변경 사항 커밋 * 을 선택해야 합니다.

* * 변경 사항을 커밋합니다 *
+
가상 어플라이언스의 네트워크 설정에 대한 변경 사항을 적용합니다. 변경 사항을 적용하려면 이 옵션을 선택해야 합니다. 그렇지 않으면 변경 내용이 적용되지 않습니다.

* * 호스트에 Ping *
+
IP 주소 변경 또는 DNS 구성을 확인하기 위해 타겟 호스트에 ping을 보냅니다.

* * 기본 설정으로 복원 *
+
모든 설정을 출하 시 기본값으로 재설정합니다. 변경 사항을 적용하려면 * 변경 사항 커밋 * 을 선택해야 합니다.

* * 뒤로 *
+
기본 메뉴 * 로 돌아갑니다.

* * 종료 *
+
유지보수 콘솔을 종료합니다.


