---
permalink: health-checker/reference-system-configuration-menu.html 
sidebar: sidebar 
keywords:  
summary: 시스템 구성 메뉴를 사용하면 서버 상태 보기, 가상 시스템 재부팅 및 종료 등의 다양한 옵션을 제공하여 가상 어플라이언스를 관리할 수 있습니다. 
---
= System Configuration(시스템 구성) 메뉴
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템 구성 메뉴를 사용하면 서버 상태 보기, 가상 시스템 재부팅 및 종료 등의 다양한 옵션을 제공하여 가상 어플라이언스를 관리할 수 있습니다.

[NOTE]
====
Unified Manager가 Red Hat Enterprise Linux, CentOS 또는 Microsoft Windows에 설치된 경우 시스템 구성 메뉴를 사용할 수 없습니다.

====
다음 메뉴를 선택할 수 있습니다.

* * 서버 상태 표시 *
+
현재 서버 상태를 표시합니다. 상태 옵션에는 실행 중 및 실행 중이 아닙니다.

+
서버가 실행되고 있지 않으면 기술 지원 부서에 문의해야 할 수 있습니다.

* * 가상 머신을 재부팅합니다 *
+
가상 시스템을 재부팅하여 모든 서비스를 중지합니다. 재부팅 후 가상 머신과 서비스가 다시 시작됩니다.

* * 가상 머신 종료 *
+
가상 머신을 종료하고 모든 서비스를 중지합니다.

+
이 옵션은 가상 시스템 콘솔에서만 선택할 수 있습니다.

* * <로그인한 사용자> 사용자 암호 변경 *
+
현재 로그인한 사용자의 암호를 변경합니다. 이 암호는 유지 관리 사용자만 될 수 있습니다.

* * 데이터 디스크 크기 증가 *
+
가상 시스템에서 데이터 디스크(디스크 3)의 크기를 늘립니다.

* * 스왑 디스크 크기 증가 *
+
가상 시스템에서 스왑 디스크(디스크 2)의 크기를 늘립니다.

* * 시간대 변경 *
+
시간대를 사용자의 위치로 변경합니다.

* * NTP 서버 변경 *
+
IP 주소 또는 FQDN(정규화된 도메인 이름)과 같은 NTP 서버 설정을 변경합니다.

* * OCUM 백업에서 복원 *
+
Unified Manager 데이터베이스와 구성 설정을 이전에 백업된 버전에서 복원합니다.

* * 서버 인증서 재설정 * 을 선택합니다
+
서버 보안 인증서를 재설정합니다.

* * 호스트 이름 변경 *
+
가상 어플라이언스가 설치된 호스트의 이름을 변경합니다.

* * 뒤로 *
+
시스템 구성 메뉴를 종료하고 주 메뉴로 돌아갑니다.

* * 종료 *
+
유지보수 콘솔 메뉴를 종료합니다.


