---
permalink: health-checker/task-generating-and-uploading-a-support-bundle.html 
sidebar: sidebar 
keywords:  
summary: 전체 진단 정보가 포함된 지원 번들을 생성하여 검색한 다음 기술 지원 부서에 보내 문제 해결을 도울 수 있습니다. 일부 유형의 데이터에서 많은 양의 클러스터 리소스를 사용하거나 완료하는 데 시간이 오래 걸릴 수 있으므로 지원 번들에 포함하거나 제외할 데이터 유형을 지정할 수 있습니다. 
---
= 지원 번들 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전체 진단 정보가 포함된 지원 번들을 생성하여 검색한 다음 기술 지원 부서에 보내 문제 해결을 도울 수 있습니다. 일부 유형의 데이터에서 많은 양의 클러스터 리소스를 사용하거나 완료하는 데 시간이 오래 걸릴 수 있으므로 지원 번들에 포함하거나 제외할 데이터 유형을 지정할 수 있습니다.



== 시작하기 전에

유지보수 사용자로서 유지보수 콘솔에 액세스할 수 있어야 합니다.



== 이 작업에 대해

Unified Manager에서는 가장 최근에 생성된 2개의 지원 번들만 저장합니다. 이전 지원 번들은 시스템에서 삭제됩니다.

[NOTE]
====
Windows 시스템에서는 명령을 사용합니다 `supportbundle.bat` 은(는) 지원 번들을 생성하는 데 더 이상 지원되지 않습니다.

====


== 단계

. 유지보수 콘솔 * 주 메뉴 * 에서 * 지원/진단 * 을 선택합니다.
. 지원 번들 생성 * 을 선택합니다.
. 지원 번들에 포함하거나 제외할 다음 데이터 유형을 선택하거나 선택 취소합니다.
+
** * 데이터베이스 덤프 *
+
MySQL Server 데이터베이스의 덤프.

** * 힙 덤프 *
+
기본 Unified Manager 서버 프로세스 상태의 스냅샷 이 옵션은 기본적으로 비활성화되어 있으며 고객 지원 부서에서 요청할 때만 선택해야 합니다.

** * 촬영 녹화 *
+
Unified Manager와 모니터링되는 클러스터 간의 모든 통신 내용을 기록하는 것입니다.



+
[NOTE]
====
모든 데이터 유형의 선택을 취소하면 지원 번들이 다른 Unified Manager 데이터와 함께 계속 생성됩니다.

====
. 유형 `g`키를 누른 다음 Enter 키를 눌러 지원 번들을 생성합니다.
+
지원 번들 생성은 메모리를 많이 사용하는 작업이므로 지원 번들을 생성할지 확인하는 메시지가 표시됩니다.

. 유형 `y`키를 누른 다음 Enter 키를 눌러 지원 번들을 생성합니다.
+
이때 지원 번들을 생성하지 않으려면 을 입력합니다 `n`키를 누릅니다.

. 지원 번들에 데이터베이스 덤프 파일을 포함시킨 경우 성능 통계를 포함할 기간을 지정하라는 메시지가 표시됩니다. 성능 통계를 포함시키면 많은 시간과 공간이 소요되므로 성능 통계를 포함하지 않고 데이터베이스를 덤프할 수도 있습니다.
+
.. YYYYMMDD 형식으로 시작 날짜를 입력합니다.
+
예를 들어, 를 입력합니다 `20170101` 2017년 1월 1일 기준 를 입력합니다 `n` 성능 통계를 포함하지 않으려는 경우

.. 오전 12시부터 통계 일수를 입력합니다 지정된 시작 날짜에.
+
1부터 10까지의 숫자를 입력할 수 있습니다.



+
성능 통계를 포함하는 경우 성능 통계를 수집하는 기간이 표시됩니다.

. 지원 번들 생성 * 을 선택합니다.
+
생성된 지원 번들은 에 상주합니다 `/support` 디렉토리.





== 작업을 마친 후

지원 번들을 생성한 후 SFTP 클라이언트를 사용하거나 UNIX 또는 Linux CLI 명령을 사용하여 검색할 수 있습니다. Windows 설치에서 RDP(원격 데스크톱)를 사용하여 지원 번들을 검색할 수 있습니다.

생성된 지원 번들은 에 상주합니다 `/support` VMware 시스템의 디렉토리 `/opt/netapp/data/support/` Linux 시스템 및 에서 `ProgramData\NetApp\OnCommandAppData\ocum\support` Windows 시스템에서
