---
permalink: health-checker/task-creating-custom-rules.html 
sidebar: sidebar 
keywords:  
summary: 데이터 센터 요구사항에 따라 맞춤형 규칙을 생성하여 데이터 정책에 추가하여 무한 확장 볼륨을 통해 SVM에 쓰는 데이터 배치를 결정할 수 있습니다. 기존 템플릿을 사용하지 않고 규칙 만들기 대화 상자에서 사용자 지정 규칙을 만들 수 있습니다. 
---
= 사용자 지정 규칙 만들기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 센터 요구사항에 따라 맞춤형 규칙을 생성하여 데이터 정책에 추가하여 무한 확장 볼륨을 통해 SVM에 쓰는 데이터 배치를 결정할 수 있습니다. 기존 템플릿을 사용하지 않고 규칙 만들기 대화 상자에서 사용자 지정 규칙을 만들 수 있습니다.



== 시작하기 전에

* OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 스토리지 클래스가 있는 무한 확장 볼륨이 있는 SVM이 포함된 클러스터를 Unified Manager 데이터베이스에 추가해야 합니다.




== 이 작업에 대해

무한 확장 볼륨을 가진 SVM에 대해서만 데이터 정책 탭이 표시됩니다.



== 단계

. 왼쪽 탐색 창에서 * 상태 * > * SVM * 을 클릭합니다.
. Health/Storage Virtual Machines * 인벤토리 페이지에서 적절한 SVM을 선택합니다.
. 데이터 정책 * 을 클릭합니다.
. Create * 를 클릭합니다.
. 규칙 만들기 * 대화 상자의 * 템플릿 * 목록에서 * 사용자 정의 규칙 * 을 선택합니다.
. Matching Criteria * 영역에서 필요에 따라 조건을 추가합니다.
+
조건을 사용하면 파일 형식, 디렉터리 경로 또는 소유자를 기준으로 규칙을 만들 수 있습니다. 이러한 조건의 조합은 조건 집합입니다. 예를 들어, "'Place all.mp3 Owned by John in bronze storage class"라는 규칙이 있을 수 있습니다.

. 스토리지 클래스 * 드롭다운 목록에서 적절한 스토리지 클래스를 선택합니다.
. Create * 를 클릭합니다.
+
새로 생성된 규칙이 데이터 정책 탭에 표시됩니다.

. 데이터 정책의 다른 변경 사항을 미리 봅니다.
. SVM의 규칙 속성 변경을 활성화하려면 * 활성화 * 를 클릭합니다.

