---
permalink: health-checker/task-resynchronizing-protection-relationships-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: 중단된 SnapMirror 또는 SnapVault 관계의 데이터를 다시 동기화한 다음 소스의 데이터가 대상의 데이터와 일치하도록 대상을 읽기/쓰기로 만들 수 있습니다. 소스 볼륨에서 필요한 공통 스냅샷 복사본이 삭제되어 SnapMirror 또는 SnapVault 업데이트가 실패하는 경우에도 재동기화할 수 있습니다. 
---
= 상태/볼륨 세부 정보 페이지에서 보호 관계를 재동기화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
중단된 SnapMirror 또는 SnapVault 관계의 데이터를 다시 동기화한 다음 소스의 데이터가 대상의 데이터와 일치하도록 대상을 읽기/쓰기로 만들 수 있습니다. 소스 볼륨에서 필요한 공통 스냅샷 복사본이 삭제되어 SnapMirror 또는 SnapVault 업데이트가 실패하는 경우에도 재동기화할 수 있습니다.



== 시작하기 전에

* OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* OnCommand Workflow Automation를 설정해야 합니다.




== 단계

. Health/Volume * 세부 정보 페이지의 * Protection * 탭에서 재동기화하려는 보호 관계를 토폴로지에서 찾아 마우스 오른쪽 버튼으로 클릭합니다.
. 메뉴에서 * 재동기화 * 를 선택합니다.
+
또는 * Actions * 메뉴에서 * Relationship * > * ResSynchronize * 를 선택하여 현재 세부 정보를 보고 있는 관계를 다시 동기화합니다.

+
재동기화 대화 상자가 표시됩니다.

. 재동기화 옵션 * 탭에서 전송 우선 순위 및 최대 전송 속도를 선택합니다.
. 소스 스냅샷 복사본 * 을 클릭한 다음 * 스냅샷 복사본 * 열에서 * 기본값 * 을 클릭합니다.
+
소스 스냅샷 복사본 선택 대화 상자가 표시됩니다.

. 기본 스냅샷 복사본을 전송하지 않고 기존 스냅샷 복사본을 지정하려면 * 기존 스냅샷 복사본 * 을 클릭하고 목록에서 스냅샷 복사본을 선택합니다.
. 제출 * 을 클릭합니다.
+
재동기화 대화 상자로 돌아갑니다.

. 재동기화할 소스를 두 개 이상 선택한 경우 기존 스냅샷 복사본을 지정할 다음 소스에 대해 * 기본값 * 을 클릭합니다.
. Submit * 을 클릭하여 재동기화 작업을 시작합니다.
+
재동기화 작업이 시작되고 상태/볼륨 세부 정보 페이지로 돌아가며 페이지 상단에 작업 링크가 표시됩니다.

. 상태/볼륨 * 세부 정보 페이지에서 * 작업 보기 * 를 클릭하여 각 재동기화 작업의 상태를 추적합니다.
+
필터링된 작업 목록이 표시됩니다.

. 브라우저의 뒤로 화살표를 클릭하여 * 상태/볼륨 * 세부 정보 페이지로 돌아갑니다.
+
모든 작업 작업이 성공적으로 완료되면 재동기화 작업이 완료됩니다.


