---
permalink: health-checker/task-resolving-capacity-issues.html 
sidebar: sidebar 
keywords:  
summary: 이 워크플로우는 용량 문제를 해결하는 방법의 예를 제공합니다. 이 시나리오에서는 관리자 또는 운영자인 경우 Unified Manager 대시보드/개요 페이지에 액세스하여 모니터링되는 스토리지 개체에 용량 문제가 있는지 확인합니다. 용량 위험이 있는 볼륨이 있으며 문제의 가능한 원인과 해결 방법을 결정하려고 합니다. 
---
= 용량 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 워크플로우는 용량 문제를 해결하는 방법의 예를 제공합니다. 이 시나리오에서는 관리자 또는 운영자인 경우 Unified ManagerDashboards/Overview 페이지에 액세스하여 모니터링되는 스토리지 객체에 용량 문제가 있는지 확인합니다. 용량 위험이 있는 볼륨이 있으며 문제의 가능한 원인과 해결 방법을 결정하려고 합니다.



== 시작하기 전에

운영자, OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.



== 이 작업에 대해

대시보드/개요 페이지에서는 미해결 인시던트 및 위험 영역을 살펴보고 위험 SVM 볼륨 용량 아래의 용량 창에서 "'볼륨 공간 가득 참'" 오류 이벤트를 확인할 수 있습니다.



== 단계

. 대시보드/개요 * 페이지의 * 해결되지 않은 인시던트 및 위험 * 영역에서 * 용량 * 창에서 볼륨 공간 가득 참 오류 이벤트의 이름을 클릭합니다.
+
오류에 대한 이벤트 세부 정보 페이지가 표시됩니다.

. 이벤트 * 세부 정보 페이지에서 다음 작업 중 하나 이상을 수행할 수 있습니다.
+
** 원인 필드의 오류 메시지를 검토하고 권장 해결 조치 아래에 있는 제안 사항을 클릭하여 가능한 해결 방법을 검토합니다. xref:task-performing-suggested-remedial-actions-for-a-full-volume.adoc[전체 볼륨에 대해 제안된 개선 작업 수행]
** 객체에 대한 세부 정보를 보려면 소스 필드에서 객체 이름(이 경우 볼륨)을 클릭합니다. xref:reference-health-volume-details-page.adoc[볼륨 세부 정보 페이지]
** 이 이벤트에 대해 추가되었을 수 있는 참고 사항을 찾습니다. xref:task-adding-and-reviewing-notes-about-an-event.adoc[이벤트와 관련된 메모 추가 및 검토]
** 이벤트에 메모를 추가합니다. xref:task-adding-and-reviewing-notes-about-an-event.adoc[이벤트와 관련된 메모 추가 및 검토]
** 다른 사용자에게 이벤트를 할당합니다. xref:task-assigning-events-to-specific-users.adoc[이벤트 할당]
** 이벤트를 확인합니다. xref:task-acknowledging-and-resolving-events.adoc[이벤트 확인 및 해결]
** 이벤트를 Resolved 로 표시합니다. xref:task-acknowledging-and-resolving-events.adoc[이벤트 확인 및 해결]



