---
permalink: health-checker/task-restoring-data-using-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: 상태/볼륨 세부 정보 페이지의 복원 기능을 사용하여 스냅샷 복사본에서 덮어쓰거나 삭제된 파일, 디렉토리 또는 전체 볼륨을 복원할 수 있습니다. 
---
= 상태/볼륨 세부 정보 페이지를 사용하여 데이터를 복원합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
상태/볼륨 세부 정보 페이지의 복원 기능을 사용하여 스냅샷 복사본에서 덮어쓰거나 삭제된 파일, 디렉토리 또는 전체 볼륨을 복원할 수 있습니다.



== 시작하기 전에

OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.



== 이 작업에 대해

NTFS 파일 스트림은 복원할 수 없습니다.

다음과 같은 경우에는 복원 옵션을 사용할 수 없습니다.

* 볼륨 ID는 알 수 없습니다. 예를 들어, 인터클러스터 관계가 있고 대상 클러스터가 아직 검색되지 않은 경우입니다.
* 볼륨이 FlexGroup 볼륨입니다.
* 볼륨은 SnapMirror Synchronous 복제에 대해 구성됩니다.




== 단계

. Health/Volume * 세부 정보 페이지의 * Protection * 탭에서 복구할 볼륨의 이름을 마우스 오른쪽 버튼으로 클릭합니다.
. 메뉴에서 * 복원 * 을 선택합니다.
+
또는 * Actions * 메뉴에서 * Restore * 를 선택하여 세부 정보를 보고 있는 현재 볼륨을 보호합니다.

+
Restore(복원) 대화 상자가 표시됩니다.

. 기본값과 다른 경우 데이터를 복원할 볼륨 및 스냅샷 복사본을 선택합니다.
. 복원할 항목을 선택합니다.
+
전체 볼륨을 복원하거나 복원할 폴더 및 파일을 지정할 수 있습니다.

. 선택한 항목을 복원할 위치를 * 원래 위치 * 또는 * 대체 기존 위치 * 중에서 선택합니다.
. 기존 위치를 다른 위치로 선택하는 경우 다음 중 하나를 수행합니다.
+
** Restore Path(복원 경로) 텍스트 필드에 데이터를 복원할 위치의 경로를 입력한 다음 * Select Directory(디렉터리 선택) * 를 클릭합니다.
** 찾아보기 * 를 클릭하여 디렉터리 찾아보기 대화 상자를 시작하고 다음 단계를 완료합니다.
+
... 복원할 클러스터, SVM 및 볼륨을 선택합니다.
... 이름 테이블에서 디렉토리 이름을 선택합니다.
... 디렉터리 선택 * 을 클릭합니다.




. 복원 * 을 클릭합니다.
+
복원 프로세스가 시작됩니다.

+
[NOTE]
====
NDMP 오류가 있는 Cloud Volumes ONTAP HA 클러스터 간에 복구 작업이 실패할 경우 대상이 소스 시스템의 클러스터 관리 LIF와 통신할 수 있도록 타겟 클러스터에 명시적 AWS 경로를 추가해야 할 수 있습니다. OnCommand Cloud Manager를 사용하여 이 구성 단계를 수행합니다.

====

