---
permalink: health-checker/task-updating-saml-authentication-settings-after-unified-manager-certificate-change.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager 서버에 설치된 HTTPS 보안 인증서를 변경하려면 SAML 인증 구성 설정을 업데이트해야 합니다. 호스트 시스템의 이름을 바꾸거나 호스트 시스템에 새 IP 주소를 할당하거나 시스템에 대한 보안 인증서를 수동으로 변경하면 인증서가 업데이트됩니다. 
---
= Unified Manager 보안 인증서 변경 후 SAML 인증 설정을 업데이트하는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager 서버에 설치된 HTTPS 보안 인증서를 변경하려면 SAML 인증 구성 설정을 업데이트해야 합니다. 호스트 시스템의 이름을 바꾸거나 호스트 시스템에 새 IP 주소를 할당하거나 시스템에 대한 보안 인증서를 수동으로 변경하면 인증서가 업데이트됩니다.



== 이 작업에 대해

보안 인증서가 변경되고 Unified Manager 서버가 다시 시작되면 SAML 인증이 작동하지 않고 사용자가 Unified Manager 그래픽 인터페이스에 액세스할 수 없습니다. 사용자 인터페이스에 대한 액세스를 다시 활성화하려면 IDP 서버 및 Unified Manager 서버 모두에서 SAML 인증 설정을 업데이트해야 합니다.



== 단계

. 유지보수 콘솔에 로그인합니다.
. 주 메뉴 * 에서 * SAML 인증 비활성화 * 옵션에 대한 번호를 입력합니다.
+
SAML 인증을 비활성화하고 Unified Manager를 다시 시작할지 확인하는 메시지가 표시됩니다.

. 업데이트된 FQDN 또는 IP 주소를 사용하여 Unified Manager 사용자 인터페이스를 시작하고, 업데이트된 서버 인증서를 브라우저에 적용하고, 유지 관리 사용자 자격 증명을 사용하여 로그인합니다.
. 설정/인증 * 페이지에서 * SAML 인증 * 탭을 선택하고 IDP 연결을 구성합니다.
. Unified Manager 호스트 메타데이터 URI를 복사하거나 호스트 메타데이터를 XML 텍스트 파일에 저장합니다.
. 저장 * 을 클릭합니다.
+
구성을 완료하고 Unified Manager를 다시 시작할지 확인하는 메시지 상자가 표시됩니다.

. 확인 및 로그아웃 * 을 클릭하면 Unified Manager가 다시 시작됩니다.
. IDP 서버에 액세스한 다음 Unified Manager 서버 URI 및 메타데이터를 입력하여 구성을 완료합니다.
+
|===
| ID 공급자 | 구성 단계 


 a| 
고급
 a| 
.. ADFS 관리 GUI에서 기존 기반 당사자 신뢰 항목을 삭제합니다.
.. 를 사용하여 새 신뢰할 수 있는 상대 트러스트 항목을 추가합니다 `saml_sp_metadata.xml` 업데이트된 Unified Manager 서버에서
.. Unified Manager가 이 기반 당사자 신뢰 항목에 대한 ADFS SAML 응답을 구문 분석하는 데 필요한 세 가지 클레임 규칙을 정의합니다.
.. ADFS Windows 서비스를 다시 시작합니다.




 a| 
시바볼레스
 a| 
.. Unified Manager 서버의 새 FQDN을 으로 업데이트합니다 `attribute-filter.xml` 및 `relying-party.xml` 파일.
.. Apache Tomcat 웹 서버를 다시 시작하고 포트 8005가 온라인 상태가 될 때까지 기다립니다.


|===
. Unified Manager에 로그인하고 IdP를 통해 SAML 인증이 예상대로 작동하는지 확인합니다.

