---
permalink: health-checker/task-accessing-the-maintenance-console.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager 사용자 인터페이스가 작동 중이 아니거나 사용자 인터페이스에서 사용할 수 없는 기능을 수행해야 하는 경우, 유지보수 콘솔에 액세스하여 Unified Manager 시스템을 관리할 수 있습니다. 
---
= 유지보수 콘솔 액세스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager 사용자 인터페이스가 작동 중이 아니거나 사용자 인터페이스에서 사용할 수 없는 기능을 수행해야 하는 경우, 유지보수 콘솔에 액세스하여 Unified Manager 시스템을 관리할 수 있습니다.



== 시작하기 전에

Unified Manager를 설치하고 구성해야 합니다.



== 이 작업에 대해

15분 동안 비활성 상태가 지속되면 유지보수 콘솔에서 로그아웃합니다.

[NOTE]
====
VMware에 설치된 경우 VMware 콘솔을 통해 유지 관리 사용자로 이미 로그인한 경우에는 Secure Shell을 사용하여 동시에 로그인할 수 없습니다.

====


== 단계

. 다음 단계에 따라 유지보수 콘솔에 액세스합니다.
+
|===
| 이 운영 체제에서... | 다음 단계를 따르십시오... 


 a| 
VMware
 a| 
.. Secure Shell을 사용하여 Unified Manager 가상 어플라이언스의 IP 주소 또는 정규화된 도메인 이름에 연결합니다.
.. 유지보수 사용자 이름과 암호를 사용하여 유지보수 콘솔에 로그인합니다.




 a| 
리눅스
 a| 
.. Secure Shell을 사용하여 Unified Manager 시스템의 IP 주소 또는 정규화된 도메인 이름에 연결합니다.
.. 유지보수 사용자(umadmin) 이름 및 암호를 사용하여 시스템에 로그인합니다.
.. 명령을 입력합니다 `maintenance_console` Enter 키를 누릅니다.




 a| 
Windows
 a| 
.. 관리자 자격 증명을 사용하여 Unified Manager 시스템에 로그인합니다.
.. Windows 관리자로 PowerShell을 실행합니다.
.. 명령을 입력합니다 `maintenance_console` Enter 키를 누릅니다.
+
[NOTE]
====
Microsoft Windows Server 2012에서 실행 정책 오류가 발생하면 다음 명령을 입력하고 c 단계를 다시 시도하십시오. `PowerShell.exe -ExecutionPolicy RemoteSigned`

====


|===
+
Unified Manager 유지보수 콘솔 메뉴가 표시됩니다.


