---
permalink: health-checker/task-resolving-a-protection-job-failure.html 
sidebar: sidebar 
keywords:  
summary: 이 워크플로우에서는 Unified Manager 대시보드에서 보호 작업 장애를 식별하고 해결하는 방법의 예를 제공합니다. 
---
= 보호 작업 실패 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 워크플로우에서는 Unified Manager 대시보드에서 보호 작업 장애를 식별하고 해결하는 방법의 예를 제공합니다.



== 시작하기 전에

이 워크플로의 일부 작업에서는 OnCommand 관리자 역할을 사용하여 로그인해야 하므로 에 설명된 대로 다양한 기능을 사용하는 데 필요한 역할에 익숙해야 합니다 xref:reference-unified-manager-roles-and-capabilities.adoc[Unified Manager 사용자 역할 및 기능].



== 이 작업에 대해

이 시나리오에서는 대시보드/개요 페이지에 액세스하여 보호 작업에 문제가 있는지 확인합니다. 보호 인시던트 영역에서 볼륨에 보호 작업 실패 오류가 표시된 작업이 종료됨 인시던트가 있음을 알 수 있습니다. 이 오류를 조사하여 가능한 원인과 가능한 해결 방법을 결정합니다.



== 단계

. Dashboard * Unresolved Incidents and Risks * 영역의 * Protection Incidents * 패널에서 * Protection job failed * 이벤트를 클릭합니다.
+
[TIP]
====
이벤트에 연결된 텍스트가 양식에 기록됩니다 `object_name:/object_name - Error Name`예를 들면, 입니다 `cluster2_src_svm:/cluster2_src_vol2 - Protection Job Failed`.

====
+
실패한 보호 작업에 대한 이벤트 세부 정보 페이지가 표시됩니다.

. 요약 * 영역의 원인 필드에 있는 오류 메시지를 검토하여 문제를 확인하고 가능한 수정 조치를 평가합니다.
+
을 참조하십시오 xref:task-identifying-the-problem-and-performing-corrective-actions-for-a-failed-protection-job.adoc[문제 식별 및 실패한 보호 작업에 대한 수정 조치 수행].


