---
permalink: health-checker/task-performing-corrective-action-for-storage-failover-interconnect-links-down.html 
sidebar: sidebar 
keywords:  
summary: 스토리지 페일오버 관련 이벤트의 이벤트 세부 정보 페이지를 표시할 때 페이지의 요약 정보를 검토하여 이벤트의 긴급성, 문제의 가능한 원인 및 가능한 문제 해결 방법을 결정할 수 있습니다. 
---
= 스토리지 페일오버 상호 연결에 대한 수정 조치를 수행하면 연결이 다운됩니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 페일오버 관련 이벤트의 이벤트 세부 정보 페이지를 표시할 때 페이지의 요약 정보를 검토하여 이벤트의 긴급성, 문제의 가능한 원인 및 가능한 문제 해결 방법을 결정할 수 있습니다.



== 시작하기 전에

운영자, OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.



== 이 작업에 대해

이 예제 시나리오에서는 이벤트 세부 정보 페이지에 제공된 이벤트 요약에 스토리지 페일오버 상호 연결 연결 연결 해제 상태에 대한 다음 정보가 포함됩니다.

[listing]
----
Event: Storage Failover Interconnect One or More Links Down

Summary

Severity: Warning
State: New
Impact Level: Risk
Impact Area: Availability
Source: aardvark
Source Type: Node
Acknowledged By:
Resolved By:
Assigned To:
Cause: At least one storage failover interconnected link
       between the nodes aardvark and bonobo is down.
       RDMA interconnect is up (Link0 up, Link1 down)
----
예제 이벤트 정보는 HA 쌍 노드 aardvark와 bonobo 간의 스토리지 페일오버 상호 연결 링크 Link1이 중단되었지만 Apple과 Boy 사이의 link0이 활성 상태임을 나타냅니다. 하나의 링크가 활성화되었기 때문에 RDMA(원격 동적 메모리 액세스)가 계속 작동하고 있으며 스토리지 페일오버 작업을 계속 수행할 수 있습니다.

그러나 링크 장애 및 스토리지 페일오버 보호를 모두 완전히 비활성화하기 위해 Link1이 다운된 이유를 추가로 진단하기로 결정합니다.



== 단계

. Event * details 페이지에서 Source 필드에 지정된 이벤트에 대한 링크를 클릭하여 스토리지 페일오버 상호 연결 링크 다운 상태와 관련된 다른 이벤트에 대한 자세한 정보를 얻을 수 있습니다.
+
이 예제에서 이벤트의 소스는 aardvark라는 노드입니다. 이 노드 이름을 클릭하면 상태/클러스터 세부 정보 페이지의 노드 탭에 영향을 받는 HA 쌍, aardvark 및 bonobo에 대한 HA 세부 정보가 표시되고, 영향을 받는 HA 쌍에서 최근에 발생한 다른 이벤트가 표시됩니다.

. 이벤트에 대한 자세한 내용은 * HA 세부 정보 * 를 참조하십시오.
+
이 예제에서 관련 정보는 Events 테이블에 있습니다. 이 테이블에는 "스토리지 페일오버 연결 하나 이상의 링크 다운" 이벤트, 이벤트가 생성된 시간, 이 이벤트가 발생한 노드 등이 표시됩니다.





== 작업을 마친 후

HA Details의 노드 위치 정보를 사용하여 영향을 받는 HA Pair 노드에서 스토리지 페일오버 문제의 물리적 검사 및 복구를 요청하거나 직접 수행합니다.
