---
permalink: health-checker/task-restoring-database-backup-on-a-virtual-machine.html 
sidebar: sidebar 
keywords:  
summary: 데이터 손실 또는 데이터 손상이 발생할 경우 복원 기능을 사용하여 최소한의 손실로 Unified Manager를 이전의 안정적인 상태로 복원할 수 있습니다. Unified Manager 유지보수 콘솔을 사용하여 가상 머신에서 Unified Manager 데이터베이스를 복구할 수 있습니다. 
---
= 가상 시스템에서 데이터베이스 백업을 복원합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 손실 또는 데이터 손상이 발생할 경우 복원 기능을 사용하여 최소한의 손실로 Unified Manager를 이전의 안정적인 상태로 복원할 수 있습니다. Unified Manager 유지보수 콘솔을 사용하여 가상 머신에서 Unified Manager 데이터베이스를 복구할 수 있습니다.



== 시작하기 전에

* 유지보수 사용자 자격 증명이 있어야 합니다.
* Unified Manager 백업 파일이 로컬 시스템에 있어야 합니다.
* 백업 파일은 이어야 합니다 `.7z` 유형.




== 이 작업에 대해

백업 호환성은 플랫폼과 버전에 따라 다릅니다. 가상 어플라이언스에서 다른 가상 어플라이언스로, 또는 가상 어플라이언스에서 Red Hat Enterprise Linux 또는 CentOS 시스템으로 백업을 복원할 수 있습니다.

[NOTE]
====
원래 백업 파일이 생성된 시스템과 다른 가상 어플라이언스에서 복구 작업을 수행할 때 새 vApp의 유지 보수 사용자 이름 및 암호는 원래 vApp의 자격 증명과 동일해야 합니다.

====


== 단계

. vSphere 클라이언트에서 Unified Manager 가상 머신을 찾은 다음 * Console * 탭을 선택합니다.
. 콘솔 창을 클릭한 다음 사용자 이름과 암호를 사용하여 유지보수 콘솔에 로그인합니다.
. 주 메뉴 * 에서 * 시스템 구성 * 옵션의 번호를 입력합니다.
. 시스템 구성 메뉴 * 에서 * OCUM 백업에서 복원 * 옵션에 대한 번호를 입력합니다.
. 메시지가 표시되면 백업 파일의 절대 경로를 입력합니다.
+
[listing]
----
Bundle to restore from: opt/netapp/data/ocum-backup/UM_9.4.N151112.0947_backup_unix_02-25-2018-11-41.7z
----
+
복원 작업이 완료되면 Unified Manager에 로그인할 수 있습니다.





== 작업을 마친 후

백업을 복원한 후 OnCommand Workflow Automation 서버가 작동하지 않으면 다음 단계를 수행하십시오.

. Workflow Automation 서버에서 Unified Manager 서버의 IP 주소를 최신 시스템을 가리키도록 변경합니다.
. 1단계에서 획득에 실패한 경우 Unified Manager 서버에서 데이터베이스 암호를 재설정합니다.

