---
permalink: health-checker/task-determining-if-a-volume-is-offline-because-of-broken-disks-in-an-aggregate.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager 웹 UI를 사용하면 RAID 디스크 문제로 인해 호스트 애그리게이트는 오프라인 상태가 되기 때문에 볼륨이 오프라인 상태가 될 가능성을 확인 또는 제거할 수 있습니다. 
---
= Aggregate의 손상된 디스크로 인해 볼륨이 오프라인 상태인지 확인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager 웹 UI를 사용하면 RAID 디스크 문제로 인해 호스트 애그리게이트는 오프라인 상태가 되기 때문에 볼륨이 오프라인 상태가 될 가능성을 확인 또는 제거할 수 있습니다.



== 시작하기 전에

운영자, OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.



== 이 작업에 대해

볼륨 오프라인 상태가 호스팅 애그리게이트를 오프라인으로 전환하는 RAID 디스크 문제로 인한 것인지 확인하려면 다음 작업을 수행하십시오.



== 단계

. Health/Volume * 세부 정보 페이지의 * Related Devices *(관련 장치 *) 창에 있는 Aggregate(집계) 아래에 표시된 하이퍼텍스트 링크를 찾아 클릭합니다.
+
상태/집계 세부 정보 페이지에는 호스팅 애그리게이트의 온라인 또는 오프라인 상태가 표시됩니다. 집계 상태가 온라인인 경우 RAID 디스크 문제는 볼륨이 오프라인 상태가 되는 원인이 아닙니다.

. 집계 상태가 오프라인인 경우 * 디스크 정보 * 를 클릭하고 * 디스크 정보 * 탭의 * 이벤트 * 목록에서 손상된 디스크 이벤트를 찾습니다.
. 손상된 디스크를 더 자세히 식별하려면 * Related Devices *(관련 장치 *) 창의 Cluster(클러스터) 아래에 표시된 하이퍼텍스트 링크를 클릭합니다.
+
상태/클러스터 세부 정보 페이지가 표시됩니다.

. Disks * 를 클릭한 다음 * Filters * 창에서 * Broken * 을 선택하여 손상된 상태의 모든 디스크를 나열합니다.
+
깨진 상태의 디스크로 인해 호스트 애그리게이트의 오프라인 상태가 발생한 경우 해당 애그리게이트의 이름이 영향받는 애그리게이트 열에 표시됩니다.





== 작업을 마친 후

손상된 RAID 디스크와 그로 인한 오프라인 호스트 집계로 인해 볼륨 오프라인 상태가 발생했는지 확인한 후 해당 관리자 또는 운영자에게 문의하여 손상된 디스크를 수동으로 교체하고 애그리게이트를 다시 온라인으로 전환합니다.
