---
permalink: health-checker/task-configuring-global-health-threshold-settings.html 
sidebar: sidebar 
keywords:  
summary: 용량, 증가, 스냅샷 예약, 할당량, inode에 대한 글로벌 상태 임계값 조건을 구성하여 애그리게이트, 볼륨 및 qtree 크기를 효과적으로 모니터링할 수 있습니다. 지연 임계값을 초과하는 이벤트를 생성하기 위한 설정을 편집할 수도 있습니다. 
---
= 전역 상태 임계값 설정 구성 중
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
용량, 증가, 스냅샷 예약, 할당량, inode에 대한 글로벌 상태 임계값 조건을 구성하여 애그리게이트, 볼륨 및 qtree 크기를 효과적으로 모니터링할 수 있습니다. 지연 임계값을 초과하는 이벤트를 생성하기 위한 설정을 편집할 수도 있습니다.



== 이 작업에 대해

글로벌 상태 임계값 설정은 애그리게이트, 볼륨 등 연결되어 있는 모든 개체에 적용됩니다. 임계값을 넘어지면 이벤트가 생성되고 경고가 구성된 경우 경고 알림이 전송됩니다. 임계값 기본값은 권장 값으로 설정되지만 특정 요구에 맞게 이벤트 간격을 생성하도록 수정할 수 있습니다. 임계값이 변경되면 다음 모니터링 주기에서 이벤트가 생성되거나 폐기됩니다.

글로벌 상태 임계값 설정은 구성/상태 임계값 페이지에서 액세스할 수 있습니다. 재고 페이지 또는 해당 객체의 세부 정보 페이지에서 개별 객체에 대한 임계값 설정을 수정할 수도 있습니다.



== 선택

* xref:task-configuring-global-aggregate-health-threshold-values.adoc[글로벌 애그리게이트 상태 임계값 구성]
+
모든 애그리게이트의 용량, 증가 및 스냅샷 복사본에 대한 상태 임계값 설정을 구성하여 모든 임계값 위반을 추적할 수 있습니다.

* xref:task-configuring-global-volume-health-threshold-values.adoc[글로벌 볼륨 상태 임계값을 구성하는 중입니다]
+
용량, 스냅샷 복사본, qtree 할당량, 볼륨 증가, 덮어쓰기 예약 공간에 대한 상태 임계값 설정을 편집할 수 있습니다. 모든 볼륨에 대한 inode를 통해 임계값 위반을 추적할 수 있습니다.

* xref:task-configuring-global-qtree-health-threshold-values.adoc[글로벌 qtree 상태 임계값을 구성하는 중입니다]
+
모든 qtree의 용량에 대한 상태 임계값 설정을 편집하여 모든 임계값 위반을 추적할 수 있습니다.

* xref:task-configuring-lag-threshold-settings-for-unmanaged-protection-relationships.adoc[관리되지 않는 보호 관계에 대한 지연 상태 임계값 설정 편집]
+
경고 또는 오류 지연 시간 비율을 늘리거나 줄이면 사용자의 요구에 더 적합한 간격으로 이벤트가 생성됩니다.


