---
permalink: health-checker/task-performing-corrective-action-for-a-flashcard-offline.html 
sidebar: sidebar 
keywords:  
summary: 플래시 카드 오프라인 이벤트 세부 정보 페이지의 원인 필드에서 설명을 검토한 후 조건을 해결하는 데 도움이 되는 추가 정보를 검색할 수 있습니다. 
---
= 플래시 카드에 대한 수정 조치를 오프라인으로 수행합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
플래시 카드 오프라인 이벤트 세부 정보 페이지의 원인 필드에서 설명을 검토한 후 조건을 해결하는 데 도움이 되는 추가 정보를 검색할 수 있습니다.



== 시작하기 전에

운영자, OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.



== 이 작업에 대해

이 예제 시나리오에서는 이벤트 세부 정보 페이지에 제공된 이벤트 요약에 오프라인 플래시 카드 상태에 대한 다음 정보가 포함됩니다.

[listing]
----
Severity: Critical
State: New
Impact Level: Incident
Impact Area: Availability
Source: alpha-node
Source Type: Node
Acknowledged By:
Resolved By:
Assigned To:
Cause: Flash cards at slot numbers 3 are offline.
Alert Settings:
----
이벤트 정보는 클러스터 노드 "alpha-node"의 슬롯 3에 설치된 플래시 카드가 오프라인 상태임을 나타냅니다.

이 정보는 플래시 카드의 오프라인 상태를 특정 클러스터 노드의 특정 슬롯에 현지화하지만 플래시 카드가 오프라인 상태인 이유는 제안하지 않습니다.



== 단계

. 플래시 카드의 오프라인 상태를 진단하는 데 도움이 되는 자세한 정보를 보려면 이벤트 소스의 이름을 클릭합니다.
+
이 예에서 이벤트 소스는 ""알파 노드"" 클러스터 노드입니다. 이 노드 이름을 클릭하면 영향을 받는 클러스터에 대한 상태/클러스터 세부 정보 페이지의 노드 탭에 HA 세부 정보가 표시됩니다. 표시된 HA Details는 해당 노드가 속한 HA 쌍에 대한 정보를 표시합니다.

+
이 예에서 관련 정보는 HA 세부 정보의 이벤트 요약 테이블에 있습니다. 이 표에는 플래시 카드의 오프라인 이벤트, 이벤트가 생성된 시간, 이 이벤트가 발생한 클러스터 노드가 지정됩니다.

. ONTAP CLI 또는 OnCommand System Manager를 사용하여 영향을 받는 클러스터의 EMS(이벤트 관리자 시스템) 로그에 액세스합니다.
+
이 예제에서는 이벤트 이름, 이벤트 시간 및 이벤트 소스를 사용하여 이 이벤트에 대한 EMS 보고서를 찾습니다. 이벤트에 대한 EMS 보고서에는 이벤트에 대한 자세한 설명과 이벤트가 나타내는 상황을 해결하는 데 도움이 되는 조언이 포함되어 있습니다.





== 작업을 마친 후

문제를 진단한 후 해당 관리자 또는 운영자에게 연락하여 플래시 카드를 다시 온라인 상태로 전환하는 데 필요한 수동 단계를 완료하십시오.
