---
permalink: health-checker/task-reversing-protection-relationships-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: 재해로 인해 보호 관계의 소스 볼륨이 비활성화되면 소스를 복구하거나 교체하는 동안 대상 볼륨을 사용하여 데이터를 읽기/쓰기로 변환하여 제공할 수 있습니다. 소스를 다시 사용하여 데이터를 수신할 수 있으면 역재동기화 작업을 사용하여 역방향의 관계를 설정하여 소스의 데이터를 읽기/쓰기 대상의 데이터와 동기화할 수 있습니다. 
---
= Health/Volume(상태/볼륨) 세부 정보 페이지에서 보호 관계를 반대로 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
재해로 인해 보호 관계의 소스 볼륨이 비활성화되면 소스를 복구하거나 교체하는 동안 대상 볼륨을 사용하여 데이터를 읽기/쓰기로 변환하여 제공할 수 있습니다. 소스를 다시 사용하여 데이터를 수신할 수 있으면 역재동기화 작업을 사용하여 역방향의 관계를 설정하여 소스의 데이터를 읽기/쓰기 대상의 데이터와 동기화할 수 있습니다.



== 시작하기 전에

* OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* Workflow Automation을 설정해야 합니다.
* 관계가 SnapVault 관계여야 합니다.
* 보호 관계가 이미 있어야 합니다.
* 보호 관계가 끊어야 합니다.
* 소스와 대상이 모두 온라인 상태여야 합니다.
* 소스가 다른 데이터 보호 볼륨의 대상이 아니어야 합니다.




== 이 작업에 대해

* 이 작업을 수행하면 공통 스냅샷 복사본의 데이터보다 최신 소스의 데이터가 삭제됩니다.
* 역재동기화 관계에 생성된 정책 및 스케줄은 원래 보호 관계에 있는 정책과 동일합니다.
+
정책과 스케줄이 없으면 생성됩니다.





== 단계

. 상태/볼륨 * 세부 정보 페이지의 * 보호 * 탭에서 소스와 대상을 반대로 이동할 SnapMirror 관계를 찾아 마우스 오른쪽 단추로 클릭합니다.
. 메뉴에서 * Reverse Resync * 를 선택합니다.
+
역방향 재동기화 대화 상자가 표시됩니다.

. 역방향 재동기화* 대화 상자에 표시된 관계가 역방향 재동기화 작업을 수행할 관계인지 확인한 다음 * 제출 * 을 클릭합니다.
+
역방향 재동기화 대화 상자가 닫히고 상태/볼륨 세부 정보 페이지 맨 위에 작업 링크가 표시됩니다.

. 상태/볼륨 * 세부 정보 페이지에서 * 작업 보기 * 를 클릭하여 각 역방향 재동기화 작업의 상태를 추적합니다.
+
필터링된 작업 목록이 표시됩니다.

. 브라우저의 뒤로 화살표를 클릭하여 * 상태/볼륨 * 세부 정보 페이지로 돌아갑니다.
+
모든 작업 작업이 성공적으로 완료되면 역방향 재동기화 작업이 완료됩니다.


