---
permalink: config/reference-identity-provider-requirements-um.html 
sidebar: sidebar 
keywords:  
summary: 'ID 공급자 \(IDP\)를 사용하여 모든 원격 사용자에 대해 SAML 인증을 수행하도록 Unified Manager를 구성하는 경우 Unified Manager에 성공적으로 연결되도록 몇 가지 필수 구성 설정을 알고 있어야 합니다.' 
---
= ID 공급자 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ID 공급자(IDP)를 사용하여 모든 원격 사용자에 대해 SAML 인증을 수행하도록 Unified Manager를 구성하는 경우 Unified Manager에 성공적으로 연결되도록 몇 가지 필수 구성 설정을 알고 있어야 합니다.

IDP 서버에 Unified Manager URI 및 메타데이터를 입력해야 합니다. 이 정보는 Unified ManagerSAML 인증 페이지에서 복사할 수 있습니다. Unified Manager는 SAML(Security Assertion Markup Language) 표준의 서비스 공급자(SP)로 간주됩니다.



== 지원되는 암호화 표준

* AES(고급 암호화 표준): AES-128 및 AES-256
* 보안 해시 알고리즘(SHA): SHA-1 및 SHA-256




== 검증된 ID 공급자

* 시바볼레스
* ADFS(Active Directory Federation Services)




== ADFS 구성 요구 사항

* Unified Manager가 이 기반 당사자 신뢰 항목에 대한 ADFS SAML 응답을 구문 분석하는 데 필요한 세 가지 청구 규칙을 다음 순서로 정의해야 합니다.
+
|===
| 청구 규칙 | 값 


 a| 
SAM-계정-이름
 a| 
이름 ID입니다



 a| 
SAM-계정-이름
 a| 
urn:OID: 0.9.2342.19200300.100.1.1



 a| 
토큰 그룹 -- 비정규화된 이름
 a| 
urn:OID: 1.3.6.1.4.1.5923.1.5.1.1

|===
* 인증 방법을 ""양식 인증""으로 설정해야 합니다. 그렇지 않을 경우 Internet Explorer를 사용할 때 Unified Manager에서 로그아웃할 때 오류가 발생할 수 있습니다. 다음 단계를 수행하십시오.
+
.. ADFS 관리 콘솔을 엽니다.
.. 왼쪽 트리 뷰에서 Authentication Policies 폴더를 클릭합니다.
.. 오른쪽의 작업 에서 글로벌 기본 인증 정책 편집 을 클릭합니다.
.. 인트라넷 인증 방법을 기본값인 "Windows 인증" 대신 " 양식 인증"으로 설정합니다.


* 경우에 따라 Unified Manager 보안 인증서가 CA 서명되면 IDP를 통한 로그인이 거부됩니다. 이 문제를 해결하기 위한 두 가지 해결 방법이 있습니다.
+
** 링크에 나와 있는 지침에 따라 연결된 CA 인증자에 대한 ADFS 서버의 해지 확인을 비활성화합니다.
+
http://www.torivar.com/2016/03/22/adfs-3-0-disable-revocation-check-windows-2012-r2/[]

** CA 서버가 ADFS 서버 내에 상주하여 Unified Manager 서버 인증서 요청에 서명하도록 합니다.






== 기타 구성 요구 사항

* Unified Manager 시간 차이는 5분으로 설정되어 있으므로 IDP 서버와 Unified Manager 서버 간의 시간 차이는 5분 이내이거나 인증이 실패합니다.
* 사용자가 Internet Explorer를 사용하여 Unified Manager에 액세스하려고 하면 다음 메시지가 표시될 수 있습니다. * 웹 사이트에서 페이지를 표시할 수 없습니다 *. 이 경우, 이러한 사용자는 * 도구 * > * 인터넷 옵션 * > * 고급 * 에서 "HTTP 오류 메시지 표시" 옵션을 선택 해제하십시오.

