---
permalink: config/task-changing-the-unified-manager-host-name-on-rhel-or-centos.html 
sidebar: sidebar 
keywords:  
summary: 경우에 따라 Unified Manager를 설치한 Red Hat Enterprise Linux 또는 CentOS 시스템의 호스트 이름을 변경할 수 있습니다. 예를 들어 Linux 시스템을 나열할 때 호스트 이름을 Unified Manager 서버를 유형, 작업 그룹 또는 모니터링되는 클러스터 그룹별로 더 쉽게 식별하도록 변경할 수 있습니다. 
---
= Linux 시스템에서 Unified Manager 호스트 이름 변경
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
경우에 따라 Unified Manager를 설치한 Red Hat Enterprise Linux 또는 CentOS 시스템의 호스트 이름을 변경할 수 있습니다. 예를 들어 Linux 시스템을 나열할 때 호스트 이름을 Unified Manager 서버를 유형, 작업 그룹 또는 모니터링되는 클러스터 그룹별로 더 쉽게 식별하도록 변경할 수 있습니다.



== 시작하기 전에

Unified Manager가 설치된 Linux 시스템에 대한 루트 사용자 액세스 권한이 있어야 합니다.



== 이 작업에 대해

호스트 이름(또는 호스트 IP 주소)을 사용하여 Unified Manager 웹 UI에 액세스할 수 있습니다. 배포 중에 네트워크에 대한 정적 IP 주소를 구성한 경우 네트워크 호스트의 이름을 지정했을 것입니다. DHCP를 사용하여 네트워크를 구성한 경우 DNS 서버에서 호스트 이름을 가져와야 합니다.

호스트 이름이 할당된 방식에 관계없이 호스트 이름을 변경하고 새 호스트 이름을 사용하여 Unified Manager 웹 UI에 액세스하려는 경우 새 보안 인증서를 생성해야 합니다.

호스트 이름 대신 서버의 IP 주소를 사용하여 웹 UI에 액세스하는 경우 호스트 이름을 변경할 경우 새 인증서를 생성할 필요가 없습니다. 그러나 인증서의 호스트 이름이 실제 호스트 이름과 일치하도록 인증서를 업데이트하는 것이 가장 좋습니다. 새 인증서는 Linux 시스템을 다시 시작할 때까지 적용되지 않습니다.

Unified Manager에서 호스트 이름을 변경하는 경우 WFA(OnCommand Workflow Automation)에서 호스트 이름을 수동으로 업데이트해야 합니다. 호스트 이름은 WFA에서 자동으로 업데이트되지 않습니다.



== 단계

. 수정할 Unified Manager 시스템의 루트 사용자로 로그인합니다.
. 다음 명령을 표시된 순서대로 입력하여 Unified Manager 소프트웨어 및 관련 MySQL 소프트웨어를 중지합니다.
. Linux를 사용하여 호스트 이름을 변경합니다 `hostnamectl` 명령: `hostnamectl set-hostname new_FQDN`
+
`hostnamectl set-hostname nuhost.corp.widget.com`

. 서버에 대한 HTTPS 인증서를 다시 생성합니다.``/opt/netapp/essentials/bin/cert.sh create``
. 네트워크 서비스를 다시 시작합니다. `service network restart`
. 서비스가 다시 시작된 후 새 호스트 이름이 스스로 ping을 수행할 수 있는지 확인합니다. `ping new_hostname`
+
`ping nuhost`

+
이 명령은 원래 호스트 이름에 대해 이전에 설정된 것과 동일한 IP 주소를 반환해야 합니다.

. 호스트 이름 변경을 완료하고 확인한 후 다음 명령을 표시된 순서대로 입력하여 Unified Manager를 다시 시작합니다.

