---
permalink: install/concept-requirements-and-limitations-for-unified-manager-in-mscs.html 
sidebar: sidebar 
keywords:  
summary: 페일오버 클러스터링 환경에 Unified Manager를 설치하기 전에 클러스터 노드가 Unified Manager를 지원하도록 올바르게 구성되어 있는지 확인해야 합니다. 
---
= 페일오버 클러스터링 환경의 Unified Manager에 대한 요구사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
페일오버 클러스터링 환경에 Unified Manager를 설치하기 전에 클러스터 노드가 Unified Manager를 지원하도록 올바르게 구성되어 있는지 확인해야 합니다.

페일오버 클러스터 구성이 다음 요구 사항을 충족하는지 확인해야 합니다.

* 두 클러스터 노드 모두 동일한 버전의 Microsoft Windows Server를 실행해야 합니다.
* 두 클러스터 노드에서 동일한 경로를 사용하여 동일한 버전의 Unified Manager를 설치해야 합니다.
* 페일오버 클러스터링은 두 노드에 모두 설치 및 설정되어야 합니다.
+
자세한 내용은 Microsoft 설명서를 참조하십시오.

* 스토리지 백엔드로 공유 데이터 디스크를 생성하려면 Fibre Channel 스위치 패브릭 또는 iSCSI 기반 스토리지를 사용해야 합니다
* 선택 사항: Windows용 SnapDrive를 사용하여 고가용성 설정의 두 노드에서 액세스할 수 있는 공유 위치를 생성해야 합니다.
+
공유 위치 설치 및 만들기에 대한 자세한 내용은 _SnapDrive for Windows 설치 안내서_를 참조하십시오.

+
스토리지 시스템의 명령줄 인터페이스를 사용하여 LUN을 관리할 수도 있습니다. 자세한 내용은 SnapDrive for Windows 호환성 매트릭스를 참조하십시오.

* 와 함께 Perl이 설치되어 있어야 합니다 `XML::LibXML` 및 `File::chdir` 스크립트 작동 모듈
* 클러스터 설정에는 2개의 노드만 있어야 합니다.
* 장애 조치 클러스터링에는 노드 및 디스크 과반수 쿼럼을 사용해야 합니다.
* Unified Manager에 액세스하려면 클러스터 글로벌 IP 주소로 사용할 해당 FQDN을 사용하여 공유 IP 주소를 구성해야 합니다.
* 두 노드의 Unified Manager 유지보수 사용자 암호는 동일해야 합니다.
* IPv4 IP 주소만 사용해야 합니다.

