---
permalink: install/concept-virtual-infrastructure-or-hardware-system-requirements.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager를 가상 인프라에 설치하거나 물리적 시스템에 설치하는 경우, 메모리, CPU 및 디스크 공간에 대한 최소 요구사항을 충족해야 합니다. 
---
= 가상 인프라 및 하드웨어 시스템 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 가상 인프라에 설치하거나 물리적 시스템에 설치하는 경우, 메모리, CPU 및 디스크 공간에 대한 최소 요구사항을 충족해야 합니다.

다음 표에는 메모리, CPU 및 디스크 공간 리소스에 권장되는 값이 나와 있습니다. 이러한 값은 Unified Manager가 허용 가능한 성능 수준을 충족할 수 있도록 검증을 받았습니다.

|===
| 하드웨어 구성 | 권장 설정 


 a| 
RAM
 a| 
12GB(최소 요구 사항 8GB)



 a| 
프로세서
 a| 
CPU 4개



 a| 
CPU 사이클 용량입니다
 a| 
총 9572MHz(최소 요구 사항 9572MHz)



 a| 
사용 가능한 디스크 공간
 a| 
VMware:

* 5GB(씬 프로비저닝)
* 152GB(씩 프로비저닝)




 a| 
Red Hat 또는 CentOS: 150GB, 여기서 용량은 다음과 같이 할당됩니다.

* 루트 파티션에 50GB가 할당됩니다
* 에 할당된 사용 가능한 디스크 공간 100GB입니다 `/opt/netapp/data` LVM 드라이브 또는 타겟 시스템에 연결된 별도의 로컬 디스크에 마운트되는 디렉토리입니다


[NOTE]
====
를 클릭합니다 `/tmp` 디렉토리에는 최소 10GB의 사용 가능한 공간과 가 있어야 합니다 `/var/log` 디렉토리에는 최소 16GB의 여유 공간이 있어야 합니다.

==== a| 
Windows: 150GB, 여기서 용량은 다음과 같이 할당됩니다.

* 설치 디렉토리를 위한 100GB의 디스크 공간
* MySQL 데이터 디렉토리용 50GB의 디스크 공간


|===
적은 용량의 메모리가 있는 시스템에 Unified Manager를 설치할 수 있지만 권장되는 12GB RAM을 사용하면 최적의 성능을 위해 충분한 메모리를 사용할 수 있으며, 따라서 시스템이 구성 증가에 따라 추가 클러스터 및 스토리지 오브젝트를 수용할 수 있습니다. Unified Manager가 구축된 VM에서 메모리 제한을 설정하지 않아야 하며 소프트웨어에서 시스템에서 할당된 메모리를 사용하지 못하도록 하는 기능(예: 풍선 벌루닝)을 사용하면 안 됩니다.

또한 Unified Manager의 두 번째 인스턴스를 설치하기 전에 Unified Manager의 단일 인스턴스에서 모니터링할 수 있는 노드 수에 제한이 있습니다. 자세한 내용은 _모범 사례 가이드_를 참조하십시오.

http://www.netapp.com/us/media/tr-4621.pdf["기술 보고서 4621: Unified Manager 모범 사례 가이드"]

메모리 페이지 스와핑은 시스템 및 관리 응용 프로그램의 성능에 부정적인 영향을 줍니다. 전체 호스트 활용률로 인해 CPU 리소스를 사용하지 않는 경우 성능이 저하될 수 있습니다.



== 전용 사용 요구 사항

Unified Manager를 설치하는 물리적 또는 가상 시스템은 Unified Manager에만 사용해야 하며 다른 애플리케이션과 공유해서는 안 됩니다. 다른 애플리케이션은 시스템 리소스를 소모하며 Unified Manager의 성능을 크게 줄일 수 있습니다.



== 백업에 필요한 공간 요구 사항

Unified Manager 백업 및 복원 기능을 사용하려면 "데이터" 디렉토리 또는 디스크에 150GB의 공간이 있도록 추가 용량을 할당해야 합니다. 백업은 로컬 대상 또는 원격 대상에 쓸 수 있습니다. 모범 사례는 최소 150GB의 공간이 있는 Unified Manager 호스트 시스템 외부의 원격 위치를 식별하는 것입니다.



== 호스트 연결 요구 사항

Unified Manager를 설치하는 물리적 시스템 또는 가상 시스템은 성공적으로 구성할 수 있도록 구성해야 합니다 `ping` 호스트 자체의 호스트 이름입니다. IPv6 구성의 경우, 이를 확인해야 합니다 `ping6` 호스트 이름에 Unified Manager 설치가 성공적으로 수행되었는지 확인합니다.

호스트 이름(또는 호스트 IP 주소)을 사용하여 제품 웹 UI에 액세스할 수 있습니다. 배포 중에 네트워크에 대한 정적 IP 주소를 구성한 경우 네트워크 호스트의 이름을 지정합니다. DHCP를 사용하여 네트워크를 구성한 경우 DNS에서 호스트 이름을 얻어야 합니다.

사용자가 FQDN(정규화된 도메인 이름) 또는 IP 주소를 사용하는 대신 짧은 이름을 사용하여 Unified Manager에 액세스할 수 있도록 하려는 경우 네트워크 구성에서 이 짧은 이름을 유효한 FQDN으로 해석해야 합니다.



== 탑재됨 `/opt/netapp` 또는 `/opt/netapp/data` 요구 사항

마운트할 수 있습니다 `/opt/netapp` 또는 `/opt/netapp/data` NAS 또는 SAN 디바이스에서 원격 마운트 지점을 사용하면 확장 문제가 발생할 수 있습니다. 원격 마운트 지점을 사용하는 경우 SAN 또는 NAS 네트워크의 용량이 Unified Manager의 I/O 요구 사항을 충분히 충족하는지 확인합니다. 이 용량은 모니터링하고 있는 클러스터 및 스토리지 오브젝트의 수에 따라 달라질 수 있으며 증가할 수 있습니다.

을(를) 장착한 경우 `/opt/netapp` 또는 `/opt/netapp/data` 루트 파일 시스템 및 사용자 환경에서 SELinux를 설정한 경우 마운트된 디렉토리에 대해 올바른 컨텍스트를 설정해야 합니다.

항목을 참조하십시오 xref:task-selinux-requirements-for-mounting-opt-netapp-or-opt-netapp-data-on-an-nfs-or-cifs-share.adoc[NFS 또는 CIFS 공유에 /opt/NetApp 또는 /opt/NetApp/데이터를 마운트하기 위한 SELinux 요구 사항] 올바른 SELinux 컨텍스트를 설정하는 방법에 대한 자세한 내용은 을 참조하십시오.
