---
permalink: install/concept-requirements-for-unified-manager-in-vcs.html 
sidebar: sidebar 
keywords:  
summary: 'VCS(Veritas Cluster Server) 환경에 Unified Manager를 설치하기 전에 클러스터 노드가 Unified Manager를 지원하도록 올바르게 구성되었는지 확인해야 합니다.' 
---
= VCS의 Unified Manager에 대한 요구사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VCS(Veritas Cluster Server) 환경에 Unified Manager를 설치하기 전에 클러스터 노드가 Unified Manager를 지원하도록 올바르게 구성되었는지 확인해야 합니다.

VCS 구성이 다음 요구 사항을 충족하는지 확인해야 합니다.

* 두 클러스터 노드 모두 지원되는 운영 체제 버전을 실행하고 있어야 합니다.
* 두 클러스터 노드에서 동일한 경로를 사용하여 동일한 버전의 Unified Manager를 설치해야 합니다.
* 두 노드의 MySQL 사용자는 동일한 사용자 ID와 그룹 ID를 가져야 합니다.
* 네이티브 ext3, ext4 파일 시스템 및 LVM(Logical Volume Manager)을 사용해야 합니다.
* Unified Manager는 파이버 채널(FC) 또는 iSCSI를 통해 스토리지 시스템에 연결되어 있어야 합니다.
+
또한 FC 링크가 활성화되어 있고 스토리지 시스템에서 생성된 LUN을 두 클러스터 노드에서 모두 액세스할 수 있는지 확인해야 합니다.

* 공유 데이터 디스크에는 Unified Manager 데이터베이스, 보고서, 인증서, 스크립트 플러그인 폴더에 필요한 공간(최소 80GB)이 있어야 합니다.
* 각 시스템에 노드 간 통신을 위한 네트워크 인터페이스와 노드 간 통신을 위한 네트워크 인터페이스 등 최소 두 개의 네트워크 인터페이스를 설정해야 합니다.
+
노드-클라이언트 통신에 사용되는 네트워크 인터페이스의 이름은 두 시스템 모두에서 동일해야 합니다.

* 클러스터 노드 간에 별도의 하트비트 링크를 설정해야 합니다. 그렇지 않으면 네트워크 인터페이스를 사용하여 클러스터 노드 간에 통신합니다.
* 선택 사항: SnapDrive for UNIX는 고가용성 설정에서 두 노드에 액세스할 수 있는 공유 위치를 생성하는 데 사용해야 합니다.
+
공유 위치 설치 및 생성에 대한 자세한 내용은 _SnapDrive for UNIX 설치 및 관리 가이드_를 참조하십시오. SnapDrive 또는 스토리지 시스템 명령줄 인터페이스를 사용하여 LUN을 관리할 수도 있습니다. 자세한 내용은 UNIX용 SnapDrive 호환성 매트릭스를 참조하십시오.

* SnapDrive 및 VCS 애플리케이션에서 추가 RAM을 사용할 수 있어야 합니다.

