---
permalink: install/reference-red-hat-and-centos-software-and-installation-requirements.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager를 설치하는 Linux 시스템에는 특정 버전의 운영 체제 및 지원 소프트웨어가 필요합니다. 
---
= Red Hat Enterprise Linux 및 CentOS 소프트웨어 및 설치 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 설치하는 Linux 시스템에는 특정 버전의 운영 체제 및 지원 소프트웨어가 필요합니다.



== 운영 체제 소프트웨어

Linux 시스템에는 다음 버전의 운영 체제와 지원 소프트웨어가 설치되어 있어야 합니다.

* Red Hat Enterprise Linux 또는 CentOS 64비트 버전 7.x
+
Red Hat Enterprise Linux 6.x는 Unified Manager 9.4부터 지원되지 않습니다.



지원되는 Red Hat Enterprise Linux 및 CentOS 버전의 전체 최신 목록은 상호 운용성 매트릭스를 참조하십시오.

http://mysupport.netapp.com/matrix["mysupport.netapp.com/matrix"]

다음과 같은 타사 패키지가 필요합니다.

* MySQL Community Edition 버전 5.7.23 이상(MySQL 리포지토리에서) 5.7 제품군 버전
* OpenJDK 버전 11(Red Hat Extra Enterprise Linux Server 리포지토리에서)
+
[NOTE]
====
Oracle Java는 Unified Manager 9.5부터 지원되지 않습니다.

====
* p7zip 버전 16.02 이상(Enterprise Linux용 Red Hat Extra Packages 리포지토리)


[NOTE]
====
Unified Manager를 실행한 후 타사 소프트웨어를 업그레이드하려면 먼저 Unified Manager를 종료해야 합니다. 타사 소프트웨어 설치가 완료되면 Unified Manager를 다시 시작할 수 있습니다.

====


== 사용자 인증 요구 사항

Red Hat Enterprise Linux 시스템 또는 CentOS 시스템에 Unified Manager 설치는 루트 사용자 또는 을 사용하여 비루트 사용자가 수행할 수 있습니다 `sudo` 명령.



== 설치 요구 사항

Red Hat Enterprise Linux 또는 CentOS 및 시스템에 관련 리포지토리를 설치하는 모범 사례는 다음과 같습니다.

* Red Hat 모범 사례에 따라 Red Hat Enterprise Linux 또는 CentOS를 설치해야 하며, "GUI를 사용하여 서버"를 선택해야 하는 다음 기본 옵션을 선택해야 합니다.
* Red Hat Enterprise Linux 또는 CentOS에 Unified Manager를 설치하는 동안 설치 프로그램이 필요한 모든 소프트웨어 종속성을 액세스하고 설치할 수 있도록 해당 저장소에 대한 액세스 권한이 시스템에 있어야 합니다.
* 의 경우 `yum` 설치 관리자 Red Hat Enterprise Linux 리포지토리에서 종속 소프트웨어를 찾으려면 Red Hat Enterprise Linux 설치 중에 또는 유효한 Red Hat 서브스크립션을 사용하여 시스템을 등록해야 합니다.
+
Red Hat 서브스크립션 관리자에 대한 자세한 내용은 Red Hat 설명서를 참조하십시오.

* 시스템에 필요한 타사 유틸리티를 설치하려면 EPEL(Enterprise Linux) 리포지토리용 추가 패키지를 활성화해야 합니다.
+
EPEL 리포지토리가 시스템에 구성되어 있지 않은 경우 리포지토리를 수동으로 다운로드하고 구성해야 합니다.

+
xref:task-manually-configuring-the-epel-repository.adoc[EPEL 리포지토리를 수동으로 구성합니다]

* 올바른 버전의 MySQL이 설치되어 있지 않은 경우 MySQL 리포지토리를 활성화하여 시스템에 MySQL 소프트웨어를 성공적으로 설치해야 합니다.
+
MySQL 리포지토리가 시스템에 구성되어 있지 않은 경우 리포지토리를 수동으로 다운로드하고 구성해야 합니다.

+
xref:task-manually-configuring-the-mysql-repository.adoc[MySQL 리포지토리를 수동으로 구성합니다]



시스템에 인터넷 액세스가 없고 저장소가 인터넷에 연결된 시스템에서 연결되지 않은 시스템으로 미러링되지 않은 경우 설치 지침에 따라 시스템의 외부 소프트웨어 종속성을 결정해야 합니다. 그런 다음 필요한 소프트웨어를 인터넷에 연결된 시스템에 다운로드하고 를 복사할 수 있습니다 `.rpm` Unified Manager를 설치하려는 시스템에 파일. 아티팩트 및 패키지를 다운로드하려면 를 사용해야 합니다 `yum install` 명령. 두 시스템이 동일한 운영 체제 버전을 실행하고 있고 해당 서브스크립션 라이센스가 적절한 Red Hat Enterprise Linux 또는 CentOS 버전인지 확인해야 합니다.

[NOTE]
====
여기에 나열된 리포지토리가 아닌 리포지토리에서 필요한 타사 소프트웨어를 설치해서는 안 됩니다. Red Hat 리포지토리에서 설치되는 소프트웨어는 Red Hat Enterprise Linux용으로 명시적으로 설계되었으며 Red Hat 모범 사례(디렉터리 레이아웃, 권한 등)를 준수합니다. 다른 지역의 소프트웨어는 이러한 지침을 따르지 않을 수 있으며, 이로 인해 Unified Manager 설치가 실패하거나 향후 업그레이드에 문제가 발생할 수 있습니다.

====


== 포트 443 요구 사항

Red Hat 및 CentOS의 일반 이미지는 포트 443에 대한 외부 액세스를 차단합니다. 브라우저에서 OnCommand 제품에 연결할 수 없는 경우 이 문제가 발생할 수 있습니다. 다음 명령을 실행하면 모든 외부 사용자 및 애플리케이션에 대해 포트 443에 액세스할 수 있습니다. `# firewall-cmd –zone=public –add-port=443/tcp –permanent; firewall-cmd –reload`

이 명령을 실행하기 전에 IT 부서에 문의하여 보안 정책에 다른 절차가 필요한지 확인하십시오.
