---
permalink: install/reference-windows-software-and-installation-requirements.html 
sidebar: sidebar 
keywords:  
summary: Windows에 Unified Manager를 성공적으로 설치하려면 Unified Manager가 설치된 시스템이 소프트웨어 요구사항을 충족하는지 확인해야 합니다. 
---
= Windows 소프트웨어 및 설치 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/
:pp: &#43;&#43;


[role="lead"]
Windows에 Unified Manager를 성공적으로 설치하려면 Unified Manager가 설치된 시스템이 소프트웨어 요구사항을 충족하는지 확인해야 합니다.



== 운영 체제 소프트웨어

Unified Manager는 64비트 영어 Windows 운영 체제에서만 실행됩니다. Unified Manager를 다음 Windows 플랫폼에 설치할 수 있습니다.

* Microsoft Windows Server 2012 Standard 및 Datacenter Edition
* Microsoft Windows Server 2012 R2 Standard 및 Datacenter Edition
* Microsoft Windows Server 2016 Standard 및 Datacenter Edition


[NOTE]
====
Windows Server 2012 R2에서는 Windows 업데이트 KB2919355가 대상 시스템에 설치되어 있어야 합니다. 그렇지 않으면 설치가 실패합니다.

====
Windows Server 2008은 이전 버전에서와 같이 지원되지 않습니다. 지원되는 Windows 버전의 전체 최신 목록은 상호 운용성 매트릭스 를 참조하십시오.

http://mysupport.netapp.com/matrix["mysupport.netapp.com/matrix"]

이 서버는 Unified Manager 실행 전용이어야 하며, 서버에 다른 애플리케이션을 설치할 수 없습니다.

다음과 같은 타사 패키지가 필요합니다.

* Microsoft Visual C&#43;&#43; 2015 재배포 가능 패키지 버전 14.0.24212
* Microsoft Visual C&#43;&#43; Visual Studio 2013 버전 12.0.40660용 재배포 가능 패키지
* MySQL Community Edition 버전 5.7.23 이상 버전(5.7 제품군)
* OpenJDK 버전 11
* p7zip 버전 18.01 이상


이러한 타사 패키지가 설치되어 있지 않으면 Unified Manager에서 설치 시 타사 패키지를 설치합니다.

[NOTE]
====
Unified Manager 9.5부터 OpenJDK는 Unified Manager 설치 패키지에 제공되어 자동으로 설치됩니다. Oracle Java는 Unified Manager 9.5부터 지원되지 않습니다.

====
MySQL이 사전 설치된 경우 다음 사항을 확인해야 합니다.

* 기본 포트를 사용하고 있습니다.
* 샘플 데이터베이스가 설치되지 않았습니다.
* 서비스 이름은 "MYSQL"입니다.


[NOTE]
====
Unified Manager를 실행한 후 타사 소프트웨어를 업그레이드하려면 먼저 Unified Manager를 종료해야 합니다. 타사 소프트웨어 설치가 완료되면 Unified Manager를 다시 시작할 수 있습니다.

====


== 설치 요구 사항

* Microsoft .NET 4.5.2 이상이 설치되어 있어야 합니다.
* 에 대해 2GB의 디스크 공간을 예약해야 합니다 `temp` 디렉토리를 클릭하여 설치 파일의 압축을 풉니다.
* Unified Manager MSI 파일을 캐시하려면 Windows 드라이브에서 2GB의 디스크 공간을 예약해야 합니다.
* Unified Manager를 설치할 Microsoft Windows Server는 FQDN(정규화된 도메인 이름)으로 구성해야 합니다 `ping` 호스트 이름 및 FQDN에 대한 응답이 성공했습니다.
* Microsoft IIS Worldwide 웹 게시 서비스를 비활성화하고 포트 80 및 443이 사용 가능한지 확인해야 합니다.
* 설치 중에 ""Windows Installer RDS 호환성""에 대한 원격 데스크톱 세션 호스트 설정이 비활성화되어 있는지 확인해야 합니다.
* UDP 포트 514는 사용 가능해야 하며 다른 서비스에서 사용할 수 없습니다.


[NOTE]
====
Unified Manager 설치 프로그램은 Windows Defender에서 다음 제외 사항을 구성합니다.

* Unified Manager 데이터 디렉토리(Windows Server 2016만 해당)
* Unified Manager 설치 디렉토리
* MySQL 데이터 디렉토리


서버에 다른 바이러스 백신 스캐너가 설치되어 있는 경우 이러한 제외 항목을 수동으로 구성해야 합니다.

====