---
permalink: install/reference-protocol-and-port-requirements.html 
sidebar: sidebar 
keywords: Unified Manager 
summary: 브라우저, API 클라이언트 또는 SSH를 사용하여 Unified Manager UI 및 API에서 필요한 포트에 액세스할 수 있어야 합니다. 필요한 포트와 프로토콜을 사용하면 Unified Manager 서버와 관리되는 스토리지 시스템, 서버 및 기타 구성 요소 간에 통신할 수 있습니다. 
---
= 프로토콜 및 포트 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
브라우저, API 클라이언트 또는 SSH를 사용하여 Unified Manager UI 및 API에서 필요한 포트에 액세스할 수 있어야 합니다. 필요한 포트와 프로토콜을 사용하면 Unified Manager 서버와 관리되는 스토리지 시스템, 서버 및 기타 구성 요소 간에 통신할 수 있습니다.



== Unified Manager 서버에 대한 연결

기본 포트는 항상 사용되므로 Unified Manager 웹 UI에 연결할 때 포트 번호를 지정할 필요가 없습니다. 예를 들어, Unified Manager가 항상 기본 포트에서 실행되므로 를 입력할 수 있습니다 `\https://<host>` 대신 `\https://<host>:443`. 기본 포트 번호는 변경할 수 없습니다.

Unified Manager 서버는 특정 프로토콜을 사용하여 다음 인터페이스에 액세스합니다.

|===
| 인터페이스 | 프로토콜 | 포트 | 설명 


 a| 
Unified Manager 웹 UI
 a| 
HTTP
 a| 
80
 a| 
Unified Manager 웹 UI에 액세스하는 데 사용되며 보안 포트 443으로 자동으로 리디렉션됩니다.



 a| 
API를 사용하는 Unified Manager 웹 UI 및 프로그램
 a| 
HTTPS
 a| 
443
 a| 
Unified Manager 웹 UI에 안전하게 액세스하거나 API 호출을 하는 데 사용되며 HTTPS를 통해서만 API 호출을 수행할 수 있습니다.



 a| 
유지보수 콘솔
 a| 
SSH/SFTP
 a| 
22
 a| 
유지보수 콘솔에 액세스하고 지원 번들을 검색하는 데 사용됩니다.



 a| 
Linux 명령줄
 a| 
SSH/SFTP
 a| 
22
 a| 
Red Hat Enterprise Linux 또는 CentOS 명령줄에 액세스하고 지원 번들을 검색하는 데 사용됩니다.



 a| 
MySQL 데이터베이스
 a| 
MySQL
 a| 
3306
 a| 
OnCommand 및 OnCommand Workflow Automation API Services에서 Unified Manager에 액세스할 수 있도록 설정하는 데 사용됩니다.



 a| 
Syslog를 클릭합니다
 a| 
UDP입니다
 a| 
514
 a| 
ONTAP 시스템에서 서브스크립션 기반 EMS 메시지에 액세스하고 메시지를 기반으로 이벤트를 생성하는 데 사용됩니다.



 a| 
휴식
 a| 
HTTPS
 a| 
9443
 a| 
인증된 ONTAP 시스템에서 실시간 REST API 기반 EMS 이벤트에 액세스하는 데 사용됩니다.

|===


== Unified Manager 서버와의 연결입니다

Unified Manager Server와 관리형 스토리지 시스템, 서버 및 기타 구성 요소 간의 통신을 지원하는 포트를 열도록 방화벽을 구성해야 합니다. 포트가 열려 있지 않으면 통신이 실패합니다.

환경에 따라 Unified Manager 서버가 특정 대상에 연결하는 데 사용하는 포트와 프로토콜을 수정할 수 있습니다.

Unified Manager 서버는 다음 프로토콜과 포트를 사용하여 관리형 스토리지 시스템, 서버 및 기타 구성 요소에 연결합니다.

|===
| 목적지 | 프로토콜 | 포트 | 설명 


 a| 
수행할 수 있습니다
 a| 
HTTPS
 a| 
443/TCP
 a| 
스토리지 시스템을 모니터링 및 관리하는 데 사용됩니다.



 a| 
수행할 수 있습니다
 a| 
NDMP
 a| 
10000/TCP
 a| 
특정 스냅샷 복원 작업에 사용됩니다.



 a| 
AutoSupport 서버
 a| 
HTTPS
 a| 
443
 a| 
AutoSupport 정보를 전송하는 데 사용됩니다. 이 기능을 수행하려면 인터넷에 액세스해야 합니다.



 a| 
인증 서버
 a| 
LDAP를 지원합니다
 a| 
389
 a| 
인증 요청, 사용자 및 그룹 조회 요청을 하는 데 사용됩니다.



 a| 
LDAPS
 a| 
636
 a| 
보안 LDAP 통신에 사용됩니다.
 a| 
메일 서버



 a| 
SMTP
 a| 
25
 a| 
경고 알림 이메일을 보내는 데 사용됩니다.
 a| 
SNMP 트랩 보낸 사람



 a| 
SNMPv1 또는 SNMPv3
 a| 
162/UDP
 a| 
알림 SNMP 트랩을 보내는 데 사용됩니다.
 a| 
외부 데이터 공급자 서버



 a| 
TCP
 a| 
2003년
 a| 
Graphite와 같은 외부 데이터 공급자에게 성능 데이터를 보내는 데 사용됩니다.
 a| 
NTP 서버

|===