---
permalink: install/task-upgrading-mysql-on-linux.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager가 설치된 Linux 서버에서 최신 버전의 MySQL으로 업그레이드하여 보안 취약점에 대한 수정 사항을 확인할 수 있습니다. 
---
= Linux에서 MySQL 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager가 설치된 Linux 서버에서 최신 버전의 MySQL으로 업그레이드하여 보안 취약점에 대한 수정 사항을 확인할 수 있습니다.



== 시작하기 전에

Unified Manager가 설치된 Linux 시스템에 대한 루트 권한이 있어야 합니다.



== 이 작업에 대해

MySQL 5.7의 업데이트(예: 5.7.1 ~ 5.7.2)로만 업그레이드할 수 있습니다. 예를 들어, MySQL 버전 5.8과 같은 주요 버전으로 업그레이드할 수 없습니다.



== 단계

. Unified Manager 호스트 시스템에서 루트 사용자로 로그인합니다.
. 최신 MySQL Community Server를 다운로드합니다 `.rpm` 타겟 시스템에 번들로 제공됩니다.
. 번들을 대상 시스템의 디렉토리에 압축을 풉니다.
. 여러 개를 받게 됩니다 `.rpm` 번들을 언덜어 디렉토리에 패키지가 있지만 Unified Manager에서는 다음 rpm 패키지만 필요합니다.
+
** mysql-community-client-5.7.x
** MySQL - 커뮤니티 - libs - 5.7.x
** mysql-community-server-5.7.x
** mysql-community-common-5.7.x
** MySQL - community-libs-compat-5.7.x 다른 모든 항목을 삭제합니다 `.rpm` 패키지. RPM 번들에 모든 패키지를 설치하는데 문제가 발생하지는 않습니다.


. Unified Manager 서비스 및 관련 MySQL 소프트웨어를 표시된 순서대로 중지합니다.
. 다음 명령을 사용하여 MySQL 업그레이드를 호출합니다. `yum install *.rpm`
+
`*.rpm` 을(를) 참조합니다 `.rpm` 최신 버전의 MySQL을 다운로드한 디렉토리에 있는 패키지.

. 다음 순서대로 Unified Manager를 시작합니다.

