---
permalink: install/task-configuring-existing-unified-manager-setup-to-high-availability.html 
sidebar: sidebar 
keywords:  
summary: 기존 Unified Manager 설치를 업데이트하고 고가용성을 위한 설정 환경을 구성할 수 있습니다. 
---
= 고가용성을 위해 기존 Unified Manager 설정을 업데이트합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 Unified Manager 설치를 업데이트하고 고가용성을 위한 설정 환경을 구성할 수 있습니다.



== 시작하기 전에

* 기존 데이터의 백업 및 지원 번들을 생성해야 합니다.
* OnCommand 관리자 또는 스토리지 관리자 역할이 있어야 합니다.
* 두 번째 노드를 클러스터에 추가하고 두 번째 노드에 VCS(Veritas Cluster Server)를 설치해야 합니다.
+
Veritas Cluster Server 6.2.1 설치 가이드 _ 를 참조하십시오.

* 새로 추가된 노드는 high-availability 설정에서 기존 노드의 공유 위치와 동일한 공유 위치에 액세스하도록 구성해야 합니다.




== 단계

. 클러스터의 새 노드에 로그인합니다.
. 노드에 Unified Manager를 설치합니다.
+
xref:concept-installing-unified-manager-on-rhel-or-centos.adoc[Red Hat Enterprise Linux 또는 CentOS에 Unified Manager 설치]

. 데이터가 있는 기존 노드의 구성 스크립트를 사용하여 Unified Manager 서버를 구성합니다.
. 두 번째 노드로 수동 페일오버를 시작합니다.
. 를 실행합니다 `perl ha_setup.pl --join -t vcs -f``mount_path` 명령을 실행하여 Unified Manager 서버 데이터가 공유 LUN을 가리키도록 클러스터의 두 번째 노드에 명령을 내립니다.
. WFA(OnCommand Workflow Automation)가 Unified Manager에 대해 구성된 경우 WFA 연결을 사용하지 않도록 설정하고 다시 구성하십시오.
. SnapProtect가 Unified Manager로 구성된 경우 새 클러스터 IP 주소와 기존 스토리지 정책으로 SnapProtect를 재구성합니다.
. 맞춤형 보고서를 재생성하고 이 보고서를 Unified Manager에 새 클러스터 IP 주소로 추가합니다.

