---
permalink: install/task-installing-unified-manager-linux.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager를 물리적 또는 가상 Red Hat Enterprise Linux 또는 CentOS 플랫폼에 설치할 수 있습니다. 
---
= Red Hat Enterprise Linux 또는 CentOS에 Unified Manager 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager를 물리적 또는 가상 Red Hat Enterprise Linux 또는 CentOS 플랫폼에 설치할 수 있습니다.



== 시작하기 전에

* Unified Manager를 설치할 시스템은 시스템 및 소프트웨어 요구사항을 충족해야 합니다.
+
xref:concept-virtual-infrastructure-or-hardware-system-requirements.adoc[하드웨어 시스템 요구 사항]

+
xref:reference-red-hat-and-centos-software-and-installation-requirements.adoc[Red Hat 및 CentOS 소프트웨어 및 설치 요구 사항]

* Unified Manager를 다운로드해야 합니다``.zip`` 파일을 NetApp Support 사이트에서 타겟 시스템으로 이동합니다.
* 지원되는 웹 브라우저가 있어야 합니다.
* 터미널 에뮬레이션 소프트웨어에 scrollback이 활성화되어 있어야 합니다.




== 이 작업에 대해

Red Hat Enterprise Linux 또는 CentOS 시스템에는 필요한 지원 소프트웨어(Java, MySQL, 추가 유틸리티)의 모든 필수 버전이 설치되어 있거나 필요한 소프트웨어 중 일부만 설치되어 있거나 필요한 소프트웨어가 설치되지 않은 새로 설치된 시스템일 수 있습니다.



== 단계

. Unified Manager를 설치할 서버에 로그인합니다.
. 적절한 명령을 입력하여 설치를 지원하기 위해 타겟 시스템에 설치 또는 업그레이드해야 할 소프트웨어를 평가합니다.
+
|===
| 필수 소프트웨어 및 최소 버전 | 명령을 사용하여 소프트웨어 및 버전을 확인합니다 


 a| 
OpenJDK 버전 11
 a| 
`java -version`



 a| 
MySQL 5.7.23 커뮤니티 에디션
 a| 
`rpm -qa | grep -i mysql`



 a| 
p7zip 9.20.1
 a| 
`rpm -qa | grep p7zip`

|===
. 나열된 소프트웨어 버전이 필요한 버전보다 이전일 경우 적절한 명령을 입력하여 해당 모듈을 제거합니다.
+
|===
| 제거할 소프트웨어입니다 | 명령을 사용하여 소프트웨어를 제거합니다 


 a| 
MySQL

[NOTE]
====
MySQL 5.7.23 Community Edition 이상이 아닌 버전을 제거합니다.

==== a| 
`rpm -e` 를 누릅니다``mysql_package_name``를 누릅니다

[NOTE]
====
종속성 오류가 발생하면 을 추가해야 합니다 `--nodeps` 구성 요소를 제거하는 옵션입니다.

====


 a| 
기타 모든 모듈
 a| 
`yum remove` `module_name`

|===
. 설치를 다운로드한 디렉토리로 이동합니다 `.zip` Unified Manager 번들 파일 및 확장: `unzip OnCommandUnifiedManager-rhel7-9.5.zip`
+
필수 요소입니다 `.rpm` Unified Manager용 모듈의 압축이 대상 디렉토리에 풀립니다.

. 디렉토리에서 다음 모듈을 사용할 수 있는지 확인합니다. `ls *.rpm`
+
** `ocie-au-<version>.x86_64.rpm`
** `ocie-server-<version>.x86_64.rpm`
** `ocie-serverbase-<version>.x86_64.rpm`
** `netapp-application-server-<version>.x86_64.rpm`
** `netapp-platform-base-<version>.x86_64.rpm`
** `netapp-ocum-<version>.x86_64.rpm`


. 사전 설치 스크립트를 실행하여 Unified Manager 설치와 충돌할 수 있는 시스템 구성 설정이나 설치된 소프트웨어가 없는지 확인합니다. `pre_install_check.sh`
+
사전 설치 스크립트는 시스템에 유효한 Red Hat 서브스크립션이 있으며 필요한 소프트웨어 리포지토리에 액세스할 수 있는지 확인합니다. 스크립트에서 문제가 식별되면 Unified Manager를 설치하기 전에 문제를 해결해야 합니다.

+
[NOTE]
====
설치에 필요한 패키지를 수동으로 다운로드해야 하는 경우 7_Only_단계를 수행해야 합니다. 시스템에 인터넷이 연결되어 있고 필요한 모든 패키지를 사용할 수 있는 경우 8단계로 이동합니다.

====
. 인터넷에 연결되어 있지 않거나 Red Hat Enterprise Linux 리포지토리를 사용하지 않는 시스템의 경우 다음 단계를 수행하여 필요한 패키지가 있는지 확인한 다음 해당 패키지를 다운로드하십시오.
+
.. Unified Manager를 설치할 시스템에서 사용 가능한 패키지 및 사용할 수 없는 패키지 목록을 봅니다. `yum install *.rpm --assumeno`
+
""설치 중:"" 섹션의 항목은 현재 디렉터리에서 사용할 수 있는 패키지이며 ""종속성 설치:"" 섹션의 항목은 시스템에 없는 패키지입니다.

.. 인터넷에 액세스할 수 있는 시스템에서 누락된 패키지를 다운로드합니다. `yum install <package_name\> --downloadonly --downloaddir=.`
+
[NOTE]
====
플러그인 ""yum-plugin-downloadonly""가 Red Hat Enterprise Linux 시스템에서 항상 활성화되어 있는 것은 아니므로 패키지를 설치하지 않고 패키지를 다운로드할 수 있도록 기능을 설정해야 할 수 있습니다. `yum install yum-plugin-downloadonly`

====
.. 인터넷 연결 시스템에서 설치 시스템으로 누락된 패키지를 복사합니다.


. 소프트웨어를 설치합니다. `yum install *.rpm`
+
이 명령은 를 설치합니다 `.rpm` 필요한 기타 모든 지원 소프트웨어 및 Unified Manager 소프트웨어를 패키지로 제공합니다.

+
[NOTE]
====
와 같은 다른 명령을 사용하여 설치를 시도하지 마십시오 `+rpm -ivh ...+`)를 클릭합니다. Red Hat Enterprise Linux 또는 CentOS 시스템에 Unified Manager를 성공적으로 설치하려면 모든 Unified Manager 파일과 관련 파일이 에 의해 자동으로 적용되는 특정 디렉토리 구조에 특정 순서로 설치되어야 합니다 `yum install *.rpm` 명령.

====
. 설치 메시지 직후에 표시되는 이메일 알림은 무시하십시오.
+
e-메일은 초기 cron 작업 실패를 루트 사용자에게 알려 주며 설치에 부정적인 영향을 주지 않습니다.

. 설치 메시지가 완료된 후 Unified Manager 웹 UI의 IP 주소 또는 URL, 유지보수 사용자 이름(umadmin), 기본 암호가 표시되는 메시지가 표시될 때까지 메시지를 다시 스크롤합니다.
+
이 메시지는 다음과 유사합니다.

+
[listing]
----
OnCommand Unified Manager installed successfully.
Use a web browser and one of the following URL(s) to configure and access the Unified Manager GUI.
https://default_ip_address/    (if using IPv4)
https://[default_ip_address]/  (if using IPv6)
https://fully_qualified_domain_name/

Log in to Unified Manager in a web browser by using following details:
  username: umadmin
  password: admin
----
. IP 주소 또는 URL, 할당된 사용자 이름(umadmin) 및 현재 암호를 기록합니다.
. Unified Manager를 설치하기 전에 사용자 지정 홈 디렉터리를 사용하여 umadmin 사용자 계정을 만든 경우 umadmin 사용자 로그인 셸을 지정해야 합니다.``usermod -s /bin/maintenance-user-shell.sh umadmin``




== 작업을 마친 후

웹 UI에 액세스하여 _OnCommand Unified Manager 시스템 구성 가이드_에 설명된 대로 Unified Manager의 초기 설정을 수행할 수 있습니다.
