---
permalink: install/task-upgrading-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: Red Hat 플랫폼에서 설치 파일을 다운로드하여 실행하면 Unified Manager 버전 7.3 또는 9.4에서 Unified Manager 9.5로 업그레이드할 수 있습니다. 
---
= Red Hat Enterprise Linux 또는 CentOS에서 Unified Manager 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Red Hat 플랫폼에서 설치 파일을 다운로드하여 실행하면 Unified Manager 버전 7.3 또는 9.4에서 Unified Manager 9.5로 업그레이드할 수 있습니다.



== 시작하기 전에

* Unified Manager를 업그레이드하는 시스템은 시스템 및 소프트웨어 요구사항을 충족해야 합니다.
+
xref:concept-virtual-infrastructure-or-hardware-system-requirements.adoc[하드웨어 시스템 요구 사항]

+
xref:reference-red-hat-and-centos-software-and-installation-requirements.adoc[Red Hat 및 CentOS 소프트웨어 및 설치 요구 사항]

* Unified Manager 9.4부터는 Red Hat Enterprise Linux 6.x가 더 이상 지원되지 않습니다. RHEL 6을 사용하는 경우 Unified Manager 9.5로 업그레이드하기 전에 RHEL 인스턴스를 버전 7.x로 업그레이드해야 합니다.
* Unified Manager 9.5부터는 Oracle Java가 더 이상 지원되지 않습니다. Unified Manager 9.5로 업그레이드하기 전에 올바른 버전의 OpenJDK를 설치해야 합니다.
* Red Hat Enterprise Linux Subscription Manager에 가입해야 합니다.
* 업그레이드 중에 문제가 발생할 경우 데이터 손실을 방지하려면 Unified Manager 데이터베이스의 백업을 생성해야 합니다. 또한 에서 백업 파일을 이동하는 것이 좋습니다 `/opt/netapp/data` 외부 위치에 대한 디렉터리입니다.
* 업그레이드 프로세스 중에는 Unified Manager를 사용할 수 없으므로 실행 중인 작업을 모두 완료해야 합니다.




== 이 작업에 대해

[NOTE]
====
다음 단계에는 Veritas Operation Manager를 사용하여 고가용성을 위해 구성된 시스템에 대한 정보가 포함되어 있습니다. 시스템이 고가용성을 위해 구성되지 않은 경우 이 추가 단계를 무시하십시오.

====


== 단계

. 대상 Red Hat Enterprise Linux 또는 CentOS 서버에 로그인합니다.
. 서버에 Unified Manager 번들을 다운로드합니다.
+
xref:task-downloading-unified-manager.adoc[Red Hat 또는 CentOS용 Unified Manager 다운로드]

. 타겟 디렉토리로 이동하고 Unified Manager 번들을 확장합니다. `unzip OnCommandUnifiedManager-rhel7-9.5.zip`
+
Unified Manager에 필요한 RPM 모듈의 압축이 대상 디렉토리에 풀립니다.

. 나열된 모듈이 있는지 확인합니다. `ls *.rpm`
+
다음 RPM 모듈이 나열되어 있습니다.

+
** `ocie-au-<version>.x86_64.rpm`
** `ocie-server-<version>.x86_64.rpm`
** `ocie-serverbase-<version>.x86_64.rpm`
** `netapp-application-server-<version>.x86_64.rpm`
** `netapp-platform-base-<version>.x86_64.rpm`
** `netapp-ocum-<version>.x86_64.rpm`


. 인터넷에 연결되어 있지 않거나 RHEL 리포지토리를 사용하지 않는 시스템의 경우 다음 단계를 수행하여 필요한 패키지가 있는지 확인하고 해당 패키지를 다운로드하십시오.
+
.. 사용 가능한 패키지 및 사용할 수 없는 패키지 목록을 봅니다. `yum install *.rpm --assumeno`
+
""설치 중:"" 섹션의 항목은 현재 디렉터리에서 사용할 수 있는 패키지이며 ""종속성 설치:"" 섹션의 항목은 시스템에 없는 패키지입니다.

.. 인터넷 액세스가 가능한 다른 시스템에서 누락된 패키지를 다운로드합니다. `yum install package_name --downloadonly --downloaddir=.`
+
[NOTE]
====
플러그인 ""yum-plugin-downloadonly""가 Red Hat Enterprise Linux 시스템에서 항상 활성화되어 있는 것은 아니므로 패키지를 설치하지 않고 패키지를 다운로드할 수 있도록 기능을 설정해야 할 수 있습니다. `yum install yum-plugin-downloadonly`

====
.. 인터넷 연결 시스템에서 설치 시스템으로 누락된 패키지를 복사합니다.


. Unified Manager가 고가용성을 지원하도록 구성된 경우 Veritas Operation Manager를 사용하여 첫 번째 노드에서 모든 Unified Manager 서비스를 중지합니다.
. 다음 스크립트를 사용하여 Unified Manager 업그레이드: `upgrade.sh`
+
이 스크립트는 RPM 모듈을 자동으로 실행하여 필요한 지원 소프트웨어 및 실행 중인 Unified Manager 모듈을 업그레이드합니다. 또한 업그레이드 스크립트는 시스템 구성 설정이 있는지 또는 Unified Manager 업그레이드와 충돌하는 소프트웨어가 설치되어 있는지 확인합니다. 스크립트에서 문제가 식별되면 Unified Manager를 업그레이드하기 전에 문제를 해결해야 합니다.

+
[NOTE]
====
과 같은 다른 명령을 사용하여 업그레이드를 시도하지 마십시오 `+rpm -Uvh ...+`)를 클릭합니다. 업그레이드를 성공적으로 수행하려면, 모든 Unified Manager 파일과 관련 파일을 스크립트에서 자동으로 실행 및 구성되는 특정 디렉토리 구조로 특정 순서로 업그레이드해야 합니다.

====
. 고가용성 설치의 경우 Veritas Operation Manager를 사용하는 두 번째 노드에서 모든 Unified Manager 서비스를 중지합니다.
. 고가용성 설치의 경우 서비스 그룹을 고가용성 설정의 두 번째 노드로 전환하고 두 번째 노드의 Unified Manager를 업그레이드합니다.
. 업그레이드가 완료된 후 Unified Manager 웹 UI의 IP 주소 또는 URL, 유지보수 사용자 이름(umadmin) 및 기본 암호가 표시된 메시지가 나타날 때까지 메시지를 다시 스크롤합니다.
+
이 메시지는 다음과 유사합니다.

+
[listing]
----
OnCommand Unified Manager upgraded successfully.
Use a web browser and one of the following URLs to access the OnCommand Unified Manager GUI:

https://default_ip_address/    (if using IPv4)
https://[default_ip_address]/  (if using IPv6)
https://fully_qualified_domain_name/
----




== 작업을 마친 후

지원되는 웹 브라우저에 지정된 IP 주소 또는 URL을 입력하여 Unified Manager 웹 UI를 시작한 다음, 앞서 설정한 유지보수 사용자 이름(umadmin) 및 암호를 사용하여 로그인합니다.
