---
permalink: install/task-removing-unified-manager-vapp.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager 소프트웨어가 설치된 가상 어플라이언스를 제거하여 Unified Manager를 제거할 수 있습니다. 
---
= VMware에서 Unified Manager 제거
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager 소프트웨어가 설치된 가상 어플라이언스를 제거하여 Unified Manager를 제거할 수 있습니다.



== 시작하기 전에

* VMware vCenter Server 및 vSphere Web Client(vSphere 버전 6.5의 경우) 또는 vSphere Client(vSphere 버전 5.5 또는 6.0의 경우)에 액세스하기 위한 자격 증명이 있어야 합니다.
* Unified Manager 서버가 외부 데이터 공급자에 연결되어 있지 않아야 합니다.
+
활성 연결이 있는 경우 Unified Managermaintenance 콘솔을 사용하여 연결을 삭제해야 합니다.

* Unified Manager 서버가 Workflow Automation 서버에 연결되어 있지 않아야 합니다.
+
활성 연결이 있는 경우 Administration(관리) 메뉴를 사용하여 연결을 삭제해야 합니다.

* 가상 머신(VM)을 삭제하기 전에 모든 클러스터(데이터 소스)를 Unified Manager 서버에서 제거해야 합니다.




== 단계

. Unified Manager 유지보수 콘솔을 사용하여 Unified Manager 서버가 외부 데이터 공급자에 대해 활성 연결을 가지고 있지 않은지 확인하십시오.
. vSphere Client에서 * Home * > * Inventory * > * VMs and Templates * 를 클릭합니다.
. 제거할 VM을 선택하고 * 요약 * 탭을 클릭합니다.
. VM이 실행 중인 경우 * 전원 * > * 게스트 종료 * 를 클릭합니다.
. 제거할 VM을 마우스 오른쪽 단추로 클릭하고 * 디스크에서 삭제 * 를 클릭합니다.

