---
permalink: install/task-changing-the-jboss-password.html 
sidebar: sidebar 
keywords:  
summary: 새로운 맞춤형 JBoss 암호를 생성하여 설치 중에 설정된 기본 암호를 덮어쓸 수 있습니다. 이 작업은 선택 사항이지만 일부 사이트에서는 Unified Manager 설치 기본 설정을 재정의하기 위해 이 보안 기능이 필요할 수 있습니다. 이 작업은 JBoss가 MySQL에 액세스하는 데 사용하는 암호도 변경합니다. 
---
= JBoss 암호 변경
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새로운 맞춤형 JBoss 암호를 생성하여 설치 중에 설정된 기본 암호를 덮어쓸 수 있습니다. 이 작업은 선택 사항이지만 일부 사이트에서는 Unified Manager 설치 기본 설정을 재정의하기 위해 이 보안 기능이 필요할 수 있습니다. 이 작업은 JBoss가 MySQL에 액세스하는 데 사용하는 암호도 변경합니다.



== 시작하기 전에

* Unified Manager가 설치된 Red Hat Enterprise Linux 또는 CentOS 시스템에 대한 루트 사용자 액세스 권한이 있어야 합니다.
* NetApp에서 제공하는 에 액세스할 수 있어야 합니다 `password.sh` 디렉토리에 있는 스크립트입니다 `/opt/netapp/essentials/bin`.




== 단계

. 시스템에서 루트 사용자로 로그인합니다.
. 다음 명령을 표시된 순서대로 입력하여 Unified Manager 서비스를 중지합니다. `service ocieau stop``service ocie stop`
+
연결된 MySQL 소프트웨어를 중지하지 마십시오.

. 다음 명령을 입력하여 암호 변경 프로세스를 시작합니다. `/opt/netapp/essentials/bin/password.sh resetJBossPassword`
. 메시지가 표시되면 이전 JBoss 암호를 입력합니다.
+
기본 암호는 입니다 `D11h1aMu@79%`.

. 메시지가 표시되면 새 JBoss 암호를 입력한 다음 다시 입력하여 확인합니다.
. 스크립트가 완료되면 다음 명령을 표시된 순서대로 입력하여 Unified Manager 서비스를 시작합니다. `service ocie start``service ocieau start`
. 모든 서비스가 시작되면 Unified Manager UI에 로그인할 수 있습니다.

