---
permalink: install/task-upgrading-the-unified-manager-virtual-appliance-vapp.html 
sidebar: sidebar 
keywords:  
summary: Unified Manager 버전 7.3 또는 9.4에서 Unified Manager 9.5로 업그레이드할 수 있습니다. 
---
= Unified Manager 가상 어플라이언스 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager 버전 7.3 또는 9.4에서 Unified Manager 9.5로 업그레이드할 수 있습니다.



== 시작하기 전에

* 을(를) 다운로드해야 합니다 `.iso` NetApp Support 사이트에서 파일을 선택합니다.
* Unified Manager를 업그레이드하는 시스템은 시스템 및 소프트웨어 요구사항을 충족해야 합니다.
+
xref:concept-requirements-for-installing-unified-manager.adoc[가상 인프라 요구 사항]

+
xref:reference-vmware-software-and-installation-requirements.adoc[VMware 소프트웨어 및 설치 요구 사항]

* vSphere 6.5 사용자의 경우 VMware Remote Console(VMRC)을 설치해야 합니다.
* 다음 정보가 있어야 합니다.
+
** NetApp Support 사이트의 로그인 자격 증명
** VMware vCenter Server 및 vSphere Web Client(vSphere 버전 6.5용) 또는 vSphere Client(vSphere 버전 5.5 또는 6.0용)에 액세스하기 위한 자격 증명
** Unified Manager 유지보수 사용자의 자격 증명






== 이 작업에 대해

업그레이드 프로세스 중에는 Unified Manager를 사용할 수 없습니다. Unified Manager를 업그레이드하기 전에 실행 중인 작업을 완료해야 합니다.

Workflow Automation과 Unified Manager가 페어링된 경우 Workflow Automation에서 호스트 이름을 수동으로 업데이트해야 합니다.



== 단계

. vSphere Client에서 * Home * > * Inventory * > * VMs and Templates * 를 클릭합니다.
. Unified Manager 가상 어플라이언스가 설치된 가상 머신(VM)을 선택합니다.
. Unified Manager VM이 실행 중인 경우 * 요약 * > * 명령 * > * 게스트 종료 * 로 이동합니다.
. Unified Manager VM의 스냅샷 또는 클론과 같은 백업 복사본을 생성하여 애플리케이션 정합성이 보장되는 백업을 생성합니다.
. vSphere Client에서 Unified Manager VM의 전원을 켭니다.
. Unified Manager 업그레이드 이미지 선택:
+
|===
| 사용 중인 경우... | 다음을 수행하십시오. 


 a| 
vSphere 5.5 또는 6.0입니다
 a| 
.. CD/DVD 드라이브 * 아이콘을 클릭하고 * 로컬 디스크의 ISO 이미지에 연결 * 을 선택합니다.
.. 를 선택합니다 `OnCommandUnifiedManager-9.5-virtual-update.iso` 파일을 선택하고 * 열기 * 를 클릭합니다.




 a| 
vSphere 6.5
 a| 
.. VMware Remote Console을 시작합니다.
.. CDROM * 아이콘을 클릭하고 * 디스크 이미지 파일에 연결 (.iso) * 을 선택합니다.
.. 를 선택합니다 `OnCommandUnifiedManager-9.5-virtual-update.iso` 파일을 선택하고 * 열기 * 를 클릭합니다.


|===
. Console * 탭을 클릭합니다.
. Unified Manager 유지보수 콘솔에 로그인합니다.
. 주 메뉴 * 에서 * 업그레이드 * 를 선택합니다.
+
업그레이드 프로세스 중에 Unified Manager를 사용할 수 없으며 작업이 완료되면 다시 시작한다는 메시지가 표시됩니다.

. 유형 `y` 를 눌러 계속합니다.
+
가상 어플라이언스가 상주하는 가상 머신을 백업하도록 알리는 경고가 표시됩니다.

. 유형 `y` 를 눌러 계속합니다.
+
업그레이드 프로세스와 Unified Manager 서비스를 다시 시작하는 데 몇 분 정도 걸릴 수 있습니다.

. 계속하려면 아무 키나 누르십시오.
+
유지보수 콘솔에서 자동으로 로그아웃됩니다.

. 유지보수 콘솔에 로그인하여 Unified Manager 버전을 확인합니다.




== 작업을 마친 후

업그레이드된 버전의 Unified Manager를 사용하려면 웹 UI에 로그인할 수 있습니다. UI에서 작업을 수행하기 전에 검색 프로세스가 완료될 때까지 기다려야 합니다.
