---
permalink: install/task-upgrading-to-unified-manager-on-microsoft-windows.html 
sidebar: sidebar 
keywords:  
summary: Windows 플랫폼에서 설치 파일을 다운로드하여 실행하여 Unified Manager 7.3 또는 9.4를 Unified Manager 9.5로 업그레이드할 수 있습니다. 
---
= Windows에서 Unified Manager 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows 플랫폼에서 설치 파일을 다운로드하여 실행하여 Unified Manager 7.3 또는 9.4를 Unified Manager 9.5로 업그레이드할 수 있습니다.



== 시작하기 전에

* Unified Manager를 업그레이드하는 시스템은 시스템 및 소프트웨어 요구사항을 충족해야 합니다.
+
xref:concept-virtual-infrastructure-or-hardware-system-requirements.adoc[하드웨어 시스템 요구 사항]

+
xref:reference-windows-software-and-installation-requirements.adoc[Windows 소프트웨어 및 설치 요구 사항]

+
[NOTE]
====
Unified Manager 9.5부터 OpenJDK는 Unified Manager 설치 패키지에 제공되어 자동으로 설치됩니다. Oracle Java는 Unified Manager 9.5부터 지원되지 않습니다.

====
+
[NOTE]
====
Unified Manager 9.4부터 Microsoft .NET 4.5.2 이상이 필요합니다. 업그레이드를 시작하기 전에 올바른 버전의 .NET이 설치되어 있는지 확인하십시오.

====
* Windows 관리자 권한이 있어야 합니다.
* NetApp Support 사이트에 로그인하려면 유효한 자격 증명이 있어야 합니다.
* 업그레이드 중에 문제가 발생할 경우 데이터 손실을 방지하려면 Unified Manager 시스템의 백업을 생성해야 합니다.
* 업그레이드를 수행하려면 충분한 디스크 공간이 있어야 합니다.
+
설치 드라이브의 사용 가능한 공간은 데이터 디렉토리의 크기보다 2.5GB가 커야 합니다. 사용 가능한 공간이 충분하지 않은 경우 업그레이드를 중지하고 추가할 공간의 양을 나타내는 오류 메시지를 표시합니다.





== 이 작업에 대해

업그레이드 프로세스 중에는 Unified Manager를 사용할 수 없습니다. Unified Manager를 업그레이드하기 전에 실행 중인 작업을 완료해야 합니다.

Unified Manager가 OnCommand Workflow Automation 인스턴스와 페어링되어 있고 두 제품 모두에 사용할 수 있는 새로운 소프트웨어 버전이 있는 경우 두 제품의 연결을 끊고 업그레이드를 수행한 후 새 Workflow Automation 연결을 설정해야 합니다. 제품 중 하나로 업그레이드하는 경우, 업그레이드 후에 Workflow Automation에 로그인하여 Unified Manager에서 데이터를 아직 취득하고 있는지 확인해야 합니다.



== 단계

. NetApp Support 사이트에 로그인하고 Windows 플랫폼에 Unified Manager를 설치하기 위한 다운로드 페이지를 찾습니다.
+
http://mysupport.netapp.com/NOW/cgi-bin/software["NetApp 다운로드: 소프트웨어"]

. Unified Manager Windows 설치 파일을 Windows 시스템의 대상 디렉토리에 다운로드합니다.
. Unified Manager가 고가용성을 지원하도록 구성된 경우 Microsoft Cluster Server를 사용하여 첫 번째 노드에서 모든 Unified Manager 서비스를 중지한 다음 에서 MySQL 서비스를 시작합니다 `services.msc`.
. 오른쪽 클릭하고 Unified Manager 설치 관리자 실행 파일을 실행합니다 `(.exe)` 관리자 권한으로 파일을 선택합니다.
+
Unified Manager에 다음 메시지가 표시됩니다.

+
[listing]
----
This setup will perform an upgrade of ‘OnCommand Unified Manager’. Do you want to continue?
----
. 예 * 를 클릭한 후 * 다음 * 을 클릭합니다.
. 설치 중에 설정된 MySQL root 패스워드를 입력하고 * Next * 를 클릭합니다.
. 업그레이드가 완료된 후 시스템이 고가용성을 지원하도록 구성된 경우 페일오버 클러스터 관리자에서 모든 Unified Manager 서비스를 시작하고 나머지 작업을 수행합니다.
. 명령 프롬프트에서 를 실행합니다 `ha_setup.pl` 페일오버 클러스터의 새 서비스와 공유 위치에 있는 파일을 구성하는 스크립트입니다.
+
`C:\Program Files\NetApp\ocum\bin> perl .\ha_setup.pl --upgrade --first -t mscs -g kjaggrp -i "New IP Address1" -n scs8003.englab.company.com -k "Cluster Disk 2" -f E:\ -u user -p userpass`

. Microsoft Cluster Server를 사용하여 첫 번째 노드에서 모든 Unified Manager 서비스(사회, 사회 및 MySQL)를 중지합니다.
. 에서 두 번째 노드에서 MySQL 서비스를 시작합니다 `services.msc`.
. 서비스 그룹을 high-availability 설정에서 두 번째 노드로 전환합니다.
. 두 번째 노드에서 Unified Manager 업그레이드
. 명령 프롬프트에서 를 입력합니다 `Y` 계속하려면 다른 문자를 입력하고 중단하십시오.
+
Unified Manager 서비스의 업그레이드 및 재시작 프로세스를 완료하는 데 몇 분 정도 걸릴 수 있습니다.

. Microsoft Cluster Server를 사용하여 양쪽 노드에서 모든 Unified Manager 서비스를 시작합니다.
. 명령 프롬프트에서 를 실행합니다 `ha_setup.pl` 와 함께 스크립트를 작성합니다 `--upgrade` 옵션을 선택합니다.
+
`perl ha_setup.pl --upgrade --join -t mscs -f E:\`

. Unified Manager 웹 UI에 로그인하고 버전 번호를 확인합니다.




== 작업을 마친 후

[NOTE]
====
Unified Manager의 자동 업그레이드를 수행하려면 다음 명령을 실행합니다. `OnCommandUnifiedManager-9.5.exe /s /v"MYSQL_PASSWORD=netapp21! /qn /l*v C:\install.log`

====